### ISSUE TITLE
Fiat Instant

### ISSUE THREAD

**Issue by meapistol** [bisq-network/proposals#100]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I suggest that, similar to Altcoins Instant, that there is an option for fiat trades to commit to do the transfer of fiat within one (or maybe two) hour(s). There are several payment methods that are fast (Faster Payments, Zelle, Interac e-Transfer, SEPA Instant, ?) between participating banks.
Many traders value speed and an Instant option decreases the exposure to price changes substantially.

**Comment by MwithM** [comment]
There is already sepa instant option with lower exchanging time, but SEPA instant is not very used yet so there aren't too many offers with it, I guess that when you can have both in your same bank but there's more volume in normal SEPA you choose that.

**Comment by m52go** [comment]
It's a good idea, but I think it would only be feasible after robust protection mechanisms are put in place so that scammers cannot take advantage.

**Comment by mpolavieja** [comment]
I am closing this proposal as it does not seem to have much community support.  @meapistol, if you want to re-open the issue please do it by following the [proposal submission and review process](https://docs.bisq.network/proposals.html).
