### ISSUE TITLE
Bisq on mobile (priority Android)

### ISSUE THREAD

**Issue by niyid** [bisq-network/proposals#106]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Hello everyone. I think the rate of adoption of Bisq can improve greatly by dedicating effort to bringing it to mobile - and with emphasis on Android and iOS.

To also hasten development, we can look at the open source JavaFXPorts or other similar frameworks that allow JavaFX port to mobile. Then with those ports released, work on native versions targeting each of those mobile OSes.

Going by the market share data shown below, I will suggest that priority should be placed on Android; work on iOS can be deferred.

[Global mobile market share by Operating System](https://gs.statcounter.com/os-market-share/mobile/worldwide)

**Comment by blabno** [comment]
There have already been attempts to create mobile client using ionic framework, but that relies on API being merged into Bisq.

**Comment by niyid** [comment]
Thanks Bernard. It appears those attempts have been discontinued since
there was never a release? How long ago was this?

**Comment by niyid** [comment]
I will like to obtain authorization to get free licenses to proceed with research on this matter.

Please view the request form here:

https://gluonhq.com/programs/free-gluon-licenses/open-source-license-request/

Alternatively @ManfredKarrer or any other experienced developer can get the licenses and share.

Regards.

**Comment by niyid** [comment]
Thanks Bernard. It appears those attempts have been discontinued since
there was never a release? How long ago was this?

From my research so far, the Gluon Mobile plugin requires very little change to the existing code-base as [as seen here](https://docs.gluonhq.com/charm/5.0.1/) which is just to add 2 lines to the build.gradle file.

**Comment by blabno** [comment]
No, those attempts have not been discontinued, but instead have been queued, because first there need to be an API to which the mobile client could connect.

There is no way to run the whole Bisq on mobile due to the nature of those devices. The battery saving policies cause system to shut down apps at will while Bisq must be constantly on when the offer is published.

**Comment by HarryMacfinned** [comment]
I have also to add (sorry) that I don't see the point to do work for mass market adoption, whereas the main obstacles for mass market adoption are not solved **at first**.
This would just be work done for 0 ROI (as alas other such previous works).

**Comment by niyid** [comment]
@HarryMacfinned 
I will defer to superior judgement since you've had more experience on the matter.

Regards.

**Comment by mpolavieja** [comment]
As @blabno points out.  It has been discussed previously that current energy management system on mobile devices would not allow to run Bisq properly.  I am closing this proposal for now.   

@niyid, feel free to do more research on this topic at bisq's github repos and bisq.community and if you want yo can open a new proposal following [the guidelines for submitting proposals](https://docs.bisq.network/proposals.html)
