### ISSUE TITLE
Dev-Calls revisited

### ISSUE THREAD

**Issue by freimair** [bisq-network/proposals#107]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

The Bisq DAO helps us decide on stuff (proposals, compensation requests, paramenter changes, ...). However, for the DAO to be able to help us, we have to communicate, discuss, get creative and actually suggest stuff the DAO can help us decide on. Here is a suggestion on a "Developer Call" structure that may help to focus our efforts on bringing reasonable "stuff" to the DAO.

# DevCall NG

In "Developer Calls" the focus lies on technical and/or strategic stuff regarding Bisq. For example, we can discuss on how to get seed nodes more stable or we can discuss whether we should migrate the code-base to plain-C. We will not give a narrated step-by-step guide on how to make your first trade.

## Dev Call preparations
- collect topics in this very issue https://github.com/bisq-network/events/issues/31
- create an upcoming dev-call issue here https://github.com/bisq-network/events/issues
- select a reasonable set of topics to focus on in the dev call along with a time frame
- schedule
  - short-term: 1-2h before
  - long-term: days before
- announce 
  - Slack channel "events"
  - publish on [bisq calendar](bisq.network/calendar)
  - Youtube life-stream announcement (optional)

## Doing the dev call
- a host
  - leads the discussions (makes sure to stay focused on the topics planned)
  - takes notes (enhance the agenda)
  - track progress
- developers
  - prepare themselves for the topics at hand
  - propose stuff, discuss stuff
- others
  - can listen and learn
- all
  - raise questions (that might be discussed instantly or scheduled for another dev call)

## Aftermath
- record and publish on youtube (optional)
- update future dev call agenda(s)
- close the dev call issue and reference the video if there is one

# Whats next

I am willing to be the guy doing all the preparations, being the host and doing the aftermath just to get the thing started (again).Someday, we may not need a dedicated person to do this anymore.

**Comment by mpolavieja** [comment]
Accepted on Cycle 5 DAO voting

**Comment by cbeams** [comment]
This proposal was originally approved in cycle 5 as documented above, but the dev calls never proceeded as planned. #231 is a new proposal to re-institute regular dev calls and I've just labeled this issue as superseded to reflect.

**Comment by freimair** [comment]
> but the dev calls never proceeded as planned

actually, there have been quite a few calls: https://github.com/bisq-network/events/issues?q=is%3Aissue+is%3Aclosed+dev-call and a couple of planned ones. The agendas and meeting minutes are quite entertaining to read through and kind-of shows us that the stuff we are discussing right now has been brought up months ago already :thinking:
