### ISSUE TITLE
Hold workshops to attract developers

### ISSUE THREAD

**Issue by m52go** [bisq-network/proposals#109]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Bisq needs more developers. Efforts on social media, blogging, and videos will pick up, and perhaps we can weave a subtle message into the software and source code too, but I'm not sure if that will be enough.

This proposal is to gauge interest for a more concerted effort IRL, based on workshops that cover more detail than a conference event could possibly do.

## Rationale

**Intuition**
There's nothing like meeting and talking to people in real life, with a hands-on tour of the software, no matter how much effort we put in to digital outreach.

**Precursor**
Manfred did a ~10 country tour in the early days of the project to bootstrap the user base. While it's hard to pinpoint how much early traction came from this initiative, it's safe to say it helped significantly since other channels were brand-new (social channels, word of mouth, etc).

**Precedent**
BTCPay has held developer workshops around the world, and apparently they're so heavily attended that they're now [charging for entry](https://twitter.com/BtcpayServer/status/1154799006742130688). Their contributor base is rather solid...they will have _20 contributors_ in Riga next month.

**Opportunity**
I will be in Europe in October. Given the right circumstances, I could hold a few events to showcase Bisq, spotlight the DAO, and perhaps spark some interest in developers to contribute. I don't do development for Bisq, but I do develop software elsewhere, so I should be able to communicate well to potential developers with a bit of study and preparation.

## Concept

Hold Bisq workshops in proximity to large bitcoin/general developer-oriented events (or in partnership with big meetups that draw similar people). Goal would be to hold these workshops at a time that doesn't conflict with any main events, but that take place during the conference's general time frame so that as many people as possible can join.

Conferences tend to dictate format, allotted time, etc. and most aren't conducive to holding a thorough workshop that would achieve our goals. Holding adjacent events might be better.

Upcoming examples:
* HCPP
* Money Badger
* [Other big events that developers are likely to attend, possibly not in Bitcoin space...ideas?]
* [Large meetups]

## Workshop Details

These need to be worked out. First I think it's important to see if this idea is even good to begin with.

High level, this is what I have in mind:
* Brief introduction about Bisq, how it works, etc & do test trade (30 minutes)
* Show GitHub, Slack, roles, etc. and how collaboration and work actually gets done (20 minutes)
* Show the DAO, perhaps run through voting cycle with regtest setup that everyone can participate in right there (remainder)

After showing the DAO, it would be cool to show people this very proposal (if it's approved) and resulting compensation requests to show how that very presentation is being approved and funded through the DAO (!).

In general, my approach would be less "here's Bisq and how you can get involved" to "here's what this project is and why it's so cool and different from what you've seen" from the standpoints of technology, mission, culture/practical work conventions, etc. and let people make their own decisions.

Ideally, a Bisq developer would join these events too.

Estimated time: 1.5 hours

**Crucial**: we should probably develop a short list of bounties/tasks for first-time developers so that those who become interested at the events have a clear segue to get started if they want (or at least make sure [the ones we have](https://github.com/bisq-network/bisq/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) are up-to-date).

## Optional

* Make a bigger splash. Instead of simply "holding some workshops", we could theme it by calling it something like "The First Real Software Company Tour" ([credit](https://twitter.com/manfred_karrer/status/1160857296563515392)). It is a little gutsy, but it's sure to get attention from those beyond the Bitcoin or "crypto" space.
  * The recruiting process for software developers, at least here in the States, is horrible. As are office politics, privacy/ethical issues (now a real concern at virtually every company), and other various aspects of working for software companies. It would be differentiate Bisq on these points as an ethical place for mature developers to do _good_ work and earn a good living without the downsides of a _company_.
* Do the tour in partnership with another project like Tor for added visibility and "branding". Not sure what the actual partnership could be, but seeing Bisq with Tor in an event title/description would help get people from outside the space in the right mindset, and perhaps keep away those who don't care as much about privacy and freedom.

## Longer-term benefits

If the format works out, we could open the content, format, and other specifics so that anyone could hold similar events in their area.

## Next steps

- [ ] determine if this idea is any good (in general, also vs standard overview-style presentations)
- [ ] if so, determine which events/localities can be targeted, as well as costs
- [ ] decide on workshop details, start planning logistics, etc.

## Costs

This is the main reason I'm making the proposal. Planning a 1.5-hour somewhat-technical workshop will not be trivial, and traveling to host them won't be either. I don't know exact numbers, but it probably only makes sense to discuss if people are on-board with the idea of doing something like this in the first place.

## Urgency

High. Time is tight, as arrangements need to be made very soon for any events to be held in October. If this proposal turns out to be controversial, or if the initiative seems rushed, we can hold off and focus on digital outreach. In the mean time I can make some test runs at meetups around here, and plan a longer trip to Europe for later.

And of course, Bisq needs to implement the new trade protocol, off-chain trade protocol, etc. ASAP so we need to do all we can now.

**Comment by thehapax** [comment]
I believe HCPP would have values that align with Bisq. HCPP would be a good place to do a conference workshop. The bitcoin lightning conference is being held in Berlin in October. 
Also CCC conference at the end of the year. 

> Upcoming examples:
> 
> * HCPP
> * Money Badger
> * [Other big events that developers are likely to attend, possibly not in Bitcoin space...ideas?]
> * [Large meetups]
> 
Do you mean Honey Badger in Riga?

> The recruiting process for software developers, at least here in the States, is horrible. As are office politics, privacy/ethical issues (now a real concern at virtually every company), and other various aspects of working for software companies. It would be differentiate Bisq on these points as an ethical place for mature developers to do good work and earn a good living without the downsides of a company.

Agreed. Although it depends on where and whom. There aren't enough that have been red pilled.

**Comment by MwithM** [comment]
This is a big one. 4-6th oct,  Paralelní Polis, Prague.
https://opt-out.hcpp.cz/

**Comment by m52go** [comment]
> Do you mean Honey Badger in Riga?

Apparently there's [another event called "Money Badger"](https://moneybadger.events/) happening later this year, but details are scarce right now. Saw it listed on [bitcoin-only.com](https://bitcoin-only.com/#conferences).

**Comment by ManfredKarrer** [comment]
I am not sure if developers would expect from a workshop some hacking workshop where you either build a small feature in Bisq or get into the code base deeper. But I fear that would be unfeasible at the current state as it would require at least one developer to be there who knows the complete code base and iy also might lead to a wrong impression about the neature of Bisq (it is not a library projects like IPFS where you can easily build on top of the library).
I would recommend to limit scope to the minimum and prefer to do it earlier rather than later. To have it more a workshop-like format rather than a presentation is for sure a good idea but probably needs to be communicated right so that devs don't expect a hacker workshop.

**Comment by thehapax** [comment]
Transylvania Crypto Confernce 10.-12. October 2019

More here:
https://towardsliberty.com/events

**Comment by m52go** [comment]
Thanks for the feedback on this. Given constraints, I will likely tackle this in a different way. Will discuss further on [this Thursday's developer call](https://github.com/bisq-network/events/issues/29). 

Not putting this up for vote in the DAO, and closing for now, possibly to be revisited again soon.
