### ISSUE TITLE
Switch from Transifex to Weblate infrastructure

### ISSUE THREAD

**Issue by sanecito** [bisq-network/proposals#111]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

**Proposal:** Move from using Transifex to translate the project to Weblate (non-self-hosted instance). Note that Weblate hosted (vs self-hosted) would likely be free given their [Gratis for libre projects pricing](https://weblate.org/en/hosting/).

**Implementer(s):** @erciccione (mentioned in Slack that they'd be happy to help, has experience moving from Pootle to self-hosted Weblate), myself, and/or those who implemented Transifex (was thinking mainly for feedback  / lessons learned, but if they want they can set up the config too). Weblate admins and language maintainers would be the same as Transifex.

**Testing:** Before executing the migration itself, as suggested by y3v63n we'd be having "a couple of test projects (for software and website) and having everyone involved in translations and @ripcurlx (who pulls the translations in the app) expressing their opinion"

**Why should the Bisq community care about improving our localization tools?:** Apart from maybe adding new fiat processing methods, localization is arguably the biggest factor in improving liquidity. Don't believe me? Look at other language based issues where you hear things like [this](https://github.com/bisq-network/proposals/issues/37): 

> Yes, the language barrier has been the biggest obstacle on-boarding new users to Bisq in Japan, as nobody really speaks English except foreigners or internationalized Japanese people. Since non-English speakers are afraid they might make a mistake and lose funds, they are too scared to try it. Currently the order book is entirely made up of a few foreigners who are the members of the Tokyo Bitcoin community, and we really need Japanese translations to get Bisq adoption in Japan. Thank you for this!

**But we already have Transifex and it works well enough. Why should any effort be put into moving to another tool when we could spend it elsewhere?:**

- **In short, FOSS has value.** Let's assume for a moment that Transifex and Weblate are exactly the same, with the only difference being that Transifex is proprietary and Weblate is FOSS. Which one would you choose? People would most likely choose FOSS. Let's break down why FOSS is boss.

- **Anyone can submit a patch**. Is there a feature you want or bug that's irritating you with Transifex? Too bad; the code is proprietary, you can't help make the tool better. Furthermore, since Bisq is a (presumably) free customer of Transifex, any requests to add features or fix bugs are likely going to be the lowest priority for Transifex as Bisq isn't a paying customer. Conversely, Weblate you can take ownership and work with other members of the Weblate community to get that feature, that bug fix, or even further improve the localization of Weblate itself. Individuals can also place bounties on said bugs or fixes via things like BountySource.

- **No worries if the Weblate maintainers leave:** This is admittedly a low risk, but if Transifex were to go out of business that would be it. Weblate is FOSS which means anyone can fork and become new maintainers or we can resort to self-hosting.

- **Free advertising on Weblate's front page.** Visit both https://www.transifex.com/ and https://weblate.org While both advertise their product, Weblate also advertises the active communities (seen below). Free advertising is great as it means more eyeballs which can translate into more localizers for Bisq. **Note that this is for Weblate hosting, not for self-hosted.

![image](https://user-images.githubusercontent.com/3056597/64071539-1c31cb80-cc31-11e9-9741-3f94b18f9b87.png)

- **Arguably more feature rich than Transifex.** There's a variety of features that Weblate has over Transifex. One such feature is the ability to [easily advertise the Bisq project and current status via widgets](https://docs.weblate.org/en/latest/devel/share.html)

- **Weblate has a better UX which translates to better productivity.** I'm not going to provide an exhaustive list, just a few examples. Let's start with the Watching settings. Transifex tells you to go to the project page and subscribe there:

![image](https://user-images.githubusercontent.com/3056597/64071609-9f9fec80-cc32-11e9-93bd-3455c36ae6eb.png)

But I'm already here in the config panel and I know the project name, why not just let me type and subscribe? Weblate gets this:

![image](https://user-images.githubusercontent.com/3056597/64071637-37053f80-cc33-11e9-9ee0-a16924b081db.png)

A proprietary mindset leads to proprietary design which is at odds with FOSS collaboration ideals. Take for example Huey today highlighted in Slack for Persian/Farsi localizers to look at strings like [this](https://www.transifex.com/bisq/bisq-website/translate/#fa/vision/174374890). Let's say I'm on mobile and just want to look at the string in question. Can't, because you have to have to be logged into an account to look at anything. Even when I'm logged in on PC it doesn't let me look at how the Persian/Farsi speakers translated it, only 'my' language, Japanese. Weblate you don't need to be logged in to view and can easily see how other people might have syntactically styled things:

![image](https://user-images.githubusercontent.com/3056597/64071742-906e6e00-cc35-11e9-9817-c22ecb45ecc9.png)

Probably the biggest quality of life improvement from a localizer viewpoint that I've come across is that Weblate nicely marks up when a string has been modified, no clicks to show the diff required:

![image](https://user-images.githubusercontent.com/3056597/64071765-fe1a9a00-cc35-11e9-86d3-89a972648acc.png)

Transfiex on the other hand requires that you click around in Translation Memory:

![image](https://user-images.githubusercontent.com/3056597/64071776-581b5f80-cc36-11e9-9d59-6fd3d741d185.png)

**In Summary:** Moving to Bisq gives us among other things: the ability to fix or add features to our tool (or otherwise bountify), free advertising to other fellow FOSS contributors which can turn into more Bisq localizers, and a better UX which leads to better productivity. We can further improve the liquidity offered on Bisq by switching from Transifex to Weblate.

**Comment by y3v63n** [comment]
@sanecito Thanks for your proposal!

I would like to add my input here.

There are certainly advantages of using a FOSS tool over Transifex, yet I would proceed with caution. I believe there should be value in migrating rather than just doing it for the sake of using an open-source platform.

1. We do have a free Transifex licence, and there are no plans to acquire a paid license for any tool right now. Therefore, we would need to choose the Self-Hosted option for Weblate, leaving us without the "Free advertising" feature and requiring someone to host and maintain the Weblate server.

2. There is no guarantee that if we want to request a feature, it would be implemented any time soon unless there is enogh interest in it from other projects as well.

3. Interface-wise Weblate looks a bit outdated, imo. Transifex is definitely more convenient to work with, though it is far from perfect as well. At the same time, as you mentioned, the markup of changed strings is better implemented in Weblate.

This being said, I don't want to discourage anyone from exploring other tools and improving translators experience, but I would like to suggest that if the proposal is supported, we should give it a series of test runs first by launching a couple of test projects (for software and website) and having everyone involved in translations and @ripcurlx who pulls the translations in the app expressing their opinion.

**Comment by sanecito** [comment]
Thanks for your feedback! I've updated the issue to address all of your concerns I believe apart from the outdated look you mentioned.

In short:

1.  Weblate has a Gratis pricing tier which I believe Bisq would qualify for given Bisq qualifies for the Transifex FOSS pricing.

2.  True, but there's a greater deal of transparency via issues and implementation status via commits/PR's. Furthermore and perhaps more importantly, individuals across the community can create or otherwise contribute to bounties via BountySource, etc if there are so inclined.

**Comment by mpolavieja** [comment]
Hi @sanecito, what is the status of this proposal?

**Comment by mpolavieja** [comment]
Closed as stalled
