### ISSUE TITLE
Bonded role for becoming a mediator

### ISSUE THREAD

**Issue by leo816** [bisq-network/proposals#112]
I would like to become a mediator (mediation support is in development). I am very familiar with Bisq and the arbitration process and I am aware of the duties involved in that role and willing to set up the 10000 BSQ bond for mediators.
As mediators are not paid in BTC from trading fees like arbitrators I will deliver a monthly report about the number of cases and based on that number request BSQ for that role. 
My rate is 50 BSQ/mediation case.

thank you.

**Comment by mpolavieja** [comment]
Thank you for your offering. Please move this message to https://github.com/bisq-network/roles/issues

In order to mantain the list of proposals clear and specific, we need to folow the guidelines so we keep our github organized please see the proposal [submission and review process](https://docs.bisq.network/proposals.html)

**Comment by chimp1984** [comment]
@mpolavieja Please re-open as it is required for a mediator to make a bonded role request.

But we should add the accepted and bonded mediators to the role repo.

https://bisq.network/dao-proposals/# forwards to https://github.com/bisq-network/proposals/issues/#

**Comment by mpolavieja** [comment]
Accepted in DAO voting

**Comment by m52go** [comment]
@ripcurlx would you mind inviting @leo816 to the Bisq GitHub organization, so they can be assigned to https://github.com/bisq-network/roles/issues/87?

**Comment by ripcurlx** [comment]
> @ripcurlx would you mind inviting @leo816 to the Bisq GitHub organization, so they can be assigned to [bisq-network/roles#87](https://github.com/bisq-network/roles/issues/87)?

Done 👍
