### ISSUE TITLE
Bonded role for becoming a mediator

### ISSUE THREAD

**Issue by bisquser** [bisq-network/proposals#113]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I am very familiar with Bisq and the trading process and customer support and would like to become a mediator. My rate is initially 50 BSQ/mediation case. After the first month we can discuss again if that rate is realistic for the effort. I will also do the bonding of 10 000 BSQ.

**Comment by mpolavieja** [comment]
Thank you for your offering.  Please move this message to https://github.com/bisq-network/roles/issues 

In order to mantain the list of proposals clear and specific, we need to folow the guidelines so we keep our github organized please see [the proposal submission and review process](https://docs.bisq.network/proposals.html)

**Comment by chimp1984** [comment]
@mpolavieja Please re-open as it is required for a mediator to make a bonded role request.

But we should add the accepted and bonded mediators to the role repo.

https://bisq.network/dao-proposals/# forwards to https://github.com/bisq-network/proposals/issues/#

**Comment by mpolavieja** [comment]
Ok.  I have reopened the issue.  IMO the procedure should be changed so the request of bonded roles are in a separate repo.

**Comment by chimp1984** [comment]
>  IMO the procedure should be changed so the request of bonded roles are in a separate repo.

Agree, but it would require to change validation of url in the app

**Comment by huey735** [comment]
@bisquser did I miss some update on the new trade protocol? Isn't this proposal a little premature?

**Comment by ripcurlx** [comment]
> @bisquser did I miss some update on the new trade protocol? Isn't this proposal a little premature?

https://github.com/bisq-network/bisq/commits/release/v1.1.6 already includes mediation support and might be released early as next Monday.

**Comment by huey735** [comment]
@ripcurlx I don't mean to high-jack this thread but how will these changes manifest in the current trade protocol. Or will they at all?

**Comment by mpolavieja** [comment]
Accepted in DAO voting
