### ISSUE TITLE
Use 90 days average BSQ price for compensation requests

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#114]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

We use still 1 USD as orientation price for compensation requests. The BSQ price has been surprisingly stable around that value, probably because of that orientation. We should move to the real market price and use either the average or median price for the last 90 days. Thought median is not considering trade amount, so might be off in some cases.

This [PR](https://github.com/bisq-network/bisq/pull/3212) implements it so it is now easy to look up the average price. 
We could use the start date of the proposal phase for a consensus for the BSQ price used in that cycle. The maintainer of the compensation repository could upload a screenshot at that day and all contributors use that price for calculating their requests.

I would suggest that we start using the real price with Cycle 6. 

I will add a DAO proposal for voting. Before voting starts we still can adjust and discuss details...

**Comment by huey735** [comment]
@chimp1984 what are the pros of using the 90 day average? I'm sill leaning towards using USD as a unit of account.

Here's a chart of:
* blue - BSQ/BTC price
* red - USD/BTC price
* orange BSQ/BTC price 90d average
![bsqprice](https://user-images.githubusercontent.com/44140017/64419172-3423a800-d094-11e9-9a9d-c1b9504a7239.png)

**Comment by chimp1984** [comment]
BSQ price is not bound to 1 USD. That was onlye used before BSQ trading was possible to have a consensus about the conversion. Now the free market decides the price and we need to adopt compensation amounts. If BSQ is 5 USD a 10 000BSQ request would not be 10 000 USD as now but 50 000 USD. Quite a bit of a difference ;-)

**Comment by mrosseel** [comment]
a contributor could ask e.g. 5000 USD in the compensation request, which is then translated in the corresponding BSQ amount. This exchange rate will then indeed have to be determined using some average/median calculation by the dao code. The 'guess the exchange rate' burden should not be put on the contributor. Only possible downside to this is the gaming of the exchange rate if the period is too short, and an 'unfair' exchange rate if the period is too long.

**Comment by chimp1984** [comment]
The timing of the request could be then used to game it. You wait for a low price (or self trade to move the price)... Not a big risk but seems easier the manual way. But if anyone wants to implement that and build some safeguards against gaming, why not...

**Comment by sqrrm** [comment]
@mrosseel it's not an easy task to get an oracle to work properly. For now it would have to be fed to the system, presumably by contributors so we might as well agree before the filing of compensation requests and use that exchange rate.

I also think, like @chimp1984 mentions, that it invites market manipulation. I don't think it's a good idea to incentivize market manipulation further.

**Comment by chimp1984** [comment]
I think that proposal can be considered accpeted. 8 upvotes on 10.9.2019.
I would suggest that we start with beginning of Cycle 6 to take the 90 days average (visible in UI in the 1.1.6 release). The proposal repo maintainer should add a screenshot so that all contributors use that rate for new requests.

**Comment by chimp1984** [comment]
This proposal got accepted in DAO voting. So lets use the 90 days average BSQ price when proposal phase of  Cycle 6 starts as conversion rate for requesting BSQ.

**Comment by mpolavieja** [comment]
Approved on Cycle 5 DAO voting

**Comment by user718141** [comment]
>The BSQ price has been surprisingly stable around that value, probably because of that orientation.

#161
Could the contributors and burningman not be trading properly i.e. have an assumption over the price. Burningman should maximize BSQ burning and contributors maximize BTC issuance. Or perhaps the financial result is close to break even.
