### ISSUE TITLE
New Roles: Analytics Operator and Analytics Administrator

### ISSUE THREAD

**Issue by m52go** [bisq-network/proposals#115]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

The main Bisq site has finally gotten rid of Google Analytics in favor of Matomo, which is self-hosted and more privacy-minded. The Docs site will switch over soon too. This requires the creation of new roles. Neither role should require a significant financial commitment from the network, but we figure it better to make a clear proposal in the interest of openness.

I present these roles with the details [in the spec](https://docs.bisq.network/roles.html) to reduce ambiguity.

## Analytics Operator

This role would be for the person actually running the Matomo server, @wiz. This is wholly a new role, as the job was being done before by Google.

**Role Issue**
TBD upon approval

**Role Team**
TBD upon approval

**Duties**
* Ensure the Matomo server is functioning properly, secured, and updated
* Install plugins and provision accounts as required by the Analytics Administrator and others
* Write a monthly report on the appropriate issue.

**Rights**
N/A; no additional GitHub rights.

**Bond**
2000 BSQ, to account for the importance of analytics and need to handle the data responsibly.

**Other Considerations**
Ongoing costs will include hosting for the Matomo instance, at the discretion of the role owner, probably in the 50-100 USD range.

## Analytics Administrator

This role would be for the person operating the Matomo server, @FKrauss. Fabio is a long-time user who recently became a more active contributor. He has a background in this function of configuring analytics and driving web traffic.

Until now this work wasn't really done by anyone, as Google Analytics includes all functionality built-in, and this project made no significant efforts to use analytics beyond monthly traffic reporting. The goal for this role is to set up and maintain a Matomo configuration that is useful for the project, and help implementing techniques that optimize traffic acquisition, reduce bounce, increase conversions (downloads), etc.

**Role Issue**
TBD upon approval

**Role Team**
TBD upon approval

**Duties**
* Optimize Matomo setup for insights on traffic, conversions, etc.

**Rights**
N/A; no additional GitHub rights.

**Bond**
0 BSQ

**Other Considerations**
Ongoing costs will be based on work delivered.

**Comment by m52go** [comment]
Good to see positive initial feedback here. I will now file this as a Generic Proposal in the DAO for the current cycle.

**Comment by wiz** [comment]
@m52go since the voting hasn't started yet, I'd like to propose amending this proposal to increase the bond amount for analytics operator from 1K BSQ to 2.5K BSQ. After reviewing the other bonded roles after discussing with @ripcurlx, we felt 2.5K BSQ would be more appropriate considering the amount of trust involved which is around half of a BTC node operator role.

**Comment by mpolavieja** [comment]
Accepted on DAO voting Cycle 5
