### ISSUE TITLE
Bitcoin donation address holder

### ISSUE THREAD

**Issue by burning2019** [bisq-network/proposals#116]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I would like to become the Bisq donation address owner.
I am willing to set up the required 50000 BSQ bond.
I will buy BSQ with the received BTC at least every 4 weeks and if the  BTC balance goes above 50% (currently about 2.5 BTC) I will do the trades more frequently so that the balance does not exceed the 50% mark. I buy the BSQ on Bisq with the average market price in small amounts for fast trading. After the BSQ is purchased I will use the Burn BSQ feature in Bisq to burn the BSQ and convert it back to the BSQ economy.
The BTC address I will use is: 3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp
With the burn feature I can verify at any time the signature of a challenge message that I did the burning. I will do a monthly report at github.com/bisq-network/proposals/issues/116 about the trades and the burned BSQ and BTC balance.
For covering my effort, risks and compensation for locking up the high BSQ bond I will request 1000 BSQ per voting cycle. I bought a new ssd-disk  and use a dedicated computer for this role and so on. If the effort is not much I will decrease the request in subsequent cycles. Half the request is for the interest on the bond as well as the volatility risk (the bond is not tradable).

**Comment by chimp1984** [comment]
Invalid url: github.com//issues/116 
Should be probably a new role entry at https://github.com/bisq-network/roles/issues/

For additonal context: This role becomes relevant in context of the new trade protocol which is in development and hopefully gets deplyed in the next 2-4 weeks. See: https://github.com/bisq-network/proposals/issues/52

**Comment by m52go** [comment]
Looks like there is already an issue:
https://github.com/bisq-network/roles/issues/80

Can assign and document as appropriate once voting approves.

**Comment by chimp1984** [comment]
Ah good. 

Yes process is:
1. Request for bonded role on proposals repo in GH
2. If accepted make bond
3. Now the role is official and can be defined in the roles repo.

**Comment by mpolavieja** [comment]
Approved on DAO voting

**Comment by m52go** [comment]
@ripcurlx would you mind inviting @burning2019 to the Bisq GitHub organization, so they can be assigned to https://github.com/bisq-network/roles/issues/80?
