### ISSUE TITLE
Bonded role for becoming a mediator

### ISSUE THREAD

**Issue by bisquser** [bisq-network/proposals#117]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

--

I am very familiar with Bisq and the trading process and customer support and would like to become a mediator. My rate is initially 50 BSQ/mediation case. After the first month we can discuss again if that rate is realistic for the effort. I will also do the bonding of 10 000 BSQ.

**Comment by mpolavieja** [comment]
Approved on Cycle 5 DAO voting

**Comment by m52go** [comment]
@ripcurlx would you mind inviting @bisquser to the Bisq GitHub organization, so they can be assigned to https://github.com/bisq-network/roles/issues/87?

**Comment by ripcurlx** [comment]
Done 👍
