### ISSUE TITLE
Cash deposits and F2F independent of taker having an account

### ISSUE THREAD

**Issue by rafaelpac** [bisq-network/proposals#121]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

When a user wants to take an offer of **CASH DEPOSIT** or **F2F**, this user should not need to have his own account as a receiver set up.

It is not necessary and creates a blockade for new users. When somebody hears that there is this new piece of decentralized exchange software, no KYC/AML, and he or she just wants to get in and buy some BTC with cash (either depositing or F2F), it is weird to need to set up an account (that is for sellers, after all).

Specifically for CASH DEPOSITS, even if the user sets up an account to receive deposits, that is, for whenever he or she is selling, as far as I could dig into the code, it cannot be used to engage in a CASH DEPOSIT buy trade if the seller has a different bank.

But in cash-world, we don't need to have a bank account at the bank where we are depositing cash. Even though I don't have a bank account at some bank, I can enter their branch and deposit cash to the seller account (the seller is the one that needs to set up an account, not the buyer).

Well, that is what I think. I just had to open a new bank account today because there is somebody around selling and he chose to take cash deposits, but my bank was different from his.

I can code, not the ultimate master of coding, but I can do some... I have tried to understand how it works now, and I can tell that we would need some changes to `bisq/core/payment/ReceiptPredicates.java` and `bisq/core/payment/ReceiptValidator.java`, possibly some other places... I might need some help with Git.

**Comment by mpolavieja** [comment]
@rafaelpac, did you try to set up a dumb account with the same bank? (as a workaround in the meantime)

**Comment by mpolavieja** [comment]
I don´t think this has enough entity to be a proposal please see [submission and review process.](https://docs.bisq.network/proposals.html).  

What proposals are not good for:

- Smaller changes to existing components, infrastructure or processes, where a broad consensus of contributors is not required

Please consider closing this proposal and submitting it into the [support repo ](https://github.com/bisq-network/support/issues).

**Comment by mpolavieja** [comment]
@rafaelpac, please transfer this to the support repo https://github.com/bisq-network/proposals/issues

**Comment by rafaelpac** [comment]
Hi, sorry for not responding before, I went offline for a few days. I was thinking about my proposal. Actually, I don't find it to be a "smaller change", but I re-thought about it in the last days and even I was not completely aware of what changes I think Bisq needs. I think I have a better understanding now of what was disturbing me. Could I detail it here, open a new proposal or ask somewhere else if it is big enough to deserve a proposal status?

**Comment by rafaelpac** [comment]
> 
> 
> @rafaelpac, please transfer this to the support repo https://github.com/bisq-network/proposals/issues

That is where it is.

Do you mean support/issues? There it says that it is being used for reimbursements.

**Comment by m52go** [comment]
@rafaelpac yes, the support repository is for reimbursements. On GitHub, the main https://github.com/bisq-network/bisq repository is probably the best place for this discussion. Otherwise you could discuss on Slack (https://bisq.network/slack-invite). 

Since it seems you're proposing a change to an existing payment method, I don't think it would warrant a new proposal, but you can see how the discussion goes and what comes out of it.

**Comment by mpolavieja** [comment]
Sorry @rafaelpac I pasted the wrong link.  Yes, I think that https://github.com/bisq-network/bisq  would be the right place. 

Maybe you are right and it is a big change, but I think what you propose is easier / quicker to get implemented as an issue (proposals require support and consensus).  If you see that the issue remains unsolved and you still think it is an important change, then maybe a more elaborated proposal would get enough support.  But bear in mind that then your proposal would have to compete for priority with all the important proposals (new trade protocol, protection tools, API, off-chain protocol, etc).
