### ISSUE TITLE
New role: Keybase Administrators

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#128]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Bisq has had a Keybase team since @cbeams created it a couple years back, and since then over 100+ people have joined it. A few months ago @cbeams set me as the "admin" and I created some new channels and added a bunch of people and now we are starting to see daily conversations. However as the Keybase team gets used more, and especially in light of #127, I think we should formalize the role and responsibilities.

## Keybase Administrators
This role would held by primary @wiz (current keybase admin) and secondary @m52go (current slack admin).

The goal for this role is to maintain the Keybase channels, ban abusive users, and generally grow the Bisq community on Keybase and promote useful collaboration between the users.

**Role Issue**    
TBD upon approval    

**Role Team**    
TBD upon approval    

**Duties**    
* Moderate channels
* Remove abusive users
* etc.

**Rights**    
N/A; no additional GitHub rights.    

**Bond**    
0 BSQ    

**Other Considerations**    
Ongoing costs will be based on work delivered.

**Comment by wiz** [comment]
There being no objection, I added @m52go as admin on Keybase team and closing this proposal as approved

**Comment by m52go** [comment]
Reopened [the corresponding issue](https://github.com/bisq-network/roles/issues/60) and assigned admins accordingly.
