### ISSUE TITLE
Primary role owners should write monthly report comments on their respective role issues

### ISSUE THREAD

**Issue by cbeams** [bisq-network/proposals#13]
For the last few months, myself and now several other contributors including @ripcurlx, @alexej996 and @mrosseel have been writing monthly report comments on our respective role issues.

Here are some examples:

 - @mrosseel on the Freenode Admin role: https://github.com/bisq-network/roles/issues/22#issuecomment-378513604
 - @ripcurlx on the YouTube Admin role: https://github.com/bisq-network/roles/issues/56#issuecomment-377538172
 - @ripcurlx on the Analytics Maintainer role: https://github.com/bisq-network/roles/issues/40#issuecomment-378660293
 - @cbeams on the Founder role: https://github.com/bisq-network/roles/issues/1#issuecomment-355271944
 - @cbeams on the Twitter Admin role: https://github.com/bisq-network/roles/issues/21#issuecomment-378518384

I am proposing here that every primary role owner write a monthly report comment on the role(s) that they own (see #12 regarding the distinction between primary and secondary role owner).

The reasons for this are several:

1. These reports are a great way to share information with other contributors and with the Bisq community at large about the things you're responsible for. Anyone can click the "Subscribe" button on any role issue (or indeed can Watch the entire bisq-network/roles repository), and get regular updates about whichever roles they care about. This is a fundamentally scalable approach to information sharing.

2. These reports serve as a basic kind of "heartbeat" message from role owners, letting the network (of other contributors) know that they are in fact on top of their duties, or at least that they are not obviously derelict in their duties. If there is nothing to report on a given month, just say "Nothing to report". The important thing there is that you are reporting in the first place, and in doing so, letting folks know "all is well with this role" (and that you should indeed be compensated for performing the duties of that role).

3. Doing reports this way makes compensation requests easier to write and easier to evaluate. Where roles are involved, compensation requests should consist of nothing more than a set of links to monthly role updates. For an example of how this looks in practice, see my own compensation requests, e.g. bisq-network/roles#57 and bisq-network/roles#40. This way, you can say as much or as little about your roles as you like in the monthly reports for each, and then simply link to that report comment from your compensation request. This makes it easier for stakeholders to evaluate compensation requests during voting as well, because they know that compensation requests are mostly "thin" documents consisting of links to more substantive reports that follow a common format. This way we don't have to parse every contributors different, idiomatic approach to writing compensation requests.

So, to re-iterate: **I propose that every primary role owner start writing monthly report comments starting with the next round of compensation requests that we will vote on from May 1–3rd.**

If we have a rough consensus on this proposal by that time, I will vote `0` for any proposal that does not include monthly report comments in May, and I will vote `-1` for any proposal that does not include them in June and beyond.

Also, I propose we continue with the format that has emerged for these comments, which is as follows:

```
## 2018.03 report

[primary role owner's notes, observations, data as they see fit]

/cc bisq-network/compensation#42
```

Where the date obviously changes with each month, and the linked compensation issue is that role owner's current (draft) compensation request for the month. You can see the effect that this kind of round-trip referencing has between roles and compensation requests by looking at my request for this month at bisq-network/compensation#57.

I wanted to get this proposal together now, just as our May voting is finishing up, so everybody has plenty of time to consider it prior to the next voting round. Thanks, all.

(See also this month's Roles Maintainer role update, where I first suggested that we institutionalize this process of writing monthly updates: https://github.com/bisq-network/roles/issues/28#issuecomment-378542433)

**Comment by ManfredKarrer** [comment]
I agree basically but have the feeling that it would require (at least for me) quite a bit of time which might be better used elsewhere. Maybe it is like with the role specs just a bit too early to enforce those more strict rules. For certain roles though it makes more sense than for others for sure. So for now I stay neutral to that proposal. Concept-ACK but not timing-ACK... ;-)

**Comment by ripcurlx** [comment]
I agree with the proposal as I think it will help anyone who wants to take over a role later to be able to see what is required on a monthly basis. Also it is kind of an intermediary step if there is no exact role description available to think about what makes sense to add to the role description based on the monthly reports.

**Comment by flix1** [comment]
Absolutely agree with this. As the team grows this is the only way to check on status in asynchronous manner. Writing a few lines a month per role on what (if anything) was done seems like a bare minimum requirement to claim compensation.

**Comment by cbeams** [comment]
Closing as accepted, with 5 👍 and no 👎 at time of this writing:

![image](https://user-images.githubusercontent.com/301810/39630212-f9bb2b78-4fae-11e8-91a9-18affc949308.png)

@ManfredKarrer, thanks for giving this a try this month, despite your concerns about it being too time consuming. Everyone else has taken this on as well, and while there remain rough edges to smooth out, we can do that over the voting periods to come. I continue to have ideas about how to streamline this as we go (I desperately need that streamlining as well, while I still have so many roles on my plate).

In any case, I'll capture the decisions made here in the forthcoming Roles at bisq-network/bisq-docs#46.
