### ISSUE TITLE
Include an option to prevent offers from being taken by non-signed accounts

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/proposals#133]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

### Problem description

It should be obvious that new users that come to Bisq to buy 0,25 BTC or more don´t really want to make 25 or more transactions as that would be prohibitively expensive and time consuming.  If those users I am referring to are posting offers to buy 0,01 BTC, it is very likely that they post them in order to get their account signed. 

If their offers are taken repeteadly by non signed accounts, that could be quite frustrating.  It could be a rather serious onboarding barrier as it would be a waste of time and fees for the new user.  Moreover, having a lot of undesired small transactions might be also an issue with the bank.  Might be too noisy.

### Suggested solution

Provide the **option** to makers to restrict their offers so they can only be taken by signed accounts.  The risk of siloing liquidity amongst old users is very low, as it is unlikely that old signed users post offers as low as 0,01 BTC to trade only with signed accounts.   And if old users restrict their sell offers of 0.06, 0.12 or 0.25 BTC, the buyers that have the limits to take those offers are probably already signed, specially on the long run.

I suggest to include this option as a checkbox in the "Create Offer" screen and that it is always unchecked by default if the account is already signed.  If the account with which the offer is being created is unsigned, I am not sure if it should be checked by default.  If it is checked by default it will make things easier for the new user.  If it is unchecked by default, a pop up would be necessary to explain the user that he can check that checkbox if he wants to get his account signed quicker (not to waste time and fees).

**Comment by ripcurlx** [comment]
> If it is enabled by default it will make things easier for the new user.

The only risk for newbies would be, is that this checkbox might be checked forever. Maybe if we check it by default we have to additionally let the user choose in the "you got signed"-popup, if we should deactivate this setting again.

**Comment by mpolavieja** [comment]
> this checkbox might be checked forever.

My suggestion is that the checkbox would be checked by default **only** if the acount with which the offer is being created is an unsigned account.  Otherwise it would be always unchecked. (maybe the confusion is that I used the words "enabled" / "disabled" instead of checked / unchecked, I´ll ammend that.)

**Comment by mpolavieja** [comment]
Would it be a good idea to enable this checkbox only for **buy** offers with insecure payment methods? The checkbox would not be even available for BTC sell offers, so it doesn´t play as a barrier in any case?   

The only downside I am able to see is that if it is checked by default for unsigned accounts, new users that only want to test and play around with Bisq doing small real trades should be aware of this so they know they have to uncheck the box when creating the offer.

As a more general thought, I am of the opinion that from a security point of view this kind of protection, if implemented, should be for the BTC sellers which are the ones that bear the most risk when accepting fiat, but for the sake of bootstrapping and being as less disruptive as possible,  I suggest to use this option very specifically (at least initially) to make the signing process less painful for newbies.

**Comment by sqrrm** [comment]
I think it would be ok to have it there for both buy and sell offers for unsigned accounts as accounts get signed in both directions. But then you already get that filter implicitly when selling if selling more than 0.01 BTC.

**Comment by mpolavieja** [comment]
As @flix1 suggested during yesterday´s call, a very good an easy workaround for this problem is to post very small offers, like selling 0,0001 BTC.

The only drawback of doing it this way is that the signer would need a huge premium over the market if he wants to cover his costs.   So market incentives for seed signers are a bit better if this is possible to do it with 0.01 BTC and restricting signed accounts.

In any case, as Félix suggested, we should encourage those who are willing to collaborate by signing new  accounts to use this suggestion to improve chances that his offers are only taken by unsigned accounts. (Cautioning also not to sign too many accounts so the trust tree is not too narrow, and always remembering to delay the release of the funds as much as possible).

**Comment by ExPrgrmmr** [comment]
Shouldn't a web of trust keep out unknown elements? 

https://github.com/bisq-network/bisq/issues/3590

**Comment by ripcurlx** [comment]
> Shouldn't a web of trust keep out unknown elements? Perhaps KYC?

As I assume this is a sarcastic comment: 🤔 Yes, we could just prevent anyone else to join the web of trust, that would keep it safe for sure.

**Comment by ExPrgrmmr** [comment]
So is it naivety or false security or is something wrong is the follow up question.

**Comment by ExPrgrmmr** [comment]
> > Shouldn't a web of trust keep out unknown elements? Perhaps KYC?
> 
> As I assume this is a sarcastic comment:  Yes, we could just prevent anyone else to join the web of trust, that would keep it safe for sure.

@ripcurlx 
I am suggesting this now for increased safety and security

https://github.com/bisq-network/bisq/issues/3604

**Comment by mpolavieja** [comment]
@ripcurlx, @sqrrm and everyone else.  Is this worth implementing or should I close it as stalled?

**Comment by sqrrm** [comment]
I would say it's low priority. Ok for me to close as stalled.

**Comment by mpolavieja** [comment]
Closed as stalled / low priority

**Comment by mpolavieja** [comment]
@sqrrm , I have had a conversation regarding onboarding new users within the scope of growth plans.  The problem of signed users taking 0,01 BTC sell offers still remains.     I am reopening this issue wo we can discuss it again.  Maybe If the development effort is not big, it might be worth including it as a priority.

See also the concerns raised by @cbeams here: https://github.com/bisq-network/projects/issues/10

**Comment by sqrrm** [comment]
Yes, it's one of my top priorities. I haven't been able to do much development lately so I had to focus on even more urgent issues. It's not forgotten.

**Comment by MwithM** [comment]
Is this on a to-do list? Let me know if it is and I'll close as approved.
I edited the [wiki](https://bisq.wiki/Account_limits#How_to_get_an_account_signed) to explain the "risks" on creating your own offer to get your account signed. Taking one is recommended while this is not developed.

**Comment by MwithM** [comment]
Closed as stalled. Not a priority.
