### ISSUE TITLE
Off-chain BTC trading using Lightening Network

### ISSUE THREAD

**Issue by ExPrgrmmr** [bisq-network/proposals#134]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

The Lightning Network is a cryptocurrency "Layer 2" payment protocol that operates on top of the blockchain. Lightening nodes form a mesh network where repeated bidirectional payments can take place. Only the opening and closing of a channel is registered on the blockchain.

The use-case in question is on a marketplace (i.e. Bisq) with a multisignature transaction. The payment channel is administered by the marketplace. The payment channel is used here for a single payment only. This results in one more blockchain transaction compared to direct a wallet-wallet transfer.

The main reason for adopting it is that it implies a trading protocol in a standardized and recognized way.

**Comment by mpolavieja** [comment]
This proposal does not make any sense, please see proposal [submission and review process ](https://docs.bisq.network/proposals.html).  You can reellaborate and submit a new one if you want.

**Comment by ExPrgrmmr** [comment]
https://github.com/bisq-network/proposals/issues/125
