### ISSUE TITLE
Start daily update calls for active developers 

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#137]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I suggest that we start to have short daily update meetings (voice/video chats, anonymous contributors can use the text chat) for developers who actively and regulary work on Bisq. This should improve communication so that all devs know what others are working on and should consist in a short update of the past work (last day) and current work (current day, next day) with about 1 minute each dev. It should be time-boxed to 10-15 min. to not waste too much time and is not intended as discussion meeting for bigger topics or onboarding for new developers. By providing a regular pulse it should help to improve motivation and commitment and also helpt to communicate when developers are on holiday or not working so we get a better feeling about our work force. Any developer can join but I think it might be better to limit it to development area. Other areas like webpage, support could start the same initiative among them. The Bisq brief or other formats can be used for cross communcation between different "departments".

Additionally it would be good if developers fill in either in our existing Google calendar or in a new dedicated calendar the time when they are not available (holiday,...).

**Comment by wiz** [comment]
Yes! A huge part of being in any organization or company or startup, is simply showing up to the office each day and updating your colleagues about the status of the projects and tasks you are responsible for... if nobody takes responsibility for things, they never get done. I think Bisq would greatly benefit from a quick 10 minute scrum call each day, where we coordinate on what projects we're working on, and the current status.

We should also keep a log of attendance for who shows up and who doesn't join the call, and reference this log with our compensation requests, just for everyone to have more skin in the game. If you have privacy concerns about joining a phone call, you can join by chat.

**Comment by ripcurlx** [comment]
I agree that a daily standup would help to increase communication and collaboration between devs. But it only works if everyone is prepared for it and that we find a time spot that works for everyone. To make it more obvious who is working on what to the outside world, besides the standup, we could think about assigning devs to stories  and start to use them as intended on our ZenHub Kanban board (Inbox, Discussion, In Progress, Closed). We do have some additional swim lanes like Bounties and Priorities configured right now we could get rid of.

**Comment by clearwater-trust** [comment]
The arbitrators/mediators would benefit from daily/weekly/monthly calls too.

**Comment by devinbileck** [comment]
I agree sharing status updates is a very good idea. For those that cant attend the chat, perhaps can post status updates in a chat channel.

**Comment by ripcurlx** [comment]
I just created a quick Doodle for  Monday next week to find a good time slot for most devs. Please add your preferred time here: https://doodle.com/poll/2qk2bnw6hd56tkyh

**Comment by ExPrgrmmr** [comment]
It is a balance between DAO and open software principles if a core is going to act as employees in a standard organisation. But maybe then regular hiring of "personnel" is possible, but guess that was not the intention. Should have developer roles in DAO then for some purpose. Implying kicking out developers not in DAO.

**Comment by ExPrgrmmr** [comment]
DAO vs Open source? Employees next?

**Comment by chimp1984** [comment]
> DAO vs Open source? Employees next?

@ExPrgrmmr Like in many other places your comments make no sense. I think it reaches a level where a ban is getting justified. Github is used for work not for trolling.

**Comment by ripcurlx** [comment]
Time slot winner is 8pm (CET) https://doodle.com/poll/2qk2bnw6hd56tkyh. I think we should start with our first daily update call tomorrow on Nov 20th 8pm. I'll post the URL for the daily standup in the #dev channel on keybase. Please everyone who participates be prepared to compress your status update within one minute max.

**Comment by ripcurlx** [comment]
@freimair Would it be fine for you to host this calls when I'm unavailable or host them in general?

**Comment by wiz** [comment]
@ripcurlx as the maintainer I think you should lead the calls every day 😉

**Comment by chimp1984** [comment]
Close that as it has been implemented.

**Comment by cbeams** [comment]
Update: I've posted the following request to all members of the Bisq keybase team. We only ever did video calls once or twice (as suggested in this proposal), and the practice that has emerged is to send textual updates at or around 8p CET in the #standup channel. This practice has been working pretty well, so I've asked every active contributor to begin doing it on days that they do work for Bisq.

> `@channel` this message is primarily intended for current and potential future contributors, but users and BSQ stakeholders may also be interested in its content. Please forgive the global `@mention`, but I actually do want to get everyone's attention here.
> 
> As many of you know, we're in the process of putting together a budget, a prioritized list of goals for the project and other important organizational changes. These will be announced soon and will begin taking effect with DAO Cycle 10, which is just starting now. Stay tuned for full details, but in the meantime **I have a request for everyone that is currently contributing, including anyone who plans to issue a compensation request for Cycle 10:**
> 
> You may have seen that a number of us have been submitting updates every weekday in the #standup channel for the last month or so. **I'm now asking everyone who plans to submit a compensation request in Cycle 10 to begin doing the same.**
> 
> If you're not familiar with what a "standup" is, it's a name for a short meeting that many professional software teams hold every day. Team members get in the same room and literally stand up while giving updates on what they're doing. The discomfort of standing helps ensure that the meeting goes quickly. Obviously we can't actually get in the same physical room together and you don't actually have to stand up when you send your update, but you get the idea.
> 
> Updates should typically be short and as clear as you can make them. A good guideline is the "three questions" common to many standup meetings (from https://en.wikipedia.org/wiki/Stand-up_meeting#Three_Questions):
> 
>  1. What did I do yesterday that helped the team meet the sprint goal?
>  2. What will I do today to help the team meet the sprint goal?
>  3. Do I see any impediment that prevents me or the team from meeting the sprint goal?
> 
> Nevermind the "sprint goal" for now. As we roll out the budget and priority list, it will become clear what the current goals are, and you'll easily be able to figure out whether what you're working on is toward those goals or not (and therefore whether what you're working on is eligible for compensation or not). **For the time being, please just send an update that says what you worked on today and what, if anything, is standing in your way of making progress.**
> 
> If you don't work on Bisq every day, that's just fine and there is no need to send an update every day. Just send an update every day that you do work. In any case, if you don't send an update the assumption will be that you did not contribute anything on that day.
> 
> If you're someone who typically works most or every day and you know you're going to be away for a while, send an update that says so.
> 
> Those of us that have been doing this for a while try to send our updates around 8p Central European Time, but our contributor base is widely distributed, so **if 8p CET is not convenient for you, please send your update at the end of your workday,** whenever that may be.
> 
> The goal of doing these standup updates is to help us focus together on accomplishing the most important things and to help control costs as we do so. They also have the wonderful effect of making it feel like you're _actually part of a team._ I and the others who have been doing these updates see them as the bare minimum amount of communication required for a distributed team like ours to stay in touch and succeed.
> 
> If you have other questions about how to submit these updates, please ask them here or in the #standup channel. If you are unwilling to accept this request, please consider sending me a direct message to explain why; I will appreciate and take seriously any feedback. Please hold off for now on questions about the larger set of changes we're rolling out; it's my number one priority to deliver an announcement about that as soon as possible.
> 
> Thanks for reading, and I look forward to seeing you in #standup!
> 
> P.S.: Note that I plan to cross-post this message to the `bisq-contrib` mailing list, which I intend to use a bit more frequently for this sort of thing. If you're not already subscribed, please consider doing so at https://lists.bisq.network/listinfo/bisq-contrib. Everyone interested in BSQ, the Bisq DAO and our plans for Bisq in general is welcome to join.

**Comment by ripcurlx** [comment]
> Update: I've posted the following request to all members of the Bisq keybase team. We only ever did video calls once or twice (as originally suggested in this proposal), and the practice that has emerged is to send textual updates at or around 8p CET in the #standup channel. This practice has been working pretty well, so I've asked every active contributor to begin doing it on days that they do work for Bisq.
> 
> >

I'll remove the calendar entry for the video calls they are not taking place as mentioned above.
