### ISSUE TITLE
Bounty for a comparative study of DAO projects

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#141]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

## Overview
I would suggest to offer a bounty for a comparative study of the most prominent DAO projects. The study could be made by several persons familiar with one of the candidate projects. It can also be done by active members of those projects but critical objectivity is a key goal - this is not intended to be a PR paper for any project (also not for Bisq or course).

## Goal
The goal of that study is to learn about the concepts and solutions other DAO projects have developed and learn from those. As most of those projects are based either on Ethereum or have their own blockchain there is usually not much overlap and knowledge transfer as each crypto community tends to be a bit self-focussed and partizipants are often too busy to follow what is going on outside of their own eco-system. Tribablism and ethical concern with ICOs are adding more to the mix to prevent a potentially productive knowledge transfer. I think this is unfortunate but understand the reasons as I am myself victim of that as well. This proposal is an attempt to get over those boundaries in the hope to benefit from learning about alternative solutions to similar problems.

## Criteria for project selection
The study should define criterias for the selection of the DAOs we want to cover.
I leave it to the study authors to define those criterias but I think clearly failed/fraudulent projects like "The DAO" should be ignored for an in-depth analysis.

## Candidate projects
I have not followed closely other projects so I might miss some important projects. The projects which come to my mind are:
- [Bisq](https://bisq.network/)
- [Colony](https://colony.io/)
- [Aragon](https://aragon.org/0)
- [Decred](https://decred.org/)

## Main content
The main aspects covered by the study should include (just a rough suggestion, study authors should define their own list):
- What is the main goal the projects tries to achieve with it's DAO
- How decentralized and censorship resistant is it?
- How does it work from the technical perspective?
- How is the organisational/legal structure (e.g. based on foundation, companies,...)?
- What are the properties and use cases of the token?
- How was it funded? What is the revenue model?
- How big is the community of developers, contributors and users?
- What makes it different to other DAOs?
- What are the weak points/main problems of that DAO?

## Process
The result of the study should be sent to the representatives of the selected projects for review so they have a chance to correct mistakes and add missing pieces. 

## Format
A format which allows easy update would be good. A wiki format might work for that, but up the the study authors.

## Compensation
I assume that the main content will be delivered by the project representatives - it might be a bit like an interview where the study authors prepare the questions and structure and the projects representatives provide the answers and content. I leave the estimation for the costs for the study to the bounty taker. We can decide then if we want to fund that or not. 

## Side note:
Anyone up for adding Bisq to the [Wikipedia page about DAOs](https://en.wikipedia.org/wiki/Decentralized_autonomous_organization)?

**Comment by thehapax** [comment]
I'd love to add studies here for other DAO projects that I'm currently involved with. They aren't listed here but I have knowledge of both Bitshares DAC as well as EOSIO DACs. Would these be acceptable? They are working models but it seems like a lot of peel don't know about them. I do know that @m52go was on a panel with Bitshares DEX at one point; many are familiar with it as an old project but also unaware of how mature it is as a DAC

**Comment by thehapax** [comment]
> > _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._
> 
> ## Overview
> I would suggest to offer a bounty for a comparative study of the most prominent DAO projects. The study could be made by several persons familiar with one of the candidate projects. It can also be done by active members of those projects but critical objectivity is a key goal - this is not intended to be a PR paper for any project (also not for Bisq or course).
> 
> ## Goal
> The goal of that study is to learn about the concepts and solutions other DAO projects have developed and learn from those. As most of those projects are based either on Ethereum or have their own blockchain there is usually not much overlap and knowledge transfer as each crypto community tends to be a bit self-focussed and partizipants are often too busy to follow what is going on outside of their own eco-system. Tribablism and ethical concern with ICOs are adding more to the mix to prevent a potentially productive knowledge transfer. I think this is unfortunate but understand the reasons as I am myself victim of that as well. This proposal is an attempt to get over those boundaries in the hope to benefit from learning about alternative solutions to similar problems.
> 
> ## Criteria for project selection
> The study should define criterias for the selection of the DAOs we want to cover.
> I leave it to the study authors to define those criterias but I think clearly failed/fraudulent projects like "The DAO" should be ignored for an in-depth analysis.
> 
> ## Candidate projects
> I have not followed closely other projects so I might miss some important projects. The projects which come to my mind are:
> 
> * [Bisq](https://bisq.network/)
> * [Colony](https://colony.io/)
> * [Aragon](https://aragon.org/0)
> * [Decred](https://decred.org/)
> 
> ## Main content
> The main aspects covered by the study should include (just a rough suggestion, study authors should define their own list):
> 
> * What is the main goal the projects tries to achieve with it's DAO
> * How decentralized and censorship resistant is it?
> * How does it work from the technical perspective?
> * How is the organisational/legal structure (e.g. based on foundation, companies,...)?
> * What are the properties and use cases of the token?
> * How was it funded? What is the revenue model?
> * How big is the community of developers, contributors and users?
> * What makes it different to other DAOs?
> * What are the weak points/main problems of that DAO?
> 
> ## Process
> The result of the study should be sent to the representatives of the selected projects for review so they have a chance to correct mistakes and add missing pieces.
> 
> ## Format
> A format which allows easy update would be good. A wiki format might work for that, but up the the study authors.
> 
> ## Compensation
> I assume that the main content will be delivered by the project representatives - it might be a bit like an interview where the study authors prepare the questions and structure and the projects representatives provide the answers and content. I leave the estimation for the costs for the study to the bounty taker. We can decide then if we want to fund that or not.
> 
> ## Side note:
> Anyone up for adding Bisq to the [Wikipedia page about DAOs](https://en.wikipedia.org/wiki/Decentralized_autonomous_organization)?

Would love to do this. Just give me the green light and I will do.

**Comment by m52go** [comment]
I like the idea of exploring the space to mine for ideas, but as much as I hate to say it, I'm skeptical there would be much value in the outcome. Could be my ignorance though. 

Would prefer to see a short pre-study with expected goals and insights included with any bounty proposal, along with a justification of why such a thing would add value to the Bisq network (i.e., why it should be compensated).

Regarding Wikipedia...do we really want Bisq to be listed among such other projects? At the risk of sounding like a snob, Bisq just seems like a totally different thing, and I'm not sure the differences can be sufficiently explained on that page without significant work/restructuring.

**Comment by sqrrm** [comment]
I'm with Steve. Don't want to spend too much on vague research but since I don't know what's out there and what's there to learn it would be silly to say it's not worth it.

**Comment by eyalron33** [comment]
I comment using this Github account since that's the one I use for compensation requests. I think though that I'm better known in the community as Neiman.

I'm a bit of a DAO junkie, so I'll be happy to conduct this research. I do such researches regularly as a freelancer, and normally charge 8K-10K, depends on how much work was needed in the end. If the price is OK, I could aim to publish this research in January 2020 (or at latest in February 2020, depends on when I begin). 

As for who I am, I hope some here know me for my contributions for Bisq DAO and Bisq new trading protocol. 

I'm gonna let others decide on the necessity of such a research, but here's my point of view:

On the technical level I doubt Bisq has much to study from other DAOs, since none of them is based on Bitcoin, and afaik none of them is a second layer DAO like Bisq.

However, on the governance level I think there is what to study. Either in "what to do" or in "what not to do". Bisq governance is simple to nativity at the moment, and my personal view was always that it will have to evolve with time as the project grows. However, it is unclear if and how to evolve it, and here we can possibly study from other projects efforts, who I believe did some creative experiments.

Besides the projects mentioned in the original message, I believe that MolochDAO and Daostack may be interesting. But further research is needed to really decide which DAOs are of interest to us.

I know that this proposal is a bit vague, so if desired I could do a short pre-study to describe the future research better. However, I usually also charge a few hundred dollars for such pre-studies (since they do take a considerate time and effort).

I understand if this proposal will be rejected due to its price or if people think it's irrelevant to the project. However, if it not it will be an interesting project for myself.

**Comment by chimp1984** [comment]
@eyalron33 
Thanks for your offer and input!
Let's see if that proposal gets more support. So far not much support has been voiced.

**Comment by sqrrm** [comment]
I like the idea but I don't think this is the right way to use our limited funds right now. Probably best to revisit in a few months time.

**Comment by user718141** [comment]
>What are the properties and use cases of the token?

Everybody wants their token as an investable object (stake) in the DAO. But your corrupt compensation scheme does not allow that. Fools.

**Comment by chimp1984** [comment]
Closed as it did not reach enough support.

**Comment by m52go** [comment]
Here's a research report on DAOs published last week by an Australian firm. The firm reached out a couple of weeks ago for a blurb on Bisq (there is a mention toward the end in the Appendix, but sadly not much more). Seems like a decent effort overall though.

[DAO-A-Decentralized-Governance-Layer-for-the-Internet-of-Value.pdf](https://github.com/bisq-network/proposals/files/4692664/DAO-A-Decentralized-Governance-Layer-for-the-Internet-of-Value.pdf)
