### ISSUE TITLE
Default to Bisq-wallet unless extra privacy is wanted

### ISSUE THREAD

**Issue by taxd** [bisq-network/proposals#147]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I propose that the present system where one has to transfer BTC to and fro the Bisq trading wallet at each trade should be optional and that the default should be that this is done automatically from the Bisq-wallet. Users that want the extra privacy-protection of using an external wallet to fund the trade should have select this in the Settings. At the first time upstart Bisq could ask the user if they want the extra privacy-protection. 

I suspect that most users do not use the possibility of funding a trade using an external wallet and every click saved will improve the UX.

**Comment by sqrrm** [comment]
A good point but I feel this is more suitable for the redesign project and not as a stand alone proposal. I suggest you join the keybase #design channel and share your ideas there.

**Comment by MwithM** [comment]
Is it a big burden for users? I've used both ways to fund the wallet depending depending on my needs and maybe changing this is counterproductive for ease of use.

**Comment by mpolavieja** [comment]
@taxd I agree with @sqrrm that this should not be a proposal.  Could you please close it once it is included somewhere else?  Thanks.
