### ISSUE TITLE
Request to take over the Bisq donation address

### ISSUE THREAD

**Issue by burningman2** [bisq-network/proposals#149]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I would like to request to take over the Bisq donation address. 

I will do once a week a sale of the received BTC and burn the purchased BSQ afterwards and post the trade history as well as the proof of burn.

I will trade according to the following rules:
I will take all the best "sell BSQ" offers on the market sorted by BSQ price. If an offer requires more BTC as I have left over I will skip to the next offer. As soon the left over BTC is too small to make trades with reasonable prices I will leave it for the next trade round.
I will trade always on the weekend (2 days). So interested sellers should be online with their offers on the weekend.  I might wait between trades to get better prices but try to get all traded over the weekend. I might prefer non-instant offers, as the 1 hour limit might produce too much stress for me.

My address is: 3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV

I will request 800 BSQ per month for compensating my time for trading/burning/reporting if I get accepted. This covers also the included risks (BSQ bond, trade mistakes,...).

Why should anyone trust me?
- I have to set up the 50 000 BSQ bond
- Only if some major stakeholders will accept me in DAO voting I can become the "burning man" - I will reveal my identity to some Bisq core contributors (who might up-vote me then in DOA voting), but I prefer to keep my anonymity to the public.
- Do not vote or reject my proposal if you don't trust me

**Comment by sqrrm** [comment]
This sounds good to me, but I would suggest to not have it as a solid requirement to trade only over weekends as there could be spikes in BTC coming in during the week that should be addressed sooner. The aim should still be to trade over weekends during normal times.

**Comment by burningman2** [comment]
Made the proposal in Bisq: Here is the tx ID: 0cb712cd0f4c0e375b2baef1dedebedf9061ee9c0cd45ede0537563579e9ccf0

**Comment by burningman2** [comment]
> This sounds good to me, but I would suggest to not have it as a solid requirement to trade only over weekends as there could be spikes in BTC coming in during the week that should be addressed sooner. The aim should still be to trade over weekends during normal times.

Yes agree. I thought it is just the easiest way that everyone knows when trading happens in case they do not have their Bisq app running all the time.

**Comment by MwithM** [comment]
I will reject this proposal because this role requires a high grade of [trust](https://github.com/bisq-network/proposals/issues/135) and I don't know you. I know there's advantages of being anonymous, but I feel it's not responsible to vote blindly on this proposal because bond can't cover possible damages.

Maybe address holder proponent should first reveal its identity to major stakeholders and then one of major stakeholders should make this role proposal. It's still not the best, but at least we would have a reason to trust on this role owner.

Anyways, this is not clear to me:
Will you replace the first Bisq address holder or is this a second role for the same function?

**Comment by burningman2** [comment]
@MwithM 
This is exactly the correct attitude and shows that you take due diligence serious!
Only those should vote and accept who are sure. 

Privacy and transparency is sometimes hard to combine. Having anonymity improves the level of censorship resistance, but if any core contributor is willing to take the role in a non-anonymous way, I have no problem to leave it to that person then....

 > Will you replace the first Bisq address holder or is this a second role for the same function?

It will replace the current role owner. There is no support for multiple role owners implemented.

**Comment by MwithM** [comment]
> It will replace the current role owner. There is no support for multiple role owners implemented.
I'd rather keep the current burner. At least has proven some track record.

I agree with some of your the rules you're proposing, though.

**Comment by wiz** [comment]
> Made the proposal in Bisq: Here is the tx ID: 0cb712cd0f4c0e375b2baef1dedebedf9061ee9c0cd45ede0537563579e9ccf0

This proposal is only to take ownership of the donation address, where is your bond proposal?

Also, do you have a Keybase account?

**Comment by burningman2** [comment]
Ah sorry forgot to make a proposal for the bonded role. 
Just made the bonded role proposal. 
Tx ID: aa616eef833f3e6176b83e197da0db08166825eaeb80f0d39ff4dc472fd1af50

I do not use Keybase. I think communicating in Github should be enough.

**Comment by wiz** [comment]
> I do not use Keybase. I think communicating in Github should be enough.

Well, since this is a very trusted role I think you will get more support if you come on Keybase and talk to the regular contributors, unless you are already doing so.

**Comment by wiz** [comment]
I agree with @MwithM on his previous points:
1) the 50K BSQ bond is only worth $33K USD or so
2) the Burning Man role could buy the entire offer book and then do nothing and wait, and all the trade money would get donated to the burning man address and steal 10 ~ 20 BTC per attack
3) the current Burning Man has some merit already
So I would NACK this proposal

**Comment by burningman2** [comment]
@wiz That is perfectly fine and a responsible attitude. I share my identity only with few major stakeholders and if they accept my request it represents trust of those who have lots of skin in the game.

**Comment by burningman2** [comment]
My request got accepted in DAO voting and I locked up my bond.
https://bsq.wiz.biz/tx.html?tx=efa078ed800ae6bf24571ca842a1d41830f8cd9b76c3c2286f4d6572fb1bcaa5

Param change request:
<img width="709" alt="Screen Shot 2019-12-22 at 11 25 02" src="https://user-images.githubusercontent.com/58760636/71324532-c8801200-24ad-11ea-89bf-a82a3a9104ae.png">

Role:
<img width="714" alt="Screen Shot 2019-12-22 at 11 25 22" src="https://user-images.githubusercontent.com/58760636/71324533-c918a880-24ad-11ea-96c4-3d099a4ff1ea.png">
