### ISSUE TITLE
Add Detailed BSQ Issuance Information to Cycle Report

### ISSUE THREAD

**Issue by julianknutsen** [bisq-network/proposals#150]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

### TL;DR

Currently, the [end-of-cycle report](https://bisq.network/blog/cycle-7-results/) currently lists the amount of BSQ that was issued and an approximate amount that was burned. I propose that we expand the BSQ Issuance information to include the breakdown of where the issued BSQ was "spent".

### Motivation

> I use the term "spent" in this proposal to reference issued BSQ that causes inflation.

There are two major questions that I had when evaluating the end-of-cycle report:

1. Where is the project spending money right now?
2. Does that spending match the priorities of the project?

Currently, it is hard to find where the money is being spent so evaluating whether or not the values are inline with the project priorities is hard. Currently, an interested party has to go through every compensation report, decode the initiative that each person participated in, and group them together. Then, they can analyze the data.

But, I believe that having 1 person do this (and potentially updating the compensation request template to require contributors to fill in this information) will give much more transparency to the project in terms of how much Bisq is spending on each initiative.

With that information more accessible, it should make it easier to identify areas where more investment is needed or incentives should be changed to ensure the priorities of the project are also the priorities of the contributors. Or, where funding should be reduced because the ROI isn't there.

### Implementation

I propose a simple broad set of categories that can always be expanded or reduced as appropriate. Each of these would be a sub-bullet under the "X BSQ Issued" line that already exists in the end-of-cycle report. The goal would be to start collecting the information so future proposals or discussions can happen backed with real data.

I've gone through the last few cycles and I think this list covers the major pieces. Feel free to comment if you think something should be added or removed. Or, if you have a particular use case that isn't covered in one of these sections.

1. Software Development (devs, maintainers, etc)
2. Testing
3. Marketing
4. Translations
5. Support
6. Infrastructure (Node operators, hosting, donation address owner salary, etc)

**Comment by m52go** [comment]
I like this idea...since I usually do these reports, here are my concerns:

* time required to collect the information, as it would need to be done manually, although maybe it's less daunting than it looks.
* is "software development" a sufficiently helpful category? Would it be better to further segment development into 3-4 initiatives?

I can give it a go for this cycle's results, and maybe then we can have a better discussion about how it worked out from my end as producer and others' end as consumers/readers.

**Comment by m52go** [comment]
Also if this works out, we should probably give some thought to structuring findings such that they're analyzable over time (the utility of such data is greatly diminished if it's stuck in a pile of text). 

So maybe the raw data is stored in a JSON file in some Bisq repository, updated at the end of each cycle, and the report presents the data in a well-written, human-readable format.

**Comment by clearwater-trust** [comment]
What about an issuance report from the REFUND AGENT? At this point nobody knows if failed trades are being properly handled. Transparency is a **must** for this role.. (ALL roles should be transparent).

**Comment by chimp1984** [comment]
@julianknutsen 
I highly welcome that idea and discussion!

As I commented at https://github.com/bisq-network/compensation/issues/417#issuecomment-565268347 I think we are lacking at the moment management of efforts, targets and achieved goals. To track expenses by category would be a good first start. But I think it will require more and it might be a bit challenging how to do that in a non-hierarchical DAO-compatible way. Any good ideas are very welcome!

> Marketing

Usually we try to avoid the term "Marketing" or "PR" as it has quite a bit of negative smell and traditional marketing was never a goal of Bisq (e.g. using advertising, paid articles,...). We prefer to use the term "communications".

**Comment by ripcurlx** [comment]
> As I commented at [bisq-network/compensation#417 (comment)](https://github.com/bisq-network/compensation/issues/417#issuecomment-565268347) I think we are lacking at the moment management of efforts, targets and achieved goals. To track expenses by category would be a good first start. But I think it will require more and it might be a bit challenging how to do that in a non-hierarchical DAO-compatible way. Any good ideas are very welcome!

In a centralized approach this would be the responsibility of the product owner. In our case one for each of following products: website, docs and client. As we don't want to push for such a role which would be a newly introduced centralized entity - how can we do it instead?

- Making everyone accountable for their own work

This kind of accountability is unfortunately very hard to do as we don't have lots of key metrics at hand and we can't do it in an objective way right now.

This boils down to the question of what means success for each of these contributions?

If we take a super high-level ROI approach, it would mean:
-  Every contribution is paid with newly issued BSQ so success means if it increases the amount of BSQ burnt

ROI calculations work well for continuous improvement of existing products if they would be in place, but not for highly experimental new ideas/projects.

Using total numbers, which are partly available, won't work as those are more influenced by outside factors than by changes within client, website or documentation.

Having a product that doesn't care about privacy would track the flow from external referrals to the website/docs to the client and up to the first or recurring trades within Bisq. Introducing new features would not be deployed to everyone as to keep a significant control group to make objective decisions.

We don't want/can't do something like that as one of the selling points of Bisq is privacy.

So what could we do?
- Everyone who files a compensation request adds a section explaining what a success of this contribution would mean
- For the client: start thinking about how we could measure if a new version update was a success
- For the website: here we could use regular strategies for success already (goal conversions to client download)
- For docs: we could measure if we are able to reduce support requests on Keybase/bisq.community in comparison to the monthly active accounts

Those are just a few thoughts on this and if it went a little bit off-topic - my apologies.

**Comment by MwithM** [comment]
Closed as approved
