### ISSUE TITLE
Bisq should be the future of value transfer - let me help you promote it

### ISSUE THREAD

**Issue by winston-smythe** [bisq-network/proposals#152]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

# Use of alternative social media to promote Bisq
## With the rise of platforms like Diaspora and Bitchute, I'd like to help promote this software - an application that makes use of the best parts of "trustless trust", the TOR network and the Blockchain.

I have been following Bisq for several years now and the concept of a truly peer-to-peer exchange - not just for trading Bitcoin but for any type of wealth transfer, using the functionality of the Blockchain, is truly inspired.

Now that the DAO is in place and developers and contributers are able to both invest in their own work and receive compensation for their skills, **_Bisq should be the only platform people need in order to transfer value, buy Bitcoin or exchange Altcoins_**.

The "burning" of the BSQ tokens under certain circumstances, a inspired idea, ensures it's a truly deflationary token is also, to the best of my knowledge, a feature unique not only to cryptocurrency but to currency in general - as burnt tokens cannot be "reprinted" or forged.

### What I can contribute

For a very few tokens, I'd like to write an article promoting the software, to be published on Diaspora (and any other platform you'd like) and produce a short video, to be published on Bitchute - a video platform that more and more users are turning to as they realise that Youtube is engaging more and more in censorship.

### Further media - articles, videos, e-learning

If you're impressed with what I produce, I will submit further proposals for more articles, videos and e-learning. I'm experienced not only with producing e-learning but also with implementing  and maintaining open-source Learning Management Systems, including the management of the required Linux server.

_Whilst Bisq is extremely intelligent software - it's also a little complicated, even for those used to trading in Bitcoins. I have experience in writing articles, technical documents and producing e-learning that explains simply the benefits of the software and how it's used whilst ensuring that the intelligence behind the design is not lost in translation._

**For examples of my writing:**

[Why hasn’t distributed internet / network i2p taken off in the way it deserves? It has no “killer app”](https://pod.asap-soft.com/posts/b789a1106e5f0137a5aa0218b7b8d087)

[Don't buy Libra](https://pod.asap-soft.com/posts/89ad63e0c2da0137f3c90cc47ac87654)

[Dear UK Home Secretary, thank you for your recent comments on encryption](https://pod.asap-soft.com/posts/fbe0f5509b44013747b30cc47ac87654)

[Create Archived Versions of Pages when Researching](https://pod.asap-soft.com/posts/b6e9d1e096b4013747a30cc47ac87654)

**Comment by m52go** [comment]
Hi, thanks for your ideas. We could use your kind of skills. Might be best to discuss more on Keybase in #growth.

**Comment by user718141** [comment]
"Future" of value LMFO

**Comment by winston-smythe** [comment]
value *transfer*

**Comment by m52go** [comment]
I think this issue can be closed...any further conversation can take place on Keybase. The topic didn't really warrant a proposal to begin with.

**Comment by winston-smythe** [comment]
Sorry. I'm new.

On January 4, 2020 5:41:30 AM UTC, Steve Jain <notifications@github.com> wrote:
>I think this issue can be closed...any further conversation can take
>place on Keybase. The topic didn't really warrant a proposal to begin
>with.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bisq-network/proposals/issues/152#issuecomment-570758939

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mpolavieja** [comment]
Closed as invalid.  This will be discussed on keybase
