### ISSUE TITLE
Whitelist major banks and regions using 2FA to avoid mandatory account signing.

### ISSUE THREAD

**Issue by taxd** [bisq-network/proposals#154]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I suggest that for major banks having two-factor authorisation (2FA) the account signing should not be necessary. See https://cib.db.com/insights-and-initiatives/flow/safety-twice.htm for the plans for mandatory 2FA in Europe. Similar efforts are in the pipeline for Asia and America. Many banks in Europe have 2FA already implemented and within maybe a year all of them will be forced to have it. 2FA makes it very hard to steal bank accounts.

**Comment by clearwater-trust** [comment]
Of course we should make it easy to use major payment networks at all banks. However, the issue isn't stolen bank accounts. The issue is how easily banks will reverse payment on their clients. Most reversals are perpetrated by the account owner claiming their funds were sent without their consent. You see. The banks are in on it. No amount of security will prevent legacy bank claw back.

**Comment by taxd** [comment]
Within the SEPA-region it is illegal to reverse a SEPA bank-transfer without the recipients consent. See https://bisq.community/t/clarify-sepa-credit-transfer/7753/2 and the link given there. Tax authorities in certain countries can deduct funds from an account without the owners consent.

**Comment by mpolavieja** [comment]
The problem is that if a chargeback is requested, the recipient bank might not send the funds back without the beneficiary consent, but it can close his account right away.  Most banks won´t tolerate more than 1 or 2 chargebacks.   

Regarding the chargeback problems we had back in April, I wouldn´t be that sure that 2FA protected bank accounts were not compromised.   Moreover, there are 2FA methods that are easily overriden by scammers, such as SMS codes.

**Comment by taxd** [comment]
@mpolavieja So you mean that I can close somebodys bank account by making 1 or 2 chargeback requests?
2FA using SMS codes can be broken but not particularly easily.

**Comment by mpolavieja** [comment]
@taxd it depends on how you as a recipient can justify that the chargeback is ilegitimate.  In this case, the evidence you have are Bisq screenshots and a Bitcoin transaction from a block explorer and cryptographic proofs.  Theoretically, this is the strongest evidence that a bank could ever dream to have from any transaction.  But practically and being realistic the odds that they will close your account as soon as they hear the word Bitcoin are pretty high.  

If instead, you just reject the chargeback without any explanation or by being evasive or not very clear when asked for evidence, the bank might also decide to close your account.

**Comment by taxd** [comment]
@mpolavieja It is the sender of fiat that has to justify that a chargeback is legitimate, and that tends to involve a court process. I see no incentives for a sender to try to get a chargeback invoking a bitcoin purchase as the reason. The sender will possibly lose his bank account, will become well known by the authorities and it is highly unlikely he will get his fiat back.
In the two jurisdictions I am familiar with, the receiver of a bank transfer is VERY strongly protected by the law against any tampering of his account.

Bisq is having very little trading activity and I see little, if any, interest in making Bisq more userfriendly for an average person who does not know what an elliptic curve is. I am afraid Bisq will die unless this is improved.

**Comment by mpolavieja** [comment]
@taxd The sender will just say that it was an unathorized transaction and as such he has no clue about it.   The recipient's Bank will freeze the funds and ask his client about the transaction when he receives the chargeback request, All these happens waaaaay before any court process takes place.   Also remember that a bank can close your account the same way you can decide to close it, No justification needed. That's indeed what N26 and other banks are doing when they think a transaction is related to BTC (they dont even need a chargeback to take that decission)

Bisq experience has to be secure.  we are dealing with money here. There are proposals to lift the trading limits quicker such as #93 and #138

**Comment by taxd** [comment]
@mpolavieja Well, I've had an unauthorized withdrawals from my account of about $200 and just telling the bank that it was unauthorized does nothing of course. The recipients bank will not "freeze" any funds until the sender can show that the transfer was unauthorized which is almost impossible to do. I never got my funds back. 

Bisq experience cannot be secure, just secure enough. Bisq is not growing, if anything it is declining. Without an improved UX it will die. Technically excellent, nobody uses it.

**Comment by mpolavieja** [comment]
@taxd The recipient bank does freeze funds upon a chargeback request from other bank.  It happened to me.  N26 also closes accounts if they suspect a transaction is related to Bisq (no chargeback at all). It also happened to me, and that was because it is easy for them to relate users that have had transactions with chargebacked users.  They dont even ask the customers, they just act in order to minimize problems.

Maybe you think that Bisq developers are taking the big effort to implement all these just because they want to have fun annoying Bisq users?  Seriously, did you take the time to read the discussions about all these problems?

>  I see little, if any, interest in making Bisq more userfriendly for an average person who does not know what an elliptic curve is.

Precisely in order to onboard that kind of users you need to minimize chargebacks, otherwise the user will tend to think Bisq is a scam in itself if he gets scammed.

**Comment by taxd** [comment]
@mpolavieja 
i) Banks do not issue chargebacks unless the sender can show very strong evidence of an unauthorised transaction, likely involving a police investigation. Anybody thinking otherwise should try to do a chargeback in practice instead of guessing.
ii) Maybe N26 closes accounts on account of suspected Bisq-related transactions. This has nothing to do with chargebacks and nothing to do with the proposal. There is no incentive for either the buyer or seller to mention Bisq in their transaction, neither as the owner of an account or having stolen an account. 

There has been one scammer with stolen accounts out of 45000+ trades on Bisq. On LocalBitcoins there is one scam per 5000 trades. I doubt that implementing my proposal will increase scams at all and I don't even see how. Not implementing it will be a big friction point for Bisq-users and most of them will not even bother to try.

**Comment by mpolavieja** [comment]
Receiving a chargeback request within 2 days of receiving the money can´t possible involve any investigation beyond just submitting a formal complaint to the police.  It was very accurate you used the word "likely", which by the way is not very very coherent with the way you use the word "guessing" in the following claim: 

> Anybody thinking otherwise should try to do a chargeback in practice instead of guessing.

If you are suggesting that I try to do this and get in trouble with my bank, I´ll answer you very clear: 
 I won´t.  Moreover, you are the one that is making the proposal, so it is you who have to support your claims with real evidence on how the banks apply the rules (not just a link to the rules).

The reason N26 closes accounts is indirectly related to chargebacks, as I explained above.

**Comment by chimp1984** [comment]
> However, the issue isn't stolen bank accounts. 

NO. The only issue the account age signing is targeted to preven is the "stolen bank account" scam.

**Comment by chimp1984** [comment]
>  Moreover, there are 2FA methods that are easily overriden by scammers, such as SMS codes.

If we use 2FA we have to look at each banks way how they do it. SMS codes or allowing same decive to do mobile banking and token generation is terrible insecure. Might be still harder for a stoeln bank account scammer but if we get again a stolen bank account scam, reputation damage for Bisq is considerable and the only working protection mechanism we have has to be questioned (maybe for minor reasons as we did not verify enough the multitude of 2FAs and public information likely not available to collect that details).

So I am a bit skeptical if the added benefit justifies the risks and effort to generate such a list. But if there is easy way to render such a list which is reliable to not be polluted by insecure 2FA methods, I think its ok.

**Comment by chimp1984** [comment]
I think we should limit our discussion to the "stolen bank account" scenario. "Friendly chargeback" is exceptional and cannot be repeated. We had a few cases over 3,5 years but those are not a systemic problem. From my experience the difficulty do do a "friendly chargeback" is very different depending on payment mehtod, county and bank and even there might exist laws and rules banks don't care sometimes if you know the bank employee (as it happend when my father made a SEPA chargeback with the the bank employee for a transfer from my mothers account to a charity as they thought the charity is scammy without even telling her!).

**Comment by mpolavieja** [comment]
> If you are suggesting that I try to do this and get in trouble with my bank, I´ll answer you very clear:
I won´t.

Despite having said the above, this morning I visited my bank office and asked my account manager what did she need in the event I request a chargeback.  And she told me that she just needed me to request it, nothing more.  However, one other very different thing is that the recipient bank would accept the request or not and require justification and evidence.

**Comment by taxd** [comment]
I can generate a list which certainly will not cover all banks, but a select set that will include at least 20 million people as customers.

**Comment by user141718** [comment]
This issue is up to date and important. "Stolen" bank accounts will be very rare from 2020 and onwards, hence friendly chargeback is the everlasting risk that cannot be avoided. One can easy conclude that current "account signing" is not in line with the banking development but seems more of a delusional security measurement.

**Comment by chimp1984** [comment]
> banking development

Is that a joke? Banks are not developing ;-) at least not if you count in years and not in decades for any small improvement.

**Comment by user718141** [comment]
> > banking development
> 
> Is that a joke? Banks are not developing ;-) at least not if you count in years and not in decades for any small improvement.

Good news, no joke!

PSD2 as of 14 September 2019 requires banks to implement multi-factor **authentication** for all proximity and remote transactions performed on any channel.

https://www2.deloitte.com/cy/en/pages/financial-services/articles/psd2-finalised-standard-on-sca-and-csc.html

**Comment by chimp1984** [comment]
One of my bank gives a fuck on that and still ddoes not has 2FA.

**Comment by user718141** [comment]
> One of my bank gives a fuck on that and still ddoes not has 2FA.

The compliance should be fully enforced by **31 December 2020**.
https://support.stripe.com/questions/strong-customer-authentication-sca-enforcement-date

**Comment by user718141** [comment]
> I can generate a list which certainly will not cover all banks, but a select set that will include at least 20 million people as customers.

If the list of banks or regions is SCA compliant it can confidently rule out "account signing" for the refered accounts. No question about it.

**Comment by mpolavieja** [comment]
> I can generate a list which certainly will not cover all banks, but a select set that will include at least 20 million people as customers.

Would those banks enforce that the banking app and the 2FA token generator are always on separate devices?

**Comment by user718141** [comment]
**SCA Requirements**

>**Article 97(1)** of the directive requires that payment service providers use strong customer authentication where a payer:[6]

>(a) accesses its payment account online;
>(b) initiates an electronic payment transaction;
>(c) carries out any action through a remote channel which may imply a risk of payment fraud or other abuses.

>**Article 4(30)** defines "strong customer authentication" itself (as multi-factor authentication):[6]
> 
> an authentication based on the use of two or more elements categorised as knowledge (something only the user knows), possession (something only the user possesses) and inherence (something the user is) that are independent, in that the breach of one does not compromise the reliability of the others, and is designed in such a way as to protect the confidentiality of the authentication data

**Comment by user718141** [comment]
> Would those banks enforce that the banking app and the 2FA token generator are always on separate devices?

This new framework, mandating 2-factors authentication, means that users need to prove their identity by two separate elements out of three:

Something they know (e.g., a PIN code or password)

Something they possess (e.g., a “trusted” mobile device, a card)

Something they are (i.e., biometrics such as fingerprints, a face scan)

**Comment by mpolavieja** [comment]
> This new framework, mandating 2-factors authentication, means that users need to prove their identity by two separate elements out of three:

We must care not about what they are trying to enforce but about what is actually going to be implemented for real.

**Comment by user718141** [comment]
> We must care not about what they are trying to enforce but about what is actually going to be implemented for real.

The central bank in each country work as a supervisory body under the European Banking Authority (EBA) to see that it is implemented. It is unlikely that any bank will try to escape the regulations with risk of losing it's banking license.

**Comment by mpolavieja** [comment]
So now we should trust banks and central banks on their diligence... Ok, very good.

**Comment by user718141** [comment]
Yes why not, and the European Central Bank is on top of the European Banking Authority.

**Comment by MwithM** [comment]
I think that the most prudent approach is to wait how this new laws affect to real security on this payment methods before removing our own protection mechanism.

**Comment by user718141** [comment]
> I think that the most prudent approach is to wait how this new laws affect to real security on this payment methods before removing our own protection mechanism.

What you mean with "real" security? Friendly chargeback vulnerability is unchanged with account signing or any KYC-less mechanism.

**Comment by taxd** [comment]
Any "wait and see" instead of improving the usability of Bisq will simply kill it. Nobody will get scammed if they can't use Bisq but I doubt that is the way to go. Trading activity on Bisq is decreasing despite adequate liquidity and a stable platform. There is a reason for this.

**Comment by user718141** [comment]
> Any "wait and see" instead of improving the usability of Bisq will simply kill it. Nobody will get scammed if they can't use Bisq but I doubt that is the way to go. Trading activity on Bisq is decreasing despite adequate liquidity and a stable platform. There is a reason for this.

Forget them. They are all retards.

**Comment by mpolavieja** [comment]
Closed as rejected as there were no positive reactions to this proposal.
