### ISSUE TITLE
Kickstart the Bisq Knowledge Base

### ISSUE THREAD

**Issue by FKrauss** [bisq-network/proposals#156]
# SUBJECT 

Kickstart the Bisq Knowledge Base

# OUTLINE

## Problems

* users raise issues on forum and/or keybase and don't get good responses (or any responses)
* documentation is too convoluted, high level and not approachable enough for casual users - self service support is just impossible

## Proposed Solutions

* Have a knowledge base (**core of this proposal**)
* have people who can regularly help users with support issues & an escalation process where higher impact cases are dealt with by Bisq contributors that have the appropriate experience for it (not in this proposal)
* have a ticketing system (will be considered later, different proposal)

### Knowledge Base

* Build knowledge base to serve as practical, to-the-point guide to solve common issues.
* Should use Zammad because: active, feature-rich project; multiple admin roles for support staff and translators; WYSIWYG editors (so no pull request workflow needed); self-hosted; has ticketing mechanism if we need it, etc.
* Already have ~3 users interested in seeding content, which should cost at max. 2000 BSQ for seeding the content(assuming ~100 BSQ/hour rate for ~20 hours of work, capped at 500 BSQ per contributor)
* Compensation and compensation guidelines - we don't yet have a proposal on how this work needs to be reported. We kindly ask contributors to show the value of the work provided (goes without saying: always keeping users' identities secret)
* Initial deployment and ongoing hosting costs for this new infrastucture should cost ? BSQ.

#### How is KB different than Docs?

KB is a more fluid and tactical set of content pieces. It is meant to be dynamic as the issues appear, more knowledge is gathered and they eventually get a solution in a release or a workaround, for example. Plus, KB articles are more like tutorials and Docs are more like higher level specification of how the system works (non-technically).

KB is also different in the sense that more people can contribute to them as local relevance asks

# Final Remarks

This proposal is not a complete solution to Bisq's support needs, but it should get support on the right track in the near-term. More proposals on this front will come regarding ticketing system and processes around managing the knowledge base and a possible support crew as well as related work

**Comment by FKrauss** [comment]
Things are moving in https://bisq.wiki/

**Comment by cbeams** [comment]
Labeling as superseded by bisq-network/projects#14.
