### ISSUE TITLE
Designate contributors for support

### ISSUE THREAD

**Issue by m52go** [bisq-network/proposals#157]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Support needs help. Users report issues and there are no people ultimately responsible for resolving them...a bunch of people pitch in as they can, but I think we need to designate 2-3 existing, consistent contributors to be **"support providers of last resort"** responsible for support cases so that no users fall through the cracks.

We already have [a role for Support Staff](https://github.com/bisq-network/roles/issues/64) but don't really have people and formalized conventions for it. 

This proposal is meant to rectify that until a minimal [knowledge base is established](https://github.com/bisq-network/proposals/issues/156) and ticketing is figured out. At that point, we can begin to hand off the roles by onboarding newer people and treating it like a more typical role with provable contributions. The suggestions in this proposal are part of a larger effort.

Here are parameters I have in mind:

**Should be existing, consistent, knowledgeable contributors**
These 2-3 people should be around Bisq a lot already and be able to help with most issues on their own. As mentioned above, in the future, once we have a knowledge base and more documentation of critical things, we can onboard less-experienced people. But for now, the people who fill these roles should be ready to go on day 0.

Note that the intention is not that these 2-3 people are the _only_ people providing support, but that they are "support providers of last resort" in case no one else does, and that they take ultimate responsibility for tracking cases and making sure they're resolved.

We have 1-2 people who might be able to help but exact contributors remain to be determined.

**Compensation tiers**
In this case, support isn't a continuous heads-down job with discrete outputs...it's more of a sporadic responsibility that cannot be discretely measured with our current tools. So I suggest establishing tiers for support staff (heavy, medium, light) that roughly correspond to time spent in a cycle in this role (1500 BSQ, 1000 BSQ, 500 BSQ respectively). 

I know this isn't ideal, but consider:
* linking to support cases with existing support channels isn't possible (keybase - can't link to posts) or feasible (forum - sheer quantity). Regular reports should be filed. [Huey's were brilliant](https://github.com/bisq-network/roles/issues/64#issuecomment-540553141).
* this responsibility is to be held by existing, experienced contributors, so chances are low they will misrepresent the value of their work; having tiers gets rid of some of the subjectivity in determining numbers
* no one aside from designated contributors can claim this compensation (for now)
* it should be a temporary arrangement until we set up a more formal, measurable system (e.g., ticketing)
* stakeholders can see activity on Keybase and forum and determine if activity seems to represent requested compensation tier
* numbers above are approximate and up for discussion

Ideally, the people in this role should help with the initiative to build [a knowledge base](https://github.com/bisq-network/proposals/issues/156) and figure out the future of support (e.g., ticketing).

That's really it. I guess this proposal is more of a formal call-to-action than anything else.

**Comment by chimp1984** [comment]
@huey735 Would you be interested to be part of those efforts? You did a great job in the past! We miss you ;-)

**Comment by mpolavieja** [comment]
@m52go, @chimp1984, Is proposal #82 useful in this regard?

**Comment by m52go** [comment]
Addressed by the recent reorganization and support initiative detailed here:
https://youtu.be/4HIbOeLbeds
