### ISSUE TITLE
Increase BSQ max issuance parameter

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#160]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

The Bisq DAO has a "BSQ max issuance" parameter. If more BSQ is approved to be issued than this parameter in a single cycle, [all compensation requests will be forcefully rejected for that cycle](https://github.com/bisq-network/bisq/issues/2679). Currently this parameter is set to 200K BSQ, and last cycle the DAO approved over 150K BSQ worth of compensation requests, so we are now dangerously close to hitting this parameter and having everyone's compensation requests denied.

Of course, it would be best if we implement a budgeting system as per proposal #158 - but I feel the budgets are a "soft limit", whereas this BSQ max issuance parameter is the "hard limit" - we need to be very careful never to hit this or we will lose our compensations and it will be very bad for the DAO.

Simply as a safety measure, I propose to increase this parameter to 300K BSQ just to give us some more breathing room. We should obviously issue far less than the current value of 200K BSQ using proper budgets, but for some reason if a few large compensation requests come in at the same time, we could inadvertently hit the limit and mess up everything.

**Comment by chimp1984** [comment]
It is a DAO parameter so can be changed by voting. I think at current revenue level (10k-20k) the limit with 200k is reasonable. It shows a severe management problem we face at the moment.

**Comment by chimp1984** [comment]
But I agree that increasing might be good, as the reimbursement for the refund agent could be very high in the worst case and it would be very bad if we would delay a cycle and increase volatility risk in such a case. It can be changed by max. 2 times, so 400 000 would be max change in once vote.

**Comment by user718141** [comment]
Maybe high stakeholders also can support Bisq by working for free until revenues get higher. Free work 
by stakeholders pays double, as protecting an investment and as not inflating BSQ.

**Comment by MwithM** [comment]
> Maybe high stakeholders also can support Bisq by working for free until revenues get higher. Free work
> by stakeholders pays double, as protecting an investment and as not inflating BSQ.

They could work for free or not work at all. DAO was created to pay for their work in case some of them wanted to be paid for it.

I guess Bisq will be always open to altruistic contributors.

**Comment by user718141** [comment]
> They could work for free or not work at all. DAO was created to pay for their work in case some of them wanted to be paid for it, Bisq just needs to control BSQ issuance to keep BSQ being valuable.
> 
> I guess Bisq will be always open to altruistic contributors.

How about enforce this by not compensating high stakeholders in hard times like this? By budgetized limits or by down voting. Inflation is very dangerous, as we know.

**Comment by m52go** [comment]
> How about enforce this by not compensating high stakeholders in hard times like this?

From what I've seen, some of the biggest Bisq stakeholders are also the most altruistic ones.

**Comment by user718141** [comment]
> > How about enforce this by not compensating high stakeholders in hard times like this?
> 
> From what I've seen, some of the biggest Bisq stakeholders are also the most altruistic ones.

That may indeed be true among top stakeholders. With a budget limitation altogether there is better control and healthy economy must be enforced by founders and top stakeholders voting. Printing money by increasing max issuance  is no solution to an unhealthy situation.

**Comment by m52go** [comment]
I don't think anyone is suggesting we actually issue more BSQ. As I understand it, this proposal is intended as a safety measure to handle future cycles of high issuance.

**Comment by user718141** [comment]
I suppose the max issuance parameter is the only working economic safety measure by now. As I understood it the economy is under pressure by high issuance and low revenue, then it may be the wrong time to raise the parameter, still with a budget.

**Comment by sqrrm** [comment]
As the value of BSQ has been falling it's quite reasonable to increase the max issuance to at least keep it at a stable level value wise. I also agree that hitting the ceiling would be quite bad for the DAO as an event, and then there would be the backlog to deal with. Better be proactive an raise the limit as this limit was only introduced to limit damage from bugs rather than meant as a tool to limit the budget.

**Comment by chimp1984** [comment]
This parameter was added for security to limit max. possible damage of issuance per cycle not as limit in an economic sense.

**Comment by user718141** [comment]
Flooding with BSQ without demand  is not good for the value. But the value is already artificially set to 1BSQ~1 USD using BSQ as an internal remuneration token. That's the reason why you potentially can increase issuance forever. But in the long run bigger revenues are needed to cover up issuance and establish a real market value for BSQ > 1 USD. You live in big inflation debt so issuance would better stop and you should start burning instead.

**Comment by user718141** [comment]
You should use two values for BSQ.

1. Nominal value = 1 USD
2. Market value = sell price in USD

When asking for reimbursement nominal value 1 USD is used. Not the market value. Otherwise it can not be called a stock only a remuneration token with an artificial value.

**Comment by user718141** [comment]
> As the value of BSQ has been falling it's quite reasonable to increase the max issuance to at least keep it at a stable level value wise. 

NO, it is not sustainable to compensate a BSQ price fall by issuing more BSQ like now. Increasing the supply is inflating which causes the price go down even more in a potentially negative spiral and the finances can eventually break.

The finances should be corrected by issuing compensations in a nominal BSQ value as told. The market then decides what the compensations real value is by the BSQ market price.

Furthermore. If the BSQ price goes down the only sustainable way is to reduce issuance (by costs) or increase burning (by revenues) to properly compensate.

As the Bisq finances are designed now is not sustainable and will eventually break.

**Comment by user718141** [comment]
Any "stakeholder" that now is seeing BSQ as a scam type of asset can donate 2 BSQ to me for a proposal. Maybe I will post my BSQ address. No offence.

**Comment by anonbisq** [comment]
Since the BSQ economy is flawed you must not relax this security parameter.

**Comment by mpolavieja** [comment]
Isn´t an extremely harsh measure to reject all compensation requests when compensation is greater than "BSQ max issuance" parameter?  Wouldn´t it be more reasonable in that case to proportionally readjust down the compensation to everyone?

If this is feasible, then the "BSQ max issuance" parameter could work as a general budget limit that can be proposed and voted on each cycle for the next one.

**Comment by sqrrm** [comment]
@mpolavieja That would be a hard fork. For not upgraded nodes they would see all compensation requests rejected if more than max value was requested while newer nodes would see valid BSQ created.

I don't think this is worth a hard fork. It's also not trivial to make changes to the DAO in itself, not considering it would be a hard fork.

**Comment by chimp1984** [comment]
@mpolavieja This limit was added as security measurement to limit max. issuance in case of a security flaw. It was not intended to use it as limitation for management decisions (who much Bisq wants to spend).

**Comment by mpolavieja** [comment]
Closing as approved by DAO voting - Cycle 9
