### ISSUE TITLE
About stakes, compensations and reimbursements

### ISSUE THREAD

**Issue by user718141** [bisq-network/proposals#161]
**Prerequisites**

It is assumed compensation requests represent work valued in USD as a major and stable currency.
It is assumed that a BSQ amount represents an authentic  _stake_ (price volatile) i.e. not valuing work.

**Proposal part 1**

I propose that all compensation requests amounts are calculated in _nominal_ prices e.g. 1 BSQ/USD.

To use the market price is neither correct for a stake or sustainable because of positive feedback looping. Looping the market price makes the finances unstable and can even break it under some circumstances. That is, when the same requested amount in USD will:

1) increase BSQ issuance when BSQ market price decreases -> unstable
2) decrease BSQ issuance when when BSQ market price increases -> unstable

The _actual_ vale of the compensation is decided by the market. 

**Proposal part 2**

I also propose that all reimbursement requests are calculated in market prices because they does not value work.

Topic monologue #160
Opposing proposal #114

**Comment by user718141** [comment]
Donation needed to execute proposal (not buying any fake stakes).

B1JtSquVUYoKU88FCX53rsm3RAWkJ2SdaSH

**Comment by sqrrm** [comment]
I don't exactly follow what's being suggested here, but it sounds like you're suggesting that people ask for less compensation than the value of the work they have done. That doesn't seem sustainable. I think we need to work to get to a sustainable DAO, starting with proposal #158

**Comment by user718141** [comment]
@sqrrm 

I suggest that:

1) If work creates profit it will increase the BSQ compensation value in a stable manner.
2) If work creates loss it will decrease the BSQ compensation value in a stable manner.

Only healthy economical principles. 

The DAO can not guarantee a fixed salary in fiat under all circumstances.

**Comment by user718141** [comment]
@sqrrm @m52go 
>  I think we need to work to get to a sustainable DAO, starting with proposal #158 

You'll need to construct a regulating budget that can balance an unstable system. A normal budget would only create less or more work and return no gain to stakeholders. It is leaning towards that the BSQ stake is a scam to investors.

**Comment by user718141** [comment]
@cbeams @ManfredKarrer
ping

**Comment by user718141** [comment]
How are you supposed to survive if you are not competetive, attracting the best skills and raising quality by means of economical principles?

**Comment by m52go** [comment]
The suggestions in this proposal sound like valuation and accounting gymnastics that don't address the underlying problems: need for growth and spending discipline.

**Comment by user718141** [comment]
Maybe you don't understand better. Sorry for that. Can see from other posts that you are hopeless. Without return on investments you'll never afford V2, SegWit, LN or anything but maintaining a slowly dying project.

**Comment by m52go** [comment]
Your suggestions don't make sense. Following your logic, it would make sense to artificially increase issuance when BSQ price is higher.

Just because we can control supply of the unit of account doesn't mean we should use that control. To me that would be manipulation, an abuse of power.

**Comment by user718141** [comment]
> it would make sense to artificially increase issuance when BSQ price is higher.
Yes it heats the economy in good times, while cooling down in bad times. Not inflating every time. Plain economy, take a course.

**Comment by FKrauss** [comment]
> > it would make sense to artificially increase issuance when BSQ price is higher.
> 
> Yes it cools the economy in good times, while heating in bad times. Not inflating every time. Plain economy, take a course.

sounds a lot like a Keynsian to me.

The DAO cannot and should not guarantee nor attempt any peg to the fiat world. if there were to be any of such things it should be pegged to BTC. 

right now we can afford the things we are building because BSQ earners/holders hold their BSQ for a day when the burn rate (Burn rate in the DAO is completely the opposite as in accounting) exceeds the issuance rate.

Like @m52go said manipulating the supply or attempting a peg does not solve for increase in growth nor discipline in spending. That is exactly why BSQ holders are the ones who vote on what compensation requests get approved or not.

**Comment by user718141** [comment]
@FKrauss 
Well go ahead and take a poo on the stakeholders and investors, couldn't care less. You communist workers.

**Comment by user718141** [comment]
_Monetarist you fools. Not Kenyanism. You're all foolish retards on Bisq. Die._

**Comment by chimp1984** [comment]
@user718141 If you don't care why not leave. And this time forever? You IQ leaves a fingerprint and reminds on other accounts you used. Please stop spamming Bisq channels with your unqualified inputs. It's repeated pure nonsense.

**Comment by clearwater-trust** [comment]
I would like to add some levity to this thread.

Most people that have the time and inclination to troll on the Bisq repo probably are experiencing some sort of "market loathing" as the price of their main asset is stagnating. Consider it some form of PTSD.

I know we all want the best. I believe the Bisq team is doing their best. That's all we can ask for. If you really want to test Bisq, consider buying up the voting shares. This is certainly an option for you. Current valuation is north of 3mil USD.  Really seems like a bargain for a legit commercial opportunity on the cutting edge of the nascent blockchain ecosystem.  :moneybag:

**Comment by user718141** [comment]
> The DAO cannot and should not guarantee nor attempt any peg to the fiat world. if there were to be any of such things it should be pegged to BTC.

Pegged? Maybe you all live off-grid and not pay your bills in fiat. When your rent is 1000 USD and BSQ drops 50% the monkey brain suggest you request 2xBSQ next month. And when it drops 50% under heavy inflation the month after you claim 4xBSQ and so on...

Can not stop when the chimpanzee monkey brain here is saying "nonsense" without a clue of an intellectual response.

**Comment by user718141** [comment]
Happy New Fools Year!

[Nominal value](https://www.investopedia.com/terms/n/nominalvalue.asp)

**Comment by daonewbie** [comment]
@huey735 

Have a look at this...

**Comment by anonbisq** [comment]
@huey735

Have a look at this...

**Comment by user718142** [comment]
Dear DAO members,

An unstable economical system isn't predictable and is out of control.

Understand what happens if the DAO economy gets succecively chilled from inflation.
It will make the BSQ supply go towards infinity, while BSQ price goes towards 0.

Understand what happens if the DAO economy gets successively overheated from deflation.
It will make the BSQ supply go towards 0, while BSQ price goes towards infinity.

You will notice that after some cycles.

A budget can possibly delay the symptoms but the system is still corrupt.

It's purpose is to regulate a fixed compensation rate instead of financial stability and reason.

That is why I am talking about an enumeration token with a fixes exchange rate and absolutely no gain to stakeholders.


All the best (for now).

?
