### ISSUE TITLE
Use multiple Bitcoin market data providers to create a weighted price index for Bisq pricenodes

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#163]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

### Summary

This proposal picks up on discussion from back in 2017 about [the current flaw with Bisq pricenodes](https://github.com/bisq-network/bisq/issues/1074) where @ManfredKarrer summarized the issue quite well:

> We are very dependent on BitcoinAverage as the only Fiat price provider. If there are issues (as we just faced) all percentage based prices cannot be taken. We need secondary price sources and either fall back to that in case we have issues with BitcoinAverage or mix it.

Recently 2 of our pricenode operators encountered a critical issue where they were unable to receive BitcoinAverage market data, due to BitcoinAverage having multiple issues with their website, changing their payment plan structure, and their payment provider not being able to process Bitcoin payments (all at the same time).

### Proposal 1

I propose that we add https://www.coinapi.io/ as a 2nd data provider, but of course this introduces a new issue, again as @ManfredKarrer already summarized it:

> Thought there is some complexity as all price relays need to have the same source as otherwise take offer attempts can fail if the price what the maker and the taker sees is above a small tolerance window. E.g. If one peer gets the price from a relay which gets it from BitcoinAverage and the other peer is connected to a relay which is connected to coinmarketcap the price will be likely different and exceeds the tolerance window.

> So it need some creative solution how to deal with those issues.

I propose we create a Bisq weighted price index, that weighs each data provider equally, so that in the event one of the data providers is unavailable, the pricenodes can still serve price data to Bisq nodes. The technical details can be discussed here, but I think this general idea works well for many other projects.

### Budget

Currently each pricenode must pay BitcoinAverage $60/month for "startup" plan, and around $40/month for hosting costs, for a total of $100/month. By adding coinapi, we would need to double the pricenode budget to around $200/month each. Considering that BitcoinAverage is a Trusted Third Party and a huge CPOF for Bisq, the weighted price index will add a lot of value to Bisq.

### Proposal 2

Alternatively, it would be ideal to eliminate the trusted third party data providers completely, and have the price nodes actually collect data from hundreds of Bitcoin exchanges around the world, and aggregate it. This would of course be a much larger project, but we should consider the cost/benefit analysis of both proposals before deciding which direction to work on. There may already be an existing GitHub project we can build on top of that aggregates data from all Bitcoin exchanges in the world.

**Comment by Auklium** [comment]
That is only one issue in several years and the new BitcoinAverage startup plan costs only $49/month. A fallback to the Bisq exchange local price can be implemented with a minimal developing budget instead, better than nothing.

**Comment by chimp1984** [comment]
Any work in that area requires los of care to not lead to the situation that take-offer attempts fail because of diverging price data. Any risk to cause more UX issues as we have should be avoided or postponed until we have more dev resources again.

**Comment by wiz** [comment]
@chimp1984 another idea I had to decentralize the pricenode data and solve the distributed consensus problem you are speaking of us is to make a private blockchain just for the pricenode operators. a pricenode would gets market data from whatever providers, put it into "transactions", and generate blocks. Then every user's Bisq node can just get the last X blocks of this federated blockchain and we can be sure they all have the same exact data, and there is no API required and no possibility of a pricenode being "down" or service unavailable

**Comment by chimp1984** [comment]
Our price nodes are "federated", so we dont have that hard problems to keep them in sync. I just wanted to emphasize to be very careful here as it can lead to failed trade attempts if not done carefully.

**Comment by MwithM** [comment]
Closed as approved. Being implemented through this process: https://github.com/bisq-network/projects/issues/35
