### ISSUE TITLE
Put asset listing on hold

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#166]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

As https://github.com/bisq-network/proposals/issues/153 did not lead to any result I suggest that we put all asset listing on hold. Maintainers have the freedom to add any asset if they consider it interesting but by default no new assets get added to Bisq until we have sufficient resources to deal with it.

All issues or PRs regarding assets are getting closed.

Motivation for that step is laid out in https://github.com/bisq-network/proposals/issues/153.

**Comment by mbroemme** [comment]
@chimp1984 Actually it is okay to review the listing process, but you should at least consider coins to be merged which have opened their PR before this PR. It is a bit weird to invalidate work done in the past with a future rule adjustment. It is like blockchain. :)

**Comment by mpolavieja** [comment]
Closed as approved on DAO voting Cycle 9

**Comment by aejontargaryen** [comment]
Doth this madness _still_ persist!?

**Comment by opticbit** [comment]
Add Terra (Luna), its number 9 by market cap.

$UST is number 16 by market cap, a decentralized stable coin on the terra luna network

theres other stable coins and tokens on the Terra platform, including mirrors to the stock market.  But ust seems to be the important one to be sure to have available to trade.  

mining fees are much lower than Ethereum fees.

id pay the dao listing fee for a month on both of them, and keep active offers on the buy and sell side.

i'm still need to look at the coin more to be more knowledgeable on it, but it seems like a good coin to have.

**Comment by bwusth** [comment]
Today is Sunday, April 10, 2022.

The adding of cryptocurrencies seems to be "on hold" PERMANENTLY.

Correct?

**Comment by jayhines91** [comment]
Have added of cryptocurrencies been enabled again?

**Comment by MwithM** [comment]
No, it has not been enabled again.
