### ISSUE TITLE
Censorship Resistance with 1M5 Integration

### ISSUE THREAD

**Issue by objectorange** [bisq-network/proposals#168]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

# Censorship Resistance with 1M5 Integration
Proposal for Bisq Network to integrate [1M5](https://1m5.io) into its communication stack, inter-node and when accessing remote Bitcoin, seed, and pricing nodes (or any public node).

## Issue
[Censorship](https://en.wikipedia.org/wiki/Censorship) is the suppression of speech, public communication, or other information, on the basis that such material is considered objectionable, harmful, sensitive, politically incorrect or "inconvenient" as determined by government authorities or by community consensus. Bisq, by providing a decentralized exchange not registered in any jurisdiction, [is likely to come under attack by jurisdictions that consider it illegal](https://bitcoinexchangeguide.com/sec-vs-decentralized-exchanges-dexs-are-under-attack-from-the-securities-and-exchange-commission/).

Bisq runs its DApps as Tor hidden services using seeds to discover the Bisq network. Tor can be censored, [as is done in China](https://en.wikipedia.org/wiki/Internet_censorship_in_China#Using_Tor_and_DPI-resistant_tools), by discovering entry nodes and blocking them by IP. Bisq gets around this by offering bridges to bypass the blocks but these bridges can also be blocked, same with VPNs. There are an estimated 7000 Tor nodes in operation today with about 2000 of them entry nodes and 1000 exit nodes. To block 2000 entry nodes is easy work as they are provided publicly and it's not a large list. But Tor is the ideal method to connect to a remote Bitcoin node as they normally are ran in the clear via the internet.

## Opportunities
The [Invisible Internet Project (I2P)](https://geti2p.net/en/) is much less known and thus less targeted. It works somewhat similarly to Tor with a few differences. Where Tor shines when accessing clearnet sites privately, I2P shines accessing other nodes running I2P, e.g. peer-to-peer networking apps like messaging. I2P doesn't have entry nodes, every node is a potential entry node and there are roughly 65,000 I2P peers (all I2P peers by default are contributors to the network). I2P, like any application, has its vulnerabilities, but they are an active team working to constantly improve it. There is no known attempts to block the I2P network globally although when cellular towers are turned off or the user is behind a severely restrictive firewall (e.g. corporate), even I2P will not work as it requires internet access. This is where Bluetooth and WiFi Direct have become helpful.

[Bluetooth](https://en.m.wikipedia.org/wiki/Bluetooth) and [WiFi Direct](https://en.wikipedia.org/wiki/Wi-Fi_Direct) support sending messages to nearby peers to share information. This has been used successfully in demonstrations in Hong Kong among others. But what they do not do is propagate out until a peer with internet access is available and use that peer to complete a request for an internet resource. Bluetooth and WiFi Direct are implemented using low-powered radios in phones and PCs and they're easily jammed (WiFi more so than Bluetooth). When in this position, shortwave communications is necessary.

Using the full [radio spectrum](https://en.wikipedia.org/wiki/Radio_spectrum) is the next major advancement in commercial radio communications. Adding [anti-jamming](https://en.wikipedia.org/wiki/Electronic_counter-countermeasure) capabilities additionally will enhance censorship resistance further. But what happens when you're under serious jamming? LiFi is the next battlefield.

[LiFi](https://en.wikipedia.org/wiki/Li-Fi) is short for Light Fidelity. It is basically wireless light communications. A dongle with a LiFi transceiver can send/receive light as data to/from another LiFi transceiver and the only method for blocking it is to physically block the light. Line-of-sight is required although some bouncing can be supported with degraded bandwidth and range. 

## Proposal
Routing using Tor, I2P, Bluetooth, WiFi Direct, WiFi, Shortwave, and LiFi to ensure censorship resistance is the primary mission behind 1M5 - Invisible Matrix Services. It's designed to support additional future networks like Nym if/when they prove to be helpful. When integrated with Bisq, 1M5 would ensure each node can find each other and maintain communications regardless how attacked, even with a national or global internet shutdown. It would also ensure the same level of censorship-resistance when accessing remote Bitcoin, seed, or price nodes...any public node.

Development would require the ability to expose 1M5 as a proxy to Bisq, testing the integration, then documenting it. In addition, a 1M5 Operator/Admin Role would be added to monitor and report on 1M5 effectiveness fixing any bugs that come up while providing an expected level of support.

1M5 is open source under the Unlicense 'license'.

1M5 currently can access the Tor and I2P networks and use Bluetooth. Additional networks will be integrated in the future.

This proposal will only seek to determine how best to integrate 1M5 resulting in a concrete integration project proposal with work breakdown and milestones.

Evaluation + Design + Roadmap + Project Plan: ~80 hours = 80M Satoshis

## Notes
The best timing for this integration is unknown especially considering budgeting issues, although DEXs are beginning to get attention.

### Resources
* [1M5 Site](https://1m5.io/)
* [1M5 GitHub](https://github.com/1m5)
* [1M5 Info Deck](https://1m5.io/assets/pdf/1m5-info-deck.pdf)
* [1M5 Whitepaper](https://1m5.io/assets/pdf/1m5-wp.pdf)
* [1M5 Docs](https://github.com/1m5/1m5-docs)
* [ObjectOrange GitHub](https://github.com/objectorange)
* [ObjectOrange LinkedIn](https://www.linkedin.com/in/decentralizationarchitect/)

### Keybase Conversations
* 12/14/2019 #chinese: @ff98sha verified I2P not blocked in Shanghai
* 12/14/2019 #chinese: @wiz perhaps believes bridges are good enough for now
* 12/28/2019 #general: @sunerok knows I2P amd favors it
* 12/31/2019 #dev: @mileschet likes 1M5 and has experience with Nym, a potential future integration

### Future Projects
Future 1M5 projects will request contributions from Bisq along with other users of 1M5 to spread costs
across the user community. Some future projects include:

* using Tor when I2P gets blocked
* using Bluetooth to propagate out requests (implementation started but on hold)
* using WiFi Direct for request propagation
* using Shortwave/Full Radio Spectrum (large scope that will be broken down)
* using LiFi (some research completed, vendor relationship in place)
* [Nym](https://nymtech.net/) potentially

**Comment by chimp1984** [comment]
@objectorange Thanks for the interesting proposal.
As you mentioned yourself it might not be the right time atm for Bisq to start bigger investments as we need to get our financial sustainibility on track again. I support the basic idea and direction and as you mentioned it would help to enable the Chinese market for Bisq as Tor is not working reliable enough there (Bridges work somtimes but not always). I think Bisq need to improve first on other more trivial areas (support, bug fixes, UX,...) and get a healthy trade volume to be able to start such a larger projects. I hope you find some other ways to contribute to Bisq as there is lots of overlap in your interests with Bisq.

**Comment by sqrrm** [comment]
I find this proposal to be very much in line with the Bisq ethos, thanks for a good write up. From the sound of it there is quite a bit of work needed to integrate 1M5 with a non obvious immediate benefit. There would also be new dependencies to consider which would require even more resources.

As a principle I like the suggested improvements a lot, and it might become a necessity eventually, but at the moment I have to agree with @chimp1984 that it's not a top priority. @objectorange if you do contribute elsewhere on Bisq you will also get a better feel of what exactly would be needed to implement this.

**Comment by objectorange** [comment]
I agree with both comments - will wait until there's reasonable consensus on timing before adding to DAO cycle - is this the correct process? 

I've been digging into P2P, Bitcoin, and Monero components and will over time add to the proposal more details on what will be needed to integrate it. So far, it might just be a proxy change for Bisq but I'm not certain of that, especially with the BitcoinJ implementation.

**Comment by sqrrm** [comment]
Currently it seems the priorities are to grow trading volume and fix bugs. There are still quite a bit of trade issues that might relate to network problems. I think looking at the p2p network might be good, but there is a case to be made for supporting the monero trading and thus adding more features for those traders. It probably depends on the amount of work needed to get results within each domain to decide one should be prioritized first.

**Comment by objectorange** [comment]
Yeah, it seems like trading volume is key to ensure revenue to pay for future work so I'm starting to work with cbeams on grpc-api.

**Comment by objectorange** [comment]
If/when this is desired by someone in the community, feel free to contact me at objectorange@1m5.io or brian@resolvingarchitecture.io.

**Comment by MwithM** [comment]
Closing as stalled.
