### ISSUE TITLE
Change default fiat trade value to full euro/dollar/.. (0 Cents)

### ISSUE THREAD

**Issue by marco4444** [bisq-network/proposals#17]
In order to avoid that bisq-trades can be assigned to a person via time/amount analyses (on the fiat side), it is recommended to trade with full euro amounts (0 cents), as there are then on average 39 times as many transfers of exactly the same amount on the same day in the entire currency area (compared to the average of the frequencies of the other 99 possibilities .xy).
With the current crooked amounts, it is only a question of time when many of them can be assigned to a person after the fact, since the complete history of the amounts/times is public. The smaller a currency area is, the more important this is, since the same amounts occur less frequently on the same day than for dollars and euros. Unfavorable cents such as.74 and.93 are even 390 times less common than rounded amounts and there is a high risk to be the only person in the currency area using the same amount on the same day.

**Comment by sqrrm** [comment]
I think this sounds like a good idea. What are the potential drawbacks, apart from losing a little bit in unfavorable rounding?

**Comment by cbeams** [comment]
To be clear, @marco4444, is this something that you are proposing to implement yourself if others approve it here?

The idea seems like a good one, and would require more thought, but without someone to implement it, discussing and approving a proposal doesn't make much difference.

We just published a document about the proposal process here that you might want to take a look at. Thanks in any case for submitting this. http://docs.bisq.network/proposals.html

**Comment by sqrrm** [comment]
@marco4444 @cbeams I think this is something that would be better as an issue under the correct repo, with discussion and implementation details there. If it turns out to be controversial it will be noticed, otherwise just implemented as a generally accepted improvement.

**Comment by marco4444** [comment]
Thanks. I think I posted this already on all bisq forums, all like the proposal but recommend to post it in another area of the bisq space. I think this is the 3rd or 4th time I wrote this down.
I'm not a java programmer and not experienced with github and the bisq code so from technical point of view I cannot manage this change on my own. I can only give the idea and the math behind, consulting how the result should look like. It's now posted on several places (always following recommendations where it should be posted) and if someone pics it up to implement I can give feedback whenever wanted. If not I can recommend everybody to use it manually (by making sure the offer has a fixed Euro amount with 0 Cents), which already works now,

**Comment by sqrrm** [comment]
@marco4444 Don't be disheartened, I don't mean to just push the issue around. There is currently quite a lot of reorganization of how we do things around Bisq. There are many new contributors and hopefully more to come and finding a good work flow will help with that. My comment was more to figure out how we handle new issues and not really on topic, sorry for that.

Regarding the implementation. Someone needs to take ownership for it to happen, and since it affects the trading protocol some caution should be taken, even though it seems like a fairly easy thing to do. In my opinion it's best to create an issue in bisq-core and start a discussion on implementation there. I created an issue bisq-network/bisq-core#101

**Comment by cbeams** [comment]
Closing as moved to bisq-network/bisq-core#101. Thanks @sqrrm for taking care of that.
