### ISSUE TITLE
Prioritize refund agent in trades from burning man

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#171]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

The refund agent takes a considerable volatility and liquidity risk by pre-funding the reimbursed BSQ from his pocket with BTC. With currently low liquidity this risk has been increased. He charges some BSQ for taking that risk (1000 BSQ in last request) but that might not be enough if the currently weak BSQ market continues and refund agent cases don't go down quickly. Ultimately he will delegate the cost for taking that risk to the BSQ stakeholders by increasing his fee for doing that job. So his work will become more expensive for the DAO.

**To relax that situation I suggest that the burningman prioritizes offers from the refund agent by taking his offers before taking other offers.** 

The price of the offers need to be around the market price (as best offers can be volatile when offer get adding and removed this might not be achieved to 100% but goal is to not influence BSQ price by that). The refund agent should make his onion address public so the burning man can see which offers are his. Also other traders can help to reduce his liquidity risk by taking his offers. The refund agent should only do that until he has covered his outstanding BTC. I am aware that some trust is here involved, but doing that role shows that he is highly supportive to Bisq by willing to take that high risk to prefund the reimbursement (about 4 BTC / month). 
Also the amount the burning man has available is the sum of the trade fees paid in BTC and the BTC from those trades ended up in arbitration (refund agent). So there is no way that the refund agent could take advantage to sell more BSQ beside the amount of the fee in BTC which is rather a small part. 

As soon dev resources permit we should improve the new trade protocol by allowing traders to do the reimbursement by themself as well (optional). This would take some pressure from the refund agent, but we have to be aware that we would delegate that risk and effort to the traders which comes with significant UX decrease. We should think to find a good conceptual solution which makes it more attractive to traders to opt in to make reimbursement by themself. 

This is also needed in case the refund agent revokes. In the current situation the trade protocol would be broken. So we should make sure we don't riks to lose the refund agent (it will be very hard to fin another who can be arbitrator - requires lots of knowleadge - and who is willing to prefund about 4 BTC each month).
 
But most important is to bring refund agent cases down to close zero. A close feedback loop between @RefundAgent and developers (@ripcurlx, @sqrrm,... ) is needed to find out what are the main causes (we did already some changes for the current release).

See also: https://github.com/bisq-network/compensation/issues/465#issuecomment-574295833

Please only vote on that proposal if you are sure that you fully understand the mechanics of the new trade protocol and the role of the refund agent and burning man. If you are not sure read the documentations first. To avoid that this discussion get spammed by unqualified replies I ask the repo maintainers to delete unqualified responses (we got that problem unfortunately in the last weeks).

**Comment by ripcurlx** [comment]
> We should think to find a good conceptual solution which makes it more attractive to traders to opt in to make reimbursement by themself.

I think this will only work if using arbitration comes with a cost for the trader. Otherwise it is just more comfortable to let the arbitrator do the work.

**Comment by chimp1984** [comment]
Yes we need to find a good concept here... Or reimburse more to pay for the effort/risk.... We don't want to lose users by that. That was the reason why we use the refund agent to do that job for the user.

**Comment by sqrrm** [comment]
Let's move the discussion on the users handling refunds to another ticket as it's a big topic that needs its own space.

I support that the burning man prioritizes the refund agent offers for all the reasons stated in this PR. This is supposed to be a closed loop system and due to the low liquidity it's not really functional right now. With time it might not be necessary but until liquidity has improved it's important to keep the closed loop working.

The refund agent is taking quite a risk when there are so many refund cases. I think it would be reasonable that he ask for a fee related to the risk he takes and not just a set fee per month. That would also give the right incentive to the DAO to improve on the system to avoid more cases going to the refund agent.

**Comment by burningman2** [comment]
As this proposal got positive feedback, I take it as accepted and will apply this rule with upcoming trade and burning process.

**Comment by RefundAgent** [comment]
I am the Refund Agent and I agree with the proposal. My risk is very high at this time.
My onion address is: mkjifoi7s67o4hmc.onion

**Comment by RefundAgent** [comment]
I burnt 10 BSQ with preimage "aikprt" which gives the hash in the OP_RETURN. It can be found under **All proof of burn transactions** and has transaction ID 3bbb2f5.... .

**Comment by burningman2** [comment]
I think that proposal can be closed as accepted.

**Comment by chimp1984** [comment]
Should be marked as approved.

**Comment by cbeams** [comment]
Closed as approved.
