### ISSUE TITLE
Add "ApplePay" to current Payment methods.

### ISSUE THREAD

**Issue by scramblr** [bisq-network/proposals#172]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Please add ApplePay and Google Pay to the Payment Methods. It's worked wonderfully on Paxful for a while now and would be a very quick and relatively secure method to add to Bisq. 

Thanks.

**Comment by mpolavieja** [comment]
Closed as rejected, it did not trigger any reactions nor discussion.
