### ISSUE TITLE
Bonded role for btcnode operator

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#175]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

This proposal is for @wiz to become a bonded bitcoin node operator, currently I'm running 2 nodes for Bisq and haven't posted a bond yet.

**Comment by sqrrm** [comment]
I only see one bond proposal for two nodes. That actually sounds reasonable to me, just that we have posted one bond per node previously. I will revoke ono of my bonds as btcnode operator if there is consensus on there being one bond per role rather than per node.

**Comment by wiz** [comment]
Yeah, IMO there is no point posting one bond per instance, the number of instances a node operator runs for a role doesn't matter.

**Comment by wiz** [comment]
Yeah, the number of instances a node operator runs for a role doesn't matter, the bond is for the role itself. For example a certain role might run 5 or 10 instances of something, it's not related.

**Comment by cbeams** [comment]
> the number of instances a node operator runs for a role doesn't matter, the bond is for the role itself.

In theory, the number of instances an operator runs does matter. If we have a federation of 12 Bitcoin Core nodes and one operator runs all of them, they could do much more damage than a single negligent or malicious operator, right? From a network decentralization perspective, the general intention for most operator roles was always that it's a one-node-per-operator arrangement.

In practice, however, I don't think it's a problem that we have one operator running a couple instances of something, and that they post a single bond for doing so. Indeed, I don't want there to be a perverse incentive for people to run multiple instances of a given node type just so they can collect more bond interest.

> For example a certain role might run 5 or 10 instances of something, it's not related.

If this is happening, something is probably wrong. In this case it's less about posting multiple bonds than it is about asking why we are allowing this kind of centralization.

**Comment by mpolavieja** [comment]
Approved on DAO voting. Cycle 10
