### ISSUE TITLE
Bonded role for Seednode Operator

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#177]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

This proposal is for @wiz to become a bonded Seednode Operator. I'm currently running the `jhgcy2won7xnslrb` and `ef5qnzx6znifo3df` seednodes but I'm not bonded yet.

**Comment by mpolavieja** [comment]
Approved on DAO voting. Cycle 10
