### ISSUE TITLE
Bonded role for Twitter admin

### ISSUE THREAD

**Issue by m52go** [bisq-network/proposals#179]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

This is a placeholder issue for my DAO request to post [the bond required](https://github.com/bisq-network/bisq/blob/d4e566f6e7b49ea2a9b1f7f2ead1940ba165b769/core/src/main/java/bisq/core/dao/state/model/governance/BondedRoleType.java#L46) for the [Twitter administrator role](https://github.com/bisq-network/roles/issues/21).

**Comment by mpolavieja** [comment]
Approved on DAO voting. Cycle 10
