### ISSUE TITLE
@huey735 to assume L1 support agent role

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#183]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Not only was Huey an excellent support agent for Bisq before we formalized the new support team, he has done an outstanding job as a full-time support intern since his return last month. Huey is always promptly and accurately responding to users, and follows up on cases with a high level of professionalism.

In regards to one particular legacy arbitration case that was open for over 4 months, @huey735 showed exceptional initiative to resolve the case by coming up with his own manual manual payout scheme, and the trader got his 0.5 BTC back that was locked since last October.

Let's motivate Huey to keep being awesome and promote him to a full support agent :grin:

**Comment by cbeams** [comment]
Thanks, @wiz for submitting this. As a process note, the original intention was to have @bisq-network/intern-support-agents submit their own proposals. From https://bisq.wiki/Support_Agent#Internship:

> 3. After one full cycle of interning
>   - Submit a proposal to be added to the @bisq-network/l1-support-agents team
>   - If your proposal is approved, the support team lead will promote you as per the process below.

With that said, however, I think that doing this "nomination-style" as @wiz has done here is also a valid option.

In any case, @MwithM is currently the only other intern along with @huey735, so @MwithM, if you'd also like to be promoted to L1 agent status, please add your own proposal as well.

**Comment by huey735** [comment]
@wiz I appreciate the sentiment but this seems unnecessary. In general, [the process outlined in the wiki](https://bisq.wiki/Support_Agent#Internship) seems adequate enough. Each intern should propose themselves to a promotion.
Particularly to me, I'm not sure I'm still interested in the role. Recent development of my understanding of Bisq's risk profile for traders repels me from these responsibilities/compensations.

**Comment by cbeams** [comment]
> On Mar 10, 2020, at 2:02 PM, huey735 <notifications@github.com> wrote:
> 
> Recent development of my understanding of Bisq's risk profile for traders repels me from these responsibilities/compensations.

I recall you bringing this up in Keybase, and I believe it turned into a discussion about the roles that @RefundAgent and @burningman2 play. In any case, I'm not sure whether you got concerns addressed. Perhaps you did and are simply dissatisfied with the outcome? Is there a summary you can point to, or would you be willing to write one up somewhere? It would be a shame to lose you, and if there's something you're seeing that other's aren't, it would be a shame to miss that too.

**Comment by huey735** [comment]
It can be summed up as the following

## At present every trader needs to trust the holder of the Bisq donation address:

### Why?
With the current trade protocol, like the previous one, every btc trading fee goes directly to that address at the make and take offer stage. But also the security deposit and btc trade amount may go there if the amount locked in the 2-of-2 multisig isn't released in a amicable manner by the two traders. After 10 days for altcoins and 20 for national currencies trades, either of the traders can request arbitration and in doing so send the funds to the Donation Address and losing custody of their funds. I'm not sure this is clear to traders.

Firstly, the traders are trusting the Donation Address Holder to not run away with their security deposit and or trade amount in case of an arbitration. Secondly, and more importantly, the traders are trusting the Donation Address Holder to not make/take offers and simply wait till the funds are deposited in their address.

Plus we need and can to expect the Bisq Software to behave inappropriately and cause the trades to not go as intended. So there may always be fees, security deposits and trade amounts that must be reimbursed to traders.

### These isn'tt new criticism

Previous discussions:

- [New trade protocol](https://github.com/bisq-network/proposals/issues/52)
- [Bisq donation address huge risk?](https://bisq.community/t/bisq-donation-address-huge-risk/8618)
- [https://github.com/bisq-network/proposals/issues/135](https://github.com/bisq-network/proposals/issues/135)

After coming back, in the beginning of this year, and trying to better understand the new protocol and contrasting it to the previous one, the trust requirement became apparent to me. And putting myself in the position of a new trader coming to Bisq, the answer to the following questions didn't satisfy me:

* Do I need to trust anybody with my funds?
**Yes**

* Am I at the risk of losing custody of my btc during the trade process?
**Yes**

### Conclusion
We need to:
1. make clear to traders the risk they're incurring;
2. polish in the current protocol for more transparency, redundancy and monitoring;
3. come up with something better.

I'll be happy to continue contributing as I can in general. But uncomfortable holding the Support Agent role, being compensated for it and being associated with it.

**Comment by wiz** [comment]
> At present every trader needs to trust the holder of the Bisq donation address

This is incorrect. The holder of the Bisq donation address does not refund failed trades. I believe you misunderstand the roles, which is understandable since they have not yet been fully documented yet. Allow me to clarify based on my understanding of the v1.2 trade protocol refund process:

If a trade is not resolved between the parties within the hard time limit (10 days for crypto and 20 days for fiat), the trade capital can be donated to Bisq by either party broadcasting the pre-signed time-locked payout TX to the Bisq donation address. After verifying the funds were donated on the Bitcoin blockchain, and using the suggested payout from the mediator of the case, the ***Refund Agent*** will then refund the traders. The ***Burning Man*** is not involved in the refund process. To be clear: the Burning Man could steal all the money in the donation address and the traders would still be refunded by the ***Refund Agent***.

If the ***Refund Agent*** does not refund the traders, they can file their own Reimbursement Proposal directly with the DAO as well, based on the suggested payout of the mediator. If they do not agree with the suggested payout of the mediator, they can argue the case further with the DAO (kind of like appealing to the "supreme court", as the DAO is the highest authority in Bisq.)

So just to be really clear, if the ***Burning Man*** does not complete the Proof of Burn as part of his role, and disappears or steals the money in the donation address etc. the traders would still be refunded from the ***Refund Agent*** as normal. The DAO would fire him, revoke his bond, and hire someone new to replace him. The DAO would just lose some money that cycle and no damage would be done to the traders.

**Comment by huey735** [comment]
From having being helping with support, I don't think traders fully understand Bisq's incentive model and that they're losing custody of their funds when they go into arbitration. This may just be solved with better education.
Well, I've been around for a year and it took me this time to develop this discomfort I

**Comment by wiz** [comment]
> I don't think traders fully understand Bisq's incentive model 

I agree that we can always improve the underlying game theory and financial incentives of the trade protocol (and educating users about it) so that fewer trades need to be mediated / refunded. The original intention of this refund process was to be extremely rare, like zero or one trade a month, but unfortunately due to bugs and unresponsive traders it is probably 5-6 trades a month now, from my rough estimate.

> They're losing custody of their funds when they go into arbitration

They actually "lose custody" of their funds once they start a trade on Bisq, because when they get moved into the 2 of 2 multisig it becomes a "joint custody" held by both traders together. If the 2 traders cannot agree how to dispurse those funds (with the help of a mediator), they get donated and then the Refund Agent does a refund according to the suggested payout of the mediator. So the RefundAgent actually accelerates the process, and the trader(s) get their Bitcoin back faster.

> Well, I've been around for a year and it took me this time to develop this discomfort I have today.

Why the discomfort? No trader on Bisq has ever lost funds. The system works as intended with multiple layers of exception handling, and the DAO can always resolve any dispute by approving a reimbursement request to issue BSQ for a failed trade if it was truly needed. Fortunately the Refund Agent has always performed well and it has never come to that.

**Comment by clearwater-trust** [comment]
Why was the 2 of 3 model abandoned for this **_Refund_** laundering **_Agent_**? Why do you think the current protocol is superior to having trusted/bonded arbitrators with the third key?

**Comment by wiz** [comment]
> Why was the 2 of 3 model abandoned

It's because Bisq is not a centralized Bitcoin exchange. Bisq is a "decentralized exchange network", which means Bisq is actually just a piece of open-source software that Bitcoiners use to trade directly with each other (aka Peer to Peer), and without using a Trusted Third Party (aka Arbitrators). In other words, the entire point of Bisq is to replace the Trusted Third Party model for Trading with a distributed incentive model, just like Bitcoin has successfully done with "money" and banking.

If you want to trade Bitcoin using a Trusted Third Party, there are many centralized Bitcoin exchanges out there that can do this for you, with much more efficiency than Bisq and with a smoother UX, fancier websites, support team, etc. Please remember the goals of Bisq - the contributors who develop and support the Bisq software have no intention to be a Trusted Third Party to trades between users of the software, as this would defeat the purpose of the Bisq project.

> Why do you think the current protocol is superior to having trusted/bonded arbitrators with the third key?

If it's not clear to you why TTPs are bad, I would suggest reading [Trusted Third Parties are Security Holes](https://nakamotoinstitute.org/trusted-third-parties/). Satoshi showed the world it was possible to replace the a Trusted Third Party model (Central Banking) with a distributed incentive structure model (Bitcoin).

The donation mechanism is only intended to be an emergency recovery process for lost funds due to bugs or other critical failures when the traders can't complete a trade within the hard-time limit. The structure is correct, but we need to improve the financial incentives and game theory to reduce the frequency of how many trades get donated. However, keep in mind that nobody has ever lost any funds trading on Bisq. The system works and we are always working to improve it.

**Comment by clearwater-trust** [comment]
Sorry for hijacking the thread.

> Just like Bitcoin has successfully done with "money" and banking.

A trust-less fiat trading system is Utopian garbage. Conflating blockchain and legacy banking systems is wrong and dangerous. Attempts to game your way out of fiat pitfalls with refund agents, donation addresses and burningmen is a CHEAP excuse for a distributed network. 

> Satoshi showed the world it was possible to replace the Trusted Third Party model.

The centralized role of the refund agent is anti Nakamoto. Distributing the risk through a network of bonded arbiters is more in line with his ethos.

I concede that building a network of trust is more expensive/valuable than providing a CHEAP centralized (replaceable?) refund agent. But only capital pigs and corporate lawyers care about profit. Right?

I am not convinced that a 2 of 2 system that forces all traders to donate their funds is superior to a bonded arbiter with a 3rd key.

**Comment by MwithM** [comment]
> the traders are trusting the Donation Address Holder to not make/take offers and simply wait till the funds are deposited in their address.

That's the biggest issue. Any other thing is user experience, and can improve, but this is a huge central point of failure because locked bonds cannot cover risks of a dishonest or hacked address holder. I still don't see how is this any better than using 2of3 multisig, other than legal protection from considering moderators as money transmitters.


> ...[traders] actually "lose custody" of their funds once they start a trade on Bisq, because when they get moved into the 2 of 2 multisig it becomes a "joint custody" held by both traders together. 

> The structure is correct, but we need to improve the financial incentives and game theory to reduce the frequency of how many trades get donated. 

You always depend on another part to move funds, but if you have 0 confidence in the other part, owning 1of2 keys in a 2of2 multisig is way better than owning 0of1 in a normal BTC address.
The structure is not correct: until Bisq destroys trade funds in case of disputed, DAO address holder can take advantage of it and create its own offers in a profitable way. It's not only reducing frequency of how many trades get donated, but what do we do with these funds.
I understood that it was riskier to burn funds when a new trading protocol and software was being released, but forgetting the risk that DAO address holder creates to this project does not help. @huey735 conclusions (make clear to traders the risk they're incurring, polish in the current protocol for more transparency, redundancy and monitoring and come up with something better) it's essential.


> ... and using the suggested payout from the mediator of the case, the Refund Agent will then refund the traders.

Refund agent (I would rather still call it arbitrator) needs to collect evidence again to make its own judgement. This are refund agent's words, at Keybase:

> It is also the case that the traders are unaware that they need to explain the situation again to me as a Refund Agent. It seems that the traders think I am the same person as the mediator and knows all history. The UI should be improved in this respect.

**Comment by clearwater-trust** [comment]
Anyone that decimates corporate terms like "**Money Transmitter**" when speaking on behalf of Bisq should not be promoted. Indeed, anybody that gives fealty to **corporate law** should remove themselves from the project and go find something else to do.

### Adopting corporate limitations in development and system structure is CERTAIN DEATH.

The corporate state wants us all commodified, liquefied, and/or dead.

**Comment by huey735** [comment]
# Proposal
After many discussions I'll move on and propose myself to the role of Support Agent.

# Motivation

I came into Bisq simply to translate what I could but soon enough I noticed that the little I knew was enough to help others. So that pretty much sums up why I'm here. I'm trying to guide and help those and know less than me in the little areas I can.

# Costs

It isn't easy for me to come up with a value and as the period for proposals is close to an end, I'll follow @MwithM 's lead - https://github.com/bisq-network/proposals/issues/188 - and propose also a 7.5 usd/h rate, working 24h/week spread evenly from Monday to Saturday. The main argument for this model is the requirement of support agents to allocate specific blocs of time to serve those looking for support. I'm ready to be convinced of another model but I don't want to derail this thread any more.

**Comment by cbeams** [comment]
Thanks, @huey735. It looks like we have consensus on this proposal, so I'll close it out now and add you to the @bisq-network/l1-support-agents team accordingly.

Regarding compensation, please see and provide your feedback / reaction to @wiz's support budget proposal at https://github.com/bisq-network/proposals/issues/200.

**Comment by cbeams** [comment]
Closed as approved.
