### ISSUE TITLE
@wiz to assume mediator role

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#184]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Over the past several months I've been providing support to Bisq users full-time every day, mostly during the daytime of Asia/Pacific timezones, and I feel I have enough technical understanding and usage experience to become a Bisq mediator.

I also feel the mediation rate of 50 BSQ per case is way too high because some trades for 20 BSQ go into mediation when the counterparty is unresponsive, so I propose to only take a flat rate of 1000 USD per month compensation, which I believe is well within the current support budget.

Edit: correct 1000 BSQ to 1000 USD

**Comment by ifarnung** [comment]
This is a welcome suggestion as I have argued before that the DAO was spending too much on mediation, details here (https://github.com/bisq-network/roles/issues/83#issuecomment-572531377). 

If qualified applicants want to do that work for less, seems like a win for the DAO.

**Comment by MwithM** [comment]
I like the idea of you becoming a mediator, and the flat rate might be good.
But I don't like having prices established as BSQ. Budgets aren't, because BSQ is not a stablecoin, so I would prefer that this flat rate were based on fiat.

**Comment by sqrrm** [comment]
It's a devious plan to keep his compensation at 1000 per month as BSQ prices skyrocket ;)

**Comment by wiz** [comment]
Haha yes I meant 1000 USD not 1000 BSQ of course

**Comment by mpolavieja** [comment]
Approved on DAO voting cycle 11
