### ISSUE TITLE
@Bisq-knight to assume mediator role

### ISSUE THREAD

**Issue by Bisq-knight** [bisq-network/proposals#185]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I'd like to apply for becoming a mediator in the Bisq DAO

## Why me
* Long time Bisq user. I've onboarded many users to bisq, know common issues and have fixed many of them. 
* Support and Bisq contributor for shorter but also long time. officially Support agent since Jan 2020
* GMT timezone - 24h SLA should be fairly easy to achieve IMHO
* Nym - very few people know my real identity, thus lower risk of becoming a target and compromising user's private information
* available on keybase - close to all the time
* I can provide mediation in multiple European languages

## Costs
I believe that a rate of 20 BSQ per case is a fair number. It does account for the variability of cases: there can be cases that are easy to solve and others that require way more time and interaction with the parties to figure out the best solution. **20 BSQ** is a good balance between cost, value and service.

**Comment by cbeams** [comment]
Regarding the duties of the role, please make sure you've read and understand https://bisq.wiki/Mediator.

Regarding compensation:
 - Compensation should be denominated in USD and converted to BSQ only at the time of compensation request
 - Please see the conversation starting at https://github.com/bisq-network/roles/issues/83#issuecomment-598164440, in which we're converging on a flat 1000 USD per month for the mediator role.

**Comment by cbeams** [comment]
Please also acknowledge that you're able to post the 10,000 BSQ bond for this role, thanks.

**Comment by Bisq-knight** [comment]
I'm fine with both conditions:
* compensation of 1000 USD per cycle no matter the volume
* posting the bond in the proposal

**Comment by mpolavieja** [comment]
Closed as approved by DAO voting cycle 11
