### ISSUE TITLE
@devinbileck to assume seednode operator role

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/proposals#186]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

This proposal is for myself to become a bonded Seednode Operator. I'm currently running the 3f3cu2yw7u457ztq and fl3mmribyxgrv63c seednodes but not yet bonded.

Reference: https://github.com/bisq-network/roles/issues/15

**Comment by devinbileck** [comment]
DAO transaction ID 7febd78efea275b576d6d4365fbfcd4275ba4dc04d580201d66b1dededdf4cd8

**Comment by mpolavieja** [comment]
Closed as approved by DAO voting cycle 11
