### ISSUE TITLE
@sqrrm to post bond for Bisq maintainer role

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/proposals#187]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I propose to bond my Bisq maintainer role.

**Comment by cbeams** [comment]
I've edited the title of this proposal, and am adding this comment to make it extra clear that @sqrrm is already a member of @bisq-network/bisq-maintainers and that this proposal is about "catching up" on posting the bond required for that role.

/cc https://github.com/bisq-network/roles/issues/63

**Comment by sqrrm** [comment]
Proposal tx https://bsq.sqrrm.net/tx.html?tx=f3d37f8730ec290513189fb8e80e1ddbed36bc6d97f9615e4a2a4b11d77c0c0b

**Comment by mpolavieja** [comment]
Closed as approved by DAO voting cycle 11
