### ISSUE TITLE
@mwithm to assume L1 support agent role

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#188]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

### Proposal
After a Cycle11 internship with a lot of new procedures, I want to apply as Support Agent for Bisq.

### Motivation
I'm a long time user and contributor as Spanish translator without many technical skills, but I provided user assistance in other places. I still have a lot to learn, many times I have needed Support staff to step in, but I'm willing to keep learning.
I have been available on keybase mon-fri 08:00-14:00 GMT officially, but also at other times. I think that's more time than needed, at least by now according to user demand, so I suppose that we will adapt coverage soon. @huey735 which I hope will accept to become support agent, has done a lot more in less time. Anyway, I think I proved I have time availability and dedication. I might have less time availability in the future, but i think I'll easily manage to provide at least 10h/week for support.

### Costs
As far as I know, I'm the first one to ask for future compensation for this role, and I haven't discussed it privately with noone. I guess that, as availability for this role is essential, it should be a certain amount of USD/hour, as just being there (to be able to attend users soon) is delivering something. I'm going to ask for 7.5 USD/hour, but I'm open for discussion. For example, if a kind of case tracking finally goes on, it would make a lot of sense to make it a mixed system of an amount per hour and another amount per solved ticket.

**Comment by cbeams** [comment]
Thanks for submitting this, @MwithM. Glad to see you'd like to continue in this role, and thanks for all you've done over the last cycle. I've +1'd the proposal in general, but not necessarily with regard to compensation. I think we can sort this out separately from whether your proposal for promotion is accepted, and I'm sure we can come to some kind of arrangement that works well for everyone. Indeed it'll be good to have a larger conversation with all @bisq-network/support-agents about how we want to structure compensation. A unified approach would be desirable of course.

/cc https://github.com/bisq-network/roles/issues/64
See also: https://bisq.wiki/Support_Agent#Internship

**Comment by MwithM** [comment]
I wasn't aware of the necessity to submit the proposal at DAO for voting and I realized of that after proposal phase. If it's mandatory, it should be specified at the [wiki](https://bisq.wiki/Support_Agent#Internship).
Let me know if I should wait for next cycle to become a support agent.

**Comment by cbeams** [comment]
> I wasn't aware of the necessity to submit the proposal at DAO for voting and I realized of that after proposal phase. If it's mandatory, it should be specified at the [wiki](https://bisq.wiki/Support_Agent#Internship).

I don't believe it has been stated anywhere that a formal dao proposal is necessary. My intention in the process as documented on the wiki was to submit a proposal and get to rough consensus via informal emoji-based voting and commenting, and take it to a vote only if there's contention.

It looks to me like this proposal has in fact been approved by that standard, and we can close this out. Welcome to the @bisq-network/l1-support-agents team!

**Comment by cbeams** [comment]
Closing as approved.

**Comment by mpolavieja** [comment]
Voted as approved on DAO voting cycle 11
