### ISSUE TITLE
@robkaandorp to assume btcnode operator role

### ISSUE THREAD

**Issue by robkaandorp** [bisq-network/proposals#189]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I have been running my own full node for quite some time and would like to propose to use it for the benefit of the bisq network. I have discussed with @wiz to reuse one of the onion addresses that are already in use for bisq, so there will be no need for a PR.

For now this will be an onion-only full node.

**Comment by wiz** [comment]
Rob is a cool guy and Bitcoin OG, I had a nice long call with him today and explained how the DAO works, and he is very excited to become a Bisq contributor. He is ready to post the 5K BSQ bond for Bitcoin Node Operator role. Let's welcome Rob to the team!

**Comment by mpolavieja** [comment]
Closed as approved by DAO voting cycle 11

**Comment by Emzy** [comment]
We removed your node because is was a old tor onion v2 address.
Would you like to provide a tor onion v3 address and get added again?
