### ISSUE TITLE
@mrosseel to post bond for pricenode (data relay node operator)

### ISSUE THREAD

**Issue by mrosseel** [bisq-network/proposals#191]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

This proposal is for myself to become a bonded pricenode operator.

**Comment by ifarnung** [comment]
A BISQ Node OG!  Thanks for keeping the infrastructure running.

**Comment by mpolavieja** [comment]
Closed as approved by DAO voting cycle 11
