### ISSUE TITLE
@devinbileck to post bond for pricenode role (data relay node operator)

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/proposals#194]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I am currently running a pricenode but not yet bonded.

**Comment by devinbileck** [comment]
Tx ID 740f6cb3cc554169f1e2008530602f1a2f40e5e002bceb204e01a0c6d0a50df0

**Comment by mpolavieja** [comment]
Closed as approved by DAO voting cycle 11
