### ISSUE TITLE
@wiz to post bond for pricenode operator (aka "data relay node" operator)

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#195]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I am currently operating the [`gztmprecgqjq64zh` pricenode](https://github.com/bisq-network/bisq/blob/master/core/src/main/java/bisq/core/provider/ProvidersRepository.java#L43) for Bisq, this proposal is to post my bond.

**Comment by mpolavieja** [comment]
Closed as approved by DAO voting cycle 11
