### ISSUE TITLE
@Bayernatoor to assume L1 support agent role

### ISSUE THREAD

**Issue by Bayernatoor** [bisq-network/proposals#196]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

**Proposal**

Application to become a support agent following 1 month internship.

**Motivation**

I have been a silent Bisq user for just over a year but the ability to transact without an intermediary, buying/selling BTC without having to provide KYC documents, made it clear to me that services like Bisq are a necessity and so I decided that it was time to contribute in whatever I could. Support seemed to be the best fit. Most of my career as been spent in customer service and related fields and so I have significant experience in that sector. Over the last month I continuously improved my  knowledge of Bisq and although there still much to learn, I believe that I can provide a good level of support. Working on the wiki, and having created several pages has certainly helped strengthen my understanding. Throughout my first month of internship I was officially around for 3 hours from Mon - Wed and have since extended my hours from Mon - Fri.

**Cost**

My goal is to contribute and provide support to users of Bisq so that the project can continue to run smoothly. Considering the time spent being present during official hours, compensation does make sense and I side with @MwithM's suggestion of 7.5USD/hour but am open to discussion. 

Although I have not been around as long as @MwithM  or @huey735  i do believe that I can provide value to the team and community.

**Comment by ripcurlx** [comment]
@Bayernatoor The link you posted within the app is broken: https://bisq-network/dao-proposals/196 returns `404`. Thanks for your contribution so far! As I'm not reading the support channel very frequently I would appreciate additionally 👍 by @MwithM and @wiz.

**Comment by Bayernatoor** [comment]
@ripcurlx Woops, that damn hyphen, my bad. The vote phase is active now, i don't know believe I can fix it correct?

**Comment by ripcurlx** [comment]
> @ripcurlx Woops, that damn hyphen, my bad. The vote phase is active now, i don't know believe I can fix it correct?

Unfortunately not. I guess most stakeholder who vote will be able to figure it out. Worst case scenario would be that you need to re-submit it for next cycle if it gets voted down because of this.

**Comment by cbeams** [comment]
As I just mentioned at https://github.com/bisq-network/proposals/issues/188#issuecomment-605833928, I don't believe these L1 promotion requests require a formal DAO vote there's a rough consensus here on GitHub.

I'll close this out and add you to the @bisq-network/l1-support-agents team accordingly. Welcome!

**Comment by cbeams** [comment]
Closing as approved.
