### ISSUE TITLE
@m52go to post bond for btc node operator

### ISSUE THREAD

**Issue by m52go** [bisq-network/proposals#197]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

See:
https://github.com/bisq-network/bisq/blob/dbecc0a2f1b6f4bf88759b11c26c8eb94b666cda/core/src/main/java/bisq/core/btc/nodes/BtcNodes.java#L74

**Comment by mpolavieja** [comment]
Closed as approved by DAO voting cycle 11
