### ISSUE TITLE
Research project to integrate L-BTC as a Bisq base currency

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#198]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

## Background

Liquid is a Bitcoin sidechain (Layer 2 blockchain) developed by Blockstream as part of [the Elements open-source project](https://github.com/ElementsProject/elements), and [operated by a federation of ~30 members and 15 functionaries](https://liquid.net/) (block producers). The base asset of the sidechain is L-BTC which is an asset token pegged 1:1 to Bitcoin. Anyone can run a Liquid full-node and perform transactions without permission from anyone, and L-BTC can be freely traded with BTC on Bisq without any restrictions.

Bisq already supports multiple/alternative base currencies to Bitcoin for forks of Bitcoin such as Litecoin and Dogecoin. However, since nobody used LTC or DOGE as base trading pairs, they were dropped and Bisq is currently Bitcoin Only. Since the Elements project is a fork of Bitcoin, Bisq could potentially add L-BTC as a base currency.

Bitcoin has recently seen mempool and blockchain congestion, with high transaction fees and very long times for Bitcoin transactions and Bisq trades to get confirmed. One solution to this would be implementing the previously-discussed V2 trading protocol, but an alternative or supplemental idea might be to integrate the Liquid sidechain's L-BTC asset as a base currency in Bisq.

## Rationale

Adding L-BTC as a base currency might be desirable to Bisq traders for the following reasons:

* Base layer privacy - Liquid has Confidential Transactions and Confidential Assets, which makes blockchain analysis more difficult
* Fast block times - Liquid blockchain sees a new block generated deterministically every 60 seconds, which ensures fast confirmation times
* Very low fees - Liquid blocks are empty, so 1 sat/b gets confirmed in the next block, which would ensure low fees for Bisq trades
* Atomic swaps - Liquid supports atomic swaps into other Liquid confidential assets such as Tether USD, and Bisq could eventually serve as a decentralized marketplace for crypto/crypto swaps

## Proposal

This proposal is for a research project to create an experimental L-BTC base currency version of Bisq, to identify what issues may exist and study how Bisq can be used on top of Liquid as a Layer 3 system. If there is significant interest in the research project, another proposal can be made to expand it into an officially supported feature.

## Additional Information

Liquid mempool visualizer: https://liquid.mempool.ninja/
Liquid blockchain explorer: https://blockstream.info/liquid/
Liquid website: https://liquid.net/

**Comment by jmacxx** [comment]
Sounds like a good idea, especially if bitcoin transaction fees stay high, and why wouldn't they.  At the moment with 100+ sat/byte fees, a typical trade on bisq costs $10 to $20, which in my opinion makes it cost-prohibitive.  Its certainly stopping me from participating.  Migrating from Bitcoin to L-BTC would be conceptually easier for users since "liquid **is** bitcoin" .. you wouldn't lose your exposure like you would with altcoins (as much as I love DOGE, hehe).

Also, another big complaint at the moment is long confirmation times.  Seems L-BTC solves this too.

**Comment by ricardosaurio** [comment]
In fact, Liquid BTC was designed to be used in exchanges, and would also be a better solution than segwit support. Then again, i wouldnt like Liquid to replace bitcoin, as it is just a peg. If the two could be used together (3? ligthning?) it would be better.

**Comment by jmacxx** [comment]
@ricardosaurio I agree.  Having just read https://stephanlivera.com/episode/178/ I want to correct a mis-statement from my comment above: liquid is an IOU, it is not bitcoin.  

> 6102:
>
> Liquid is a complex IOU that you buy with bitcoin. Liquid Bitcoin tokens aka L-BTC are tokens on an a network managed by a consortium thus you have no guarantee that bitcoin you peg into liquid will be available for you to peg out in the future. Effectively you send your bitcoin to a group of companies in the hope that you’ll get it back. As such, L-BTC is not bitcoin, it’s an IOU. The risk is that retail users get on boarded into Liquid, mistakenly think that they own bitcoin and do not take steps to take self custody of bitcoin in the future. The peg-out could be denied

**Comment by wiz** [comment]
<img width="282" alt="Screen Shot 2020-06-13 at 20 07 28" src="https://user-images.githubusercontent.com/232186/84567135-8b883e80-adb1-11ea-9cc0-602747caea55.png">
There being no objections, closing this proposal as accepted, and will proceed to create a project for it in the project repo.

**Comment by cbeams** [comment]
> There being no objections, closing this proposal as accepted

... and I've just added the `was:approved` label. The work of both closing and labeling should really be done by the Proposals Maintainer, but we effectively do not have one currently (see my note about this at https://github.com/bisq-network/roles/issues/30#issuecomment-644632536).

**Comment by wiz** [comment]
Due to the recent high transactions fees on Bitcoin's base layer, @jmacxx has expressed interest in working on this project. We will work together to create a project proposal next.
