### ISSUE TITLE
Improve Memory Efficiency

### ISSUE THREAD

**Issue by niyid** [bisq-network/proposals#199]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Dear All,

I have been working on memory profiling Bisq for a few weeks and I think I have now gotten a few pointers (despite not being an expert in this area). The profile indicates that over 100 MB of memory is wasted and this number is likely a conservative estimate if further analysis is applied (for instance **`MainView.rootContainer`** which is a static property appears bloated).

I intend to do the following:

1. Resolve issues of memory leaks.
2. Replace inefficient primitive arrays.
3. Fix duplicate array and variable issues.

Please refer to the attached documents below.

Comments are welcome.

https://heaphero.io/my-heap-report.jsp?p=YXJjaGl2ZWQvMjAyMC8wMy8yNi8tLWhlYXBkdW1wLTE1ODUwMDM3MTc0NTQuaHByb2YuemlwLTE1LTU3LTMyLmpzb24tLQ==

[heapReport-2020-03-20-16-08.pdf](https://github.com/bisq-network/proposals/files/4360688/heapReport-2020-03-20-16-08.pdf)

[heapReport-2020-03-20-00-03.pdf](https://github.com/bisq-network/proposals/files/4360690/heapReport-2020-03-20-00-03.pdf)

**Comment by mpolavieja** [comment]
Hi @niyid, are you sure this issue belongs to the proposal's repo?

**Comment by niyid** [comment]
> Hi @niyid, are you sure this issue belongs to the proposal's repo?

@mpolavieja What do you suggest? Open as a bug report? Well, it is more than a single bug and will result in many fundamental changes to the application. Which is why I thought it should be a proposal.

**Comment by MwithM** [comment]
I think that this should go somewhere else. If you ask me, or anyone, if I want to improve memory efficiency, my answer is _yes_.

It would be ok to make a proposal if Bisq had to decide to cut some features or work in a very different manner in order to improve memory efficiency. But I think that's not the case.

**Comment by ripcurlx** [comment]
@niyid I think a good start for this would be to discuss your findings in the #dev channel on GitHub. @ghubstan and @stejbac have done memory profiling as well, so you might exchange ideas what change would have the biggest impact.

**Comment by niyid** [comment]
> @niyid I think a good start for this would be to discuss your findings in the #dev channel on GitHub. @ghubstan and @stejbac have done memory profiling as well, so you might exchange ideas what change would have the biggest impact.

@ripcurlx 
Thanks for the suggestion.

**Comment by mpolavieja** [comment]
@niyid if you think that this is being properly addressed in #dev channel, please close this issue.
