### ISSUE TITLE
Create a bisq-announce mailing list to replace now-defunct MailChimp newsletter

### ISSUE THREAD

**Issue by cbeams** [bisq-network/proposals#20]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

## Introduction

As documented at bisq-network/mailchimp#9 and elsewhere, MailChimp shut our account down. This leaves us with no way to communicate with our ~3,000 mailing list subscribers.

## Let's set up a new bisq-announce mailing list

We have our own mailing list infrastructure at https://lists.bisq.network; let's use it.

**I propose we create a new read-only bisq-announce@lists.bisq.network mailing list** that we use for broadcasting important announcements about Bisq and the Bisq Network, including:

 - Release announcements for user-facing applications such as Bisq Desktop and Bisq Mobile
 - Major milestones in network activity, i.e. events worth celebrating
 - Initiatives that deserve a lot of attention, such as liquidity weeks or other key growth efforts
 - Major Bisq media mentions, interviews, etc that Bisq users would want to be aware of and/or share

To date, our newsletter has been low-volume to a fault—we virtually never used it. I propose that this new newsletter would remain low-volume, but perhaps aim for a cadence of one or two emails per month. It would remain primarily focused on letting users know about new features and releases, and we would never want it to feel overtly promotional or slick. The medium is really the message here; by moving to a lo-fi Mailman mailing list, we're letting people know that this is a no-frills, value-oriented communication channel, not a marketing tool designed to surveil and manipulate.

## Pros

 - We're in full control of the Mailman infrastructure, and can't be de-platformed again.
 - This kind of Mailman-based mailing list is idiomatic for a FOSS project like Bisq. It moves away from the more corporate / startup-oriented nature of a MailChimp-based newsletter, and sends the right signal to serious Bitcoiners.
 - We can still do HTML email if we want to, and while we may not want to do any fancy templates, we can still include attachments, screenshots, etc.

## Cons

 - We can't segment by geolocation or other factors. This means, for example, we couldn't target people in a certain country for a currency-specific liquidity week. 
 - We can't segment by different types of Bisq users. For example, we had a list of BSQ genesis distribution receivers vs general newsletter subscribers under MailChimp. We couldn't do that sort of thing here, without creating a separate list.
 - We can't monitor open rates, clicks and other metrics, and we can't A/B test emails. This means we can't know much about or improve the effectiveness of our emails over time. We can only measure downstream, second-order effects, like increases in website visits, download numbers etc. It should be mentioned that we never really measured any of this stuff anyway. I did look at MailChimp reports after sending stuff out, but I never took any action or made any changes based on it, mostly because I never had time to focus on that.

## Open questions

**Can we automate the process of signing up for a Mailman list?** i.e. such that users can fill out a form field on the https://bisq.network website and subscribe to the list? This is potentially important because the Mailman web UI is super minimal and old-school. It's great for technical people, but may turn off or turn away less savvy people. And in general, it would just be good to be able to streamline this, such that we can have a simple newsletter signup form on the website. @Emzy, can you look into this? Note that even though our website is statically generated, we can hook in handling form submissions via our hosting provider, Netlify. So it is possible for us to have a bit of code that does whatever is necessary to subscribe someone.

**Anti-spam compliance.** MailChimp and other providers go to all sorts of lengths to ensure compliance with CAN-SPAM and other regulations. As far as I know, it's enough to have the usual unsubscribe link at the bottom of Mailman-generated emails. We're not a company, we don't have an address or contact information, etc, so we shouldn't need to put any of that stuff in the footer of these emails. I don't see how this list would be any different than any other open source mailing list, but I'm not a lawyer, so if someone can provide confirmation about this, please do.

**What to do with the existing 3,000 list subscribers.** I've been able to extract the set of current subscribers from our MailChimp account before being locked out forever, and I have that data now in CSV form such that we can import it into the new bisq-announce list. I would just want to confirm with everyone here that we in fact do want to do that. I don't see a strong reason not to; these subscribers did opt-in to getting announcements about Bisq, and we'd be transferring them from the old newsletter infrastructure to the new bisq-announce infrastructure that has essentially the same purpose. This seems like an entirely legit thing to do, but if anyone has a reason to object to this, please speak up.

## Prerequisites to accepting / enacting this proposal

**This list will need an owner.** I don't want to see us set up this infrastructure only to fail to use it like we did with MailChimp, and I don't want to assume this role myself. @m52go, you mentioned in https://github.com/bisq-network/roles/issues/27#issuecomment-386281850 that you'd be interested in taking on this kind of role. I'd see the minimum set of duties being making sure that we get an email out to the bisq-announce mailing list every time there's a Bisq Desktop release, and to take the time to craft that communication a bit so that it's something more substantive than just a copy-and-paste of the release notes.

## Access to the list

Whoever plays the bisq-announce mailing list admin would have write access to the list. Anyone who wants to can subscribe to the list and read it, and of course the archives would be publicly visible at https://lists.bisq.network like all our other lists.

Subscribers would not be able to respond to emails though, in order to avoid the list becoming too noisy and people dropping off. We'd want to have a standard footer that directs people to ask questions via the Bisq Forum, Slack, etc.

## Announcing / promoting the new list

If this proposal is approved, I would want to announce it via Twitter in conjunction with making a bit of noise about MailChimp shutting us down. People should know that MailChimp is doing this to honest Bitcoin projects, but we shouldn't make that noise without also giving people something to do about it, like signing up for our new bisq-announce newsletter. So I'm holding off on any MailChimp tweets for now, until we've approved this and gotten everything set up.

Note that I also removed links to the old newsletter from the website, and I would also add those links back in when we announce this new list.

Thanks for reading. Please take some time to think about this and provide feedback, thanks!

**Comment by cbeams** [comment]
@bisq-network/contributors, this proposal hasn't gotten much of a response since I posted it 9 days ago. If this is a topic that interests you, please take a few minutes to review and react to it. Thanks.

**Comment by Emzy** [comment]
Sorry missed that. 
It sounds all good to me.

> Anti-spam compliance
Yes this needs more work. I have to do some more configurations on the server for that.
But should be possible.

> What to do with the existing 3,000 list subscribers
The import is no problem. We also can ping the subscriber to approve the subscription, but with the old-school way from mailman. 

> Can we automate the process of signing up for a Mailman list?
I have to look into that. Seems the only obstacle right now.

**Comment by m52go** [comment]
Sorry for reacting so late...I wasn't sure if I could really add any value to the discussion, aside from saying I really like the idea and am willing to own the role when the infrastructure is set up.

I think email is crucial, and something we shouldn't overlook, even if it's a bit minimalist. But even minimalist has its advantages.

> We can still do HTML email if we want to, and while we may not want to do any fancy templates, we can still include attachments, screenshots, etc.

To be honest, I wouldn't be surprised to see super-concise text-only emails get higher engagement than heavy graphical ones. The Bisq userbase would almost surely prefer it, and information overload in general is only increasing every day for everyone else. 

> The medium is really the message here; by moving to a lo-fi Mailman mailing list, we're letting people know that this is a no-frills, value-oriented communication channel, not a marketing tool designed to surveil and manipulate.

Agreed. Also, as I mentioned above, I think merely _using_ the list trumps the lack of analytic fanciness, at least in the short term. Beyond that we can play it by ear. I get the impression Bisq's primary source of growth will be word-of-mouth, social mentions, etc anyway...so I'm not sure we'll ever need to have particularly sophisticated email marketing infrastructure.

Although we can't measure open rates, we could experiment with specific calls to action unique to a particular email campaign as an indirect way to measure engagement (get people to tweet a particular hashtag, etc).

> This seems like an entirely legit thing to do, but if anyone has a reason to object to this, please speak up.

I want to say that these folks have opted to receive emails from Bisq about Bisq, and the backend infrastructure we use to deliver those emails is irrelevant. But I'm not a lawyer.

> If this proposal is approved, I would want to announce it via Twitter in conjunction with making a bit of noise about MailChimp shutting us down. 

This would be awesome.

**Comment by cbeams** [comment]
I'm closing this as approved, but need to be clear: I'm not going to do this work myself. @Emzy can help with anything technical around the mailing list itself, and @m52go, if you want to spearhead the effort, write the content, etc, you're more than welcome to take this ball and run with it. In any case, it sounds like we agree this would be of value for Bisq users whether we do it now or at some point in the future.

And @HarryMacfinned, regarding your concerns about privacy above, I believe we've addressed this elsewhere. Such a mailing list, operated by @Emzy, and with a non-public list of subscribers is pretty reasonably as privacy risks go, and as mentioned elsewhere, signing up for such a list is _completely optional_ those who have extreme privacy concerns would stay away from it anyway. Lots of users would use protonmail accounts, or whatever, and many users would happily sign up with their own email addresses. People are free to take whatever degree of risk they can tolerate.

**Comment by m52go** [comment]
For the record -- I considered picking this up for the DAO launch, but then decided against it for these reasons:

- no street address, needed for US CAN-SPAM
- GDPR compliance is murky
- list has been dormant for over a year, so would need to be pruned
- effectiveness not clear

Some reasons above are stronger than others, but ultimately I think we're better off using platforms we're already established on, as well as (possibly) pioneering a presence on new platforms like Scuttlebutt or Briar that are more in line with Bisq principles.
