### ISSUE TITLE
Support Budget

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#200]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

@bisq-network/support
@bisq-network/support-agents 
@bisq-network/l1-support-agents
@bisq-network/refund-agents 
@bisq-network/intern-support-agents 

I propose to fix the compensation for Support team members as follows

refund agent: 1000 USD
burning man: 250 USD
mediators: 1000 USD
support agents: 500 USD
support interns: 0 USD

The previous per-case compensation disincentivizes support team members from reporting/fixing bugs because it would reduce their salary, but flat-rate compensation incentivizes support team members to report/fix bugs to get their case load down. We should always try to make incentives in Bisq align properly as much as possible.

**Comment by burningman2** [comment]
@wiz 
My compensation requests are usually 200 USD.
https://github.com/bisq-network/compensation/issues/535#issue-599249552

**Comment by wiz** [comment]
It's just the budget, of course you can request lower if you want. Thanks burning man!

**Comment by cbeams** [comment]
@wiz, it looks like we've already got pretty good consensus to approve this, but it might be worth submitting it as a DAO proposal just to make it official and to make sure everybody got their eyes on it. Do you plan to do that?

**Comment by cbeams** [comment]
Also, I'd say let's lower the burning man budget down to $250 based on @burningman2's comments. No need to have this extra float in the budget if it's not going to get claimed. It might find better uses. Plus, we all need to think about ways to trim the budget after the April security incident.

**Comment by wiz** [comment]
@cbeams I made the edit you requested, and since since there was no objections I think we can consider this proposal as accepted. In any case, once we get a Support Team Lead, they will be in charge of the budget, so this was only a temporary thing for the cycles where we had no Support Team Lead.

**Comment by cbeams** [comment]
I've added the `was:approved` label. Again, we need a Proposals Maintainer to do this stuff in a systematic way; see https://github.com/bisq-network/roles/issues/30#issuecomment-644632536.
