### ISSUE TITLE
Implement listing offers on multiple markets and using multiple payment methods

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#201]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

## Background

Currently, we have the following "bank transfer" payment methods in Bisq:

* Transfer with same banks
* Transfer with specific banks
* National Bank Transfer
* Japan Bank Transfer
* SEPA and SEPA Instant
etc.

As well as the following new "bank transfer" payment methods in development:

* SWIFT
* Australia PayID

## Issue

Since a single bank account can typically accept payments from multiple payment networks, such as 
SWIFT, ACH, Zengin Furikomi, etc. all at the same time, it is typical for a user to want to be able to create offers that can be taken on any payment network their bank supports. However, currently Bisq requires markets to fork their liquidity into single payment methods, as well as single currencies.

For example, as @dav1dpgit pointed out on Keybase, if you have a bank account in Japan that can receive money from anywhere in the world, in over 10 fiat currencies, why do we have to limit our offers on Bisq to a single payment network and a single currency? If someone wants to accept my offer and pay with any fiat currency my bank accepts, or pay with any payment network my bank accepts, they should be able to...

## Proposal 1

Bisq should publish the same offer multiple times, once for each payment method the maker is willing to accept for their offer. As soon as any one of the offer's listings is taken, all of the offer's listings will be removed from the offer books.

For example, I should be able to accept SWIFT and Japan Bank Transfer for the same offer.

## Proposal 2

Bisq should publish the same offer multiple times, once for each fiat currency the maker is willing to accept for their offer. As soon as any one of the offer's listings is taken, all of the offer's listings will be removed from the offer books.

For example, I should be able to accept USD, EUR, JPY, GBP, HKD, etc. for the same offer, using the automatically adjusted fiat rate system that existing offers use. I should be able to set a different % premium for each fiat currency I choose to publish my offer on, since I will have to pay a different % premium to my bank to convert to my local currency.

## Concerns about modifying trade protocol

Of course, we should avoid modifying the trade protocol as much as possible. Therefore we should probably implement this proposal by creating "virtual offers" which can spend the same "reserved funds" and use the same funding UTXO for a single offer on any of the "virtual offers"

**Comment by m52go** [comment]
This topic has come up a few times over the past few weeks...examples: SWIFT bank wires as already mentioned, [Western Union transfers](https://github.com/bisq-network/bisq/issues/2922) between different countries, and this week [Revolut enabled EUR-USD transfers](https://twitter.com/RevolutApp/status/1242422019305754630). Maybe TransferWise could be used here too.

Having payment methods cleaned up and extended beyond borders could be especially beneficial for fledgling markets (e.g., CAD and AUD) where there is consistent interest but usually not great liquidity.

**Comment by mpolavieja** [comment]
This an excellent idea that could improve a lot liquidity.  Another way to to think "Virtual offers" could be to generate a customized order book, that is, the user could see an aggregated order book with all offers included in the trading pairs he is interested in and/or his payment accounts are able to interact with.

**Comment by ricardosaurio** [comment]
Should not be limited to banks, unless there is some problem for mediators/arbitrators to do their job. I would like to be able to buy/sell with, say, western union, uphold and advanced cash, AS WELL as national bank transfers.

**Comment by MwithM** [comment]
Closing as approved.

**Comment by pazza83** [comment]
I know this is closed but just wanted to share a way I have used Bisq to view the total offers for a particular payment type. 

Maybe it is obvious to everyone else but I only found out last month that you can sort all offers by payment type. This is useful when searching for offers using a multi-currency account such as Revolut. 

Maybe an easy workaround solution is to promote search by payment method 'select payment method' on the GUI. Mostly it defaults of Search by currency 'select currency' .

![revolut](https://user-images.githubusercontent.com/66367547/97497580-a2938b80-1962-11eb-869d-8e564cafb9be.png)
