### ISSUE TITLE
Keeping BSQ trading fee discount at 50% of BTC

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#202]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._
### Motivation
After approval of proposals #173 and #181 regarding trading fees, a process to keep BSQ discount up to date in a regular, systematic way is still needed.

### Proposal
3 days before end of proposal phase, Compensation maintainer will use this [spreadsheet](https://cryptpad.fr/sheet/#/2/sheet/view/9wasbqRHbCYoknAdPQdFR3cdYaYaesxTBpqJGIteX2M/) to calculate current and, if needed, new BSQ trading fees. New BSQ trading fees will be submitted to DAO vote only when the discount is 5% over or under the **50% mark**. To reduce trader impact in case of sudden BSQ price drop, _(edited)_ max BSQ % variation for current and proposed fees should be a 15% increase (i.e. if current discount BSQ trading fees are 10 BSQ, max new BSQ trading fees should be 11.5 BSQ, even when that supposes leaving the discount over 50%).

The parameters used to calculate the discount will be USD/BSQ 30 day volume weighted [average](https://github.com/bisq-network/compensation/issues/519#issuecomment-605716911)  and current USD/BTC price as displayed in a Bisq node.

The process is detailed in the [wiki](https://bisq.wiki/Update_BSQ_trading_fees).

----

Edit: Max BSQ % variation for current and proposed trading fees increase is 15%.

**Comment by sqrrm** [comment]
I think this is good in principle, but would suggest that the fees could change by up to 20 percentage points per cycle, and it would only be done when the discount is 10 percentage points off the 50% mark.

Having a very precise measure makes little sense since both BTC and BSQ prices are quite volatile.

**Comment by MwithM** [comment]
Maybe I did not explain right how the numbers are calculated, or they're calculated weird in the spreadsheet. I created a third sheet with the calculations of a sudden drop in BSQ price scenario to show how it would be.

![imagen](https://user-images.githubusercontent.com/50149324/78378609-7cc32580-75d1-11ea-9b3a-da3daaefd73a.png)

>  fees could change by up to 20 percentage points per cycle

The max discount difference of 5% variation means that if now the discount is 60%, for the next cycle it should be 55% for the nex. As it's calculated on the spreadsheet, implies that a maximum of a 13% BSQ increase is allowed.
Going from 46 BSQ per BTC traded to 52 BSQ per BTC  from one cycle to next one looks high ennough to me.
As I understand, you're proposing to be able to go from 46 BSQ to 55 BSQ,  which is not very far from the current proposal. One objective of this proposal is to make trading fee changes steady. The reason why #173 was rejected was because that change looked too abrupt.

 > it would only be done when the discount is 10 percentage points off the 50% mark

Fees would have to be checked periodically anyway, so I think that a 5% distance from the mark should be used. For the DAO it's a simple vote, as rules are already known and easy to check consulting the spreadsheet. For contributors and traders, keeping the discount the closer possible to 50% makes it easier to predict revenue and expenses.

**Comment by MwithM** [comment]
@sqrrm I changed the spreadsheet, now the BSQ variation is easier to understand.
Anyway, my proposal is kept to cap max BSQ % variation for current and proposed fees at **15%** increase, and make a change parameter proposal when BSQ discount is **5% over or under 50%**.

**Comment by sqrrm** [comment]
That's reasonable, gave my thumbs up.

**Comment by MwithM** [comment]
### Update for cycle 12

There's no need to update fees for Cycle 12. Current BSQ discount is 50.1%, into the 44-55% range.

7050 USD/BTC and 0.61 USD/BSQ has been used to calculate new fees. USD/BTC is bitcoinaverage price at this time, and USD/BSQ is weighted volume 30 day moving average as displayed in Bisq node v1.3.2

![imagen](https://user-images.githubusercontent.com/50149324/79546362-987b0100-8092-11ea-8c24-89938ba719f0.png)

You can view the spreadsheet [here](https://cryptpad.fr/sheet/#/2/sheet/view/9wasbqRHbCYoknAdPQdFR3cdYaYaesxTBpqJGIteX2M/)

I consider this proposal approved and voting not necessary. Changes are small and I have not seen oposition to it. The 15% cap on BSQ % raise might be the most controversial or subject to change aspect of this proposal, I leave this open for review in next cycles.

@cbeams @mpolavieja Do you think that for next cycles, a new proposal should be open, or should this one be kept open?  I think that Proposals is the best way to proceed with this. I'll do what you think it's best, and modify the [wiki ](https://bisq.wiki/Update_BSQ_trading_fees) accordingly.

**Comment by MwithM** [comment]
## Cycle 13

Prices used: 9620 USD/BTC and 0,63 USD/BSQ (30 day WMA)
Current fees BSQ discount: 59,3%
New fees BSQ discount: 54%

There's a need to update BSQ trading fees, as discount is over 55%. The 15% cap for BSQ trading fee increase will be used.

![image](https://user-images.githubusercontent.com/50149324/82193227-665cf900-98f5-11ea-8262-393eb456dedc.png)

### New BSQ trading fees
A change parameter request for BSQ trading fees will be submitted to DAO voting:
New BSQ maker fee: **7.2 BSQ**
New BSQ taker fee: **50.3 BSQ**

----
<sub>Spreadsheet (cryptpad spreadsheet was broken due to a bug): https://docs.google.com/spreadsheets/d/1-hISy7F0NSqPnRxDOoi1k7df1qLJHfQTxhrVLt6NbX4/edit#gid=0
Process described at: https://bisq.wiki/Update_BSQ_trading_fees</sub>

**Comment by sqrrm** [comment]
![image](https://user-images.githubusercontent.com/23560607/82222214-42afa800-9921-11ea-9765-8f3b046d8692.png)
Should that be 46.3 as mentioned in the table?

**Comment by MwithM** [comment]
Yes, it's edited now. I'm waiting for lower mining fees to send the proposals to DAO.

**Comment by MwithM** [comment]
TXID for change parameter proposals:
1cfdff7ef0bdf72275ffe6b8191817d229384493c9035d42a950f37c8c2b2abe
759c456d684481bec1a889a8ee03398750a0eded696d255661c665217f23181d

**Comment by MwithM** [comment]
After change parameter proposals were approved, I have updated the wiki page with the new BSQ trading fees. https://bisq.wiki/Trading_fees
I'm closing this issue while we figure out the best way to keep record of the process, I don't like to create a new proposal every cycle nor leaving this forever and generate a mega thread.

**Comment by MwithM** [comment]
I'm reopening this proposal. The plan is to keep using this one until there's a need to update BSQ trading fees again. For more info, read [the wiki](https://bisq.wiki/Updating_BSQ_trading_fees) or proceed to #compensation [keybase](https://keybase.io/team/bisq) Bisq channel.

## Cycle 14

**Parameters**
* USD/BTC price: 9365 USD
* USD/BSQ price: 0.72 USD
* Current BSQ discount: 49.5%


![imagen](https://user-images.githubusercontent.com/50149324/85219744-ad338800-b3a6-11ea-8eb9-5b2b3b38b15f.png)

There's **no need** to update BSQ trading fees for Cycle 14.

**Comment by MwithM** [comment]
Closed: new BSQ trading fees have been proposed for Cycle 15.
