### ISSUE TITLE
Increase REIMBURSEMENT_MAX_AMOUNT parameter to from 10000 to 100000 BSQ

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/proposals#203]
Reimbursement requests are meant to be used to issue BSQ that's not compensation for work done. Typically it should be used by the refund agent to reimburse the amounts spent on refund to users after funds were spent to the burning man. In the last cycle the refund agent had to create a compensation request to get reimbursed as the max reimbursement amount is too low.

I propose to increase the `REIMBURSEMENT_MAX_AMOUNT` from the current `10000` BSQ to an eventual `100000` BSQ. This parameter can only be increased by a factor 2 so in the next cycle I will create a proposal to increase it to `20000` BSQ.

The amount was changed to `20000` in cycle 12.
The proposal is to change it to `40000` in cycle 13.

I think I will stop at `80000` in cycle 14 and then let it be.

**Comment by cbeams** [comment]
Good call, thanks @sqrrm. I updated the title of this proposal to make it more explicit. So you'll follow up each cycle with a new proposal to increase until the limit reaches 100000?

The schedule should look something like this:

Baseline: 10000
Cycle 12: 20000
Cycle 13: 40000
Cycle 14: 80000
Cycle 15: 100000

/cc https://github.com/bisq-network/roles/issues/93.

**Comment by chimp1984** [comment]
I doubt that 100k is needed. The refund agent should make his requests each cycle so that it does not accumulate to such high numbers as it is currently. Further he simply can make multiple requests if it really exceeds, but that should show something is not normal - e.g. too many cases -  and help to escalate the problem to the core contributors to help to address the problem.

**Comment by sqrrm** [comment]
Proposal request tx id: [3057f12f13e68a300a70739b39289b785c6d52a4b3332adaad4cc9044fe6bc5e](https://bsq.sqrrm.net/tx.html?tx=3057f12f13e68a300a70739b39289b785c6d52a4b3332adaad4cc9044fe6bc5e)

**Comment by MwithM** [comment]
Doesn't this proposal need to be made again to double to 40.000 BSQ? https://github.com/bisq-network/compensation/issues/575

**Comment by sqrrm** [comment]
Yes, I intend to make a proposal for this cycle to increase the amount to 40k.

**Comment by sqrrm** [comment]
Proposal request tx id: [3299d99a577611ea4e599ed547b6ee861527d8d3c8cbe7ee4f528f026d900881](https://bsq.ninja/tx.html?tx=3299d99a577611ea4e599ed547b6ee861527d8d3c8cbe7ee4f528f026d900881)

**Comment by chimp1984** [comment]
@sqrrm Another increase planned?

**Comment by sqrrm** [comment]
Yes, I plan to increase to 80000 and leave it at that.

**Comment by sqrrm** [comment]
Proposal request tx id: [e9d769e7b6f9125a2decfa0f0483af6082fa1dc8411c0b9790adcca622b29605](https://bsq.ninja/tx.html?tx=e9d769e7b6f9125a2decfa0f0483af6082fa1dc8411c0b9790adcca622b29605)

**Comment by sqrrm** [comment]
I plan on leaving this at 80000 which is where it's at now. Closing.
