### ISSUE TITLE
Reimburse the victims of the April 7 security incident from future trading fee revenue

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#204]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

### Protecting Bisq's perfect reputation

Nobody has ever lost any funds trading on Bisq, and we can't let this security attack mess up our perfect reputation. Over the past 12 days, approximately 3 BTC and 4000 XMR was stolen from 7 different victims on the XMR/BTC market, and I feel we should reimburse them.

### Current victim list

This is what we believe to be the victim list right now, but it will take another 10+ days to know for certain. The final list will be posted with full TXID and other details for public verification later.

```
Victim Onion            BTC Stolen  XMR Stolen
-------------------------------------------------
5n3mebt3rn3mewpz.onion  0.14000000  532.9310642
5f4wdwjruxauizpc.onion  0.60000000  507.4137509
yqdw6riz3l2l7t42.onion  0.30000000  260.12470378
zyeelafxvahizpm7.onion  1.00000000  1007.316807
zp4jmknswfzxbamd.onion  0.89000000  1467.40859
TBD                     0.30000000  246.51702261
-------------------------------------------------
Total                   3.23000000  4021.71193756
```

### Proposal

I propose that the DAO repay the victims of our recent security attack from future trading fee revenues as follows:

- Allocate 10% of monthly DAO budget to repaying the victims back for their loss
- That 10% (6000 USD worth of BSQ in a 60,000 USD / cycle budget) gets issued to someone playing this specific role (the "make 'em whole role"). The role owner requests this BSQ in a compensation request like any other.
- The role owner then sells that 6K worth of BSQ for BTC over the coming cycle in as prudently a fashion as possible
- At the end of the cycle, the role owner then broadcasts a batch bitcoin transaction paying out the BTC to the 7 victims in proportion to their loss. The BTC is sent to the bitcoin address that each victim used to pay their security deposit in the affected transactions.
- Repeat this process for as many cycles as necessary until all victims are paid back.

### Considerations

- We can adjust the % depending on how stakeholders feel
- We can adjust the budget as revenues increase over time

**Comment by clearwater-trust** [comment]
Proposing reimbursement before understanding what happened is NOT recommended.

How about we figure out WTF happened and then you can propose all u want...   

Postmortem on the incident > think > propose >

**Comment by huey735** [comment]
@clearwater-trust https://bisq.network/statement-security-vulnerability-april-2020

**Comment by wiz** [comment]
Yes, we've started writing up the post-mortem, like I said it will take at least 10 days or so to finalize all the investigations

**Comment by Bisq-knight** [comment]
Agree with the above, we need to formally post what is known before even talking about the compensation plan. But assuming that is coming soon:

- Roughly we have 260k USD to compensate. at 6k per month will take over **43 cycles** to fully compensate them. I think this is a good plan, at least from Bisq's perspective as it does not completely cripple our budget and ability to deliver and grow the network.


One add on to your proposal: the request should be a reimbursement request, not a compensation request. Comp request accrue Merit, Reimbursement requests don't ;)

**Comment by clearwater-trust** [comment]
Welp-   I suppose this will test your scheme:  **2of2 wallet to donation address to BSQ to BTC** idea.

**Comment by wiz** [comment]
After consideration, I will withdraw this proposal for now and re-post it later after the post-mortum and discussion with victims and other DAO stakeholders

**Comment by cbeams** [comment]
Sorry folks, a misunderstanding caused this proposal to get posted here prematurely. It was only intended to be a draft at this point. I'm going to delete this issue entirely to avoid further confusion, and it will be replaced when we have the proposal ready to go and more fully vetted. Please understand that what's been laid out here may change significantly!

In any case, I'm sending this message out here so that those who have already been notified about this proposal and/or subscribed to it have an explanation for its disappearance.

Thanks, all.
