### ISSUE TITLE
Double trading fees

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#208]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

As a result of the recent security incident, Bisq will likely have to repay victims around $235K USD, which will probably require slashing our current monthly budget from $60K to $20K, which is barely enough to keep the lights on. Additionally, we shouldn't cut developer resources at a time when we need them most, i.e. to put together a security team and work hard on improving our software.

The Bisq DAO now badly needs more revenue, and I think we could tolerate increasing our trading fees to make up for the stolen funds. Personally I feel the trading fees are quite low now, and users would actually be okay to pay a premium to trade on Bisq because it respects their privacy and freedom.

Currently, DAO parameters are set as follows:
- BTC maker fee: 0.001 BTC
- BTC taker fee: 0.007 BTC
- BSQ maker fee: 5.75 BSQ
- BSQ taker fee: 40.25 BSQ

I propose that we increase DAO fees by 100% as follows:
- BTC maker fee: 0.002 BTC
- BTC taker fee: 0.014 BTC
- BSQ maker fee: 11.5 BSQ
- BSQ taker fee: 80.5 BSQ

What do you guys think?

**Comment by MwithM** [comment]
I'm clearly against this proposal:

1. I don't think that current fees are that cheap. If it were, Bisq would have a lot of volume, and it doesn't. Centralized exchanges are cheaper and faster. Other so-so decentralized exchanges have more or less the same fees as us, but we're better than them so it's fine.
2. It's a very abrupt change. Even if 1.6% BTC and 0.8% BSQ trading fees would be a good trading fee, raising it so rapidly would annoy users. Normally, traders don't get to vote if they like it or not, but if fees are too high for the service provided, they will go somewhere else, and might not come back.
3. After the attack, Bisq must be perceived as less secure than other options. Bisq needs to get back the confidence, and raising trading fees is not the way.
4. With bigger trading fees, a discount becomes more attractive: if, [as it seems](https://github.com/bisq-network/proposals/issues/205#issuecomment-612824408), Bisq follows the path of paying victims using BTC fees only, it needs to encourage the use of BTC to pay trading fees, or at least not make it less attractive. 

The only thing I would modify about trading fees after the attack would be to reduce the BSQ trading fee discount from the current 50% to somewhere like 30-40%, but that just in case it was needed. The #205 proposal has been estimated using current BTC trading fee revenue, so I don't really feel there's a need to rush into reducing that discount either.

**Comment by chimp1984** [comment]
I don't think this is the right time to increase fees. The deeper problem is that BSQ demand side is only supported by traders and we have basically zero investors. That forces contributors to play the role of investors.

**Comment by cbeams** [comment]
>  [<img alt="@wiz" width="20" height="20" src="https://avatars1.githubusercontent.com/u/232186?s=60&amp;u=9873a162b49f59b1c2a9fd19ea513019fa060454&amp;v=4">](/wiz) [wiz](/wiz) closed this [3 days ago](#event-3440698770)

When closing a proposal, please always use the form "Closing as `status`". In this case, it should have been "Closing as rejected". The `was:rejected` label should also be added at the same time, but there are permissions issues around doing so, which is why all such closure and labeling issues should be done by the Proposals Maintainer (see https://github.com/bisq-network/roles/issues/30#issuecomment-644632536).

The reason we use the form "Closing as `status`" is because it makes it clear at a glance when scanning through an issue and especially when receiving email notifications why an issue was closed. Without that context, the recipient of the notification has to click through and actually look at the issue to figure out why it was closed.
