### ISSUE TITLE
Decentralize and eliminate the Domain Name Owner and DNS Admin roles

### ISSUE THREAD

**Issue by cbeams** [bisq-network/proposals#211]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

The [Domain Name Owner](https://github.com/bisq-network/roles/issues/77) and [DNS Admin](https://github.com/bisq-network/roles/issues/18) roles are problematic because they centralize control over most Bisq-related domain names. This approach was pragmatic in Bisq's early days, but is no longer appropriate today under the DAO. I propose that we eliminate these roles in favor of handing over ownership and control of each active domain to the operator of each respective web property. Doing so will allow operators to act with greater autonomy and will further general decentralization goals. It is also important to do this because @ManfredKarrer is currently paying for most of the domain renewals, and he has stepped away from the project. These domains should be owned by active contributors responsible for operating the respective web properties.

We are already taking this more decentralized approach with the bisq.wiki domain. @wiz is the current owner of the [Wiki Operator](https://github.com/bisq-network/roles/issues/92) role, and as such he is responsible for paying for renewals of the domain name and managing its DNS (see https://github.com/bisq-network/wiki/issues/7).

Likewise, we have decentralized the ownership of Bisq explorer URLs. There is a lightweight redirect in place at markets.bisq.network that routes the user to, e.g. bsq.emzy.de, bsq.vante.me and other domains owned and operated by individual owners of the [BSQ Explorer Operator](https://github.com/bisq-network/roles/issues/11) role.

The checklist below lays out how all active or once-active Bisq-related domains currently managed by the Domain Name Owner and DNS Admin roles should be transferred.

- [ ] bisq.network => Website Operator/Maintainer (bisq-network/roles#12)
- [ ] bitsquare.io => Website Operator/Maintainer
- [ ] bisq.io => Website Operator/Maintainer

The following is a list of domain names that were never active but were purchased in order to reserve them. It is less important to transfer these. These domains can continue to be owned by @ManfredKarrer if he so chooses. Perhaps certain among them can be let to expire, or perhaps some of them should be transfered, e.g. to the Website Operator/Maintainer. Feedback welcome on what we should do with these.

- bisq.co
- bisq.exchange
- bisq.foundation
- bisq.market
- bisq.org
- bitsquare.info

Also:

- [ ] @cbeams to make @m52go owner of Netlify bisq-network team so he is in full control of the platform that serves the bisq.network website, and @cbeams to remove @ManfredKarrer. @cbeams to remain a 2nd owner there as a secondary for @m52go.

Regarding bonding, the Domain Name Owner and DNS Admin roles do require bonding, but have never actually had bonds posted. That is indeed the impetus for my creating this proposal now. I own these roles, but I believe they should be eliminated, so I don't want to post bonds for them. I believe we can rely on existing bonds for existing operator roles, e.g. Website Operator/Maintainer role already has a 50K BSQ bond, and that bond can simply encompass the ownership of the domain names and DNS management.

When these actions are complete:

- [ ] Eliminate the Domain Name Owner role
- [ ] Eliminate the DNS Admin role

**Comment by wiz** [comment]
> I propose that we eliminate these roles in favor of handing over ownership and control of each active domain to the operator of each respective web property.

That's a great long-term goal to have, but it's not currently possible to do that because everything is all under the same domain name:

* bisq.network
* lists.bisq.network
* docs.bisq.network
* monitor.bisq.network
* markets.bisq.network
* matomo.bisq.network
* explorer.bisq.network

Actually the only thing that isn't on that domain is the wiki, as you pointed out. It seems to me the reason why the Domain Name bonded role was created is because everything is on the same domain name, and why it cannot be eliminated.

**Comment by wiz** [comment]
> bisq.io => Website Operator/Maintainer

Also, doesn't this belong to the Markets API Operator role? For some reason I thought that domain was used for the API.

**Comment by cbeams** [comment]
Good point, @wiz. Perhaps the best solution at this point is to consolidate the generic, catch-all Domain Name Owner and DNS Admin roles into a single "bisq.network domain owner" role whose duties include domain name renewal and DNS administration. I'll think more about it, but yeah, perhaps this just won't work.

As for bisq.io, I don't recall the relationship to the markets API.

**Comment by wiz** [comment]
Sorry it was
```
market.bisq.io is an alias for markets.bisq.network.
```

Maybe we should aim to eliminate subdomains on a centrally owned domain name and do it the BSQ explorer style where we all own our own bisq domain names. I got bisq.ninja so I can use that for something.

**Comment by cbeams** [comment]
> Maybe we should aim to eliminate subdomains on a centrally owned domain name and do it the BSQ explorer style where we all own our own bisq domain names. I got bisq.ninja so I can use that for something.

Something like that would be good. But it's a different proposal. I'm closing this as rejected for the reasons above. Thanks, @wiz.

**Comment by cbeams** [comment]
At @wiz's request, I've reopened and assigned this issue to @wiz. Also per his request, I attempted to assign @m52go but was unable to do so.

**Comment by wiz** [comment]
Thanks Chris. Yeah, after talking to @m52go I think we can implement your proposal to eliminate those roles with a bit more work. Here's the list of subdomain names to migrate that I know of, please let me know any that are missing:
- [ ] bisq.network -> @m52go as Website Operator
- [ ] lists.bisq.network -> @emzy to register new domain for Mailman Operator
- [ ] docs.bisq.network -> @m52go will merge docs into main website and eliminate this
- [ ] monitor.bisq.network -> @freimair to register new domain for Monitor Operator
- [ ] markets.bisq.network -> @wiz to migrate Markets to `bisq.market`
- [ ] matomo.bisq.network -> @wiz to register new domain for Analytics Operator
- [X] explorer.bisq.network -> already decentralized

**Comment by pazza83** [comment]
Hi @cbeams / @wiz thanks for the proposal. I am doing some housekeeping on the proposals. 

I will close this as accepted but please can you update as the status of the work to decentralize and eliminate the Domain Name Owner and DNS Admin roles. You may wish to consider making a [project](https://bisq.wiki/Project_management) for this work.

Many thanks.
