### ISSUE TITLE
@hunternyan request for btcnode operator node

### ISSUE THREAD

**Issue by HunterNyan** [bisq-network/proposals#215]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Hey Everyone,

I'm a Network/Ops/Dev/Infrastructure girl based out in Australia/New Zealand and am really keen to start helping out with this project :)

I've been around places for years running various projects on my own infrastructure and am fairly confident that I can help with this project.

I have been in discussion with @wiz about me running my own BTC Node for use with the Bisq network as a starting point ❤️  

I'll likely be publishing my ansible roles for installing, configuring tor/btc shortly.
Just as an FYI I am a pretty big rhel (centos/fedora) user so it'll likely only work for that platform at first but I can try and make it multi platform to help make this task easier :)

**Comment by wiz** [comment]
Thanks for offering to run a Bitcoin node for Bisq - please keep in mind the 5K BSQ bond requirement pending approval of this approval by the DAO next cycle :)

**Comment by sqrrm** [comment]
Good to see more interested ops.

Ansible roles would be great. Should be possible to adapt to non rhel distros too I imagine. Not super familiar with it, only used it to set up tor relays and it worked like a charm, I have no idea what it does and it (kind of) just works.

To run trusted nodes I would prefer to see some history of contributions. The bitcoin nodes are not the most sensitive but they could still collect data from the SPV usage.

**Comment by wiz** [comment]
@sqrrm check out the wiki https://bisq.wiki/Special:Contributions/HunterNyan

**Comment by wiz** [comment]
@sqrrm check out the wiki https://bisq.wiki/index.php?title=Special:Contributions/HunterNyan&offset=&limit=500&target=HunterNyan

**Comment by MwithM** [comment]
Closed as stalled.
