### ISSUE TITLE
Edit Instant Altcoins

### ISSUE THREAD

**Issue by opticbit** [bisq-network/proposals#217]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Make it possible to edit altcoin offers between instant and not instant

**Comment by cbeams** [comment]
Closing as invalid. Issues in this repository must follow the format laid out in the process link above. It's recommended that you discuss this in the Bisq keybase team first to see if there's sufficient interest to merit project proposal. You can also consider posting an "idea" in the bisq-network/proposals repository.
