### ISSUE TITLE
Schedule offers

### ISSUE THREAD

**Issue by opticbit** [bisq-network/proposals#218]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Have an automatic schedule to turn offers on and off.  Especially instant altcoins.

**Comment by cbeams** [comment]
Closing as invalid. Issues in this repository must follow the format laid out in the process link above. It's recommended that you discuss this in the Bisq keybase team first to see if there's sufficient interest to merit project proposal. You can also consider posting an "idea" in the bisq-network/proposals repository.
