### ISSUE TITLE
Improve incentives for Arbitrator (formerly known as Refund Agent)

### ISSUE THREAD

**Issue by cbeams** [bisq-network/proposals#222]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

## Background
The Arbitrator role (bisq-network/roles#93) often requires large outlays of both BTC and BSQ, putting the person playing that role at significant risk without much incentive for doing it.

## Proposal
Proposed is that we improve incentives for this role by establishing:
- a 50 USD per case fee, and
- a 1% per cycle interest rate for BTC paid out.

## Example
Let's assume that during Cycle 13, the arbitrator handled 8 cases, paying out a total of 4 BTC. Under the proposed incentive scheme, the arbitrator would be entitled to 8x50 = 400 USD plus 4*0.01 = 0.04 BTC.

Let's assume the posted USD / BSQ exchange rate for Cycle 13 is 0.63 USD / BSQ. This means that the arbitrator would be entitled to 400/0.63 = 635 BSQ.

And let's assume the current 30-day BTC / BSQ exchange rate is 0.00007553. This means that the arbitrator is entitled to 0.04/0.00007553=530 BSQ.

Total compensation requested in this example would be 635+530=1165 BSQ.

## Benefits
The main benefit is to ensure the arbitrator is sufficiently compensated for their time and risk, such that they continue performing the role. A secondary benefit is that these higher values should incentivize the DAO to reduce the number of trades that go to arbitration. Ultimately we want to do away with the role entirely, and have traders submit reimbursement requests manually, but that can only happen when there are a sufficiently low number of arbitration cases per month. It's still too high to do this.

## Notes
@RefundAgent already submitted a compensation request for Cycle 13  (bisq-network/compensation#571) based on this scheme proposed here. If you vote to approve this proposal, you should also vote to approve for that compensation request and vice versa.

**Comment by cbeams** [comment]
DAO proposal txid: e56ae10d2f0f3232b019a0ffa954095fc6a3792e1a0b0be2bce0582d542987b0

**Comment by clearwater-trust** [comment]
Did we find a new person to perform this role?

**Comment by wiz** [comment]
While I can see why we might need to do this temporarily, I would really like to see a more general discussion about how we can fix the overall Arbitration system in Bisq to consider the currently unhandled case of an unresponsive trade counterparty.

**Comment by cbeams** [comment]
@clearwater-trust wrote:
> Did we find a new person to perform this role?

We did not.

@wiz wrote:
> While I can see why we might need to do this temporarily, I would really like to see a more general discussion about how we can fix the overall Arbitration system in Bisq to consider the currently unhandled case of an unresponsive trade counterparty.

Agreed. That work needs to be defined and prioritized.

**Comment by cbeams** [comment]
Closing as approved in DAO Cycle 13 (100% approval).

**Comment by clearwater-trust** [comment]
Thank you @cbeams and @wiz. Where/how is the best way to discuss improving Bisq Arbitration that won't spam everybody with my/your "decentralization" propaganda :smile: . How can we discuss improvements?

**Comment by cbeams** [comment]
> How can we discuss improvements?

This is really an open question; we have many communication channels / options, but each have their pros and cons, and it's not really obvious where best to have such a discussion. See https://github.com/orgs/bisq-network/teams/dao/discussions/1, where I discussed these options a bit.

**Comment by cbeams** [comment]
> > How can we discuss improvements?
> 
> This is really an open question; we have many communication channels / options, but each have their pros and cons, and it's not really obvious where best to have such a discussion. See https://github.com/orgs/bisq-network/teams/dao/discussions/1, where I discussed these options a bit.

For more on this topic, see https://github.com/bisq-network/proposals/issues/231#issuecomment-646971933, where I've suggested the creation of a bisq-dev email list.
