### ISSUE TITLE
Add efecty as a payment method (Colombia users)

### ISSUE THREAD

**Issue by ricardosaurio** [bisq-network/proposals#228]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Name: Efecty https://www.efecty.com.co/

Description: Efecty is the main money transmitter here in Colombia, its widely used.

Type: Cash remittance.

Chargeback risk: Moderate. If the person reciving the Cash remittance doesnt cash it out quickly, the remitter could either ask for his money back or change the person receiving the remittance. After cashing out the money, its gone for good and no chargeback can occur.

Privacy protection: Low. You must provide your name and national ID number. When you cash out a remittance, they will also ask for your physical national ID card and your fingerprints.

Duration: Instant. After sending the money the other person can cash it out inmediatly.

Region: Colombia only. The only currency supported is the Colombian peso.

Fees: Variable fees. The highest fee is 2.99% after 500.000 COP (about 135$) https://www.efecty.com.co/calcula-tu-giro-lightbox

Trading limits: Maxium 3'000.000 COP (about 800 usd) per transaction, i couldnt find nowhere if there is a limit of the number of transactions you can do, but they do usually raise eyebrows for doing more than two trades a day. Also, large amounts of money cannot be withdrawn from most offices if they dont have the money with them (yes, 800 usd is a large amount here).

Fraud risk: Low, the sender and reciver will both get a receipt with a serial number (Numero de giro), a verification digit (VD) and national ID number that can be checked by anyone, including mediators and arbitrators. It also states if the money has ben cashed out. https://www.efecty.com.co/consulta-giros

Mandatory data: To either send or recive money, both parties would need to provide their physical ID card and biometric fingerprint. 

Aditional notes: Im proposing this method because Efecty is very popular in Colombia and there is no COP volumen in Bisq and i will volunteer in anything needed to set this method. With risk of putting a bad name on Colombian people (im Colombian anyway), people tend to be dishonest and try to fraud if the oportunity appears. I would suggest at least a 30% collateral for the 2/2 multisig, and i wouldnt mind at all at 50%. Also, to kickstart this. I would ask for a signed account under this method and i would put small trades to sign other people.

**Comment by pazza83** [comment]
https://github.com/bisq-network/growth/issues/192
