### ISSUE TITLE
@leo816 to assume Support Team Lead role

### ISSUE THREAD

**Issue by leo816** [bisq-network/proposals#230]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I would like to formally apply for this role,

My current roles include: 
-  Mediator: bisq-network/roles#83
-  Fee Reimbursement Agent: bisq-network/roles#76
-  Support Agent: bisq-network/roles#64

I have been involved with bisq for over 2 years now. I started making bisq's first ever tutorial video (https://www.youtube.com/watch?v=-o9CKiivyIc&t=1s) and then having a series of critical roles inside the support team that have made me very aware of how each one works. 
I am very passionate about this project and think I have gained enough knowledge through these years that make me an adequate candidate. 

I have added two more duties on the https://bisq.wiki/Support_Team_Lead that I think are inherent to the role, and that I happen to have done to some extent already:

- Review Team's Compensation requests as per Process.

- Manage new internship proposals and evaluate their performance once the period is over.

- Review and supervise the "on duty" schedule.

I'd like to hear if anyone, specially the @bisq-network/support have any suggestions or comments about which direction should the role develop into going forward.

**Comment by MwithM** [comment]
The duties you have added are completely logical and necessary. 
Even without cbeams' depart you were going to take this role, which is great.

**Comment by flix1** [comment]
I'm glad to see that this role will be in good hands.

It's probably not urgent now, but at some point we should start planning for multi-language support. It should factor into recruitment and internship proposals.

**Comment by cbeams** [comment]
This proposal has now been up for nearly a week (and has been discussed for much longer than that). There have been only 👍's in response, and there have been no other contributors stepping forward as interested in the role. I will therefore close this as approved once the following tasks are complete:

- [ ] @cbeams to make @leo816 the maintainer of @bisq-network/support and related teams
- [ ] @cbeams to update and reassign the Support Team Lead role at https://github.com/bisq-network/roles/issues/102 to @leo816.
 - [ ] @cbeams to announce the change via keybase support subteam
 - [ ] @cbeams to announce the change via keybase @bisq-network/support discussion
 - [ ] @cbeams to inform compensation request maintainer (@MwithM) to assign support team compensation requests to @leo816 from here out
 - [ ] @cbeams to add @leo816 to bisq.teamleads Keybase subteam
 - [ ] @cbeams to add @leo816 to @bisq-network/teamleads GitHub team

**Comment by cbeams** [comment]
Closing as approved.
