### ISSUE TITLE
@kbteamowner to post bond for Keybase Admin (Owner) role

### ISSUE THREAD

**Issue by kbteamowner** [bisq-network/proposals#232]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

This proposal is for taking over the Keybase Admin (Owner) role from @cbeams. I am willing to post the 20,000 BSQ bond.

My Keybase handle is also `kbteamowner`. 

None of the special privileges of this role are necessary on a regular basis, so I will not guarantee responses from this account. Those seeking to get in touch with me should reach out to one of the other non-Owner Keybase admins first.

I have made this clear in the name field of my account, which is abundantly visible.

![Screenshot from 2020-06-16 10-32-57](https://user-images.githubusercontent.com/66958208/84788652-e5ba1700-afde-11ea-867b-e6800e43793a.png)

![Screenshot from 2020-06-16 10-33-07](https://user-images.githubusercontent.com/66958208/84788657-e783da80-afde-11ea-892c-6441ed74083f.png)

**Comment by cbeams** [comment]
I confirm that I asked this person to take over this role.

@kbteamowner, please go ahead with submitting this to the DAO for bonding purposes, and when approved, I'll transfer ownership of the team to you and unlock my bond.

**Comment by cbeams** [comment]
@kbteamowner's bond was posted in the last cycle. I have removed myself as team owner and assigned @kbteamowner the owner role as planned. I have also just unlocked my bond.

@kbteamowner, please confirm and close this issue.

**Comment by cbeams** [comment]
I accidentally closed this myself, but probably fine.
