### ISSUE TITLE
Support for HTLC cross-chain atomic swaps between

### ISSUE THREAD

**Issue by HarryR** [bisq-network/proposals#235]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I'm surprised that Bisq doesn't already support cross-chain atomic swaps, as it could make the conversion between BTC and many Bitcoin-based (or chains with support for compatible hash functions / contracts) much faster, more reliable and with less user intervention.

This is possibly less important than making 'Altcoin instant' fully managed by the Bisq software by connecting directly to the daemon via JSON-RPC (or interacting directly with the network with the BitcoinJ fork). I would also be very interested in that too, and it could serve as a prerequisite for a HTLC implementation.

Background: 

 - https://liquality.io/blog/hash-time-locked-contracts-htlcs-explained/
 - https://en.bitcoinwiki.org/wiki/Hashed_Timelock_Contracts
 - https://en.bitcoin.it/wiki/Hash_Time_Locked_Contracts

Aside from the core logic of HTLC swaps there are client & protocol changes necessary, however I'm not very familiar with Bisq protocol so your input would would be appreciated.

For the Bisq protocol side there would need to be communication between the two parties for the swap to be accepted, e.g. both sides negotiate the hash pre-images according to the HTLC protocol.

Because direct transaction construction is needed to follow the HTLC protocol it wouldn't be feasible to require people to do potentially complex stuff with raw Bitcoin transactions, not to mention the margin for user error etc. This would need the Bisq software to push transactions directly to both networks.

Compatible coins (probably more):

 * BTC
 * LTC
 * ETH (and most tokens)
 * ZEC
 * DASH
 * DCR

Feedback is welcome

**Comment by DarkS0uls** [comment]
@HarryR,  Hi .I'm interested in one of your projects in github. please bring me a mail to contact or write me topablo.steven@hotmail.com. I'll be wait the reply.

**Comment by MwithM** [comment]
Closed as stalled.
