### ISSUE TITLE
Action Protocol for Mediators

### ISSUE THREAD

**Issue by leo816** [bisq-network/proposals#237]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Given the feedback from the first draft here is the formal proposal for mediators:

This is a proposal for a fixed action protocol for mediators, up until now was less vaguely established. These are some common situations that mediators stumble upon:

1) **_If the seller provides the wrong banking/address information_**

The seller will lose 50% of the deposit in favor of the buyer. Regardless as to whether the buyer wants to continue with the trade or not, this will be a fixed policy. 

2) **_If the buyer has made the payment and the seller is unresponsive:_**

Mediator will have to wait 48hrs for an answer from the btc seller, if he doesn’t respond, the seller will lose 75% of the deposit. 

If the seller responds on time but from then on goes missing for 48hrs, the same applies.

3) **_If the buyer doesn’t pay from the correct account._**

+ Will incur in a penalty, losing 50% of the deposit. Regardless whether the seller wants to continue with the trade or not. (he has priority when choosing if he wants to continue)

Steps to follow:
+ Ask the buyer for a screenshot of the payment as proof using [Veruv.com](https://veruv.com).(where you can see the account he made it from) And an explanation as to why he didn’t comply with the contract.

+ Given that the seller wants to continue with the trade. The mediator will penalize the buyer by having him wait to receive his btc. 3 days before indicating the seller to release. Reminding him that this is a crucial issue at bisq and this is a way to protect it from a scam.
 + If the buyer doesn’t respond and the seller wants to cancel he can choose to return the payment and cancel the trade.

**Comment by clearwater-trust** [comment]
I like having this documented. There are missing cases. For example, what if the BUYER is unresponsive? What if the buyer never sends the payment?

How does the system do this: 

> If the buyer doesn’t respond and the seller wants to cancel he can choose to return the payment and cancel the trade.

How does the cancellation proceed in terms of btc custody?
How will the penalties be scheduled? programatically?

**Comment by MwithM** [comment]
I can't find the draft but my concerns are basically the same:
1. How are sellers' penalties going to be [enforced](https://github.com/bisq-network/bisq/issues/4162)? 
2. I think that suggesting someone to accept a 100% of deposit loss is the same as sending it to arbitration. It's probably better also for the victim to suggest something like 75% so the part who broke the protocol has incentives to accept the mediation and the victim will get the BTC earlier.

Just to clarify: point 3 doesn't affect to altcoins trading, right? I mean, buyers can send from any address and as long as the quantity is ok, it will be valid.

**Comment by sqrrm** [comment]
To incentivize traders to accept payouts it will never be reasonable to take 100% of the deposit. Perhaps it's would be good to indicate that as @MwithM suggests, 25% of the deposit will always go back to the trader as incentive to accept the payout. The remaining 75% can then be used as punishment of different degrees.

It would also be good to have a protocol for arbitration here. Typically I would suggest that a party at fault that didn't accept the mediated payout should never get anything.

**Comment by leo816** [comment]
> How does the system do this:

@clearwater-trust The system does this two ways: 1) both parties accept the proposal 2) one of the parties doesn't accept, the trade goes into arbitration and the refund agent applies this action protocol given the situation.
On scenario n2 the funds come from the refund agent, and he is reimbursed after the funds from the trade go to the donation address.

> How are sellers' penalties going to be enforced?
@MwithM good question, this penalties can be enforced because its premise is that one of the parties will disagree with the mediation proposal. Therefore if the seller, for example, decides to reject the mediation proposal, the trade will eventually go into arbitration and the refund agent can enforce the penalty making the payout as he does normally.
The issue here is with a different scenario. When the seller doesn't respond/confirm the payment, he could still potentially have the buyer waiting 10-15 days before confirming and incur in no penalty whatsoever. This is what needs to be solved right now. Any ideas are welcome.

> I think that suggesting someone to accept a 100% of deposit loss is the same as sending it to arbitration. It's probably better also for the victim to suggest something like 75% so the part who broke the protocol has incentives to accept the mediation and the victim will get the BTC earlier.

I like this idea, just updated the proposal. In a way this was already the case 

> (keep in mind that it the seller will never lose 100% if the deposit because a fraction will always go back to him as we have had issues in the past with previous versions)

for example in a 0.01 btc trade, a 0.006 deposit is set. The mediator can only propose a 0.003 btc minimum to go back to the seller, he can't set it any lower. So this action protocol may not always be applied but can be left as the standard for mediators to get close to.

> Just to clarify: point 3 doesn't affect to altcoins trading, right? I mean, buyers can send from any address and as long as the quantity is ok, it will be valid.

that's right, this is referring to bank addresses.

> It would also be good to have a protocol for arbitration here

good idea, will work on that next

**Comment by MwithM** [comment]
Buyer pays after 1st confirmation, and the next day the EUR are at the sellers banking account. There's 7 days trading period for SEPA, and seller is unresponsive.
After 7 days, buyer opens mediation provides proof of payment to mediator and seller is still unresponsive. Mediator suggest that 75% of the seller's security deposit must go to the buyer. That is after 9 or 10 days since the start of the trade. Buyer agrees with that, accepts suggestion. Seller is still unresponsive.
19 days since the start of the trade, seller pushes the "payment received" button, wasting moderator's time and delaying for 19 days the reception of the trading funds for the buyer. There's no high incentive for seller to act this way, but it's still possible at a relative low cost (having from 15 to 50% of the trade funds locked into a multisig account for 19 days) and it hurts a lot.

Also on a different side: if for any reason, buyer doesn't agree with moderator's suggestion, seller can override it just pushing the "payment received" button. 

I think that implementing one of [these solutions](https://github.com/bisq-network/proposals/issues/224#issuecomment-646280169) (software lock or trading protocol change) is a priority.

**Comment by MwithM** [comment]
Supeseeded by project 39 linked above.
