### ISSUE TITLE
Try to get funding for implementing automated XMR trades

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#239]
Based on the [Integrate transaction proof verification for Monero](https://github.com/bisq-network/proposals/issues/86) proposal I would suggest to start a request for getting the implemention of that feature funded by sponsors. 

A developer or team of developers should lay out their roadmap, define delivery criterias and estimated costs. As soon enough sponsors have been found (or the DAO decides to fund the project or part of it) to cover the costs they should start to work on it and deliver it in the proposed roadmap schedule.

I think that feature can speed up XMR - BTC trades a lot on Bisq and bring back more XMR trade volume. It should also decrease number of disputes in case the XMR wallet of the BTC seller is out of date and he does not see the incoming tx or is just late with confirming the XMR receipt. It also should signal to the Monero community that Monero is important to Bisq and repair some of the reputational damage caused over the past year with various unfortunate events (e.g. XRM wallet, Reddit trolls,...). It can also be used to attract strong developers from the XMR community.

If it shows that it increases trade volume and is actively used by traders we can start to add support for other altcoins with serious trade volume as well by using a lookup to the altcoin blockexplorer. 

Rough sketch for a roadmap:
- Add option to preferences to use the automated confirmation tool. At roll out show a popup to XMR traders to inform about the feature and mention the security limitations (the tx key validation service could be corrupted). If user agrees to use it he confirms to understand different security model. Add it as new feature to the news badge as well.
- Add tx key input field for XMR sender in trade process UI
- Send tx key with the "payment started message" to peer (add new optional field)
- BTC seller starts to periodically poll one of the tx key verification services. At a first step we could use the existing services. As a second step it would be good that those services are run by bonded Bisq contributors similar to other infrastructure nodes.
- In case the services do not support connections via Tor (assumed) we need to launch another relay node similar to the mobile notification replay or price nodes.
 - After receiving a response that the tx key was found and the XMR transfer done the seller app automatically confirms payment receipt.  

Optional: Instead of a (expensive and slow) polling of data from the service we could use a subscriber model, where the service notifies the Bisq app once the interested tx is confirmed. This would work only with a custom imlementation of the service.

Both models have privacy implications as the service will learn about the onion address of the requester (or the relay service will learn about that). As we support now multiple onion addresses that might be mitigated to use a temporary address for that request, but that requires more analysis of that is feasible.

**Comment by RefundAgent** [comment]
Anything that could be automatic should be made automatic and this proposal is definitely in the right direction. There is a trade-off between privacy and security but I am confident that essentially all traders would prefer the automatic option.
