### ISSUE TITLE
Add iDEAL as payment method

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#244]
iDEAL is a instant payment method for Durch banks. It does not allow chargeback and used 2FA accourding to https://en.wikipedia.org/wiki/IDEAL. Because of that it could be added without requireing account signing and enable higher trade amounts.

 Maybe best to get a dutch Bisq trader for feedback.

**Comment by MwithM** [comment]
The wikipedia article needs is requiring a citation for the no-chargeback. Probably because iDEAL doesn't define clearly the terms of this.
It's like they don't know if this feature is important.

**Comment by chimp1984** [comment]
The wiki article seems to be written by themself....
Does anyone know a Dutch Bisq user who could assist with the spec (required data fields, chargeback risk,...)?

**Comment by pingiun** [comment]
I think no information fields are required really. The problem with the UI is that the seller will need to send a payment link instead of the buyer starting the transaction.

The UI should reflect that the seller has to send a payment link and the buyer should wait for that in the chat

**Comment by chimp1984** [comment]
Can a payment link be re-used? If so it could be used like the account number for receiving funds.

**Comment by pingiun** [comment]
This depends on the bank/service you use for ideal payment links. Some systems will allow multiple payments, but I believe all systems have some expiry. The link can thus not be used like an account number.

iDeal is really a method that is meant for online merchants. I think the OP refers to the feature that some banks provide, as wel as "[Tikkie](https://www.tikkie.me)" which allow the user to create payment links where someone else can pay using their national bank account. All Dutch banks have to support iDeal so this is an easy way to request payments in the Netherlands.

**Comment by MwithM** [comment]
Since we have @pazza83 helping with payment methods, this proposal is assigned to you, make the proper actions to include (or not) this payment method on ongoing releases.

Closed as moved.

**Comment by pazza83** [comment]
Cheers @MwithM I will take a look

**Comment by MwithM** [comment]
Ok I reopen, but as this payment method is not very different to others, next similar requests should be discussed at Growth repo.

**Comment by chimp1984** [comment]
@pazza83 is dealing with that now

**Comment by pazza83** [comment]
Although this method looks promising, and despite some information to the contrary, I am not convinced peer to peer payments are easy to set up. It seems to be more business to consumer orientated. I am investigating with https://www.ideal.nl/en/consumers/what-is-ideal/ and will create a new issue if feasible.

Tikkie seems to be purely business to consumer orientated so that is a non starter.

**Comment by pingiun** [comment]
> Tikkie seems to be purely business to consumer orientated so that is a non starter.

Tikkie is actually meant as peer to peer. The page you visited is probably oriented towards businesses who want to receive payments using Tikkie to avoid the hassle of setting up their own iDEAL payments. I will show you some screenshots to show how it works for regular people.

![IMAGE 2021-04-22 18:05:55](https://user-images.githubusercontent.com/1576660/115747284-641cdd80-a395-11eb-939b-44d40a026bb6.jpg)

This screenshot reads: "I want to ask 1 person for money". It allows you to select a maximum amount of payments here. There is also an unlimited amount, which would then only be limited by time (I could look up how long).

On this screen there is also a toggle that reads "let my friend fill in the amount". This is mostly used when the amount is not the same for everyone.

![IMAGE 2021-04-22 18:08:50](https://user-images.githubusercontent.com/1576660/115747708-cc6bbf00-a395-11eb-9eee-3c73814919df.jpg)

This reads "what is it for?". This allows for a payment reference. When used with friends this usually reads something like "Pizza". It cannot be left empty.

When this field is filled in, the big button will share a link on Whatsapp---as this is a common communication platform in the Netherlands. The small share button pops up the regular sharing menu, where a link can be shared.

The share menu generates a text to be shared with a messaging app. The text reads "Wil je mij alsjeblieft € 123,00 betalen voor 'Bisq' via https://tikkie.me/pay/kpg0efpt6ht28f7v2jsp".

This translates to "Can you please pay me € 123,00 for 'Bisq' via ..."

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/1576660/115748371-6469a880-a396-11eb-9e57-5bbff8c1c2ea.png">

This is the payment page you see when visiting the link. It shows only the first name of the receiver. From here you can pay with iDEAL, which is an online payment method supported by all Dutch banks.

If I select my bank, I get redirected to my banking website. From here the process is different for each bank. The banking page will show the full name and IBAN of the receiving party.

After the iDEAL payment is done, the payer gets redirected to the tikkie.me webpage with a thank you message. The receiving party can immediately see that the amount has been paid in the tikkie app, but might not immediately see the payment in their banking account. There is no service fee (this service makes money by having pretty high service fees for business usage, and it's owned by a large bank).

I think this method is lower risk than with SEPA payments. The bank might revert the payment from the payer, but this would result in Tikkie having to pay it back. I don't know what Tikkie's policy is regarding chargebacks, but I don't think they have the ability to remove money from the receivers bank account. 

Tikkie is developed by ABN Bank, but other banks like ING or ASN Bank have similar services. 

**I recommend reopening** this issue, but possibly making it specific for Tikkie. The other bank services work in pretty much the same way but might show the information at different times, which makes it harder to integrate into the information screens.

**Comment by pazza83** [comment]
Hi @pingiun cheers for this, much appreciated. The info is really helpful.

I will reopen as advised as Tikkie. I will cc you in so you can check the proposal. I had trouble accessing Tikkie from my region so it would be great to have your input.

Many thanks

**Comment by pazza83** [comment]
Hi @pingiun I am closing here as I have opened [Add Tikkie as a new payment method (popular in The Netherlands) #247](https://github.com/bisq-network/growth/issues/247)

**Comment by janvlug** [comment]
I'm new to Bisq. The first thing I looked for was if [iDEAL](https://ideal.nl/en) is supported, because that is the most common way for internet bank payments in the Netherlands. I use it for most internet payments. I'm living in the Netherlands.

I'm a bit confused that this issue is close in favor of Tikkie. Tikkie is not the same as iDEAL. Personally, I've never used Tikkie, although it is popular in the Netherlands. Tikkie is something different from iDEAL. I think Tikkie is a specific service of ABN AMRO bank that can also used by customers of other banks via an app. Tikkie works on top of iDEAL, according to [this article](https://www.abnamro.com/en/news/abn-amro-enables-payments-via-whatsapp-in-the-netherlands): "The app < Tikkie > processes requests through the familiar payment platform iDEAL."

Could is issue please be re-opened for pure iDEAL?

Also note that [iDEAL will become Wero](https://ideal.nl/en/naar-wero) starting next year. iDEAL is way bigger and more important than Tikkie.

**Comment by pingiun** [comment]
@janvlug as mentioned in my comments, iDeal is not available to consumers. This means it cannot be used for peer to peer payments that Bisq uses

**Comment by HenrikJannsen** [comment]
@pingiun Thanks for the info. So lets close the issue again.

**Comment by suddenwhipvapor** [comment]
payment method not accessible to normal users as per https://github.com/bisq-network/proposals/issues/244#issuecomment-3647681540
