### ISSUE TITLE
Increase Asset listing fee

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#245]
I think it is time to increase the asset listing fee. I am aware that asset listing is on hold but once it will be activated again we should have a more reasonable fee.

From the 100s of assets there are only very few actively traded and the huge percentage was never trades at all. This shows clearly that there was no real demand for that asset or no intention from the asset distributors to get trade volume on Bisq. They added it as is was very cheap and its good for PR to have one exchange more in their list.

I suggest to increase the asset listing fee from 1 BSQ/day to 10 BSQ/day (max. allowed change). This still only is about 200 USD for a month of trial period. If no trade activity happens after listing it will never happen in most cases.

This should also reflect upcoming costs for implementing automated altcoin trading which will require to run some altcoin explorers. Those costs are at least about 200 USD/months to host 2 explorer nodes.

Please up/down vote. If support is sufficient I will make a DAO proposal.

Trade volumes:
<img width="1073" alt="Screen Shot 2020-08-12 at 14 14 37" src="https://user-images.githubusercontent.com/54558767/90057595-3a5bd480-dca6-11ea-9920-ff5a5788d95d.png">

Fees paid:
<img width="1063" alt="Screen Shot 2020-08-12 at 14 14 48" src="https://user-images.githubusercontent.com/54558767/90057585-35972080-dca6-11ea-8857-d0184468da21.png">

**Comment by wiz** [comment]
ACK, but I would like to point out that the proposal I made to list L-BTC exempted it from listing fees, so I will claim reimbursement from the DAO if this proposal passes.

**Comment by chimp1984** [comment]
L-BTC has paid the fee, the change would only apply to new listings/fees. Though there is an issue when one pays additional fees lower than the existing paid as it happend with L-BTC. One paid 356 BSQ, then later one paid 30 BSQ. Now trila period is not 256 days but 30 days. That was a known limitation on implementaion side as it would be more complex otherwise to handle it correctly. I might try to fix that issue or to show at least some warning so that it does not happen again. We can also fix it by someone adding again it lost days and doing a reimbursement as the issue is a kind of bug and the extra burned BSQ are not justified.

**Comment by chimp1984** [comment]
Proposal done: c6dae566e95a1f4c2c40fef28f79d8cd8cb26a722171e82bb9eb4322927f7971

**Comment by chimp1984** [comment]
Was accepted in voting.
