### ISSUE TITLE
Denominate security incident repayments in usd

### ISSUE THREAD

**Issue by m52go** [bisq-network/proposals#249]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

When a mechanism for security incident repayments was determined in #209, two determinations were left to be made:
1. The portion of the Bisq DAO's BTC revenues used for repayments
2. Whether the amount to be repaid will be denominated in US dollars or in bitcoin

This proposal covers the second item.

I'm not sure there's an objective, data-backed approach to this topic. Whether repayments should be measured in terms of USD or BTC lost at the time of the incident seems like a judgment call.

BTC price is wildly volatile. Committing the DAO's meager and uncertain resources to a sum pegged to the price of an instrument that could be 2x or 10x (or 0.5x) its current price in just a few months seems irresponsible.

While [it has been argued](https://github.com/bisq-network/proposals/issues/209#issuecomment-613386563) that an increased BTC rate should bring about more trading activity and higher revenue, such an outcome is not guaranteed. There are a host of potential tailwinds that could push revenues in the other direction. Major mining fee spikes, another security incident, issues with common payment methods, etc could all cause major disruptions in trading volume even during major bull markets.

I suggest a two-step approach:
**1. NOW: committing network resources to repaying the full USD value of the coins stolen at the time of the theft**
2. FUTURE: offering affected users the option of requesting reimbursement from the DAO for any remaining funds after the currently-accepted payout is completed (if possible)

Item 2 is tentative, and this proposal (if approved) is not meant to serve as an assurance that it will take place. I include it here mainly to convey that this proposal doesn't _necessarily_ put a hard cap on the repayment sums for good.

Perhaps network performance and market conditions will make it reasonable to repay the full BTC value of lost funds at some point in the future. Or maybe that won't happen. **We simply cannot know right now if (or when) that scenario will play out.**

Therefore it seems to make most sense to commit to something we are reasonably sure can be delivered, while leaving open the potential for a full BTC-denominated payout if it becomes feasible.

**Comment by sqrrm** [comment]
The Bisq DAO is using USD as a unit of account, for that reason it makes sense to pay back the victims in USD.

**Comment by MwithM** [comment]
closing as approved
