### ISSUE TITLE
Detect when Tor is rate limiting connections

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#250]
As @wiz pointed out at https://github.com/bisq-network/bisq/issues/4328 Tor does apply rate limiting if traffic becomes too high. We should add a method to detect that and react by decreasing number of connections and maybe adjusting other network parameters. It should be a class other network classes can use to determine their parameters.
The information should come over an API from the netlayer library (written in Kotlin - so a Kotlin dev would be good to work on that).

Any dev up for it?

**Comment by wiz** [comment]
I think @chimp1984 is the best developer to investigate this issue 🐵
