### ISSUE TITLE
Add cancel trade button

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#251]
To reduce disputes we should make option trades a feature and give the BTC buyer the option to cancel a trade. This would trigger a message at the seller asking him if he accepts the cancel-trade request and a part of the security deposit will go to the seller as reimbursement. If he accepts he sends a pre-singed tx to the buyer and the trade completes with that payout distribution. Technically it is similar like accpeting the mediated payout distribution.

**Comment by Bayernatoor** [comment]
The trade would only cancel if both parties agreed correct?

**Comment by chimp1984** [comment]
Yes. One can make a request to peer and will get back only 0.003 BTC (min payout from sec deposit in case he loses mediation case). Peer gets a popup asked to accept or reject. if accept he gets the deposit of the peer - 0.003 btc.
its same as like when mediator close and give max to the peer who did not "cancel". Just to avoid work for mediators.

**Comment by initCCG** [comment]
Based on trends in other markets, seems that offers that are actual calls and puts from their creation might become popular.
