### ISSUE TITLE
Reimbursement for trade WTZETDH

### ISSUE THREAD

**Issue by ncstdc** [bisq-network/proposals#254]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I am the maker/seller in this trade. The taker/buyer never sent payment and in the end, requested to cancel the trade. I declined to cancel. However, both the mediator and arbitrator decided to return the buyer's security deposit.

https://github.com/bisq-network/support/issues/486

Returning the security deposit for non payment encourages users to use this as a free options trading platform. Also, what is the point of the security deposit a buyer can decide to cancel and request it back. I was willing to negotiate a portion of the security deposit to cancel, but was never given the option nor chance.

Requesting reimbursement of the buyer's security deposit of **0.06 BTC** or **975.29258778 BSQ** (30 day average 0.00006152)

**Comment by ifarnung** [comment]
I think ncstdc makes a valid argument, and should likely have received some portion of the non-performing trader's security deposit.
HOWEVER, the deposit was **.006** not ,06 BTC so this needs to be modified to be properly evaluated by the contributors.
@ncstdc Please correct this before submitting to the DAO.

**Comment by clearwater-trust** [comment]
i agree. it sucks for the arbitrator and mediators to be called out for this kind of error.  but they need to get the fees correct. 
c'mon. lets get it right. we need to be running on all cylinders for the approaching reset.

WAKE UP!

**Comment by ncstdc** [comment]
Closed this because I thought I had to open an issue here to make a proposal. Please continue the discussion here - https://github.com/bisq-network/support/issues/486
