### ISSUE TITLE
Penalty for BTC buyer's when failing to make a payment

### ISSUE THREAD

**Issue by leo816** [bisq-network/proposals#255]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

-If the Buyer doesn’t pay or says he made a mistake when accepting the wrong trade this will be the procedure followed by mediators:

A 20% deposit penalty will be set as the standard. This may be overruled by the mediator if he is given enough evidence to do so. (Consider that if this is truly a mistake from a buyer who just begun using the app, he is likely doing a small trade and 20% of the deposit won’t be very significant.)
This situation has been harder to judge because it's not easy to tell when someone is genuinely new to the app or the are just trying to take advantage of the price volatility.

 Steps to follow:
- Mediator will first asses the situation by considering the btc price volatility on the time frame when the trade was accepted to make sure the buyer is not pulling out because the price went down.
-Mediator will ask for proof of the alleged excuse as to why the buyer didn’t make the payment.
- Mediator will then consider whether he will apply, if any, a smaller or larger penalty to the buyer.

**Comment by MwithM** [comment]
If it is implemented, the conditions set on this proposal (20% security deposit lost) should be the conditions for the cancel trade button of [this proposal](https://github.com/bisq-network/proposals/issues/251).
Maybe your proposal and #251 should be merged, although it might be good to accept and implement this one as soon as possible (it doesn't require any code).

**Comment by chimp1984** [comment]
@leo816 Could you rename the proposal? "If a BTC buyer doesn't make the payment" does not sound like anything you propose.

**Comment by pazza83** [comment]
Closing as accepted but subsequently superseded by https://github.com/bisq-network/projects/issues/48 Specifically the creation of a [Table of Trade Penalties](https://bisq.wiki/Table_of_penalties)
