### ISSUE TITLE
Arbitration Action Protocol 

### ISSUE THREAD

**Issue by leo816** [bisq-network/proposals#256]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Since we've experienced incidents with the Arbitrator/ Refund Agent on past trades, he has decided to stop taking care of larger trades for security reasons. There needs to be a better communication about larger trades potentially having a delay when reimbursing in the event there is a bug or unresponsive party.

What is a large trade?
1) The threshold at the moment is 0.5 BTC.
2) The trader will get his BTC using the same rate when (if) trading with the Burning man.

Any communication with the traders should include a statement that they will get most, if not all, of the non-responding traders security deposit. So they will make a profit compensating for the trouble they've had.

**Comment by RefundAgent** [comment]
The RA follows the mediation suggestion most of the time, but increases the punishment for traders that abandons a trade. This is to incentivize the traders to accept the mediation as well as to compensate the honest trader for the extra time spent going through the RA. Since the RA does not have access to the mediation history, only to the summary, it would be helpful in difficult cases if the summary was a bit more extensive than the one-liners that are typically the case now.

The RA sees himself as person that decreases the friction of getting reimbursed, and that is why he follows the mediation suggestion. There will sometime be a mistake made by the mediators and in such cases the RA will correct the suggestion.

**Comment by leo816** [comment]
> The RA follows the mediation suggestion most of the time, but increases the punishment for traders that abandons a trade. This is to incentivize the traders to accept the mediation as well as to compensate the honest trader for the extra time spent going through the RA. Since the RA does not have access to the mediation history, only to the summary, it would be helpful in difficult cases if the summary was a bit more extensive than the one-liners that are typically the case now.
> 
> The RA sees himself as person that decreases the friction of getting reimbursed, and that is why he follows the mediation suggestion. There will sometime be a mistake made by the mediators and in such cases the RA will correct the suggestion.

@RefundAgent I would also add that you should always contrast the new information you get from users. Particularly if it's just one party the one messaging you. On the latest case where the mediator made a mistake, the user rejected the mediation proposal but you still followed up and made the payout regardless of his warnings and without doing any research about the case. This diminishes the whole point of rejecting the proposal. That is precisely done for that purpose and it deserves at least, another look from the refund agent.

**Comment by pazza83** [comment]
Hi @leo816 

Has there been a proposal or any documentation of the following:

>Since we've experienced incidents with the Arbitrator/ Refund Agent on past trades, he has decided to stop taking care of larger trades for security reasons. 

We have a new @refund-agent2 so should there preferences be considered? or is the 0.5 BTC limit imposed as larger amounts represent a risk to the DAO?

Either way it would be good to be defined and documented in a wiki so traders of over 0.5 BTC can know what to expect.

**Comment by refund-agent2** [comment]
Right now, I'm reimbursing up to 0.5BTC, 2 times max per cycle and only if the proposal phase is not close, and leaving the rest for the DAO.
My role is not dangerous for the DAO, as I need to get reimbursed from the DAO in BSQ and all the refunds are paid from my own BTC. This limit is to reduce the risk I take performing this role.

**Comment by pazza83** [comment]
Hi @leo816 / @refund-agent2 

I will keep this proposal open.

I think the limit of 0.5 BTC being refunded has been accepted as in practice refunds of over 0.5 BTC are now not happening.

The outcomes for this proposal still need documenting.

Still unclear is:

- [Partial reimbursements](https://github.com/bisq-network/proposals/issues/296)
- What BTC/BSQ rate to be used?
- Where the information is documented to make traders aware

**Comment by pazza83** [comment]
Closing as accepted. This proposal has been implemented and there have not been any opinions to the contrary
