### ISSUE TITLE
Establish new role for Monero Explorer Operator

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#257]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

As part of the new auto-confirmation feature for Monero trading implemented in https://github.com/bisq-network/bisq/pull/4458, the Bisq DAO needs bonded Monero Node Operators. This proposal is to formally establish the new role under the Ops Team as follows:

Initial Owners: @emzy @wiz 
Bond Requirement: 20,000 BSQ
Monthly Compensation: 100 USD

The currently unused DAO bonded role for "BSQ Explorer Operator" will be renamed to "Explorer Operator" and used for this purpose.

**Comment by Emzy** [comment]
TXID: d037578e2a8a123961f34babf5c37e76b387c0586220974c229b38ed81ad1f02

**Comment by wiz** [comment]
TXID: f56cf2877b6537f4be66719788677f30ffe1047208dd6c6161210df00276c3d3

**Comment by MwithM** [comment]
I don't expect much polemic about this proposal, as the new auto-confirmation feature needs it and the prices are standard, so I tag it as approved and I'll close it in a week or so.

**Comment by wiz** [comment]
@mwithm please leave open for now as it requires DAO voting approval for the bonded role holders.

**Comment by devinbileck** [comment]
Tx ID c9596d0fd31b44825267050e659703442d6c37946e68024124a67246236d7adc

**Comment by MwithM** [comment]
Approved through bonded role proposals at DAO voting on cycle 17.
