### ISSUE TITLE
Add BOLETO as payment method for brazilian currency real (BRL) transactions

### ISSUE THREAD

**Issue by smcama** [bisq-network/proposals#262]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Boleto is one the most popular ways to pay bills in Brazil. Banks, companies and people use it for a long time. Basically it is a barcode that you can pay at banks, lottery agents, supermarkets and many retail stores in Brazil. You can also buy online at your e-bank, by phone or at any brazilian ATM. The payment is credited in one business day and there is **no chargeback**. Payments made in cash have complete privacy to the btc buyer.

This improvement has the potential to increase the BRL/BTC market size exponentially.

[https://en.wikipedia.org/wiki/Boleto]

The boleto shows some seller information, but not more than many payment methods we already use in Bisq with no issues about it. Full name, Adress and Brazilian tin (CPF/CNPJ).

The only important field is the **barcode** itself, but in order to check it would be good to inform also **due date**. I suggest the due date should be always the next business day. The buyer can still pay at the same day and it will be credited next day. or pay at the next day and the credit will come in the day after this. The timer could be set for a maximum of 6 days to finish the trade because it is not credited on weekends, therefore if you buy btc at friday and decide to pay it the next business day (monday), the seller will need until tuesday morning to confirm it was credited. So you need a maximum of 5 days, but I added one extra day just in case.

**Comment by m52go** [comment]
@smcama hi, appreciate the suggestion. Would you mind moving this issue to https://github.com/bisq-network/growth/issues? 

That's a better place for this discussion.

**Comment by smcama** [comment]
I don't mind, but I don't know how to do it. Can you help me?

**Comment by m52go** [comment]
I don't think it's possible to move issues from one repository to another...just close this issue and open a new one here (https://github.com/bisq-network/growth/issues). And you can copy/paste the text from this issue to the new issue.

**Comment by smcama** [comment]
I will create a new and delete this.

**Comment by smcama** [comment]
I just created a new one: https://github.com/bisq-network/growth/issues/199
