### ISSUE TITLE
Require the Burning Man and Refund Agent roles to maintain a Google Docs spreadsheet

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#263]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

It is currently very difficult to track or audit the financials of the Bisq DAO. For example, I can see the [Bisq donation address](https://mempool.space/address/3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV) has now received over 50 BTC, which also contains user funds that got refunded, but where is the accounting of that 50 BTC? How much of it was actual BTC revenue from trading fees, and how much of it was trading capital donated to Bisq? How much of it was refunded by the Refund Agent? Can anyone answer these questions at all? Is anyone tracking the DAO's financials?

AFAIK this data only exists scattered among random GitHub comments in a long thread that's not easy to follow or verify. In the past while trying to follow the money, I [found an obvious mistake where 2.14 BTC was accidentally paid out twice and lost by the Refund Agent](https://github.com/bisq-network/roles/issues/93#issuecomment-657219687). As he said in [his reimbursement request to the DAO for the lost 2.14 BTC](https://github.com/bisq-network/support/issues/461#issue-661744919), it's not entirely his fault, the "system" is just really bad.

I propose that the BM and RA collaborate on a simple Google Docs spreadsheet. It does not need to be fancy, but the numbers should absolutely add up, and my questions at the top of this proposal should be able to be answered with a quick glance. Simple mistakes like the ones would likely have been avoided by using a simple spreadsheet, and users should be able to easily verify the data contained in it by clicking on blockchain explorer links.

If the BM and RA do not want to create the spreadsheet themselves, perhaps we can make a BSQ bounty for someone who is good with spreadsheets for this very critical task of auditing the DAO financials.

cc @burningman3 @refundagent

**Comment by cbeams** [comment]
Agreed. I did basic auditing of refund agent reimbursement requests a number of times as part of the duties of playing the support team lead role. It was very cumbersome to do, and incomplete in any case as I had no real visibility into donation address inflows and outflows. As far as I can tell, we are operating more or less completely on trust here, and doing little or no systematic verification or auditing that actually makes a difference. The suggestion of a spreadsheet seems like the bare minimum that should be done to better account for things. It would be a welcome contribution from my perspective if someone steps up to own this. It'll require working closely with the burning man and refund agent to understand their process and ensure that they update that process to incorporate using the spreadsheet.

**Comment by sqrrm** [comment]
We made a mistake to mix fees and payouts that are to be refunded in the same address. That makes it very cumbersome to distinguish fees from refund cases. We can work around this for now setting a different fee address in the filter that's currently used to decided where fees are sent. I think we could even allow for a native segwit address now, or at least after we hard for in segwit to the trade protocol. 

It's not that simple changing the donation address that's used for delayed payout txs. If we were to enforce the address that's voted through the DAO it would fail for traders that don't use the DAO so we're now relying on a set of hard coded addresses, which are also the ones voted on through the DAO, but if a new one was voted in without being hard coded that would be a problem.

Separating into two addresses would surely help with auditing. The second issue doesn't really matter for auditing but it matters in how fast we can move when it comes to changing anything in this area.

**Comment by chimp1984** [comment]
@sqrrm We do not know 100% if segwit requires a hard fork. Probably not. A trade protocol update will be enough. So in that case it need to be legacy address. We can change it later after a few released when 95% have updated and require the 1.4.2. version as min. version in the filter.

**Comment by wiz** [comment]
Closing as approved, @burningman3 @refundagent let's talk on Keybase about how to setup the Google Docs spreadsheet together.
