### ISSUE TITLE
Features which would require/benefit from a Bisq hard fork

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#267]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

There are several ideas around which come with rather large changes and it will be challenging to implement those in a backward compatible way. In fact to achieve that is often a considerable effort. Of course we want to avoid a hard fork as far as possible as it comes wich severe disruption for users. Bisq only had 1 real hard fork so far. There are severl shades of soft/hard fork and we have several tools at hand. But I consider a hard fork here that users basically need to switch to a new application, using a different network and cannot use the old local data (conversion tool can be provided).

Here is an uncomplete list of features/ideas which would be candidates to require or at least benefit from a hard fork:
- [Remove maker and taker fee tx](https://github.com/bisq-network/proposals/issues/265)
- [Use a dedicated signature and encryption key for each offer instead of using the same global keys which is a privay issue.](https://github.com/chimp1984/bisq/tree/new-keypair-per-offer)
- Use EC keys instead of DSA/RSA keys as they are much smaller
- Use a new onion address for each offer (same as above reuse of onion leaks privacy)
- Use blinded data instead of account age witness in offer (privacy issue)
- Add proof of work for offers
- [Add proof or work for p2p network messages (dos protection)](https://github.com/bisq-network/proposals/issues/268)
- Add atomic swaps for BSQ/BTC (can be done without hardfork but would make dev life easier)
- Use new key for local reputation instead of onion address as root for reputation
- Fix some minor crypto issues 
- Change DAO state model

Some of those projects would be easier and some harder to implement in a backward compatible way. I am not arguing we should run for a hard fork, I just wanted to bring those ideas to attention and start a discussion about the pro and cons.

**Comment by RefundAgent** [comment]
These are important improvements. E. g. DDOS-attacks could kill Bisq and need to be prevented. Bisq is presently growing by about 5-10%/month by trades and any hard fork should be done early rather than late.

**Comment by ripcurlx** [comment]
I think those are all great ideas to improve Bisq, even if it requires a hard fork. But I think the bigger threat that is slowly approaching are the rising mining fees, that might make Bisq not feasible anymore for small trades. I do know that we ran into a dead end with the off-chain protocol, but I guess we have to put all our brainpower to alternative solutions sooner than later.
