### ISSUE TITLE
Calculate the BSQ price rate for compensation and reimbursement requests from Burning Man trades

### ISSUE THREAD

**Issue by wiz** [bisq-network/proposals#269]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Following the discussion on Keybase, someone has obviously manipulated the 30 day and 90 day BSQ market price averages very high by doing some weird outlier BSQ trades at 90K sats, 89K sats, 30K sats:

<img width="318" alt="Screen Shot 2020-10-24 at 14 08 33" src="https://user-images.githubusercontent.com/232186/97068426-6da1d480-1602-11eb-8115-9d8e78cf5648.png">

This has caused the 30 day average used for compensation to be much higher than the mid market price. Starting from Cycle 19, I propose that we start calculating our monthly BSQ compensation and reimbursement rates from the "average fill" price the Burning Man pays to buy BSQ from the market in the previous cycle. Recently I made another proposal https://github.com/bisq-network/proposals/issues/263 for the BM to start maintaining a Google Docs spreadsheet, so it could also be used for this purpose.

For example, the current 30 day average BSQ/BTC rate is 6239 sats, but you can tell this has been manipulated much higher than what the average price Burning Man actually buys BSQ at from the market, which is closer to 5600 sats, a difference of about 10%:

![97058195-0560dd80-1585-11eb-9e4a-0fb212314b57](https://user-images.githubusercontent.com/232186/97068813-f4a47c00-1605-11eb-9c0b-4a84549e45f5.png)

**Comment by chimp1984** [comment]
To use the market price (based on trade statistics which cannot be verified) for the BSQ/USD rate for compensation requests was a bad idea. We cannot fix that as a malicious actor could publish fake trade statistics in any manner which would be not detected if its done in a smart way (what we see here is at least not a covert manipulation). To use the offer price has the same problem. No guarantee that those offers are backed by real BTC and not just created for manipulation purpose.

The Burning man might be one solution but it adds more problems to the BM (requiring more trust) and we have plans to get rid of him.

What about another idea to use DAO voting to determine the BSQ/USD rate for the next cycle? It could be done via a generic proposal. The compensation maintainer could do that, to use the market rate which he sees realisitc (e.g. filter out such manipulation attempts) and suggest that rate. Theoretically there could be competing requests and the one which received the highest vote weight and support would be selected. But I guess its better to not over-use that and try to get consensus in Github before making the proposal.
The DAO stakeholders have incentive to keep BSQ rate fair. They do not want to dump or pump it as both would cause reputation damage and with that loss of the market value of BSQ.

**Comment by MwithM** [comment]
This manipulation also affects BSQ trading fee update, which uses the 30 day weighted average.
This method worked quite well. I don't like that the burningman if the burning man is the only one to determine what's the price of BSQ, but he already makes a big part of BSQ trading volume.
Still, Bisq needs to find a way to determine a way to estimate BSQ prices for the DAO to use that are as simple and automatic as the one we were using, but that doesn't count this manipulation attempts. Voting when the manipulation is so obvious might be a good idea. On the meantime, I could announce that the USD/BSQ rate for Cycle 19 won't be final until a week after the start of that cycle, to give time to determine the rate.

Let's consider this manipulation as a donation to the DAO. Even though it was not real trades, about 50USD (double if paid in BTC) in trading fees were spent.

**Comment by sqrrm** [comment]
I think rough consensus is a reasonable target, with DAO voting as the exception. The compensation maintainer suggests the BSQ price for next cycle a week before end of proposals. If there is no contention that number stays, otherwise it has to be taken to voting, much like what @chimp1984 is suggesting but without the vote if there is no disagreement beforehand.

In the end, the DAO participants are voting on compensation requests and if those requests use a BSQ value that is not considered right, then the CRs won't get approved.

**Comment by chimp1984** [comment]
> Let's consider this manipulation as a donation to the DAO. Even though it was not real trades, about 50USD (double if paid in BTC) in trading fees were spent.

Consider that the trade statistics are just p2p network data anyone could publish. You do not need to trade at all, not even self trade and not paying trade fees. It requires a bit of code manipulation to do that but not hard for a motivated and skilled attacker.

At the end the conversion rate is always a subjective value and determined by the party who provides the service. If a bank offers USD/EUR conversion they set the rate. It is based on market rates but they can adjust as they wish. If its too much off not clients will use it. In Bisq if our rate for comp. requests is off reality we will lose contributors or BSQ stakeholders/investors so they have the incentive to be as close as possible to the real rate. 
To make that more practical we can use the 30 and 90 days average excluding outliers and let the BM have a kind of veto in case the rate is off his experienced price. The 30 and 90 days can also be off in case the attack is more sophisticate (e.g. publishing lots of small trade statistics and slowly moving in one direction - that is hard to detect, only when you trade yourself you will discover if that price is the real market price or not.

We would need a proof of trade, but that is not compatible with privacy. The only exceptions are the BM as he need to be transparent anyway and is a trusted, bonded role. The other way is to trade yourself and knowing its not a self trade and not fake trade statistics finding out what the market is willing to pay for BSQ.

**Comment by chimp1984** [comment]
> I think rough consensus is a reasonable target, with DAO voting as the exception. The compensation maintainer suggests the BSQ price for next cycle a week before end of proposals. If there is no contention that number stays, otherwise it has to be taken to voting, much like what @chimp1984 is suggesting but without the vote if there is no disagreement beforehand.
> 
> In the end, the DAO participants are voting on compensation requests and if those requests use a BSQ value that is not considered right, then the CRs won't get approved.

I agree to 100% to avoid voting as long there is rough consensus. Lets start with that now to avoid that manipulation will have effect in the next cycle. 

Maybe its good to make this time a DAO proposal for requesting approval from the stakeholders to change the model to not use automatically the 30 days average price but to use the model described above.
I would make that GH and DAO proposal, if nobody has strong reasons against it.

Additionally to make a DAO proposal for defining the rate for the next cycle.
@MwithM Could you make a proposal for the BSQ rate you think is correct for the next cycle? 

As it is a change of a social consensus rule I think a DAO voting has more weight and finds better acceptance.

For upcoming cycles we only need rough consesnsu on the GH proposal and only if that is not clear we need to make a generic DAO proposal.

**Comment by pazza83** [comment]
Closing as superseded by #270
