### ISSUE TITLE
BSQ rates voting for cycle 19

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#271]
After detecting that BSQ averages calculated from price statistics are being manipulated with way overpriced trades, we have to determine what's the price via vote as proposed in #270 

30 Day BTC/BSQ: 0.00005600
30 Day USD/BSQ: 0.65
90 Day BTC/BSQ: 0.00005770
90 Day USD/BSQ: 0.67

5600 sats is the price Wiz estimated [here](https://github.com/bisq-network/proposals/issues/269#issue-728667491) for 30 Day Average and very close to the price of a recent trade I was involved into. This is how I estimate USD/BSQ price: I got 11.600USD as 30 day EMA from a trading app. 0.0000560*11600=0,649USD/BSQ.
90 Day averages are roughly estimated considering that on the Bisq DAO prices are lower for 90 than 30 days.

I'll wait for tomorrow 26Oct 13:00GMT to send this proposal for DAO voting. Data above is subject to change depending on your comments. I won't edit this post once the proposal has been submitted to DAO. You can send a proposal with different parameters to DAO voting and the one with more weight will be used.

----------
Edit: I changed prices for 90 day after [removing outliers](https://github.com/bisq-network/bisq/pull/4706). 30 day prices stay the same, I'm confident that prices for 30 day are ok. I'm sending this to DAO voting soon, no further edit of this proposal is expected.

**Comment by chimp1984** [comment]
I added some tools to make your life easier ;-)
Adjustable outlier removal: https://github.com/bisq-network/bisq/pull/4706  
Export trade statistics as csv: https://github.com/bisq-network/bisq/pull/4705

**Comment by MwithM** [comment]
First post edited, I raised prices for 90 day.

**Comment by MwithM** [comment]
I was waiting for prices to be included into the next block to be reduced. Now I worry if the proposal tx might not get to be voted for this cycle.
https://mempool.space/tx/f95eb74eea16db9cb8b77468f0170782caee7a20cfd82935637e9cdb5ad96268

**Comment by chimp1984** [comment]
All good, already confirmed....but better to not risk for last minute....

**Comment by MwithM** [comment]
Closed as approved.
