### ISSUE TITLE
Review GRIN listing on Bisq

### ISSUE THREAD

**Issue by klavinger** [bisq-network/proposals#272]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

As I understand it, the listing of GRIN token is haulted because trading it caused some confusion for some users. However, GRIN already uses a new standard way of sending coins: slatepack addresses. This eases the process and also unifies it.

I suggest that GRIN is allowed to be traded on Bisq once again. The sending/receiving process has been improved, users should be more familiar with the coin now.

I also suggest we add some simple UI for GRIN trading. For example, a simple pop up window telling people how is GRIN different to other cryptos and maybe refer them to GRIN documentation.

As GRIN focuses on privacy just as Bisq does, I think it could be very valuable. Look at how monero's doing.

**Comment by MwithM** [comment]
Hi, I suggest you to move this to [growth](https://github.com/bisq-network/growth/issues)
>_[Proposals](https://bisq.wiki/Proposals_) are a way to suggest significant project-wide changes or new initiatives where a broad consensus of contributors, users, and stakeholders is desired. Smaller changes to existing components, infrastructure, or processes are generally best discussed in other channels (on Keybase, other GitHub repositories, etc)._ 

Closing as invalid.
