### ISSUE TITLE
Integrate with OpenDEX for Bitcoin-to-Crypto Trading

### ISSUE THREAD

**Issue by kilrau** [bisq-network/proposals#277]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

@initCCG [brought up the idea](https://github.com/opendexnetwork/opendex/issues/23#issuecomment-716966084) to integrate trading on [OpenDEX](https://opendex.network/) within the bisq app. Feasible? Definitely. But admittedly not trivial and not a small feat. I am putting this out here as an early-stage proposal to get early feedback from the bisq community.

How I see it, there are several ways how to go about it:
1. Implement the [OpenDEX protocol](https://opendex.network/read/00-introduction) directly in the bisq java stack, package the minimum necessary swap clients into the bisq app: lnd(light) + connext(light)
2. Use an existing [OpenDEX implementation](https://opendex.network/trade/implementations), packaged within within the bisq app along with necessary lnd(light) + connext(light) swap clients
3. Merely provide bisq users with instructions how to externally set up an OpenDEX environment and allow connecting to & visual control+trading of such environment through the bisq app.

**Comment by klavinger** [comment]
I like the idea. Using atomic swaps would be an upgrade from today version of Bisq. This looks like a good idea for another iteration of Bisq, not just an incremental update.

**Comment by kilrau** [comment]
More comments, especially on the 3 options outlined are highly appreciated!

**Comment by LeadManPL** [comment]
3rd option will be too difficult for most users.

**Comment by pazza83** [comment]
Hi @kilrau thanks for the proposal. I am doing some housekeeping on the proposals. Please can you take steps to move this forward or alternatively close the proposal.

Many thanks.

Ref: https://bisq.wiki/Proposals

**Comment by pazza83** [comment]
Closing as stalled, looks like the idea of collecting user data is acceptable if it can stay anonymous.

@kilrau you might want to consider re-submitting the [proposal](https://bisq.wiki/Proposals#Create_GitHub_Issue) at a future date with more information, context and objectives.
