### ISSUE TITLE
Use Keybase to increase accessibility to Bisq for new traders with no funds for security deposit, trading and mining fees

### ISSUE THREAD

**Issue by pazza83** [bisq-network/proposals#283]
## Use Keybase to increase accessibility to Bisq for new new traders with no funds for security deposit, trading and mining fees

This is an idea for using Keybase to increase accessibility to Bisq for new traders that do no have any Bitcoin.

It would be great to get your feedback.

### Description

For new users of the platform Bisq requires approximately 0.007 BTC for traders to make their first trade. 

This is made up of:

- 0.006 BTC Security deposit
- 0.001 BTC Miner and Trade fees

New users of Bisq that have no Bitcoin often ask in Bisq channels how they can acquire their first Bitcoin to start trading. General responses are:

1. Find a friend
2. Find a Bitcoin ATM
3. Buy off an Exchange
4. Use Local Bitcoins
5. Use Paxful

For example recent Reddit posts: 

- [How to Obtain Your First Bitcoin](https://www.reddit.com/r/bisq/comments/jzad5e/how_to_obtain_your_first_bitcoin/)
- [ATM to Bisq?](https://www.reddit.com/r/bisq/comments/k6pnct/atm_to_bisq/)
- [I need help buying my first bitcoin on Bisq](https://www.reddit.com/r/bisq/comments/k3atzy/i_need_help_buying_my_first_bitcoin_on_bisq/)
- [How do I buy bitcoin if i have 0?](https://www.reddit.com/r/bisq/comments/kjmfen/how_do_i_buy_bitcoin_if_i_have_0/)
- Recent Keybase chat: 
![keybase](https://user-images.githubusercontent.com/66367547/100461581-e17f4300-30c0-11eb-9a00-8ab38e89960e.png)

For new users of the platform often choose to trade on Bisq due to Privacy, anonymity provided. Bisq offers a platform of no requirements for Know Your Customer (KYC)  or Anti Money Laundering (AML).

Most of the above options have the following issues

- Not private
- Not anonymous
- May require KYC
- Sends a user off to start their BTC journey on another platform

More and more countries have introduced regulation for Bitcoin ATMs to require users complete KYC. It is becoming increasingly difficult for people to purchase Bitcoin without KYC.

I have been thinking of an idea to keep new users within the Bisq ecosystem and enable them to quire their first  0.007 BTC with no security deposit needed.

### Idea

Bisq to set up a channel on the Bisq Keybase to facilitate new users to purchase 0.007 BTC from traders without security deposit. 

Eg: # buy-bitcoin

### Assumptions

The idea I have is predicated on the following assumptions:

- Keybase is an important resource for Bisq, therefore, Bisq should not do anything that would risk it's ability to use Keybase. I have checked Keybase's [acceptable use policy](https://keybase.io/docs/acceptable-use-policy) and this idea sits within it.
- BTC seller that want access to # buy-bitcoin would have to request access from the channel owner (I don't think this is the proper term for it). 
- Traders that wanted to sell could pay a fee eg 50 BSQ per annum to access this channel.
- Trader that wanted to sell could pay a BSQ bond to ensure they adhered to trade protocols eg 2,000 BSQ to access platform
- BTC buyer that want access to # buy-bitcoin would have to request access from the channel owner. No fees to pay.
- BTC buyer would **only be able to buy 0.007 BTC**
- BTC buyer would post on # buy-bitcoin what they are looking to buy. eg "I am looking to buy 0.007 BTC using Revolut using GBP is anyone online that can take the offer"
- BTC seller would then respond "hi, I can sell you 0.007 BTC on Revolut for 15%* over market. This would be £84, let me know if you would like to take the offer. I am here for the next 1 hour" *I am note sure if it would be of benefit for a fix amount to be charged. You do not want competition between traders. This is more about who is online at that moment to service the buyers needs. If fixed amount. I propose 15% this would be enough to cover trade deposit and mining fees, even during busy periods, and enough for the seller to make a small profit for the service they are providing.
- Trade can be taken to DMs and completed 
- The  # buy-bitcoin channel would be moderated. Any Traders can be removed at the discretion of the channel owner. If Trader is unhappy they can appeal to @Wiz, who I believe has the Keybase maintainer role
- No refunds, no mediation, no arbitration, buyer and seller beware
- No DAO compensation requests

### Benefits to new traders with no BTC

- Semi Private
- Semi Anonymous
- No KYC
- A quick and easy way to get their first BTC in a P2P manner
- Chance to get early access to the Bisq community
- Start their BTC journey getting familiar with Keybase. I think this is a big plus. I didn't access Keybase until I had a problem that needed support. It would be great if traders first experience of Keybase was a positive one. I would expect active Bidq users active on Keybase are more likely to continue to develop their relationship with Bisq as their go-to for BTC trades.

### Benefits to Bisq

- Increases accessibility to Bisq to much more people
- Increases engagement of new traders with established community at early stage
- Encourages community participation
- Keep new traders on Bisq platforms
- Potential revenue if access to # buy-bitcoin channel is charged for
- Happy buyers and sellers 

### Risks

- Only semi Private
- Only semi Anonymous
- Relies on trust and reputation of the traders. This is not what Bisq is built on.
- Reputation damage for Bisq if things go wrong
- No mediation if things go wrong for traders
- There is risk future trades may occur off Keybase. 

### How to mitigate the negatives

- Privacy and anonymity - Users are free to set up profiles in Keybase as they wish
- Trust and reputation of the seller can be gained from keybase links to social (Github, Twitter, Reddit etc). Whilst this is different from the Bisq client, trust and reputation makes communities stronger. 
- Trust and reputation of the buyers is less of an issue for sellers are choosing who to trade with and what payment methods to use. They are also charging a markup which will in have the risk of things going wrong built in
- Only payment methods used in Bisq would be allowed. Preference would be given to those with immediate payment; Revlolut, TransferWise, SEPA Instant, Zelle, Faster Payments etc
- Wiki, Keybase etc would make it clear the separate protocol that is required for these trades. Limiting reputation damage for Bisq. and reducing the probability of trades going wrong.
- Regular moderation would be needed to ensure spammers / scammers are removed.
- Policy set up for traders to adhere to to keep trades limited to the scope of the interactions that come from the # buy bitcoin channel. It would be easy to set up an 'mystery shopper' account to see if this was being adhered to. Traders violating the rules would be removed and risk the burning of their bond.

### My personal perspective

Bisq is as a platform that is an on / off ramp for fiat/ BTC in a P2P and decentralized way.

Successful platforms must find way to onboard new users and increase the accessibility to as many people as possible. 

New users today with no BTC are Bisq's future.

If I can help onboard a new user today that does not have BTC, help introduce them to the Bisq community and subsequently that user goes on to help contribute to, and add value to Bisq, I would be very happy. If that happened once in a thousand trades I would still be very happy.

> "I believe the children are our future
> Teach them well and let them lead the way"

**Comment by mpolavieja** [comment]
Hi @pazza83, please take a look at these comments about onboarding nocoiners. I am thinking on putting it together in a proposal if the idea is promising enough.

**Comment by pazza83** [comment]
> For onboarding users (buyers without BSQ bonding).
> if we want to try buyers without BSQ bonding for small quantities, maybe we could try something rather manual to get a feeling of how much demand there is for it. Only very experienced Bisq users would do this kind of sell offers (maybe initially a controlled group) and would coordinate with the buyer and require him some proof of ownership through the chat **before** disclosing their payment data to the buyer. We could pick up some old ideas such as a digital signature

This is what I had in mind for Keybase. Keep it Simple Stupid, KISS Principle. This would allow for a simple small trades to take place with minimum complexity.

I did not think past this initial step. First need to make sure there would be a market for small trades. I think there would be.  

> What I had in mind was a model where the buyer trusts the seller for small quantities. No deposits and no locked BTC.

It would be great to see your proposal for this. My idea for the moment is just to set something up quickly on Keybase to see if there is a market. If their is I think proposals likes yours and #268 are the next logical steps. 

### My Example of How a 0.007 BTC Trade would go on Keybase

Key: 👵 Seller   /    :princess: Buyer

---

:princess:  `I am looking to buy 0.007 BTC, I have Revolut`

👵 Hi, welcome to Bisq :) That is no problems I can do this for €90 if you send payment now. My Revolut ID is @pazza83 

:princess:  `Sent`

👵 Got it, DM me your Bisq BTC address. You can find it in 'Funds' under 'Fund your wallet'

(:princess: DMs Seller) `My BTC address is XXXXXXXXXXX`

(👵 DMs Buyer) Done should be with you in 10 mins here is the TX ID XXXXXXXXXXX

:princess:  `Thanks`

👵: No problems, happy trading :)

**End of trade**

---

**Trade time:** Less than 20 mins.
**POW:** The chat above!
**Security deposit:** Not required
**Trade amount:** Fixed at 0.007BTC
**Mediation required:** None

### What If's

- Trade goes well. Everyone is happy. Particularly Buyer who is has had a great first experience of the Bisq community.
- Buyer doesn't send payment, no problems seller doesn't send BTC. They are not bothered. This happens.
- Seller doesn't send BTC, Buyer calls out seller, Seller loses reputation and possibly bond 😞 This will likely never happen.

### Time require to implement this alternative trading protocol

One afternoon for v0.1. I can code this one myself 👍

**Comment by MwithM** [comment]
My main concern is that if Bisq will be considered a money transmitter. That concern and that I don't want to link so easily my avatar to my real name is what makes me think that that this initiative should be open for anyone through BSQ bonds. Not placing a deposit makes data mining free.

Sellers could be required to lock 0.05 BTC in BSQ at the DAO to get into Keybase channel. A seller could not take more than 1 order per day and messages should be destroyed every 48h. That way a seller won't be selling more BTC than bonded BSQ.
About dispute resolution, @bisq-network/mediators should do their usual work but out of Bisq just like they would do if chat doesn't work, to provide some proof for the DAO to vote.

**Comment by mpolavieja** [comment]
> First need to make sure there would be a market for small trades.

I like this because the question about not having BTC as a barrier to onboard Bisq has been the object of many discussions for ages in Bisq, and we don't have an answer.  I am not sure if Keybase would still be a barrier for the nocoiner.  But since it is available on mobile platforms my guess is that should not be a problem.

**Comment by pazza83** [comment]
Hi @MwithM thanks for all your feedback much appreciated.

> My main concern is that if Bisq will be considered a money transmitter.

Can you let me know more about this concern?

>I don't want to link so easily my avatar to my real name is what makes me think that that this initiative Should be open for anyone through BSQ bonds. 

Yes, I appreciate this concern. However you would be able to choose which trades to take and the instant payment options do not require full name just user ID and or email (which does not have to be an identifiable one). You could also if you wish set up a payment method for this sort of trading eg a Business Revolut account with the username AcmeCorp. 

>Not placing a deposit makes data mining free.

Yes, but it is free anyway if you are happy to swap fiat for BTC. Deposit would not be a barrier to anyone serious about data mining.


> Sellers could be required to lock 0.05 BTC in BSQ at the DAO to get into Keybase channel. A seller could not take more than 1 order per day and messages should be destroyed every 48h. That way a seller won't be selling more BTC than bonded BSQ.

I agree with the 0.05 BTC in BSQ. That seems reasonable. No need to limit orders. If there are a couple of buyers from Canada and only one person online with Interac e-Transfer let them trade. If seller's selling more than the BSQ amount was a problem then the BSQ amount should be lifted.

> About dispute resolution, @bisq-network/mediators should do their usual work but out of Bisq just like they would do if chat doesn't work, to provide some proof for the DAO to vote.

I disagree, these trades should occur outside of mediation. No trade fees are involved. They are for small amounts. The channel can be moderated. I think it should be kept simple. Less work for the DAO.

**Comment by pazza83** [comment]
> I like this because the question about not having BTC as a barrier to onboard Bisq has been the object of many discussions for ages in Bisq, and we don't have an answer. I am not sure if Keybase would still be a barrier for the nocoiner. But since it is available on mobile platforms my guess is that should not be a problem.

I think it would work. I see many new users asking how to get their first BTC in Bisq social channels. I get dismayed when they are sent off to other P2P providers.  New users are really important. Completing a first trade somewhere builds a sense of familiarity. A new user's second trade is likely to occur on the same platform their first trade did.

Last week I sold some BSQ to someone on Keybase that wanted to save trade fees on their first BTC trade. They did not have enough BTC for a BSQ security deposit  and a BTC security deposits. 

A new user wanting to use BSQ for their first tade (this should be encourages) Has to make 2 trades. Therefore, they require roughly 0.014 BTC just for the security deposits and trade fees. 

0.014 BTC (~$240 USD) is a lot for a new user. Especially when considered in relation the their trade amounts. In the case of the BSQ buyer above they wanted to buy 5.46 BSQ (min amount possible). This is only $3.65 worth. But it is also more than enough for multiple small buys of BTC to get them started.

I was keen to help them out and made a trade. Trade was a positive experience for everyone. Had a bit of a chat about Bisq, they were interested in asking a few questions about trades and payment methods. The new user now has BSQ, has experience using Keybase and will likely stay around longer than if I sent them of to Paxful to buy the 0.014 BTC for the BTC and BSQ trades. With money they may or may not have had.

**Comment by chimp1984** [comment]
Sorry to be late to the discussion, missed it when started...

I like the idea. Here are some comments:

- Does anyone has experience of similar OTC trade platforms on Telegram, Whatsapp,... Which kind of security do they provide. I guess its bases on reputation only...
- In case of a confiscation request for the DAO we could just leave the 2 parties present their evidence, that is more work for the DAO but it should be exceptional anyway (and if it happens it might be the end of that experiment anyway). So maybe its better to keep mediators completely out of the concept. I am not sure if one can deliver a (cryptographic) proof of the keybase chat messages, if so it would be easier, otherwise anyone could make up a screenshot...Mediators would have same dilemma... PagerSigner proof of fiat payment could be provided to some "trusted" community members as well if available...
- One barrier might be that a new user does not know really about the DAO and BSQ bonds. So they might be worried about the security as they have to pay first. Some easy to understand explaination will be required. 
- There should be clear limits of number of trades and total amounts per buyer. If that is violated by the seller it is a clear reason for confiscating the bond. In case it becomes polular users might prefer it over Bisq as it has no trade fee and less miner fee, BUT the security might be misleading and is weak. Buyers might not understand that sufficiently and long-cons (BSQ bond will not cover all if lots of trades are going on) would be a logical result long term it it becomes bigger.
- The project should be clearly "branded" as NOT-Bisq but a private initiative of community members using BSQ bonds for security. BSQ bonds could be used anyway for anything what Bisq is not aware of. In fact there are several bonded reputation bonds set up where nobody knows for what they have been used for. The DAO voters also have no obligation to vote on confiscation requests. 

Somehow its partially a low tech version of the off chain trade protocol idea ;-).

**Comment by chimp1984** [comment]
Actually, I think using "Proof of Burn" (PoB) is better here instead of BSQ bond. 
With burning a certain amount of BSQ the sellers are "buying" reputation and if that is repeated each months (like a access fee) their reputation builds up. Doing a long con scam would destroy all that accumulated reputation. The longer a seller has paid the fee the higher his potential loss is.
That would avoid completely the problematics with confiscating a BSQ and providing proof and revealing potentially private data in that process.

If the fee is fixed or can be self-defined is an open question. 
There need to be an easy way for the buyer to see how much BSQ (also in USD terms) the seller has already invested in their reputation. If a new seller wants to invest more to get more trades or start slowly can be left flexible. Maybe a min. access fee/month would be good, also to ensure that those sellers are maintaining the channel. At the end the fee is transferred via the price to the buyer, so for more security (higher reputation/higher accumulated BSQ fee paid) a higher price is justified. Buyers taking an offer from a seller with min. reputation run a higher risk. That simple model need to be communicated well. I think it is also much easier to understand for those who have no idea about the DAO. 

The main problem might be that initially the security would be weak as seller likely do not want to burn 100s or 1000s of BSQ.
So a burned BSQ would not cover even a single trade. After a while that might be mitigated. E.g. if fee is 50 BSQ each months, in 6 months its 300 BSQ so should cover at least 1 trade. Still not very strong but maybe acceptable.

@chimp1984 What do you think about that idea? What do you think a seller would be willing to burn initially to get started?
Maybe that model is too expensive for the seller to work ;-( ? Maybe we should combine bond and PoB, where the bond can be revoked once the PoB amount is sufficiently high? So bond is for bootstrapping and PoB is for long term? But making the simple model more complicated...

**Comment by MwithM** [comment]
> The main problem might be that initially the security would be weak as seller likely do not want to burn 100s or 1000s of BSQ.
So a burned BSQ would not cover even a single trade. After a while that might be mitigated. E.g. if fee is 50 BSQ each months, in 6 months its 300 BSQ so should cover at least 1 trade. Still not very strong but maybe acceptable.

In this model, the BSQ to protect buyers are burned when there is no use for them anymore, after 6 months of repeated trades without issues. If you're going to scam Bisq buyers and the DAO, specially when limits for number and volume of trades are applied, you're going to do it as soon as possible.
A mixed model where bond is lower and volume can grow after a few months burning BSQ feels more secure, but is more complex. A fixed amount of locked BSQ that covers trading volume all the time is good enough IMO.

**Comment by Conza88** [comment]
Definitely agree need to guide period to Bisq community upon entry etc. Or via program. Make it far easier. I also joined months after I had a problem.

**Comment by pazza83** [comment]
> * Does anyone has experience of similar OTC trade platforms on Telegram, Whatsapp,... Which kind of security do they provide. I guess its bases on reputation only...

I have no experience other than completing 2 trades already using Keybase. One for a small amount of BTC a trader needed to make a trade, the other for someone that wanted to buy the min amount of BSQ and did not have a security deposit. In both cases the buyers sent me the funds first prior to me releasing the BTC and BSQ.

I have seen people sell on Reddit and BitcoinTalk and they use a reputation system. The Keybase channel moderator would be free to remove any users they see fit.

> * In case of a confiscation request for the DAO we could just leave the 2 parties present their evidence, that is more work for the DAO but it should be exceptional anyway (and if it happens it might be the end of that experiment anyway). So maybe its better to keep mediators completely out of the concept. I am not sure if one can deliver a (cryptographic) proof of the keybase chat messages, if so it would be easier, otherwise anyone could make up a screenshot...Mediators would have same dilemma... PagerSigner proof of fiat payment could be provided to some "trusted" community members as well if available...

I do not think the DAO needs to be involved, no mediators, no arbitration. It is a P2P transaction not going through Bisq no trade fees are involved. Traders are not paying for Bisq services. They are simply gaining the required security deposit / miner and trade fees to trade on Bisq. 

If trade goes wrong. Either user is free to share concerns on Keybase channel.
 
> * One barrier might be that a new user does not know really about the DAO and BSQ bonds. So they might be worried about the security as they have to pay first. Some easy to understand explaination will be required.

I do not think new users would need BSQ bonds. Only sellers of BTC would need them, if this was deemed appropriate.

The risk is mainly shouldered by the Buyer as they will be sending the funds first. The Seller's are not really shouldering any risk other than to their reputation. They only send the BTC once they have been paid.

> * There should be clear limits of number of trades and total amounts per buyer. If that is violated by the seller it is a clear reason for confiscating the bond. In case it becomes polular users might prefer it over Bisq as it has no trade fee and less miner fee, BUT the security might be misleading and is weak. Buyers might not understand that sufficiently and long-cons (BSQ bond will not cover all if lots of trades are going on) would be a logical result long term it it becomes bigger.

I agree transaction limit should be 0.007, just enough to start trading on Bisq. Ideally buyers will only use the service once. Get their no KYC BTC and then start accumulating / trading on Bisq. 

If it became popular the DAO could charge the Seller's an annual fee to be a member of the Keybase channel designated for this. 

Buyers should be aware that they risk losing their funds if trading this way. They are relying on the reputation of the seller.

> * The project should be clearly "branded" as NOT-Bisq but a private initiative of community members using BSQ bonds for security. BSQ bonds could be used anyway for anything what Bisq is not aware of. In fact there are several bonded reputation bonds set up where nobody knows for what they have been used for. The DAO voters also have no obligation to vote on confiscation requests.

Agreed. 
 
> Somehow its partially a low tech version of the off chain trade protocol idea ;-).

I think the simpler it is kept the better.

**Comment by Conza88** [comment]
I'm generally against limits, minimums or caps. Unintended consequences result. Also that amount if set in stone, years or months down the track could become prohibitive still.

Folks aren't dumb. Putting through massive first buy e.g. several thousand ain't going to happen Vs doing what they can in small amounts. And if someone wants to do that, fine, just be clear we risks and purpose of channel etc. Warnings I guess
________________________________

**Comment by pazza83** [comment]
> Actually, I think using "Proof of Burn" (PoB) is better here instead of BSQ bond.

Why not both.

Bonded for security for the buyers.

Proof of burn for revenue for Bisq. I would make it annual rather than monthly to save on transaction fees and save time / administration resources.

> With burning a certain amount of BSQ the sellers are "buying" reputation and if that is repeated each months (like a access fee) their reputation builds up. Doing a long con scam would destroy all that accumulated reputation. The longer a seller has paid the fee the higher his potential loss is.

I see it more like burning BSQ is paying Bisq DAO to access a service. 

Sellers would/should be making enough in trades each month to cover these costs so I do not see it as increasing reputation. 

> There need to be an easy way for the buyer to see how much BSQ (also in USD terms) the seller has already invested in their reputation. If a new seller wants to invest more to get more trades or start slowly can be left flexible. Maybe a min. access fee/month would be good, also to ensure that those sellers are maintaining the channel. At the end the fee is transferred via the price to the buyer, so for more security (higher reputation/higher accumulated BSQ fee paid) a higher price is justified. Buyers taking an offer from a seller with min. reputation run a higher risk. That simple model need to be communicated well. I think it is also much easier to understand for those who have no idea about the DAO.

I disagree with this for the reasons above.  

Buyer will see @chimp1984 is happy to sell be 0.007 BTC for 200 Euros. His Keybase proofs look good. I can see he contributes regularly to Bisq. I am happy that he wont risk his reputation for 200 Euros.

They may also be aware that @chimp1984 has put up a bond in BSQ to access this channel.

The channel moderator will control which sellers are able to access the platform. So if a new trader comes along and wants to join they will need to build up their reputation first. This would be through linking Keybase proofs, getting involved in discussions etc. This is the same way it would work on a forum like BitcoinTalk or Reddit. 

> The main problem might be that initially the security would be weak as seller likely do not want to burn 100s or 1000s of BSQ.

I think don't worry about the burning initially. It can be determined when / if the channel becomes popular. The goal here is not to make the Keybase channel profitable it is to get the users that are being recommended to go to: HodlHodl, Local Bitcoins, Bitcoin ATMs etc to engage with the Bisq community on Keybase and then become lifelong Bisqers. 

I made the proposal as I get frustrated every time I see people ask on Bisq Reddit, forums etc how to get their first BTC and they get sent to another place. Once they use that place to buy the likelihood is they will to buy from there again. It is the equivalent to turning willing would be customers away at the door. 😠
 
> @pazza83 What do you think about that idea? What do you think a seller would be willing to burn initially to get started?
> Maybe that model is too expensive for the seller to work ;-( ? Maybe we should combine bond and PoB, where the bond can be revoked once the PoB amount is sufficiently high? So bond is for bootstrapping and PoB is for long term? But making the simple model more complicated...

I think a one time BSQ bond would work.

See how things develop. If it becomes popular and sellers are doing regular trades then introduce a annual BSQ burn fee.

**Comment by pazza83** [comment]
>A mixed model where bond is lower and trading volume can be increased after a few months burning BSQ feels more secure, but is more complex. A fixed amount of locked BSQ that covers trading volume all the time is good enough IMO.

I agree with @MwithM  I think bond to start with and then annual fee is it gets popular (sellers are making regular trades).

**Comment by pazza83** [comment]
> Definitely agree need to guide period to Bisq community upon entry etc. Or via program. Make it far easier. I also joined months after I had a problem.

I agree this is my primary motivation. I am the same. It was 3 months before I discovered Bisq's Keybase / Github. If you are using the Bisq client and everything is working as it should be you do not need to use Keybase or Github. 

New users first experience of Bisq's Keybase / Github should not be when they have a problem. They should be encouraged to join in the community. [Promote Keybase as a support channel within Bisq GUI #4904](https://github.com/bisq-network/bisq/issues/4904)

**Comment by pazza83** [comment]
> Folks aren't dumb. Putting through massive first buy e.g. several thousand ain't going to happen Vs doing what they can in small amounts. And if someone wants to do that, fine, just be clear we risks and purpose of channel etc. Warnings I guess.

I think some people are too trusting. The biggest risk I see is that someone comes along and makes a small trade. All goes well. then they send a private message asking to do another trader. Before you know if they are doing trades for 5 BTC via Keybase based on trust alone.

If this were to happen it would get messy!!!

That is why my proposal included the following to reduce this happening:

- Policy set up for traders to adhere to to keep trades limited to the scope of the interactions that come from the # buy bitcoin channel. It would be easy to set up an 'mystery shopper' account to see if this was being adhered to. Traders violating the rules would be removed and risk the burning of their bond.

It would be easy to set up an account as a new user and see what traders were following protocol. Any that were not would risk losing bond.

**Comment by Conza88** [comment]
Fair point about escalating to 5 BTC etc.
Key would be providing guidance, warnings etc. Best practices. Also a possible test of traders, sure.
Auto message after transaction maybe, removing from intro trade channel?

Checking in to see who is in there, if they've been onboarded? Guided to normal channels etc afterwards
________________________________

**Comment by chimp1984** [comment]
@pazza83 Yes agree to all you posted. Lets get it started and adjust once needed.

**Comment by pazza83** [comment]
Great I will ask @wiz about creating a keybase channel.

Any thoughts on what the bond should be for traders?

I suggested 2,000 above this would cover a 0.007 trade about 6 times over.

**Comment by pazza83** [comment]
Using Keybase to increase accessibility to Bisq for new traders to buy 0.007 BTC for their first trade has been live for almost a couple of months.

For more info see the [Keybase Buy Bitcoin wiki](https://bisq.wiki/Keybase-Buy_Bitcoin)

Still to do are:

- Complete Wiki
- Post pinned message to buy-bitcoin KeyBase channel
- Come up with a way to make trusted sellers (BSQ Bond/Burn)
- Come up with a way for buy-bitcoin KeyBase channel to be revenue producing for Bisq
- Consider how / if BSQ can or should be sold in a similar way #308 
- Promote channel on more user touchpoints; social media, wiki payments methods page, Bisq software etc

The mempool has been high recently which has resulted in less small offers being made / taken on Bisq. This could be a good way to experiment to see how Bisq can make small trades accessible to more users.

**Comment by pazza83** [comment]
The current minimum required security deposit is currently 0.006 BTC (~$360). 

The new minimum security deposit will be reduced to 0.001 BTC (~$60) in next release:
[Reduce minimum required security deposit #323](https://github.com/bisq-network/proposals/issues/323
)

It will therefore, make sense to transition the buy-bitcoin channel for maximum offers of 0.002 BTC (~$120).

I will leave it running as 0.007 BTC (~$420) for the moment as still some 0.07 BTC as there will still be some old offers available for users.

But expect an update to  0.002 BTC (~$120) as a limit soon.

**Comment by pazza83** [comment]
Going to re-assess the 0.002 BTC limit as some sellers of 0.01 BTC or less are choosing to use a deposit over 15%. Will re-assess at the end of this month.

**Comment by pazza83** [comment]
I made a couple of graphics that can be used to promote the buy-bitcoin channel on Twitter and other social media platforms:

![Starter pack - 3](https://user-images.githubusercontent.com/66367547/113442927-dfb7ea00-93e8-11eb-9ce1-564df9e34034.png)

![Starter pack - 4](https://user-images.githubusercontent.com/66367547/113442937-e5153480-93e8-11eb-9797-103ab329e729.png)

**Comment by pazza83** [comment]
Re-assessing the limits for sellers in the Keybase channel.

Looking at Bisq most offers of 0.01 BTC or less are choosing to use a deposit well over 15%.

I think it makes sense to keep the limit for sellers to 0.007 BTC for the moment. 

The [wiki](https://bisq.wiki/Informal_Market_for_Small_BTC_Trades) was updated to 0.002 BTC if anyone has any objections to me updating it back to 0.007 BTC let me know

**Comment by pazza83** [comment]
Closing as was approved. I will create a project for the works still to do.
