### ISSUE TITLE
Change donation address

### ISSUE THREAD

**Issue by burningman3** [bisq-network/proposals#285]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

## New donation address
I have setup a new donation address as explained in https://github.com/bisq-network/roles/issues/80#issuecomment-734507761

**34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC**

**Comment by MwithM** [comment]
I'm glad to know that fee and donation addresses are going to be split, I don't think this proposal will be controversial.
I thought this change was already implemented and changed this role's wiki page: https://bisq.wiki/Donation_Address_Owner#Rights
If the change is already implemented, which I'm still not sure, I'll leave this open for about 5 days as a news board.

**Comment by burningman3** [comment]
Tx ID: fbb556d1914c1c2a63ae912ed418b1df511202adc8bd6404b5097e478214055a

**Comment by burningman3** [comment]
Accepted in DAO voting.
