### ISSUE TITLE
Refund agent buys BTC from burningman with 30 day average

### ISSUE THREAD

**Issue by refund-agent2** [bisq-network/proposals#294]
Refund agent should buy BTC from burningman using 30 day average price at trade events. This is what traders do and it's less volatile than best BSQ sell offer.

**Comment by pazza83** [comment]
@refund-agent2 would this be at the same rate as the calculated 30 day rate for each cycle as per the proposal https://github.com/bisq-network/proposals/issues/270 ?

**Comment by refund-agent2** [comment]
Use a price set at Cycle beginning would expose me to volatility. I don't want that.
Traders use the price at the time they do their reimbursement proposals. I will use the average price at sunday or saturday.

**Comment by pazza83** [comment]
The average price can be manipulated in either direction. That was the the reason for the proposal above.

I agree with the sentiment. Selling BSQ a/ Buying BTC at the best offer price exposes the refund agent to the BTC/BSQ spread which can be pretty large.

Maybe a mid market price could be used. This would be less easy to manipulate (at least over any significant period).

**Comment by pazza83** [comment]
Hi @refund-agent2 I am doing some housekeeping on the proposals. Please can you take steps to move this forward or alternatively close the proposal.

Also not sure if you are already doing as proposed?

Many thanks.

Ref: https://bisq.wiki/Proposals

**Comment by pazza83** [comment]
Hi @refund-agent2 just following this up are you already doing as proposed?

**Comment by refund-agent2** [comment]
Yes. I reserve my right to sell at market if prices are higher though. I think I've been losing money performing this role.

**Comment by pazza83** [comment]
Closing as approved as this is in practice and there have been no views to the contrary
