### ISSUE TITLE
Refund agent to partially reimburse high volume trades

### ISSUE THREAD

**Issue by refund-agent2** [bisq-network/proposals#296]
Trader asks for this at [trade reimbursement case](https://github.com/bisq-network/support/issues/752):
> I am aware that the refund agent can't reimburse over 0.5BTC to me. I am asking about the possibility that I be **partially reimbursed with the 0.5BTC first and receive the remaining** 2.1BTC from the DAO. Since I am the victim here that my funds are locked out until the next DAO cycle, I would like to at least claim some of my funds first as an assurance.

I agree with it, but with some considerations:
- 2 trades per cycle max.
- If the arbitration ticket was closed close to the end of the cycle, DAO should reimburse the full amount.

Pros:
- High volume traders will get a part of the reimbursement faster and in BTC.
- Gives RA have skin in the game.

Cons:
- Adds some complexity to the DAO reimbursement process.

**Comment by pazza83** [comment]
Is there a GitHub issue you can point me to that where the 0.5 BTC limit was introduced?

**Comment by sqrrm** [comment]
I think the 0.5 BTC limit is just what @refundagent chose to limit direct refunds to after taking too much risk with a larger refund. The refunds done by refund agents are out of pocket and a personal risk they take so it's really up to them how much to refund.

The initial discussion, before the 2of2 protocol, around refunds by agents vs going to the DAO included thoughts of the refund agents (or anyone, not as a dedicated role) buying the claims at a discount for traders to get their refund as soon as possible and then having the refund agents claiming these cases to the DAO. I think the BSQ market is still not liquid enough for that to work, and users seem to get upset when they miss out on the counterparty's deposit.

**Comment by pazza83** [comment]
Hi @refund-agent2 I am doing some housekeeping on the proposals. Please can you take steps to move this forward or alternatively close the proposal.

Many thanks.

Ref: https://bisq.wiki/Proposals

**Comment by pazza83** [comment]
Hi @refund-agent2 just following this up.

Please can you move this proposal forward or close it. 

Also I was under the impression that partial reimbursements have started is this the case?

**Comment by pazza83** [comment]
Hi @refund-agent2 just following this up. Are you currently partially reimbursing traders?

**Comment by refund-agent2** [comment]
Yes, I think it was only needed once, for trade NVLSXv in Cycle 24.

**Comment by pazza83** [comment]
Closing as approved as this is now in practice and there have been no views to the contrary
