### ISSUE TITLE
Reduce delayed payout timelocks to 5 and 12 days

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#297]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I propose to reduce the timelock to 5 days for altcoins (for which higher trading window is one day) and 12 days for fiat (which higher trading windows are 8 days for USPMO and 6 days for SEPA)
Currently, when mediation is not working because of unresponsive peers, a bug or any other reason, traders have to wait for 10 or 20 days (alts or fiat) to start arbitration.
I don't think that waiting this long improves security but it creates inconveniences to honest traders.
Opening arbitration just after the timelock is triggered is not mandatory and arbitration should come with a [cost](https://github.com/bisq-network/proposals/issues/292) except for bugs, so traders must not abuse it. They can ask for a new mediation suggestion or generate their own payout (not an easy option) as long as they haven't started arbitration.
Even for long trading window payment methods, traders don't usually open mediation tickets at 8 or 6 days since start of the trade but much earlier, as soon as they see something strange. Thus, there would be time enough for mediators to suggest a payout. I thought that since there's the  trading chat, those 12 days could be even reduced to something like 8 or 10 days, but I wanted to be conservative because mediation for fiat is more difficult.
Personally, I haven't used USPMO. It looks like a slow payment method and exceeding 12 days for a trade could happen sometimes, but I've never had a valid reason to wait for more than 4 days for a SEPA transfer.

**Comment by sqrrm** [comment]
This sounds reasonable to me, but it would be good to get the input from mediators and arbitrators as they would have the best data on this.

An issue with changing the timelock delay is that it's a hard fork in the trade protocol. Since it's not an urgent change it could be introduced with an activation date, but it might still cause trouble if some users are on old clients. It wouldn't invalidate orders so that's not a problem, just the take offer process would fail.

**Comment by chimp1984** [comment]
There is a DAO param LOCK_TIME_TRADE_PAYOUT which is not used atm. The maker defines the lockTime and the taker checks that the lockTime they would calculate is not further than 3 blocks different (needed for considering chain forks).
So changing that would require some future activation time and some adjustments to ensure trades will not fail.

**Comment by pazza83** [comment]
Hi @MwithM  I am doing some housekeeping on the proposals. Please can you take steps to move this forward or alternatively close the proposal.

Many thanks.

Ref: https://bisq.wiki/Proposals

**Comment by MwithM** [comment]
I think that closing it as stalled makes sense.

**Comment by MwithM** [comment]
Reopening this stalled proposal as there have been changes in the trading protocol:
For security reasons, one security deposit is [not paid to traders](https://github.com/bisq-network/proposals/issues/386) in case of arbitration. This makes waiting until the timelocked tx can be triggered much worse for traders, as the winning part of an arbitration case receives no compensation.

I don't know if the risk of having a rogue burningman is increased after distributing the role, but I still don't think that reducing the waiting period to have the option to trigger a delayed payout transaction increases the potential damage to the DAO.

**Comment by pazza83** [comment]
Closing as stalled again due to lack of activity

**Comment by pazza83** [comment]
New related discussion for Bisq 2 MuSig https://github.com/bisq-network/bisq2/discussions/3582
