### ISSUE TITLE
Allow seller to determine the Trade ID that goes in the "Reason for Payment" field.

### ISSUE THREAD

**Issue by davterra** [bisq-network/proposals#299]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I understand the concern about putting info in the "Reason for Payment" field that might divulge the real reason for payment, buying bitcoin. It appears that currently, the Trade ID that is to be put into that field is generated automatically and for a given payment method, appears similar in format from one trade to another. 

I am concerned that payment vendors may catch on and flag future transactions that have a "Reason for Payment" that matches the current format.

Proposal:
Allow the seller to stipulate the info that goes into the "Reason for Payment" field when constructing the offer.
This would still allow for easy identification while ideally appearing more like a "legitimate" transaction to the payment vendor.
I think if I, as a seller, requested that a buyer put "purchase of bicycle" or some such thing into the Reason for Payment field it would achieve the desired purpose while making the real reason better hidden from the payment vendor.

**Comment by chimp1984** [comment]
With next release traders must leave the reason for payment field empty.
See https://github.com/bisq-network/bisq/pull/5080

Using a wrong reason might be problematic and some users strongly disagree that they should lie about it and it might have at least risks that banks close the account if it was obviously a lie. So best we can do is to not use anything.

**Comment by RififiCastorjunior** [comment]
This subject is already propose with same goal ?

**Comment by davterra** [comment]
Great! Thanks!
