### ISSUE TITLE
Increase DAO issuance limit per cycle from 300k to 400k

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#302]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

As protection mechanism there is a issuance limit per cycle. If that would be exceeded the cycle would fail and nothing would be issued. This is 300 000 BSQ at the moment. We are a bit over that limit in that cycle as it included the previous cycles requests. In case there are many reimbursement requests we also could exceed that, so I think it is justified to increase that to 400 000 BSQ. Also the DAO has matured and is running nearly 2 years without any serious issue so we can be a bit more confident.

**Comment by Conza88** [comment]
Forgive the ignorance, reimbursement - related to dev work etc? 
And other bounties?

**Comment by chimp1984** [comment]
Reimbursement is for trades ended up in arbitration. Issuance can be either compensation requests or reimbursement requests.

**Comment by chimp1984** [comment]
Proposal is made: Tx ID cd003c1d5cdb5f301b1b32f323003270a9111b1ec4d5abd0ddc2f101b1b811a1
