### ISSUE TITLE
Listing

### ISSUE THREAD

**Issue by yacrazyone** [bisq-network/proposals#309]
I believe Defichain (DFI) will be worth listing.

Leverages on Bitcoin, adds monetary functionality to the base money that is Bitcoin.

Trading, stocks and uncollateralized lending. Forked from the Bitcoin code, anchors the merkle tree in the Bitcoin chain. Own, fast chain. Non touring complete. Efficient - no games, art, casinos as on Eth, just DeFi. Interoperable. Wrapping of Bitcoin allows to send Bitcoin faster, cheaper, without centralized honeypots such as PayPal that regulators could attack.

https://bitcointalk.org/index.php?topic=5294852.0

**Comment by MwithM** [comment]
https://github.com/bisq-network/proposals/issues/166

Closed as invalid.

**Comment by yacrazyone** [comment]
Please elaborate, I do not get why is is categorized as invalid

**Comment by MwithM** [comment]
Adding new assets is on hold, so DFI won't be listed.
This repository is to propose significant changes to Bisq. Even if the hold on new assets was removed, the place to suggest adding a new asset would probably be the Growth repository.
https://bisq.wiki/Proposals

**Comment by yacrazyone** [comment]
Hm. Thanks for the explanation MwithM, I'll be submitting a second proposal in the Growth repository in 2022.

Bisq is great. I believe after the current bull run, a selection of DLTs that add to the bitcoin network and help the cypherpunk vision to become reality should be considered for integration.
