### ISSUE TITLE
Make Mediators anonymous

### ISSUE THREAD

**Issue by pazza83** [bisq-network/proposals#310]
## Problem

Mediation is a very important part of Bisq. Currently the @bisq-network/mediators in Bisq are linked to their Keybase identities, and as such other identities such as; GitHub, Twitter, Reddit, personal websites etc. This means traders know who their mediator is.

It is easy to find your mediator both in the Bisq app and on the wiki: https://bisq.wiki/Finding_your_mediator

The problems with this are:

- Mediators can expose their real life identities (might have implications for disgruntled traders or future legal recriminations)
- Knowing the identity of the mediator feels to me like it introduces an impartiality that does not need to be present
- Potential conflicts of interest for traders / mediators
- Potential problems for Bisq if mediators become subject to legal challenges.
 
## Outcome

Mediators should be anonymous.

This would introduce more neutrality in the mediation process. It would also protect mediators from any issues from being linked to their real life identities. It would also avoid any conflicts of interest.

## Solution

Mediators to be given usernames in Keybase and GitHub such as

- Mediator1
- Mediator2
- Mediator3

Usernames would only be used for Keybase and GitHub.

No identifying information would be given.

Compensation requests for Mediation would be made by the associated GitHub profile using a separate BSQ wallet address than other compensation requests. 

Maybe the identities of the Mediators should only be known by the @bisq-network/fee-reimbursement-agents 

The refund agents could also be responsible for the recruitment of future mediators. Therefore, their identities would be known by very few people.

**Comment by Conza88** [comment]
Wasn't there just a proposal to make their usernames known?

This is likely because people were asking, given they still had questions or it wasn't clear, or resolved effectively?

If the communication and improved levels of quality for mediation existed there'd be less need for anyone to care who they are?

Anonymity would if anything provide less responsibility to provide a good experience, all else being equal. 

I don't have issue with that ONCE everything else has been set in place e.g. improvements to trade communication in chat, chat notifications with mediators etc etc.

**Comment by pazza83** [comment]
Yes, I thought it would be better to include their names rather than just onion addresses. But ideally I do not think their names should be anonymous Keybase / GitHub accounts.

People would still be able to ask the mediator questions on Keybase and Github, they just would not know the identity of the person behind the account.

**Comment by Conza88** [comment]
Right. I think keep it stating who the moderator is etc. but that is a keybase name / or generic "Mediator1" etc. 

I do think they should be unique i.e. if mediator 1 retires, then replacement becomes the next number that does not exist e.g. "mediator10". Otherwise, would increase confusion etc.

**Comment by huey735** [comment]
>Anonymity would if anything provide less responsibility to provide a good experience, all else being equal.

I'm prone to agree with that sentiment but I haven't given it much thought.

 I overall agree with a more pseudo-anonymous approach for these roles anyway. And I see the role of the Mediator possibly reducing in importance down to almost a Support Agent level. With a more developed payout tool, the traders could by themselves decide on the best way to move forward. The only difference would be that the Mediator would have access to trader's sensitive info in order to help mediate tickets.

**Comment by MwithM** [comment]
I sometimes do collect sensitive info, although provided through Keybase and not Bisq client itself.

**Comment by pazza83** [comment]
> > Anonymity would if anything provide less responsibility to provide a good experience, all else being equal.
> 
> I'm prone to agree with that sentiment but I haven't given it much thought.

I do not think anonymity provides less responsibility in this instance. It is not a truly anonymous role, it just breaks the link between their real life identities. Mediators would still be held accountable by their bond, and mediator Keybase profiles, GitHub profils, role reports and compensation requests.

I do not think the burningman or refundagent are any less responsible due to the anonymity they have.

**Comment by chimp1984** [comment]
Handling anonymity right comes with quite some effort, opsec challenges and one need to be very cautious to not make mistakes specially if multiple identities are used. It is already possible to anyone to do that, but the effort should be taken seriousy. It also comes with limitation like not being able to communicate by voice chats. And without proper opsec and experience its just anonymity to Bisq community but not the deep state (to be anonymous againt those is quite challenging I think and a single mistake can destroy all the effort). I think its good that Bisq has mixed contributor community of anonymouse, pseudonymous and real life ID people.

**Comment by pazza83** [comment]
Ok, fair point. I can see that it would be a bit of an extra step and they may be happy with the current setup.

Maybe,  just leave it up to the mediators to decide if they would like to have separate GitHub / Keybase's for their mediation roles.
