### ISSUE TITLE
Use 30 day average BSQ/USD rate for compensation requests

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#313]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I propose to start using the **30 day volume weighted average at Cycle 24**, instead of the 90 day that we were using until now. The reason is to reduce the volatility contributors and DAO assumed with the 90 day average, and make it more similar to the rate reimbursements use.
I find this proposal has been already discussed in the [Cycle 22 rate](https://github.com/bisq-network/compensation/issues/782) issue and this is the conclusion of the discussion. If there is no opposition to it, it will be approved without DAO voting needed.

**Comment by pazza83** [comment]
Closing as approved
