### ISSUE TITLE
@Castorj to assume L1 support agent role

### ISSUE THREAD

**Issue by RififiCastorjunior** [bisq-network/proposals#315]
**Proposal**

Application to become a support agent for cycle 23, following internship cycle 22

**Motivation**

I have been trading on Bisq since August 2020, my trades have gone smoothly but I had 2 trades go to mediation. That moment was a bit stressful because those trades happen in night time CET, in week end. And no support available at the time.

I really want to see Bisq shine specially when those fees will get even cheaper to introduce to new traders.

**Compensation**
I Can complete 21 hours a week like in the internship support role. I also could add 7 more hours. Those are the hours i been doing during my internship.

My compensation for this role will be as suggested in the the Wiki, I think it is $1050 per cycle. If that a bit too munch i could stick to those 10 hours ($500 per cycle).

**Comment by MwithM** [comment]
Closed as approved. Welcome.
