### ISSUE TITLE
Distribute trade fee in BTC by using proof of burn

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#317]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Alternatively to #316 we could use the proof of burn feature to reduce the role of the burningman to distribute the BTC fee back to the DAO.
That way we delegate the role of the burningman to receive BTC, buy BSQ and burn BSQ to the BSQ stakeholders. They can burn their BSQ themself and receive BTC fee payments in return.

Any BSQ stakeholder can burn an arbitrary amount of BSQ and add a second BTC change address which defines the receiver address for trade fees in BTC.
Traders collect all proof of burn transactions and select probalistically the receiver. 

This simple version would not have any mechanism for a "conversion rate" so the burned BSQ could be over or under paid depending on the competition of how much BSQ get burned in total to the BTC fee volume. 
There could be a decay algorithm built in so that old POB txs get lower probability.

To model a more exact pricing seems to be problematic.
It might be difficult to find the right equilibrium and "burners" would need to figure out with how much burned BSQ they compete when adding more burned BSQ as well as the expected BTC fees. All that comes with high mental costs and will be likely a factor that it might not work out well.

**Comment by sqrrm** [comment]
I see a big challenge in the high mining fees going forward and I think that needs to be dealt with first. The idea of using bonds to distribute fees doesn't sound all that bad, but I think it won't be helpful by just switching the current scheme to directing fees to contributors directly.

One way to reduce output bloat would be to merge fees from buyer and seller to one output if we can get the single tx protocol working.

Another thought is that if party A in a trade is paying the fee by burning BSQ, then B could pay a bit more BTC to A as part of the trade and A would burn that extra BSQ to pay the fees. This would be beneficial to A as the value of BTC received would be larger than the extra value of BSQ burnt as long as we keep the BTC/BSQ fee ratio at 2.

I think that would be a quite common scenario that a frequent trader that has BSQ is trading with a new trader. A benefits by gaining some extra BTC for the BSQ burnt, A and B benefits by the smaller tx size and the DAO benefits by not having to deal with more BTC fee bloat.

**Comment by chimp1984** [comment]
Yes, I agree that the bigger problem is the high miner fee. The 1 tx trade protocol is so far the most promising suggestion to deal with it but it is a big effort.

This proposal would help a bit as the burningman need to consolidate the many small utxos and trade at some predictable periods (at least once a month). If BSQ stakeholders receive those this pressure is gone and they can wait as long they wish until minfer fee is really low to consolidate those utxos together. So in all we do not lose that much to miners as it is the case currently.

**Comment by chimp1984** [comment]
> The idea of using bonds to distribute fees

You refer probably to #316.

**Comment by sqrrm** [comment]
I meant burning rather than bonds, but the effect on distributing the fees is the same.

I don't think much is gained in fees by spreading the fees to contributors, the consolidation cost would be the same no matter who is doing it, but larger fees would get distributed unevenly and thus unfairly. I think it could work though in principle, but also quite a bit of work with risks attached so I'm not sure the balance is right.

**Comment by pazza83** [comment]
Hi @chimp184 thanks for the proposal. I am doing some housekeeping on the proposals. Please can you take steps to move this forward or alternatively close the proposal.

Ref: https://bisq.wiki/Proposals
