### ISSUE TITLE
Priorities (Bigger Picture Solutions) [Discussion]

### ISSUE THREAD

**Issue by Conza88** [bisq-network/proposals#319]
Highlighting: [https://github.com/bisq-network/bisq/discussions/5271](https://github.com/bisq-network/bisq/discussions/5271)

Which easily gets overlooked given in "discussions".

**Comment by MwithM** [comment]
The function I find for "discussions" is exactly to reduce the amount of unclear proposals and ideas, and leave this repo for those structured and consensed initiatives.
I'm closing this as invalid, although I find your post at discussions very convenient.
