### ISSUE TITLE
Reduce minimum required security deposit

### ISSUE THREAD

**Issue by m52go** [bisq-network/proposals#323]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

The current minimum required security deposit is currently 0.006 BTC. **This proposal seeks to reduce it to 0.001 BTC.**

In dollar terms the current minimum of 0.006 BTC is well over 300 USD, which is way higher than intended and makes trading on Bisq impractical and inaccessible for many people, especially for those in emerging markets. The proposed rate of 0.001 BTC is ~55 USD at current rates, which is about the same as 0.006 BTC at 10,000 USD/BTC that was in place for a long time.

The proposal is a follow-up to #295 which seemed to get stalled because it ended up being too broad, so this proposal only seeks to establish consensus on how to handle the minimum security deposit.

#### Context

The rise in BTC/USD rate has vastly increased the number of <0.01 BTC trades on the network. 
- Out of a sample size of 2000 fiat trades from the middle of 2020 when BTC/USD was ~10,000 there were 90 <0.01 BTC trades.
- Out of the last 2000 fiat trades (end of February through now) when BTC/USD has remained >50,000 there were 357 <0.01 BTC trades.

It is an attractive thought to remove the limit altogether but keeping a lower minimum makes sense to keep incentives in line for smaller trades (e.g. [discourage option trades](https://github.com/bisq-network/proposals/issues/295#issuecomment-782397118)) and compensate the DAO for disputes.

#### Technical Considerations

To my knowledge this 0.006 amount is hard-coded in the software and should be changeable without major issues or disruption.

**Comment by BtcContributor** [comment]
I totally agree with this proposal and I think it should be implement ASAP to not lose market participants.
I also agree with the fact that we should not get rid of a minimum deposit for the reasons exposed above.

Final thought: what do you think about establishing a USD value for minimum deposit (e.g. $50 USD) that automatically converts to BTC? Just to avoid that future volatility will affect minimum deposit and we spend weeks to open a new proposals.
It is not necessary to do this in real time (better though), maybe it is enough to do recalculate this value at each release with simple maths and hardcode the new value this way.

**Comment by MwithM** [comment]
I agree with this proposal, but if we go through laser eyes and this becomes a problem again I would think about removing the min security deposit at all, and leave it to the general min 15% security deposit. Then mining fees probably will make it absurd to trade less than 200USD and the 15% min security deposit should still protect from future trades (it's optional to raise it so a small trade amount has the same implications as other).
This min security deposit was set because a security deposit of i.e. 10USD was considered too small to care, even if the trade was for 70USD.

**Comment by Conza88** [comment]
_ (2) This is going to kick the can down the road ONCE AGAIN. Why is it not possible to mark it as a fixed % of current BTC price in fiat terms? 

(3) I am principally for _**no**_ minimum security deposits at all (once signed), and **_no_** maximum limit either (once signed). 
As part of that I would be clearly AF communicating to users who may be taking particular offers that don't have any security deposit, the risks etc. and consequences.. and getting them to confirm acceptance. It's a voluntary contract between two people, and Bisq is the protocol. If that means no arbitration etc. So be it. Just be clear of terms. 

(4) I am also for allowing DIFFERENT security deposit %'s to be set for MAKER and for TAKER... 
Again, an education piece with good UX about what each means.
Then truly, if A AND B WANT TO TRADE VOLUNTAIRLY, why get in the way? _ 

So TL;DR yes to the proposal but don't think it goes far enough. And we'll be having this discussion again in several months time. 

> It is an attractive thought to remove the limit altogether but keeping a lower minimum makes sense to keep incentives in line for smaller trades (e.g. [discourage option trades](https://github.com/bisq-network/proposals/issues/295#issuecomment-782397118)) and compensate the DAO for disputes.

Or it makes trying out Bisq with smaller trades unattractive and people bail entirely. I do think with communication about risks etc, and getting confirmation/agreement no arbitration etc for these type of accepted transactions. I do think the below covers it:

> I agree with this proposal, but if we go through laser eyes and this becomes a problem again I would think about removing the min security deposit at all, and leave it to the general min 15% security deposit. Then mining fees probably will make it absurd to trade less than 200USD and the 15% min security deposit should still protect from future trades (it's optional to raise it so a small trade amount has the same implications as other).
> This min security deposit was set because a security deposit of i.e. 10USD was considered too small to care, even if the trade was for 70USD.

**Comment by wallclockbuilder** [comment]
Lets keep it simple . Make minimum security deposit the BTC equivalent of 55USD. Calculatable at offer creation time. 

Scalable as it stays the same in USD but floats up/down with the BTC price.

**Comment by chimp1984** [comment]
I agree that we should decrease that. As far I am aware its not verified by trade peers, so a change will not break protocol rules. Its defined in Restrictions.getMinBuyerSecurityDepositAsCoin and Restrictions.getMinSellerSecurityDepositAsCoin.

We should consider to peg it to an USD value, should not be too hard. I think a value of 20-50 USD seems reasonable to provide enough incentives to follow the protocol even the trade amount is very low.

**Comment by pazza83** [comment]
I agree with all aspects of the proposal. 

A 0.001 BTC min security deposit would decrease the friction having the required funds needed for trading for both new and existing users.

**Comment by HeadyWook** [comment]
I'm trying to grasp this. So if the minimum security deposit (i.e., collateral) is changed to 0.001 BTC then that would allow more smaller trades. That is good. However, how will this correspond to larger trades? For example, a user should not be able to post a trade for 0.01 BTC with a security deposit of 0.001 BTC because that would create incentive to cheat. It should be some percentage of the trade, such as at least 51% of the trade amount to minimize the incentive to cheat.

**Comment by HeadyWook** [comment]
> I totally agree with this proposal and I think it should be implement ASAP to not lose market participants.
> I also agree with the fact that we should not get rid of a minimum deposit for the reasons exposed above.
> 
> Final thought: what do you think about establishing a USD value for minimum deposit (e.g. $50 USD) that automatically converts to BTC? Just to avoid that future volatility will affect minimum deposit and we spend weeks to open a new proposals.
> It is not necessary to do this in real time (better though), maybe it is enough to do recalculate this value at each release with simple maths and hardcode the new value this way.

Using fiat won't work if price goes up. It sounds like a fixed fiat amount is being suggested? If that is the case and price does increase then it would create incentive to cheat because the fiat value of the security deposit is so small.

**Comment by m52go** [comment]
@HeadyWook this proposal only changes the absolute minimum security deposit. Security deposits will still be determined as a % of trade size. I believe the current permissible range is 15% - 50% (determined by offer maker), but instead of the absolute minimum being 0.006 like it is now, the absolute minimum will be 0.001. 

Examples:
1. 0.01 trade with 15% deposit specified means both traders deposit 0.0015 (~80 USD; minimum does not apply)
2. 0.01 trade with 50% deposit specified means both traders deposit 0.005 (~270 USD; minimum does not apply)
3. 0.001 trade - % is superceded by minimum, so both traders must deposit 0.001 (minimum does apply)

Offer makers can adjust the % deposit they prefer to secure the trade, so if (1) isn't acceptable to you, you can do (2) or anything in between.

As for fiat values, the very idea is to handle BTC rate fluctuations better. Values would be pegged in fiat terms but BTC amounts would be calculated right before the deposit is put down. 

Consider this scenario: this proposal is implemented, minimum deposit is reduced to 0.001, and BTC crashes back to 10,000 USD. In this case, the minimum deposit would effectively become 10 USD—major problem. But with a pegged USD value, such BTC rate fluctuations wouldn't matter...deposits would always be calculated so that both peers would always have a reasonable amount of skin in the game (e.g., if minimum deposit is set to 50 USD, 0.005 BTC would be required at 10,000 USD/BTC and 0.001 BTC would be required at 50,000 USD/BTC) for smaller trades where percent-based deposits are too small.

**Comment by HeadyWook** [comment]
> @HeadyWook this proposal only changes the absolute minimum security deposit. Security deposits will still be determined as a % of trade size. I believe the current permissible range is 15% - 50% (determined by offer maker), but instead of the absolute minimum being 0.006 like it is now, the absolute minimum will be 0.001.
> 
> Examples:
> 
> 1. 0.01 trade with 15% deposit specified means both traders deposit 0.0015 (~80 USD; minimum does not apply)
> 2. 0.01 trade with 50% deposit specified means both traders deposit 0.005 (~270 USD; minimum does not apply)
> 3. 0.001 trade - % is superceded by minimum, so both traders must deposit 0.001 (minimum does apply)
> 
> Offer makers can adjust the % deposit they prefer to secure the trade, so if (1) isn't acceptable to you, you can do (2) or anything in between.
> 
> As for fiat values, the very idea is to handle BTC rate fluctuations better. Values would be pegged in fiat terms but BTC amounts would be calculated right before the deposit is put down.
> 
> Consider this scenario: this proposal is implemented, minimum deposit is reduced to 0.001, and BTC crashes back to 10,000 USD. In this case, the minimum deposit would effectively become 10 USD—major problem. But with a pegged USD value, such BTC rate fluctuations wouldn't matter...deposits would always be calculated so that both peers would always have a reasonable amount of skin in the game (e.g., if minimum deposit is set to 50 USD, 0.005 BTC would be required at 10,000 USD/BTC and 0.001 BTC would be required at 50,000 USD/BTC) for smaller trades where percent-based deposits are too small.

OK, I'm understanding. Thank you. 

What is the plan to handle the smaller trades where the current security deposit is 0.006 BTC? Currently there are 11 offers to buy BTC where the security deposit is greater than the buy amount.

**Comment by pazza83** [comment]
> What is the plan to handle the smaller trades where the current security deposit is 0.006 BTC? Currently there are 11 offers to buy BTC where the security deposit is greater than the buy amount.

They will get taken over time by people who are not concerned with the deposit amount (it will be refunded anyway), alternatively if they are not taken they can be edited or cancelled.

**Comment by MwithM** [comment]
Merged in pull request 5236.
