### ISSUE TITLE
Promote that Bisq contributors run Tor relay nodes

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#326]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

Bisq supports since long ime payment in BSQ for running a Tor relay node to support the Tor network. Unfortunately this never got traction and beside people running Tor nodes anyway I am only aware of one who added a relay. 

To advertise this better I would suggest a lottery payment for anyone who starts to run a Tor relay node. The Tor nickname could be used to detect those who partizipate in that and who added new nodes (to incentivize existing nodes is good as well but I think to grow the number of nodes is a better goal).

We could look up in https://metrics.torproject.org/rs.html and search for the string 'bisq'. Any such node operator would be candidate for the lottery payment. We could just make a proofable random selection at the start of a new DAO cycle and the winner is allowed to make a BSQ request for xxx BSQ. Operational costs for a relay node is rather low (about 10 USD) but to incentivice enough people to partizipate we could pay a decent sum (e.g. 200 - 500 BSQ) to the lucky winner.

I think the alternative to simply pay for each node does not give enough incentives and the relative low operational costs would not justify the effort (and costs) for making a comp. request. We also don't want to get 100s or comp. requests for that. 

To not risk that we overpay to a handful of operators we could set a goal that we want to get added 100 nodes from Bisq contributors in 3 months. If that is not reached we can drop the proposal again, otherwise it will continue each cycle. We can also start only once we have reached e.g. 30 new nodes.

A positive side effect is that it serves as a kind of advertising for Bisq and might attract new developers with Tor affinity.

There will be min. requirements for bandwidth of those nodes (e.g. a 2TB bandwidth plan seems to be good enough, such costs 10 USD at some hosters). Another requirement might be to have the node running at least 3 days to get remote bandwidth measurement (https://blog.torproject.org/lifecycle-new-relay).
To proof ownership of the winner node we could require some small change in the node config which will be reflected in the monitor page in case there are multiple persons claiming to be the operator (do not expect that is needed).
The random selection can use the IPv4 address (or fingerprint) and the blockhash of the first block of the cycle as selector input. Some small script should do it to run that selection algorithm.
All the details can be defined in case that proposal finds support....

Btw. There are only about 7000 tor nodes. Bisq has about 500 live nodes and about 20k users downloading each release. To get 10% of nodes operated by Bisq users does not seem out of reach and would be a pretty cool achievement (of course committed users can run several nodes).

**Comment by chimp1984** [comment]
Here a usefule link for relay node setup: https://github.com/coldhakca/tor-relay-bootstrap

**Comment by chimp1984** [comment]
As it seems the proposal get some basic support, I would add more specifications:

- Once there are > 30 nodes with "bisq" (lowercase) in the relay nickname at a new DAO cycle the **Tor-boost-initiative** starts
- At beginning of a new DAO cycle the compensation request maintainer takes all the nodes found at https://metrics.torproject.org/rs.html#search/bisq%20flag:fast which have an uptime > 3 days
- Easiest would be to use the IPv4 address for the winner selection as that is visible in the table result (for the fingerprint each node details need to be opened). As selector input we can use the blockhash of the first block of the new cycle.  
- The winner will be announced in the Github compensation request issues (additional promotion can be done but is not mandatory) and is permitted to file a compensation request of 10 USD x number of nodes but not more than 1000 USD (will get converted to BSQ with cycles rate) for that cycle. If the winnder does not file a compensation request in that cycle it is dropped.
- If there are not at least 30 nodes the cycle will be dropped and continued once 30 nodes are reached again.
- Bisq can stop the initiative any time, specially if it does not lead to the intended effect to increase the total number of Tor nodes (e.g. if nodes just rename their nickname)
- In case there would be multiple candidates claiming to be the operator of the winner IP they have to append a short random challenge nonce the maintainer publishes on Github to their nickname, so only the one who has access to the node can do that.  

The selection algorithm can be as follows: 
- Create sorted list from ip addresses (remove '.' and parse it as long value)
- Convert the block hash to a Big Integer and make modulo the size of the list of ip addresses.
- Use the result as index to pick the winner from the list 

Example with current data:
Block height of cycle 23: `674 707`
Block hash: `00000000000000000006572cfd4de9be2af48ed7361fb12245f20919544dbd6a`
Table: <img width="1168" alt="Screenshot 2021-04-07 at 08 27 36" src="https://user-images.githubusercontent.com/54558767/113874180-2441dd80-977b-11eb-92e0-d458b6b09dfc.png">

Code for selecting the winner:
```
 String tableInput = "bisqite (1) \t593.99 KiB/s \t1d 16h \tIndia \t139.59.30.27 \t- \tFastRunningValid \t\t9001 \t0 \tRelay\n" +
                "\tbisqotte (1) \t428.68 KiB/s \t1d 16h \tUnited States \t165.232.175.109 \t- \tFastRunningValid \t\t9001 \t0 \tRelay\n" +
                "\tbisqette (1) \t400 KiB/s \t1d 18h \tNetherlands \t188.166.1.159 \t- \tFastRunningValid \t\t9001 \t0 \tRelay";
        String[] rows = tableInput.split("\n\t");
        List<Long> ipAddresses = new ArrayList<>();
        for (String row : rows) {
            String[] columns = row.split("\t");
            String col = columns[4];
            ipAddresses.add(Long.parseLong(col.replace(".", "").trim()));
        }
        Collections.sort(ipAddresses);
        BigInteger listSize = BigInteger.valueOf(ipAddresses.size());
        BigInteger hashAsBigInt = new BigInteger("00000000000000000006572cfd4de9be2af48ed7361fb12245f20919544dbd6a".getBytes());
        int winnerIndex = hashAsBigInt.mod(listSize).intValue();
        long winnerIp = ipAddresses.get(winnerIndex);
```
Winner would be: 165.232.175.109
If anyone can convert that java code to some script would be easier to use...

**Comment by boldsuck** [comment]
> Here a usefule link for relay node setup: https://github.com/coldhakca/tor-relay-bootstrap

Because that was a bit outdated i updated the script for Debian buster:
https://github.com/boldsuck/tor-relay-bootstrap

I set up all my relays with it: https://metrics.torproject.org/rs.html#search/TorOrDie4privacyNET

**Comment by chimp1984** [comment]
Seems the proposal did not reach any momentum. 5 Bisq nodes only...

**Comment by bisqubutor** [comment]
Don't give up yet, more will follow soon.

> The random selection can use the IPv4 address (or fingerprint)

Should use fingerprint, the IPv4 address could change.
In future no IPv4 will be required but IPv6 enough for relay flags valid running.

**Comment by bisqubutor** [comment]
> Don't give up yet, more will follow soon.

Added two new relays with the bisq prefix Nickname and with proof of that I'm the Operator:
[🚀 OrNetStats](https://nusenu.github.io/OrNetStats/bisqubutor.github.io.html) 

> There will be min. requirements for bandwidth of those nodes (e.g. a 2TB bandwidth plan seems to be good enough

2TB bandwidth plan can relay <1TB.

data transfer | 

time | 1 month
data | 1 TB (terabyte)
results into average data rate | 3.044 Mb/s (megabits per second)
= 380.5 kB/s (kilobytes per second)
= 0.3805 MB/s (megabytes per second)

The min. requirements could be fulfilled with relay having only 3 Mbit/s symmetrically links, while saturated.

**Comment by boldsuck** [comment]
Nice unmetered relays in Luxembourg with FreeBSD & IPv6 :-) Do you know [HardenedBSD](https://hardenedbsd.org/) from the emerald onion people?
Hint: At frantec, you can run Tor Exit's.
Please read [AUP](https://buyvm.net/acceptable-use-policy/) beforehand and open a ticket to francisco.

@all _Cheap bare metal (not throttled at the moment) at servdiscount._

**Comment by bisqubutor** [comment]
@MwithM
