### ISSUE TITLE
I'm here for a proposal, listing a cryptocurrency native to the World Wide Web on your platform, which is WebDollar. 

### ISSUE THREAD

**Issue by cristiang2312** [bisq-network/proposals#328]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

Greetings fellow crypto enthusiasts! 

I started looking into your project a while ago and it looks like you guys are doing a great job, keep up with the good work!

One other project in which I'm very interested is WebDollar, as mentioned in the title it is a cryptocurrency native to the World Wide Web. Why do I believe in this coin? Because of its simplicity.

You just have to visit their website, which is https://webdollar.io/, and a wallet is automatically created, coins can be transferred directly from one user to another as long as they have their wallet saved. The mining rounds are 90% PoS and 10% PoW. It also uses its own blockchain. Be aware that the project is still in its early stages.

A double halving is just around the corner, nevertheless, I'm going to attach the whitepaper of the project here:

https://webdollar.io/public/doc/WebDollar-White-Paper.pdf

Thank you for your attention, I'm waiting for a reply.

Cristian Anghel

**Comment by MwithM** [comment]
This is not a _significant project-wide changes or new initiatives where a broad consensus of contributors, users, and stakeholders is desired_. https://bisq.wiki/Proposals

Listing new assets is on hold. https://github.com/bisq-network/proposals/issues/166

Closed as invalid.
