### ISSUE TITLE
BSQ/DAO oracle

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#33]
While completing the BSQ/DAO we think of any potential use cases which would make sense to support so we are flexible enough to support any of those in future. If it is consensus relevant it would otherwise require a hard fork as old not-updated clients would get a different result if we add new features which they don't know how to interpret. 

Of course we don't want to add complexity and effort for stuff what we even don't know for sure but there are features which are already implemented for special purpose DAO use cases (like bonding or parameter change) and those might be extended for a more general purpose variant without much effort.

## Voting on parameters 
I will give here an overview about the already implemented and planned features and how they can be extended to more generic types.

1. **Voting on DAO parameters to change the DAO itself**
We have already the voting for parameter change implemented (see list of current params here [[1](https://github.com/ManfredKarrer/bisq-core/blob/voting/src/main/java/bisq/core/dao/state/ext/Param.java)]). Many DAO parameters like the fees for proposals, voting or trade or the required quorum and threshold for voting or even the nr. of blocks of the different DAO phases (like the voting phase) can be changed by voting and will be applied in the next voting cycle. There is a hard coded enumeration of such parameters and adding new ones is a hard fork. All of those parameters (beside the BTC trade fee) has direct effects on BSQ/DAO consensus. So we are not very flexible with that approach.

2. **Voting on parameters to change Bisq behavior**
We have planned (not impl. yet but rather trivial) a variant to case 1 but without consequences for the BSQ/DAO consensus though consequences in Bisq: The "Remove altcoin" proposal is such a use case. If the proposal gets accepted the altcoin will get removed from the supported currencies (technically it gets filtered away from the currency list so users cannot use it anymore but is still in the code).

3. **Voting on a statement without triggering anything in Bisq**
Another proposal type which we have in planned (not impl. yet but even more trivial) is the "Generic proposal": Here a user can make any statement to be voted on. It does not has any code-based consequences but the result might give some signal. E.g. If a user makes a request for "Bisq should put priority on SegWit" and if it gets accepted by voting it will not auto-magically add segWit support :-) to Bisq but might give a strong signal to developers to pot priority on that topic. 

4. **Voting on arbitrary statements and exposing the result as an oracle**
We could use the same concept as in case 2 but with a more flexible data structure. So again it will not has direct effect on the BSQ/DAO consensus but it could be used in a code-based context new yet-not-known use cases. For a flexible data structure we can use a hashMap (key and value are strings) and users can make a proposal where they define the key and the value what should be voted on, so it is completely open which keys and values will be used here and how and by whom they will get interpreted later. If that proposal gets accepted by voting it could be used either in a Bisq context and a new software release could add code to interpret that "accredited-by-voting" data. Users who have updated will execute that data others will ignore it. 

It also could be used outside of a Bisq context and others could access that data and use it in their context (e.g. some smart contracts or as non-code based signal). If the data consumers would run Bisq they can access the data securely otherwise if accessed via an API or webpage they need to trust the data provider (there could be several to reduce risks).

### Reputation
One use case which came to my mind would be a kind of reputation poll. One could ask the Bisq stakeholders a question like: "Would you trust Craig Wright with giving him a loan of 100 000 USD?" (key: "trustCraigWrightWith100kForLoad", value: "yes"). It should has a pgp signed statement (on the linked Github issue) and the stakeholder can vote with accept/decline or ignore. If the outcome was the he got majority acceptance the proposal requester could use that outcome in a lending market as sign for reputation (that BSQ stakeholders would trust him I doubt it in that example ;-)). The peer giving him the loan could either run Bisq to look up the result himself or there might be some APIs which present those oracle results to the outside world. 

Maybe we could add here additionally a "burn BSQ" feature so it will have some extra costs (can be defined by the requester) for requesting an oracle result. That would add some weight to the result as it shows that the requester was willing to take some risk to lose that BSQ in case he would not receive acceptance.

I don't have other concrete use cases in mind yet, but I think to **expose the power of meritocracy based voting** could be an important extension and the technical effort and complexity is rather low. 

## Trust model/limitations
The trust model for those oracles is based on the group who produces the voting: The BSQ stakeholders. Voting is backed by 2/3 meritocracy and 1/3 stake. That has to be kept in mind and adds clearly limitation of the possible use cases. E.g. using the oracle for financial products (prediction markets) might be problematic. 

Other limitations come from the BSQ/DAO market capitalization and connected volatility and manipulation risks as well as trust in the BSQ implementation as well as ultimately in BTC (as BSQ is based on BTC).

Please let me know what do you think and if you have some ideas with other use cases!

[1] https://github.com/ManfredKarrer/bisq-core/blob/voting/src/main/java/bisq/core/dao/state/ext/Param.java

**Comment by chirhonul** [comment]
I like designing the DAO to allow for support of this feature eventually, as long as that future-flexibility does not increase current complexity too much. The idea of different DAOs being able to "talk to each other" by a generic ask-Bisq-Oracle feature by a user running full nodes for both DAOs does seem like it could be a very powerful idea, even if we can't completely visualize how such features would be used in the boundless future.

Re:
```
There is a hard coded enumeration of such parameters and adding new ones is a hard fork.
All of those parameters (beside the BTC trade fee) has direct effects on BSQ/DAO consensus.
So we are not very flexible with that approach.
```
I believe if we changed the logic to handle unknown / higher valued enum values for the DAO parameters by assuming our code does not understand them, we could be able to support them as a soft fork, if at least majority of BSQ stakeholders upgraded to a version that does understand the new parameters. In such a case maybe we also want to hint to the user that they could be running an old release and can consider upgrading. (Protobuf allows this pseudo-forward compatibility already for new / higher-id fields, which are ignored by clients running old releases without knowledge of those fields.)

**Comment by ManfredKarrer** [comment]
Re hard coded parameters: 
Yes for some cases soft forks might work but if it could render some BSQ invalid (e.g. changing the voting fee to a higher value (we could be tolerant if the paid fee is higher as expected from the params) would invalidate a vote and therefore can lead to a different result in issuance. Not all such cases will lead to a different state of BSQ (e.g. if the vote would not have influenced the total vote result) but we don't know in advance.
For proposals and voting we can enforce that users have to be on the latest version (we use version bytes in all important data). But to enforce passive BSQ users who only use it for paying trading fee or trading it on the market it a bit harder. If a hard fork is needed we can signal that to users. We will probably have a consensus check built in anyway so if a users has a different state then the majority of full nodes he will get alerted by sending out requests for a hash chain of the BSQ state and compare the responses with own state. We can create a hash of the BSQ state data at each block and use the previous hash to create a new consensus hash. This one will be then used for the next - similar like the BTC blocks are chained by referring to the last blocks hash.

**Comment by meapistol** [comment]
It seems like it will be possible, via soft-forks, to add new products (credit, things, work, financial derivatives based on underlying assets or on a contract, ...) which I think is highly desirable. Such amendments will split the network but in a friendly way. The subset of users that want to trade e. g. movies can do so amongst themselves and nobody else sees it. Make sure it will be easy to add and vote on parameters that act on such products (e. g. fees).
Arbitrators will be oracles for some contracts in case of conflicts and the supermajority of merito-token holders will be a stronger and more expensive arbitrator if needed.
Maybe users should be able to choose a subset of (specialist) arbitrators that vote on a statement. I. e. instead of choosing an arbitrator a set of arbitrators are chosen in case something is very difficult or sensitive. This will reduce the ability for arbitrators to scam. High quality arbitrators will then be highly paid in btc after they have established a reputation (outside of Bisq.).

**Comment by ManfredKarrer** [comment]
I think that idea is not further developed. I will leave it open still as it might still be interesting to read up and might lead to future continuation or extension.
