### ISSUE TITLE
Batch Transactions and Consolidate Them to Save on Fees 

### ISSUE THREAD

**Issue by yoshimo** [bisq-network/proposals#334]
Recently the mempool was rather full and it was quite expensive to get things through.
This affects both the many small fee transactions as well as the final payment transactions.

Payment is rarely done instant and the bought goods are not immediately required, so maybe we could benefit from the research done over at the Wasabi Research Club.

https://github.com/zkSNACKs/WabiSabi/ introduces a blind coordinator and allows to combine multiple input transactions to less output transactions without making them linkable.

**Comment by pazza83** [comment]
Hi @yoshimo thanks for creating this proposal.

Please check the [guidelines to creating a proposal](https://bisq.wiki/Proposals).

Please can you have a read and either edit your proposal to include the required information or alternatively create it a [topic for discussion](https://github.com/bisq-network/bisq/discussions).
