### ISSUE TITLE
Issue raised on back of closed request #928 (leo816)

### ISSUE THREAD

**Issue by lukaskotvan** [bisq-network/proposals#338]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

Hello,

I have made trade (buying 0.01 btc) on 23 FEBRUARY 2021, due to technical issues I got disconnected. When I have logged back in - there was no sign of any trades. I could not continue, dispute or finalize this trade: "transaction". My onion address is znngrloovnqdbdpeemckbsowjmvbmuyptug55yqebasoqmmhm5iuo3yd.onion:9999  https://mempool.space/tx/c5818b8e674b25d94b1bec860ec96e142310a9ee97f5995cdeee52566ed45dfa  
I have approached mwithm viac keybase, he has done some investigation see "mwithm@ and referred me to mediator leo816 see: "asking for support, mediator has case". **leo816 closed it IN MY FAVOR** .
I have raised request no. 928 - that has been closed, however, no refund has been received.

NOW I HAVE BEEN ASKED TO RAISE ISSUE BY leo816.
![image](https://user-images.githubusercontent.com/82460219/121901399-a7a51f80-cd26-11eb-98a0-022ef764a83b.png)

Hopefully you have enough info.

Thanks for help.
Kotvik11

**Comment by pazza83** [comment]
Hi @lukaskotvan 

This repository is for proposals.

Please post compensation requests here: https://github.com/bisq-network/support/issues
