### ISSUE TITLE
Proposal for a new Comptroller role

### ISSUE THREAD

**Issue by pazza83** [bisq-network/proposals#340]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

## Proposal for a new Comptroller role

**Background:** 

- [Running the numbers on Bisq DAO revenues](https://github.com/bisq-network/bisq/discussions/5171)
- [Summary – Bisq DAO](https://docs.google.com/document/d/1MxajknrXxZvJ4MKMhtaVhXfkb6TlaINTbqmryCbCUbw/edit)

**Related projects:**

- [Add semi-automated DAO reporting to website](https://github.com/bisq-network/growth/issues/245)

## Problem

It is currently difficult for Bisq contributors and stakeholders to know is Bisq is profitable or making a loss on a month to month, or annual basis. In my opinion this is largely a result of no one having a role with any sort of accounting function within Bisq. In July 2021 Bisq's trading volume was $4.6 million (USD equivalent). Most organizations' with this sort of trade volume with have at least some account function. Bisq does not.

A few relevant quotes from the recent [Summary – Bisq DAO](https://docs.google.com/document/d/1MxajknrXxZvJ4MKMhtaVhXfkb6TlaINTbqmryCbCUbw/edit) complied following discussions with 15 contributors are: 

> no clear understanding of current financial position eg. clear picture of basic P&L, how much was issued for each cycle, tendencies, etc.

> accounting role to keep track of P&L, projections, budgeting, etc.

> more financial people eventually when the project grows

> It may prove itself not profitable enough to fund enough contributors, especially the high caliber ones (JAVA/Bitcoin developers). Monero (XMR), Bisq’s main source of revenue may continue to leave Bisq if other protocols make its swap with BTC easier/cheaper.

> being more profit-oriented would allow bisq to grow much faster, and would be incentive to access more talents

> accounting/record-keeping for the DAO: improve on it and show people how they are doing

These are a few snippets relevant to the above proposal. Please see the report itself for full context. 

In addition to the above there was also a discussion on [Running the numbers on Bisq DAO revenues](https://github.com/bisq-network/bisq/discussions/5171). I think there was generally consensus that providing more accounts information would be of benefit.

In my opinion problems with not having account information accessible to contributors and stakeholder brings the following issues:

- Difficult to know what progress is or is not being made
- Difficult to make decisions on budgets and what resources are available
- More risk of overspending
- Morale issues can be caused by not knowing if the work being done is having an impact to the success of Bisq 
- Difficult to make future plans that take financials into consideration
- Difficult to make real time decisions, can Bisq afford to take on a new contributors, or dedicate resources to a specific projects.
- No accounts means any audit would be more difficult and their would be less to validate

I think it is important to acknowledge that as a DAO, that pays contributors for their contributions in BSQ, Bisq is insulated to a certain extent from what is usually the most critical accounts measure, cash flow. That being said however, it is still important for the continued and future success of Bisq that various accounting metrics are measured and taken into account when making decisions by the DAO.  

Likewise it is important to remember that Bisq's profit and loss is not represented the same way that  it would be with a traditional organization instead it is a measure of whether BSQ is inflationary (running at a loss) or deflationary (running at a profit).

## Objective 

Bisq contributors and stakeholders to be able to easily access quick monthly reports that give a snapshot as to how Bisq is performing in terms of profit / loss ie, is Bisq earning more in trade fees that it is spending (both in terms of USD and BTC).

This would have a positive impact on making it:

- Easier to ascertain progress
- Easier to make real-time decisions on budgets and what resources are available
- Be better able to see the impact of work done to the success of Bisq
- Easier to use as starting point for any future audit (to validate financials)

## Solution

To achieve the objective I would propose a new Comptroller role.

Initially I see this role as being kept as simple as possible to report monthly on the following: 

|   | USD | BTC |
| ------------- | ------------- | ------------- |
| Trade volume July 2021  | $X  | X BTC  |
| BSQ trade revenue fees  | $X  | X BTC |
| BTC trade revenue fees | $X | X BTC |
| Net Profit (Loss)  | $X  | X BTC |

Percentage of fees paid in BSQ was: XX.XX%

A monthly report similar to the following would also be provided:

- [Bisq - Profit & Loss - July 2021](https://docs.google.com/spreadsheets/d/1EMwuKiFxP5QreN9eNUiX5Ub7ssukGcJ4FytuAXHCDgM/edit#gid=1863760054)

This information would be reported on at the start of every month, reporting on the previous month, within a roles report that would also be referenced in any compensation request.

A annual report similar to the following would also be provided at the start of each fiscal year to report on the previous fiscal year:

- [Bisq - Balance Sheet -  Fiscal Year 20/21](https://docs.google.com/spreadsheets/d/1hpq01cjSFAkockRYLTCiLiPOYezlyxrqgfExKyrzeFM/edit?usp=sharing)
- [Bisq - Profit & Loss - Fiscal Year 20/21](https://docs.google.com/spreadsheets/d/1b6OkJmZwuxOit-x0zKBzag4VsfH2NPwUDOxFU0j9DWk/edit#gid=255820709)

I would also include a summary of observations alongside the report such as: https://github.com/bisq-network/bisq/discussions/5171#discussioncomment-971061

## Compensation

If the above information could be automated in some way to be added to something like https://github.com/bisq-network/growth/issues/245 that would be preferable. 

If the role cannot be automated, or until it can be, I would be happy to complete the role for $75 USD per monthly report and $150 USD for an annual report.  Due to the reports being monthly this might result in some cycles where no compensation is requested.

If consensus for this role is reached I would be happy to start immediately.

As this role is not vital to Bisq operations, nor would any special permissions would be required, I do not see a need for a bond for this role.

## Limitations

It is important to note also what lies outside the scope of this role:

- Auditing would not be included. Doing the last 2 reports makes me think an auditing role would be important. This would involve validating trade volume, trade fees etc.  The comptroller role would not be validating the data, it would be utilizing the data from what is provided in the Bisq app. I also think the comptroller and auditor roles should be separated and completed by separate contributors.  

- The comptroller role would be confided to accounting for Bisq's financial resources, but not for allocating them. As per @cbeams comment:

> Basically, the comptroller would not have decision making power about where funds go. Only about how we think about, account for and report on them (which is a lot!). That's what I like about the connotations around the "comptroller" versus "finance director"—the former really means "head of accounting", not more. Budget decision making is currently the domain of team leads (and ultimately DAO stakeholders through voting) and we can leave that status quo for now. The comptroller role can greatly help in this decision making process by feeding higher-quality data into it, but I think the comptroller should not have any direct power over the budget.

- Reporting would be limited to the areas defined above. It might well be that the role could be expanded in time, and this would be great. But for now I want to keep it simple and just get something started that provides information of value to stakeholders and contributors.  

- My background is not in accounting or finance. I would be happy to take on this role to get it off the ground, but I would also be equally as happy to pass it over to someone with more expertise that can grow and evolve it.

## Summary

I think having a role that provides Bisq contributors and stakeholders is important and needed.  If anyone has any comments or suggestions please share them.

**Comment by m52go** [comment]
I think it's more important that the project first have some serious conversations about its priorities and roadmap.

No amount of reporting will fix these deeper, existential issues.

**Comment by clearwater-trust** [comment]
In your mind/heart/body/soul,  what are the existential issues/priorities?  Thank you.

**Comment by m52go** [comment]
@clearwater-trust my concerns are somewhat described [in this report](https://docs.google.com/document/d/1MxajknrXxZvJ4MKMhtaVhXfkb6TlaINTbqmryCbCUbw/edit). I'm not sure it's clear _what_ the project seeks to accomplish in the mid-to-long-term, and so talking about _how_ it should manage stuff with a new administrative role seems like jumping the gun.

I'm not opposed to the role on principle but I think it needs to be combined with some more significant initiatives in order for it to make sense.

**Comment by clearwater-trust** [comment]
@m52go - Let's discuss the report you provided. 

---
Important issues of the DAO:
-       unclear distribution of responsibility is a problem – if no one feels responsible, issues will fall through the cracks. But on the other hand, since anyone can do what they want, there is a potential to cover everything that needs to be covered if it was clear for new contributors how they could pick up some field that has fallen through the cracks
-       you get more motivated contributors as compared to a company, but there is no consistency and things don’t necessarily get done
-       DAO is necessary because of legal issues, but would be much easier without a DAO – not having a leader is problematic, not really anybody to push initiatives forward
-       Centralizing in some way, and being more profit-oriented would allow bisq to grow much faster, and would be incentive to access more talents
---

The first bullet argues FOR adding new roles. 
The second bullet argues FOR adding new roles.
The third bullet is garbage.
The fourth bullet is garbage.

**Comment by m52go** [comment]
My concern isn't about adding new roles. It's about getting the project back on track.

The interface limits the program to the most motivated power-users in developed markets. Lack of interoperability cuts it off from integrations with other software and other companies. The lack of mobile cuts it off from emerging markets. Mining fees will eventually make the trade protocol unfeasible. Monero volume going elsewhere doesn't help.

Is the contention that financial analysis will address these issues?

I've spoken to many people over the past 3 months. Some savvy users, some non-technical users, men, women, young, old, existing users, and others who had no idea what Bisq was. I've sat down with people 1-1 in-person to help them use Bisq. I've spoken with folks in India, Africa, and Latin America. I've spoken with a well-known wallet company who's eager to integrate Bisq into their services. Bisq is a tremendous achievement but we're at a point now that its downsides are causing itself to fade out of relevance. The problems I listed above are serious show-stoppers, and their impact on growth of the network (and its future prospects) is being grossly underestimated.

**Comment by clearwater-trust** [comment]
Can you not see what is happening? The policies put into place by our corporate/government overlords will eliminate most of the issues you describe. The _show_ is only beginning.  

IN THE VERY NEAR FUTURE:

“First-world” populations cannot access legacy banking refusing to take part in medical apartheid.

Entire segments of working class people unable to engage with ‘transaction’ services of banks/brokerage/wheelbarrow money organizations without proof of compliance.

**WE MUST NOT CENTRALIZE THE PLATFORM IN ANY WAY.**

Hold The Line.

The limitations of Bisq, as you describe them, are about to be a feature- not a bug.

Reaching out to wallets that want to touch Bisq is a great idea. However, they must conform to us.

We only conform to DAO.

_Peace, Love, and Light._

**Comment by pazza83** [comment]
Thanks @m52go and @clearwater-trust 

I am in agreement that Bisq should remain not centralize in any way.

I also agree that it is more important (that implementing this role) that the project first have some serious conversations about its priorities and roadmap. I also agree reporting does not fix this.

I do not think having a comptroller role makes Bisq any less decentralized. 

I think that regardless of Bisq priorities and roadmap being known or unknown a role of a comptroller makes sense.

**Comment by leo816** [comment]
Since there is no one automatizing this role, I would encourage @pazza83 to take over meanwhile. I believe a 75 USD monthly compensation seems fair. A monthly report of a clear PNL seems crucial in my opinion.

**Comment by pazza83** [comment]
Closing as approved due to feedback in comments and discussion during team meetings.
