### ISSUE TITLE
Bisq regulatory issues

### ISSUE THREAD

**Issue by daveblack1** [bisq-network/proposals#341]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._
The US is on the verge of passing regulatory requirements that will effectively ban cryptocurrency software development:
https://www.coindesk.cc/coinbase-warns-infrastructure-bill-s-crypto-provisions-could-impact-20-of-us-population-39813.html
GitHub is owned my M S. 
Bisq would be in danger of being regulated out of existence. 
Should the team consider moving development to a non-US, crypo-friendly development host? 

Here are a few options:
1. Gogs - self-hosted development platform. Ensures development can continue in any country.
2. BitBucket - hosted in Australia. However, Australia is launching their own CBDC, which will likely become unfriendly to decentralized cryptocurrencies as they may follow the US's lead.
3. More alternatives: https://www.guru99.com/github-alternative.html

**Comment by pazza83** [comment]
Hi @daveblack1 thanks for making this proposal. Please would you be able to expand on it. For more info please see https://bisq.wiki/Proposals

**Comment by Conza88** [comment]
Oz is US's biatch. So yeah, matter of time. 
Whole nuclear sub deal thing reiterates close relationship.

**Comment by pazza83** [comment]
Closing due to lacking information.

@daveblack1 please feel free to expand on your proposal. Information about how to create a proposal can be found here: https://bisq.wiki/Proposals
