### ISSUE TITLE
New role request- User Researcher

### ISSUE THREAD

**Issue by UX-P** [bisq-network/proposals#344]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process]

Hello, I would like to make a proposal in regards to creating a new role possibly within the Growth team. A User Researcher. This will consist of conducting one on one user interviews which will take place via zoom where interviewees have the option to turn their cameras off if preferable, for privacy reasons.  User focused questions will be discussed in order to really identify the interviewee’s expectations, the aim is to iron out usability concerns as early as possible. I will ask questions based on their overall user experience of Bisq as well as enquiring about the usability of specific areas on the site, including any features and processes.

The next stage will be to analysis the interviews and identify common topics, words or phrases via affinity mapping, this allows me to pinpoint the user's key issues and concerns during their user journey.

I will communicate my qualitative findings through a summary report available to the community manager and others within the growth team, and make proposals based on my evaluations. This will be known as a community proposal.

-**Community Proposal**-

A community proposal will be derived from the report analysis on a per monthly basis (timescale will vary depending on previous proposal).
 
This will be a supportive addition to the current proposal system. A community proposal will assist in Optimising user feedback to make overarching issues easier to identify and help to implement changes based on the way the overall user wishes to navigate the site.

-**Project Contributions**-

The User Researcher can also contribute on a per project basis at the owner’s request. During the initial stages of production, the project owner would discuss the specific aspects that they would like to focus on and what they would like to get out of this user needs assessment. 
I will form questions based on this subject area, and subsequently, explore channels to request interviews. 

As a user myself I will be balancing what I already know about Bisq and the current user experience with an open free form discussion to really learn about the overall user, gaining a more in-depth view that you cannot otherwise gage solely through social media chat channels. 

A user researcher is an ongoing role and is valid in all stages of design with the aim to humanise the online experience. In order to advance with the product, the usability of the initial software should be considered.  
User researching is essentially about improving the current phase and also providing insights to future projects that can be turned into actionable ideas and solutions. 
In order to widen the Bisq market and grow the platform it is essential to primarily know and understand our users to ensure a pleasant and seamless experience. 

Thank you for taking the time to read my proposal, and I look forward to your feedback.

**Comment by m52go** [comment]
This sounds like a good idea but I'm not clear about what to expect on an ongoing basis to justify creating another role. 

Perhaps you can coordinate with an existing or upcoming project and provide an example of what you can deliver first so people can better evaluate what such a role would accomplish.

**Comment by UX-P** [comment]
@m52go  Thank you for your encouraging feedback. I will definitely take this on board and apply my strategy to specific projects and share the outcome with the appropriate teams.

**Comment by pazza83** [comment]
Hi @UX-P thanks for the propsoal.

Feel free to browse the [approved proposals](https://github.com/bisq-network/proposals/issues?q=is%3Aissue+is%3Aclosed+label%3Awas%3Aapproved) for ideas, or alternatively [current projects](https://github.com/bisq-network/projects/issues) for ideas.

[Keybase](https://keybase.io/team/bisq) may also a good place to discuss with other contributors how you could assist from a user researcher perspective.

I will leave this proposal open for a month or so if you want to come back with any updates as to what you might get involved with.

**Comment by UX-P** [comment]
Hi @pazza83 that's excellent, thank you. I have seen a project that would really benefit from a user researcher's perspective, I will discuss this in Keybase and be updating in the coming weeks.

**Comment by UX-P** [comment]
I have analysed the comments left by users on Keybase support and designed an [affinity map]( https://miro.com/app/board/o9J_lo8abDg=/?invite_link_id=107283228134 
) grouping the most common subjects and talking points.
Below is a summary of possible solutions based on these key points and takes into consideration the heuristics web standard.
This list is also applicable to any new releases (maybe some of these have been addressed already) and future app considerations when developing Misq. Let me know what you think. 

**Language**
Error messages were also a common issue. The user seems to be unclear of their next steps e.g. error reads ‘Contact a Bisq developer’ without providing a call to action button, contact or link. The language used in the error messages is often incomprehensible to the user, it is important to use language that the user is familiar with where possible.
-	Unmatched account details should be stated in UI as: a breach of protocol and may result in mediator intervention.
-	Error messages should be translated where possible using language familiar to the user and should contain an action e.g., restart Bisq, or contact support, including an action button.

**Support**
Although Keybase is great for discussing certain issues, Users are seeking that immediate help. There does not appear to be enough guidance given directly from the Bisq app itself, which is where the user would initially look for support.
There is not a support system on Bisq that encourages one on one queries between mediator and user outside of mediation. Here are a few ways to encourage this:
The chat panel should clearly state where the user can go for further support or who to contact.
-	Support team available on Bisq
-	Create a support chat window separate to mediation and P2P chat window, required on Bisq for general queries during trade.
-	If no resolution is provided on Bisq chat, direct the user to Keybase support using a link or button.
-	Direct users to Keybase for tech issues or specific mediator
-	Link to Keybase support displayed in chat panel and support button.
-	Separate mediation and P2P chat window

**How to guide**
Users make many ‘How to’ enquiries. The support tab currently contains mediation history and could appear misleading as the term ‘support’ is associated with help. The support click-through should contain information and links for quick access to guidance and documentation. Include a search bar to look up words and popular search terms used on Bisq. This will help to alleviate the Keybase support channel and prevent it from being clogged up with issues that can be resolved by the user. Here is a list of guides derived from the most common ‘how to’ queries:
-	Getting started guide, include the Bisq basics
-	Step by step guide on disputes
-	Security and privacy protocol
-	Trading process guide
Many users seem confused by the terms and wording used by Bisq. As a web standard users should not have to learn, they want to comprehend almost immediately using as little amount of thinking in order to relieve their cognitive load. However, it is understandable that in some cases certain words are required, so perhaps these suggestions could help the user to broaden their understanding:
Glossary
-	Glossary in Bisq support
-	Wiki descriptions available on Bisq under support tab

**Technical**
Users are having node connection issues; I am not a developer so I do not know if this is solely a technical issue. I have spoken with a user and they have explained that when Bisq has not yet connected to a node it is displayed on screen as an error message. Is this an error? If not, it could be better represented as a loading message.
-	Connections to node can be shown as a waiting period not a warning. E.g., ‘Please wait for syncing to complete’ appears at relevant points of the user journey, as opposed to appearing on screen as an error message.
Long waiting periods
The long waiting periods causes complaints and seems to agitate the user, some even stating that they won’t be using Bisq again. These issues could be rectified with the following suggestions:
-	State arbitrator’s expected response time clearly in chat e.g., arbitrator will respond within 5 days
-	Inform the user of what to do when the arbitrator does not respond after specified time.
-	Show when mediator is online
-	State mediator’s expected response time
-	Inform user of what to do when mediator does not respond

**P2P Interaction**
On average users complain on Keybase after 18 hours wait for peer to confirm.
P2P interaction should be encouraged so that it does not result in the user having to contact support. Prevention of escalation via P2P communication will make the peer less inclined to neglect a trade and may result in less mediator intervention, here are several ways this could be applied:
-	Show if peer is online with the option to switch status to offline.
-	Notifications once Bisq is minimised prompting, next steps, confirmation, chat messages, time period terminated, reminder to either confirm or transfer.
-	After 18hrs waiting period prompt user to contact peer

**UI**
These are changes that should essentially be applied for immediate enhancement of UX experience.
-	Optimise scaling so that all essential elements are displayed
-	Remove ‘locked funds from failed trade’ pop up.  Prevent it from obscuring the UI. -	Clearly displaying shortcuts are essential for both new users and power users. Shortcuts stated on UI e.g., Open mediation Ctrl + o, Open wallet data Ctrl + j
-Mediation and P2P chat box should be separated

**Next steps**
I would like to ask users on Keybase to state what features they like, dislike, or would like to improve on Bisq etc. with the option to also participate in a short user interview, any research suggestions from the team is welcome.  In the meantime, let me know what you think of the above user analyse. 

It would be excellent to hear from a UX designer and @pazza83  as I know you contribute in the support team. I am not aware of who to add to this but any feedback is welcome!

**Comment by chimp1984** [comment]
@UX-P Great thanks for all that work! Very valueable collection of issues to improve.

Regarding shortcuts:
I think those which are more essential should get a button in the relevant UI screen to open the info directly. Shortcuts have been intended to be for non critical info and for expert users. But some of those you mention clearly do not fall into that category. 

Maybe @jmacxx find some dev bandwidth to target some of those issues.

**Comment by pazza83** [comment]
Thanks @UX-P for this feedback.

I like the affinity map as a way of presenting the Keybase support enquires. Makes for interesting reading.

> Error messages were also a common issue. The user seems to be unclear of their next steps e.g. error reads ‘Contact a Bisq developer’ without providing a call to action button, contact or link. The language used in the error messages is often incomprehensible to the user, it is important to use language that the user is familiar with where possible.

> Although Keybase is great for discussing certain issues, Users are seeking that immediate help. There does not appear to be enough guidance given directly from the Bisq app itself, which is where the user would initially look for support.

I agree with these points. I suggested promoting [Keybase in the Bisq app](https://github.com/bisq-network/bisq/issues/4904) to streamline users that have issues to Keybase where issues can be most effectively handled. 

> P2P interaction should be encouraged so that it does not result in the user having to contact support.

I agree with this also. It would be great if users were prompted to communicate with peer to resolve issues before opening mediation tickets., especially when the trade window is still open. 

> Show if peer is online with the option to switch status to offline.  

This would be a privacy concern. Especially when traders may have their counterparties address!!

**Comment by pazza83** [comment]
With regards the user researcher role. I think it would make sense to limit the role initially to one project at a time.

On a recent [Bisq dev call](https://github.com/bisq-network/projects/issues/60#issuecomment-944453142) the issue of the following was discussed: 

`Monero is our most traded altcoin, we should learn as much as possible and make sure we are doing what we can to attract as many users.`

To date it has been difficult to get feedback from Monero traders. Both myself and @leo816 have been asking Monero traders when they have mediation tickets open if they have any feedback or suggestions as to how Bisq can improve but feedback has not been very forthcoming.

Maybe something like an anonymous online survey that could be access via Tor could be used to encourage traders to be more comfortable sharing feedback and suggestions.

I feel the Monero issue is an important one and so far Bisq has not been able to learn much from Bisq's Monero community.

If other Bisq contributors / stakeholder felt this would be a good project to complete, and if it is something you would be interested in, maybe you could create a fresh proposal that would define a clear project brief and budget.

**Comment by UX-P** [comment]
@chimp and @pazza thanks for the receptive feedback, and I agree with the role being applied on a per project basis. I’m glad you recognise the value of the specified UX points, please keep me updated with any changes you are considering applying from the research as it would be great to track the progress.
@pazza yes I would like to help tackle the Monero issue so a new proposal will be made regarding this, I will be posting a brief very soon.

**Comment by pazza83** [comment]
Closing as superseded by https://github.com/bisq-network/proposals/issues/349
