### ISSUE TITLE
Add AXS and SLP to list of cryptocurrencies

### ISSUE THREAD

**Issue by phma** [bisq-network/proposals#346]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I'd like to see Axie shards (AXS) and Smooth (or Small) Love Potion (SLP) added to the list. These are used in the Axie Infinity game and are ERC-20 tokens. AXS is part ownership of the game; one can stake AXS and gain more AXS, like interest but the rate varies. SLP is earned by winning the game. Breeding Axies requires both AXS and SLP.

There are over eight million Axies in existence and over two million players. I don't find statistics of how many people breed them, but I'm guessing 10% or less of players. So there's a flow of SLP, and maybe AXS, from players to breeders.

I suggest that the AXS and SLP accounts be on the Ronin sidechain, since transactions on Ronin are free up to 100 per day, whereas transactions on the main Ethereum chain cost gas fees. SLP earned by playing is deposited in Ronin, and staking is done with Ronin.

**Comment by pazza83** [comment]
Hi @phma thanks for your suggestion.

Currently Bisq has put on hold new altcoin listings.

This means that AXS and SLP can currently not be added.
