### ISSUE TITLE
Bounty to enable Cross Chain Atomic Swaps for NMC

### ISSUE THREAD

**Issue by gustavocandia** [bisq-network/proposals#347]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

What if in the not too distant future the demand for .bit domains takes off to the point where people are willing to pay far more for Premium names than their regular registration/renewal cost. It would be incredibly useful to have an application where either NMC or a name can be exchanged for NMC or any other coin.

Jeremy Rand Lead Developer from Namecoin proposed a while back using NAME_NEW outputs in Bisq trades as a way of (1) reducing tx fees, and (2) confusing graph analysis.  He has said "a lot of the BTC for names work looks very similar codewise to my Bisq proposal for NAME_NEW outputs".

I'd be willing to offer a 0.03BTC bounty to enable the exchange of ALL Namecoin name records (not just domains) for BTC.

Please send me a message via GitHub to ask further questions if needbe.

**Comment by pazza83** [comment]
Hi @gustavocandia thanks for the proposal and offer of a bounty. 

From my perspective the proposal does not provide enough information for effective discussion to take place.

I think it would benefit from you expanding on the proposal to stand the best chance of engaging users. For more info on how to write an effective proposal please see https://bisq.wiki/Proposals

**Comment by gustavocandia** [comment]
I believe Jeremy Rand will be resubmitting a proposal for this work in a week or so.

**Comment by pazza83** [comment]
Closing this for now. Please feel free to submit again with more info
