### ISSUE TITLE
Add "Seller maker/taker" and "deviation from market price" in Market>Trades history

### ISSUE THREAD

**Issue by GordianLN** [bisq-network/proposals#348]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

It would be useful, for decision helping as offer maker, and for analysis purposes, to include in the "all trades history" two more columns, one where it's defined the role of the BTC seller, if maker or taker, and another (right next to the trade price column) for the percentage deviation from current price at the moment of offer taking.

**Comment by pazza83** [comment]
Hi @asvdf thanks for making this proposal.

I think however that it would be best posted in: https://github.com/bisq-network/bisq/issues 

Apologies if it was myself that recommend you to post as a proposal!

**Comment by GordianLN** [comment]
Thanks for getting back to me, opening an issue there as we speak

**Comment by pazza83** [comment]
Closing as moved to issues https://github.com/bisq-network/bisq/discussions/5804
