### ISSUE TITLE
Hi Guys, we love Bisq and we need help to list Artizcoin (BNB) a security solution to protect NFT intellectual property. any advices pls?

### ISSUE THREAD

**Issue by Artizyou** [bisq-network/proposals#351]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

**Comment by pazza83** [comment]
Hi thanks for the proposal. currently new assets are closed to listing. No dates yet when this will change.
