### ISSUE TITLE
Increase Max BSQ reimbursement amount to 160k

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#354]
Edit: This proposal should be **rejected** as it's based on a wrong assumption.

We are exceeding the limit of 80k for this Cycle 31. Total amount of BSQ to be issued through reimbursements on this Cycle is 143k.

Refund:	76256,00
Rtgeek:	25238,11
Polygonk	39331,37
Opticbit:	1042,00
Total	**141867,48**

I'm not sure if the limit applies to a single or overall reimbursement proposals, but as there are just a few blocks to the end of proposal phase I'm accelerating this proposal.

**Comment by MwithM** [comment]
34e2a20f045c82fbcf7cb191b42dea6fba45641777e1751ffb29d3981c4bf413

**Comment by chimp1984** [comment]
The max value is per proposal. So easiest is to split the proposal into 2. 
It would not have effect for that cycle. 
I think its a good security gate and prefer to not change that. The very few times when its required to exceed that it can be easily done by making multiple proposals.

**Comment by MwithM** [comment]
Closed as rejected.
