### ISSUE TITLE
Adopt Compensation policy for work on Misq/Bisq 2

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#356]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

For the work on Misq/Bisq 2 it is not really feasible/efficient to package each work scope into defined deliverables and as its all work in progress it is not useable for users yet.
I would suggest to adjust the DAO compensation rules for this area to make every merged PR to https://github.com/bisq-network/misq subject for compensation requests.

UPDATE:
After thoughts from the feedback I think its still good to define the scope of some work packages as an issues if its smaller, or as project if scope is larger or easier to define the boundaries.

**Comment by cbeams** [comment]
Suggestion: incentivize delivering / shipping milestones, not just merged PRs. Define milestones early and often enough to make sure folks get compensated in a reasonable time frame. Still track compensation based on merged PRs (that remain merged at the milestone boundary). Doing it this way will align everyone on shipping, not just coding. What gets shipped doesn't have to be production-quality. Can be 'preview' / 'alpha' /  etc milestones, but shipped, working software that gets real feedback.

**Comment by chimp1984** [comment]
Yes that was the approach we used so far but I fear it creates too much overhead. For instance @ghubstan provided a suggestion for a config file framework. Such smaller items are hard to fit into a milestone or not worth to create one. On P2P network work there is lot of work which develops more organically during work on it. Enforcing deliveries as initially intended was not really efficient. Defining a milestone enforces one then to stick with it, or comes with overhead to change/justify why it changed. I cannot easily say what I will exactly work on in the next 1-2 weeks. And enforcing me to do that would just lower my productivity. In my case I would just not make compensation requests as I prefer to work without those restrictions, but I think thats also no correct and then lot of unpaid work stacks up...

**Comment by chimp1984** [comment]
Actually I think you are right ;-). Should not be too much effort to define a bit more clearly the scope of tasks. Will try to do that via issues as for projects the scope might be too small.

**Comment by cbeams** [comment]
You can use GitHub's Milestones feature for this. Create a milestone and then add issues to it using the right nav.

**Comment by chimp1984** [comment]
Close due inactivity
