### ISSUE TITLE
Using merit for L-BTC fee payment distribution in Bisq 2

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/proposals#358]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

There are open questions how fee payment can be done in Bisq 2.
Here is one idea for trades on Liquid: 

A DAO contributor (who earned BSQ by compensation requests) creates signed `fee share requests` and publish those to the P2P network.
The fee share request contains:
- Signature 
- IssuanceTxId (from there the EC pubKey can be derived, needed to verify the signature)
- The L-BTC address

Signing uses the private EC key of the issuance tx and the L-BTC address is the message to get signed.

Any DAO node can verify that the signature is correct.
This fee share request will be used in the Bisq 2 network (if DAO is integrated the verification can be done there by any node, otherwise we need a trust based data transfer solution).
When traders trade LBTC-USDT (or other assets) they pay a fee to one of the fee share request members according to a weighted probabilistic distribution.
If traders trade assets not containing LBTC we can consider to add another major asset address as well (e.g. USDT).
I guess confidential tx can be used so the fee amount is private. 
The fee receiver is still not private as it is linked to the issuance requesters identity.

**Comment by clearwater-trust** [comment]
Please define L-BTC

I guess confidential tx can be used so the fee amount is private.

What is a confidential tx? 

Thank you.

**Comment by chimp1984** [comment]
L-BTC is Bitcoin on Liquid
https://docs.blockstream.com/liquid/technical_overview.html

**Comment by chimp1984** [comment]
Closing in favor of https://github.com/bisq-network/proposals/issues/359
