### ISSUE TITLE
Increase altcoin trade size limits to 5 BTC

### ISSUE THREAD

**Issue by pazza83** [bisq-network/proposals#361]
The below is something I have thought about a while ago when considering ways to increase trade volume. Seeing how large trades have been reimbursed in BSQ without incident I thought it would be a good time to have a discussion around trade size limits for altcoins.

## Background

All altcoin trades on Bisq currently have a [2 BTC limit](https://bisq.wiki/Payment_methods#Altcoin_payment_methods).

Running the numbers on the most popular altcoin in Bisq by volume, XMR, there were 4,399 trades in 2021 for a total of 1,862 BTC.

625 of the XMR trades were for 2 BTC. This means 14.4% of XMR trades were for the maximum amount.

This data was pulled from the Bisq app > Markets > Trades.

## Problem

My hypothesis is that increasing altcoin trade limits have a positive correlation to trade volume. 

Therefore, I hypothesize that by limiting altcoin trades to 2 BTC Bisq is suppressing altcoin trading volume.

## Outcome

Increase trade volume on altcoin markets

## Solution

Increase altcoin trade limits to 5 BTC.

I have no reason for choosing 5 other than if implemented it can be used to reflect on the hypothesis that increasing limits increases trade volume.

## Risks

As I understand it altcoin limits are put in place to protect the DAO should any adverse security incidences occur. By its nature larger trade volume equals more risk. I would like to see Bisq trade volume increase over time, so I accept that this will bring with it some risks.

There is also some risk posed at arbitration, user error etc. I think some of the risk posed by arbitration is partially mitigated in the following by @refund-agent2 only refunding traders up to 0.5 BTC, any refunds above this are paid out in BSQ and have to be voted on by the DAO.

## Risk Mitigation

Maybe signing for altcoins?

Maybe once a user has completed a 2 BTC trade their account is signed and then 30 days later they can complete trades for up to 5 BTC?

Also hopefully there would be additional revenue generated to consider other ways risks could be mitigated.

**Comment by chimp1984** [comment]
I see the risks higher as the benefits from it. 2 BTC is already a lot of money.

**Comment by MwithM** [comment]
In the past I wanted to reduce the limit, now I don't see much difference on what the limit is, because a trader can open as much orders as they need. MIning fees, when trading 2BTC, are not a considerable cost.
This 2BTC limit increases with bitcoin value as numbers go up.

**Comment by pazza83** [comment]
Closing as was rejected
