### ISSUE TITLE
Bisq 2 Reputation Protocol/ Social User Research

### ISSUE THREAD

**Issue by UX-P** [bisq-network/proposals#362]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I am proposing to carry out user research based on the Bisq-2 reputation protocol in order to optimise the user interactivity of this project. Due to its high level of complexity, it is essential to have a good combination of functionality and design in order for Bisq 2 to reach its users effectively.
To best tackle areas regarding security and usability there must be a good understanding of user expectations, desires and needs technically, logistical and humanly.

**Objectives:**

- Have discussions with users via social media, forming questions based on the users thoughts regarding interactivity on trading platforms.

- Reach out to potential users of the Bisq 2 reputation protocol and current users of Bisq to clarify a variety of processes that may directly or indirectly affect the UX design.

- Continue to build on the User Flow diagram for Bisq 2, accurately mapping out the user journey to help determine the information architecture. 

- Research 2 or 3 potential competitors/alternatives and their key market features to pinpoint any strengths and weaknesses. 

- Analyse survey results for a UX report analysis summarising findings and common factors.

**Deliverables**

(Identities will be kept anonymous from any of the deliverables)
Similar to my previous  #349 I will deliver: 

- 3 user profiles: The reputable trader, the new trader and the regular trader derived from qualitative research. 

- A competitive analysis summary to gain a clear vision of the Bisq 2 USP and open up to other considerations where users' needs are yet to be met.

- An anonymous survey aimed at potential users of this protocol, based on the main 3 target markets.

- UX Report analysis on potential users and current users of the chat feature, referring to how these findings contribute to the Bisq 2 reputation protocol. 
Also including a summary of the survey results providing insights and solutions to current issues and help to tackle any future UX problems that may occur.

- Bisq 2 SWOT analysis, this involves the Bisq contributors, developer etc. you can all provide your input on Bisq’s  Strength,Weakness, Opportunities and Threats and I’ll turn this into a document.

**Outcome:** 

- To gain a clear user perspective of the reputation protocol in order to create a simplified user journey experience. 

- To have identified the potential initial reputable traders, in order to effectively plan the next expected steps regarding this status. 

- To have identified key user pain points to better find solutions which ensure that the UX and UI has a highly user focused design. 

- The promotion of a more human experience with decisions based primarily on user feedback.

If accepted, let me know if there’s anything else anyone would like me to look into regarding this.

**Comment by chimp1984** [comment]
@UX-P Great thanks for the proposal!

> Research 2 or 3 potential competitors/alternatives and their key market features to pinpoint any strengths and weaknesses.

There are several messanger app based OTC trading channels (e.g. Telegram, Whatsapp,...). I looked a while into some but was very disappointed about UX and scam level. But this type of trade interaction was one inspiration for the social trading project. The main problems I saw was total lack of security, difficulty to find trusted peers and a very high level of scam risk. One felt like in a dark street in a shady town expecting every minute to get robbed... 

Othere general comments: 
The social trading concept targets mainly new users (not familiar with Bisq). I expect that existing Bisq users will not see much value in it as it has lower security and privacy and higher trade prices. 
I think we need to take care to not try to target the typical Bisq user as that would render that concept to become more similar to other more security and privacy focussed protocols which comes with higher costs on usability and convenience and with that we would lose the core goal of that project that its super easy and sufficiantly safe for a newbie to get BTC.

Another important aspect is the economical part.
According to feedback from Keybase BTC sellers usual amounts are 100-200 USD and price premium 10-15%. Montly volume likely below 10k USD. I am not aware of any scam or bigger problem. There was no mediation support on the Keybase channels.
So we cannot expect too much of a trade volume. We need to find the right balance on costs for the DAO (mediators, channel moderators) and revenue (BTC sellers who pay with burned BSQ the fee). 
Though if the social aspect works out well it could be still beneficial for Bisq even if the costs are exceeding the revenue as it serves for onboarding to normal Bisq trade protocols as well it can attract newbies for getting into BTC and Bisq.

**Comment by UX-P** [comment]
Thanks for the feedback @chimp1984 

> One felt like in a dark street in a shady town expecting every minute to get robbed…

I’ll have to explore this a bit more, wish me luck...

> The social trading concept targets mainly new users (not familiar with Bisq).

It’s definitely a good decision to remain niche for this protocol, it helps to simplify the UX process. I say this because It is essential for this particular protocol to be a pleasant experience for a new trader. This is a field that could potentially be brand new for the user and Bisq has a responsibility in guiding them through a simple, well informed, satisfying journey, especially with security being slightly volatile.

> So we cannot expect too much of a trade volume. We need to find the right balance on costs for the DAO (mediators, channel moderators) and revenue (BTC sellers who pay with burned BSQ the fee).

Marketing also plays a key part here, this protocol offers a solution to a real-life problem which makes the concept increasingly valuable and could potentially attract a wider audience.

Considering the target market, here are the type of users I will be predominantly communicating with: 

- Users that have heard of bisq and trying to get started on Bisq, this is typically the keybase user

- Users who have never heard of bisq before and do not have BTC but have had an interest in buying BTC however, have not yet taken the plunge.

- Users who have other cryptocurrency and would like to add BTC to their portfolio and bypass the bisq deposit scheme. These users are less interested or more wary of trading on Bisq 1 and who I labelled as the ‘medium’ or ‘regular’ trader. It could be a learning experience for this type of user and may increase conversion rate, (in this context conversion would be the user going from Bisq 2 and eventually completing a trade on Bisq 1) so it might be worth exploring. 

I will also be initiating talks with Bisq contributors about their current roles to help gain a better insight of the potential responsibilities, rules and improvements that should be considered for the roles required in the reputation protocol.

**Comment by chimp1984** [comment]
> I’ll have to explore this a bit more, wish me luck...

Haha... don't risk real money ;-). I did not found anyone who has any meaningful security suggestions. They basically said "I am a company" so trust me, or look at my reputation on the chats...

> Marketing also plays a key part here, this protocol offers a solution to a real-life problem which makes the concept increasingly valuable and could potentially attract a wider audience.

Yes you are right. Potential is probably much bigger as what we saw from keybase trades.

> I will also be initiating talks with Bisq contributors about their current roles to help gain a better insight of the potential responsibilities, rules and improvements that should be considered for the roles required in the reputation protocol.

Maybe @pazza83  has some inputs here.

**Comment by pazza83** [comment]
Hi @UX-P

We spoke recently about the mediator role and also discussed a little of the upcoming reputation protocol.

Here are some of my thoughts about the reputation protocol and the ideas to date.

**Strengths / Positives** 

- I see having a protocol inside Bisq 2 for users to acquire no kyc BTC as vital
- I think small trades with no security deposit as feasible
- Off-chain trades = lower fees. Important for lower value trades
- Encourages social engagement and builds community
- Keeps users on platform for more types of trades
- Reputation system is a good proxy for confidence of small trades being successful
- Mediation being amiable for when things go wrong provides some peace of mind for buyer and sellers

**Weaknesses / Negatives** 

- Reputation brings with it privacy concerns. I think this fact alone would make me unlikely to want to be a seller in a reputation protocol. That being said there are plenty of traders that would not mind. Most P2P platforms are reputation based and the traders there must be happy to trade knowing their privacy is somewhat compromised.
- Increased risk of new traders mentioning things they should not on fiat payment references (Bisq, bitcoin, etc). No security deposit means less accountability for buyers?
- Increased risk of new traders mentioning things they should not on feedback references (Thanks XXXX it was great trading with you).
- Small amount of return from trades for experienced users supporting new users to successfully onboard. Especially when taken into account potential risks (above) and fees (Channel owner burning BSQ, traders burning BSQ)

**Rules**

Principles should be in-keeping with current rules:

- Promoting good behavior from traders
- Penalizing bad behavior from traders
- Promoting good payment accounts of traders
- Penalizing bad payment accounts of traders
- Put the 'wrong doer' in a worse position and the person 'not at fault' in a better position

Specific rules to consider:

- Both parties acknowledge their are increased risks using reputation protocol. It is very much buyer and seller beware; No refunds, No arbitration, No DAO compensation requests
- Each trade should be a maximum of 0.01 BTC
- On acceptance of trade buyer should send payment immediately using the agreed payment method
- BTC sellers should send payment within 24 hours of receiving payment
- Both buyer and seller should collaborate with mediators as/when required
- Do not communicate off Bisq platform
- Buyers should leave reason for payment empty

**Improvements**

- Mediators should suggest a penalty when things go wrong. Eg buyer sends partial payment, seller sends BTC late. Sellers will need to accept that there would be no way to penalize a seller that does not complete a trade / goes AWOL.
- BTC Seller should have a BSQ bond to ensure they adhered to trade rules
- BTC Seller fees should be based on their trade volume
- BTC Sellers should be able to blacklist onion addresses / users they do not want to trade with

**Comment by UX-P** [comment]
@pazza83 thanks for the summary above and the insightful discussion on helping me to gain a better understanding of the current mediator role. Feel free to share your thoughts and feedback on this [Support Agent summary  ](https://github.com/bisq-network/bisq/discussions/6011#discussioncomment-2261898) for Bisq 2 :)

**Comment by pazza83** [comment]
Closing as approved.
