### ISSUE TITLE
Discontinue tor relay operator role

### ISSUE THREAD

**Issue by Emzy** [bisq-network/proposals#363]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

We support the Tor network right now with 4 Tor relay nodes with a total for 19.06 MiB/s advertised bandwidth.
My proposal is the discontinuation of the tor relay operator role.
I would argue that the traffic from the Bisq Network alone is a net positive for Tor, better anonymization for all.
AFAIK there is no bandwidth problem in the Tor network. Also 19Mbit/s is not really much.

I would prefer to discontinue the role before we starting to expand it.
There are new people who would like to run tor nodes for Bisq. I think this gives the wrong incentives. It would be better to get people run services direct for Bisq, instead of indirect services. 
See relay operator role: https://github.com/bisq-network/roles/issues/72

An option to additionally support Tor would be to tell our users to run a bridge if they can.
There seems to be a need for Tor bridges at the moment.

I would like to ask the DAO for the final decision on this.

If you support this proposal to discontinue tor relay operator role, please up vote the DAO proposal, otherwise down vote it.

**Comment by Emzy** [comment]
A discussion on this proposal is appreciated.

**Comment by chimp1984** [comment]
I have no stroong opinion, but one option would be to have a limited budget we are willing to spend on that? I think it gives the right signal that Bisq DAO is funding some tor nodes as we heavily depend on Tor.

**Comment by bisqubutor** [comment]
> An option to additionally support Tor would be to tell our users to run a bridge if they can.
There seems to be a need for Tor bridges at the moment.

I had started to operate some bridges about two months ago, until today, not many users have found themselves on them so far no significant use.

http://hctxrvjzfpvmzh2jllqhgvvkoepxb4kfzdjm6h7egcwlumggtktiftid.onion/rs.html#search/bisqubutor

**Comment by sqrrm** [comment]
I think it's a good thing for bisq as a project to support some tor nodes. It's right to support it since bisq depends on the tor network, at least for now, and it also shows other projects that it can be done.

I'm quite happy to retire my nodes though and let some more experienced ops ppl run better nodes.

**Comment by Emzy** [comment]
edcd47dc4c3e8acca56b81740b4acc8fcd37a7960ec4cbfa7af036a6208ab995

**Comment by pazza83** [comment]
This proposal was accepted by DAO vote in cycle 33
