### ISSUE TITLE
Allow maker to restrict offer to takers with specific account age/signing status

### ISSUE THREAD

**Issue by w0000000t** [bisq-network/proposals#364]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

First of all, I feel this has a place among proposals, rather than in "feature ideas", as it's a significant change from the current model of "taker/maker selection", and because it could imply some network validation, rather than just using single clients to filter counterparties; this comes from [today's support call discussion](https://github.com/bisq-network/support/issues/916#issuecomment-1034033469).

This has been requested in two separate occasions that I can personally report about, on telegram and matrix: users would like to make their offers be takeable only by someone who has a signed account, aged at least N days; additionally, purely as a convenience (as it could still be done "manually") it might be made possible, for prospective takers, to also filter offers by same criteria.

One reason I found quite compelling for this, is to reduce (as eliminating it wouldn't still be possible) the risk of dealing with someone who sourced their funds in dubious ways, or is using a payment account that has been acquired with the same former dubious ways... ending up tainting your own account if you deal with them; naturally, someone who trades on Bisq with a "compromised setup" is more likely to not last long, so the likeness of such encounters decreases with the age of an account.

Currently, there is a workaround for this, consisting in making offers slightly above the unsigned limit, yet this implies a few shortcomings:
 - it is only available to seller makers, as buyer makers could have anyone take their offer, even someone with an account created the minute before
 - the maximum age it is possible to filter for in this way, is 60 days, as all limits would be lifted after two months (one user specifically asked for "signed since at least 100 days")
 - as duly noted by @MwithM, the general idea of filtering buyers by setting sell amount to "just above 0.01BTC" is in itself a limitation, as today even one cent of a Bitcoin is still a considerable sum

**Comment by MwithM** [comment]
This proposal was already discussed:
https://github.com/bisq-network/proposals/issues/133

Apparently it's possible, I wish there was a way to simply implement it now, but I feel this will need to wait for Bisq 2.

**Comment by w0000000t** [comment]
Checked out that thread, yes it's got some points in common with this request, the present one being more granular IMO.
I also supposed as much  with Bisq2, and actually as of now I always consider my mind time frame as "post-Bisq2" for any feature requests, as it's clear the priority is getting Bisq2 to replace Bisq first, then build on it.
Might as well leave this open for when it can be taken into consideration :)

**Comment by MwithM** [comment]
Yes, opening it was ok, so at least it's considered for Bisq 2.
I hope that at Bisq 2 this kind of changes are more flexible.

**Comment by pazza83** [comment]
Thanks @w0000000t for this proposal.

I agree that it would be good as a taker to filter offers by age / signed status, and as a maker restrict offers by age / signed status.

**Comment by pazza83** [comment]
Closing as stalled.
