### ISSUE TITLE
Have a clearly defined process for how users with accepted DAO reimbursement requests can trade with Burning Man

### ISSUE THREAD

**Issue by pazza83** [bisq-network/proposals#366]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

## Background

About 12 months ago @refund-agent2 started to [partially reimburse high volume trades](https://github.com/bisq-network/proposals/issues/296).

This was done to reduce the risk of human error (eg https://github.com/bisq-network/roles/issues/93#issuecomment-659568163) and the potential for bugs in Bisq (such as https://github.com/bisq-network/bisq/pull/5649) to affect payouts.

This meant that traders in arbitration with refunds greater than 0.5 BTC needed to approach the DAO for compensation. Recent examples of users that have been accepted for reimbursement are:

| User  | Issue | BSQ payout|
| ------------- | ------------- | ------------- |
| @wildduck379  | [1042](https://github.com/bisq-network/support/issues/1042)  | 64,000  |
| @polygonk  | [1044](https://github.com/bisq-network/support/issues/1044)  | 39,331.37  |
| @rtgeek  | [1041](https://github.com/bisq-network/support/issues/1041)  | 26,238.11  |
| @Akira45-0  | [908](https://github.com/bisq-network/support/issues/908)  | 27,426.69  |

## Problem

Currently there is no consensus on:

- If users that have been reimbursed in BSQ can trade with burningman
- How users that have been reimbursed in BSQ can trade with burningman

Of the users above it appears that at least one, @Akira45-0, traded with burningman judging by the [comment](https://github.com/bisq-network/support/issues/908#issuecomment-846414138) they posted.

For the other users I know I have personally supported @wildduck379 who concerned about how they would be able to realize a fair price for their BSQ in a reasonable time frame.

The issue has also lead to some perceived unclarity about how long funds in the donation address should be kept before being traded.  Reference; read comments from https://github.com/bisq-network/roles/issues/80#issuecomment-1046334613 downwards.  

The issue of partial reimbursements is also not documented anywhere in the Bisq wiki AFAIK.

A lack of consensus around this issue can lead to the following problems:

- Build up of funds in the donation address - risk to the DAO
- Disgruntled users, being surprised to be reimbursed in BSQ, and then frustrated when they are unable to trade at large volumes to BSQ/BTC prices similar to that on their reimbursement request.
- Uncertainty around the reimbursement process putting off people making large trades (> 0.5 BTC) on alt coin markets (XMR and ETH)
- Currently the donation address is responsible for a significant volume of the BSQ market. Not using BTC in the donation address means a lack of BSQ buying. A lack of BSQ buying leads to a downward pressure on BSQ price (even if only for a short term).

## Outcome

I see the principle of this proposal as the trader should have the option to be reimbursed in the same amount of BTC as per their arbitration summary. 

A good outcome would be:

- Decrease risk to the DAO by not having donation address funds build up to high levels.
- No surprises for traders when they are reimbursed in BSQ
- Traders to be given the opportunity to trade with burningman at a BSQ/BTC prices that is the same as their reimbursement request. Therefore the option to get the reimbursement in BTC rather than BSQ.
- Certainty around the reimbursement process making traders more comfortable to make trades > 0.5 BTC.

## Solution

I propose that their is a clearly defined process around reimbursement.

- How users that have been reimbursed in BSQ can trade with burningman

### Principles:

- Reimbursed traders should have the option to be reimbursed in the same amount of BTC as per their arbitration summary. 
- Reimbursed traders should be able to trade their BSQ with burningman

### Process:

- Should the trader want to trade with burningman directly they have 2 cycles following their arbitration summary to make a reimbursement request. If they make a reimbursement request after 2 cycles they will forfeit the option to trade directly with burningman.
- Once the trader that has had their DAO request for reimbursement approved they are pointed to instructions as to how to trade with burningman
- @refund-agent2 is responsible for advising trader about the above process at the earliest possible stage, informing the trader about putting in a reimburment request within 2 cycles, and making the connection between the trader and burningman once DAO has accepted it.
- The trader has 1 cycle following reimbursement to trade with burningman for the exact BSQ/BTC price as in their proposal. This will mean they end up with the same amount of BTC as per their arbitration summary. 
- Should the trader not trade with the burningman within 1 cycle they will not be able to trade with burningman directly and will instead have to sell BSQ on the open market in Bisq.

### To Do:

Should this proposal be accepted I will do the following:

- Create a new Github template for traders seeking partial reimbursements.
- Update the relevant pages in wiki, and create a new one if requires, to explain to users what happens during arbitration when payouts are over 0.5 BTC

## Expectations 

Should this proposal be accepted these are the additional expectations of the parties involved:

### Expectations of trader:

- Trader must raise reimbursement request within 2 cycles of final arbitration date
- Should the reimbursed trader wish to trade with burningman for the BSQ/BTC price given in their reimbursement request they must do so within 1 cycle of their request being accepted.

### Expectations of refund agent:

- Advising trader about the process at the earliest possible stage
- Inform / support the trader about how to make a reimburment request within 2 cycles
- Once reimbursement has been accepted by the DAO make the connection between the trader and burningman.

### Expectations of burningman:

- Communicate with refund agent about upcoming reimbursements and their amounts to ensure they have enough BTC in the donation address for trades with trader that have been partially reimbursed.
- Verify trader that is requesting trade is affected user.
- Report on trades that were done as partial reimbursements as part of their regular cycle reports.

## Risks

This proposal would create the following risks:

- Extra people for Burningman to communicate with. Maybe communication could be done via Refund Agent or Mediators as a proxy to avoid them communicating directly with traders.
- Potential for option trades. Traders could have the option to trade with burningman for a fixed price or use market price. Might mean traders will take a fixed amount where BSQ prices falls, but reject the fixed amount when BSQ rises. I see this is risk as small and would be part and parcel of making a trader take extra steps to be reimbursed. If they end up getting a better price then so be it.

## Summary

The above is my proposal created in discussion with the support team. I think it would be great to add more clarity to the process around partial reimbursements and achieve the objectives above.

**Comment by w0000000t** [comment]
I don't see the second risk as a proper risk, just how the market works probably... with a hint of security for the reimbursed party on the side, which is what users need to feel safer.
In general I agree with this

**Comment by refund-agent2** [comment]
This issues were already discussed when I began as Refund Agent. I launched two proposals: [limit to 0.5BTC](https://github.com/bisq-network/proposals/issues/296) the reimbursements for each trade and [define prices for reimbursement](https://github.com/bisq-network/proposals/issues/294). They were approved without much discussion, but the conclusions weren't submitted to the Wiki.
I agree with the need to clarify and point to the wiki this process.

Traders have known they have the right to sell their BSQ to burningman since I always tell them as soon as I realize the amount is big. I find one whole cycle too much for trading with burningman, next one or two Sundays should be enough for trading in order to reach a smooth process and reduce option trading risk.

I have been [reporting](https://github.com/bisq-network/roles/issues/93#issuecomment-997368810) when traders are going to need a refund, but only sometimes I have been reported back that the trades have been really performed. As after each cycle I also get a reimbursement and need to trade with burningman, I think it's ok if I'm the one linking traders and burningman for this trades; i.e. sending a message to burningman with the offers to pick after traders announce me they're willing to sell their BSQ. 
Currently traders were talking directly to burningman.

As I stated in #294 I don't find that promising a fixed rate is the best deal, since any other DAO participants have to deal with volatility. I think it's much better to use 30 day average at the moment of requesting the reimbursement and  the 30 day average at the time of trading with burningman. Anyways, whatever it is decided, I think I should have the same deal as traders. Reimbursements are the same, the only difference is that I get a compensation and do it more often.

**Comment by pazza83** [comment]
> I agree with the need to clarify and point to the wiki this process.

Ok, following this proposal being resolved I will update the wiki.

> I have been https://github.com/bisq-network/roles/issues/93#issuecomment-997368810 when traders are going to need a refund, but only sometimes

Great, I have not spotted this.

> I think it's ok if I'm the one linking traders and burningman for this trades; i.e. sending a message to burningman with the offers to pick after traders announce me they're willing to sell their BSQ.

Agreed.

> Currently traders were talking directly to burningman.

> As I stated in https://github.com/bisq-network/proposals/issues/294 I don't find that promising a fixed rate is the best deal, since any other DAO participants have to deal with volatility.

My sympathies in this instance are with the partially refunded traders that have been forced to become DAO participants. I agree that DAO participants should expect volatility, but when a trader has only been partially refunded I feel the principle should be they are refunded in full.

> I should have the same deal as traders. Reimbursements are the same, the only difference is that I get a compensation and do it more often.

I would be in agreement that you should have the exact amount of BTC you paid out reimbursed.

**Comment by pazza83** [comment]
I have updated the [Donation Address Owner - Bisq Wiki](https://bisq.wiki/Donation_Address_Owner) to reflect the agreements in this proposal.
