### ISSUE TITLE
Add statement about "every BTC is fungible at Bisq" on the wiki

### ISSUE THREAD

**Issue by w0000000t** [bisq-network/proposals#375]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

As a follow up to an event unfolded in the matrix chatrooms, and dealt with in mediation, we felt a good idea to officially state what has been true on Bisq since practically forever, that is, we don't discriminate between utxos, and every coin is fungible on our platform.

This is a mock-up of what I think could be added in a prominent (to be decided) place of the wiki, to both make a clear statement of what Bisq represents, and also to set the policy to follow if any case of "unwanted utxo" complaint arises in the future.

> Other than a p2p trading platform, Bisq also represents a philosophy, and our philosophy goes against the settled policies of nowadays central exchanges.
> At Bisq, KYC is the illicit activity, every bitcoin is a bitcoin, and **every utxo is a fungible utxo**.
> We don't endorse users doing chainalysis on the BTC funds their peer places in the security deposit multisig, meaning that anyone is obviously free to do so, yet any trade cancel request originating from a trader refusing to deal with unwanted utxos, will be treated as any other unjustified cancel request, hence incur a [penalty](https://bisq.wiki/Table_of_penalties).

**Comment by MwithM** [comment]
I'm not even sure that this is a valid proposal, meaning that I don't see a relevant change on how Bisq works. From the [wiki](https://bisq.wiki/Proposals):

> Proposals are a way to suggest significant project-wide changes or new initiatives where a broad consensus of contributors, users, and stakeholders is desired. Smaller changes to existing components, infrastructure, or processes are generally best discussed in other channels (on Matrix, other GitHub repositories, etc). 

But as it's something that might be good to discuss, I find that all BTC at Bisq are valid BTC as long as they follow the Bitcoin protocol. I might have even stated something like that at Bisq's twitter Spanish account.
How to spread this is the difficult part. Having some lines about it in the Bisq introduction and somewhere else makes sense.

@clearwater-trust It shows good manners to comment why you disagree on a proposal. I could disagree on this one as being not valid, but we cannot know why you dislike it.

**Comment by w0000000t** [comment]
@clearwater-trust would you mind explaining your thumbs down?

Everyone: the penalty thing, is not by any means a "punishment", but rather just a consequence of canceling a started trade, as the cancel "because of tainted utxo" is not recognized a valid reason.
I am editing the OP to account for this, and try if possible to make the statement even shorter.

**Comment by clearwater-trust** [comment]
Thank you. I believe marking every bitcoin trade with a disclaimer about tainted, non-fungible, sanctioned, blacklisted, whitelisted, velvet utxo's on the transparent bitcoin blockchain is unnecessary and some kind of primordial spark (that Bisq should steer clear of)-- A TOS disclaimer nightmare of chain analysis back looking.   

ALL SALES FINAL. If they cancel the trade, they pay the fee.  No additional details necessary.

Traders that put faith in "chain analysis", utxo lists maintained and operated by the lizard people, are already excommunicated from our glorious religion.

Prayers to the righteous. Endure to the end. 

We should proceed as if their list(s) have no value.

**Comment by chimp1984** [comment]
I think that is not needed and just might add unwanted legal risk exposure. Also the "KYC is the illicit activity" statements is nice but might carry uncertain legal risks and it should be avoided to expose Bisq to such by adding it to any "official" resource.

**Comment by w0000000t** [comment]
> Thank you. I believe marking every bitcoin trade with a disclaimer about tainted, non-fungible, sanctioned, blacklisted, whitelisted, velvet utxo's on the transparent bitcoin blockchain is unnecessary and some kind of primordial spark (that Bisq should steer clear of)-- A TOS disclaimer nightmare of chain analysis back looking.
> 
> ALL SALES FINAL. If they cancel the trade, they pay the fee. No additional details necessary.
> 
> Traders that put faith in "chain analysis", utxo lists maintained and operated by the lizard people, are already excommunicated from our glorious religion.
> 
> Prayers to the righteous. Endure to the end.
> 
> We should proceed as if their list(s) have no value.

thank you for explaining, this is appreciated.
So yes, a true bitcoiner doesn't need to even state what's in the OP, it is obvious and arguably offensive to the intelligence of other bitcoiners to have to read it.
The user base of Bisq is very diverse though, and many buyers will start their noKYC journey without our prior "beliefs", I feel we should be welcoming to them, so they can be with the next ones.
The OP statement goes in that direction, to make sure everyone on Bisq is on the same page.

**Comment by Conza88** [comment]
"As a follow up to an event unfolded in the matrix chatrooms, and dealt with in mediation"

What exactly was discussed? '

How often has that been raised in the last several years?

**Comment by w0000000t** [comment]
> What exactly was discussed? '

a user complained the source for the security deposit of the btc they were buying, didn't pass their chainalysis test, as they didn't like the place that utxo came from, so they expected to cancel with no penalty. Canceling is always possible, but unless something in the rules has been violated by the counterparty, it will always come at a cost in the form of a penalty.

> How often has that been raised in the last several years?

I know of just this case. So I think we will not need to add a section in the wiki, at least for now.

**Comment by pazza83** [comment]
Closing as not sure it meets requirements of proposal and there is some disagreement
