### ISSUE TITLE
Increase BSQ trading fees to 0.5% of trade amount

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#379]
A review of trading fees is needed. Last change was in #365, more than 3 cycles ago.
Last increase in BTC trading fees seemed irrelevant either on total trading volume or ratio of BSQ usage (see comptroller [reports](https://github.com/bisq-network/roles/issues/111#issuecomment-1094508003)). Bisq should keep increasing trading fee % at a steady pace until total average trading fee reaches to the 0.8% target.

BTC trading fees will be kept at 1% while BSQ trading fees will be increased to 0.5% from current 0.4% level if DAO change parameter proposal is approved. The long term goal is to keep the 50% discount for BSQ trading fees, so next time both BTC and BSQ trading fees will be increased, probably to 0.55 and 1.1%.

**Comment by pazza83** [comment]
I agree, the last three cycles 'Total fees paid as a percentage of revenue' with BSQ at a 60% discount are:

- 0.63%
- 0.66%
- 0.65%

Reducing the BSQ discount back to 50%? will get the 'Total fees paid as a percentage of revenue' closer to the [0.8% goal](https://github.com/bisq-network/proposals/issues/365).

I will monitor over the next few cycles once this change takes effect.

**Comment by MwithM** [comment]
## Cycle 38
**Parameters** ([see issue](https://github.com/bisq-network/proposals/issues/289))
* USD/BTC price: 23200
* USD/BSQ price: 0.81
* Current BSQ discount: 64.3% 

![image](https://user-images.githubusercontent.com/50149324/183264465-ab798ffe-a398-41ad-a53f-338c51067feb.png)
![image](https://user-images.githubusercontent.com/50149324/183264475-16825360-4099-4b4d-87b2-2db040e821d0.png)

It's **necessary to update** BSQ trading fee as current discount is not between the 45-55% target.

### New BSQ trading fees
A change parameter request for BSQ trading fees will be submitted to DAO voting:
New BSQ maker fee: `17.19` BSQ per BTC.
New BSQ taker fee: `126.02` BSQ per BTC.

BSQ trading fees are calculated using the values proposed at https://github.com/bisq-network/proposals/issues/365.
Discount target is 50% and fees should be adjusted to exactly 50% every cycle if they are not within the 45-55% range.

**Comment by MwithM** [comment]
Maker: f9896911af82ba4e542454f3036948ad071273e2ae897bdb7513556c8947d4b3
Taker: 6dbb76aa73848cabd21408948f2e44bde51c618cd74871dac7d5397016918360

**Comment by MwithM** [comment]
Closed as approved.
[Trading fees](https://bisq.wiki/Trading_fees) wiki page has been updated.

**Comment by ripcurlx** [comment]
Filter was updated.
