### ISSUE TITLE
Application for Github Admin Role

### ISSUE THREAD

**Issue by gabernard** [bisq-network/proposals#382]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

Hello! I would like to become a Github Admin.

**Comment by gabernard** [comment]
f22a084457a2632a25b746b6a690360c8083fb82322b58a311079b690b42840c

**Comment by pazza83** [comment]
Hi @gabernard welcome to being a Bisq contributor. Your proposal to be a Github Admin was accepted by the DAO in cycle 40.

Please see below the process for what happens next now your proposal has been accepted: 

https://bisq.wiki/Roles#Processes
