### ISSUE TITLE
Distribute the funds from the delayed payout transaction to contributors

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/proposals#385]
## Overview
We propse to distribute the funds from the delayed payout transaction (DPT) to the contributors who have been active in the past 1.5 years and who have earned more than 500 BSQ (per compensation request). We distribute the output value based on the weight of the accumulated contribution request amounts. Contributors who have worked more wil receive more. As the number of those items is probably lower than the max. possible outputs we can add all of those, so each DPT will get distributed to all potential receivers.
This allows to remove the role of the burningman.

## Details
In the current trade protocol the seller creates the delayed payout transaction using the DAO parameter entry and the buyer verifies that the address is burningman (BM) address or one of any past DAO param entries.

We propose to change the output of the DPT to multiple addresses of contributors similar like in https://github.com/bisq-network/proposals/issues/383.

There are a few differences to the fee distribution model though. As the receiver addresses need to be verified by the trade peer we need a deterministic selection model instead a random number generator as used in the fee distribution model.
The seller will create a nonce and use that together with the onion addresses of both traders (maybe we can use tx data of both traders as seed as well) for the selection. It will pass that nonce to the buyer so they can make the same selection using the same set of inputs for the selection seed. It is required that both have the same DAO data and have the DAO state in sync. To avoid failed trades with lost fee payments from issues with DAO sync state, the taker sends their hash of the issuance set to the maker and if it does not match the maker will reject the take offer request. If it matches both traders will keep a copy of that issuance set in memory to be used later when creating and verifying the DPT. That way we can be sure they will not fail later even if we just got a new block from the result phase with new issuance data in during the short time frame of the take offer process.
If the take offer fails because of mismatching hashes, the user will get a popup displayed to resync their DAO state. I guess that should be already in place anyway that the app detects globally if the DAO state is out of sync. 

To number of outputs are limited by the max. tx size but more importantly by the number of CRs, which is about 300. With excluding low amount CRs (as discussed below) we might get even lower number of CRs, say 200.
If we add the max number of say 200 CRs to each DPT the weighted distribution would have no effect anymore. We could use weighted outputs, so all 200 are used but depending on the weight the values will be defined. 

## Risks
There is a slight risk that contributors could abuse the model to gain from received funds. We will discuss here some potential cases and how we mitigate them.

1. A major contributor with a relative high weight can try to take all sell offers let them fail and try to benefit from the received delayed payouts

Lets assume one contributor has 20% of overall weight of their accumulated compensation requests (CR). They have 20% chance to receive the funds. 
Lets assume a 1 BTC trade and 15% security deposit. As buyer/taker they will lose 15% (0.15 BTC) when the arbitration case will be decided against them. They can earn 20% (20% of 1.3 BTC = 0.26 BTC) from the DPT. So it would be profitable to do that attack. 
It is important that the min. security deposit cannot be lower than a certain %. Depending on the CR weight of the contributor it still could be a profit but we have to take into account that a major contributor would earn much more with a successful Bisq and receiving long term fees and DPT outputs rather than to do such a scam which could cause severe problems for Bisq making Bisq potentially less profitable. It is similar to the 50% attack scenario of DAO stakeholders. Also it is very unlikely that someone who worked that much on Bisq to have such a high weight would scam the very project they have helped to build.
Also if it would happen at scale it cannot be hidden as the receiver address is visible and points to the contributor. This would make the contributor a "persona non grata" for the DAO. 

2. Any contributor can make self trades (being seller and buyer) let them fail and try to benefit from the reimbursements in arbitration.
A variation of the above but that the funds are not stolen from the seller but from the DAO via reimbursement requests.
We must make sure that the winner in arbitration does not receive the peers security deposit, otherwise the scammer would get 100% of their loss reimbursed and then any small % chance of receiving the DPT outputs is a gain.
This risk seems to be higher as it would include any small value contributor. A scammer could try to make a small contribution to be included in the receiver list, makes many self trades and get a payout relative to their weight as profit.
To mitigate that risk we can exclude CRs below a certain value (e.g. all CRs below 500 BSQ are excluded). Scammers usually don't have the skillset for high value contributions, they might be able to do some text changes but such small value CR will never earn much BSQ. 
The arbitrator will also be alerted if they get more cases as usual. The arbitrator might request more details from the trader as normal which can help to avoid that the scammer can repeatedly receive reimbursements. If they lose just one case they might have more loss than gain, rendering the whole scheme high risk. Scammers usually don't want to take risk. It also require high investments where the money flows back with quite some delay. This limits the attack as well.

<strike>3. Try to game the selection mechanism to be included in the payout even if the probability is very low.
A contributor who had one CR with 500 BSQ could try to game the selection mechanism to be one of the receivers. This might make the first scenario above more risky. To mitigate that we can add a very high number of outputs thus reducing the individual output value.
A 1 BTC DPT with 100 outputs would result in about 0.013 BTC per output (about 250 USD). The lost 15% security deposit (0.15 BTC) would make that attack already a loss. The seller is doing the selection, so the scammer could not inject other addresses beside those in the CRs).
The scammer could try to take all sell offers und check if they are in the selection set and let the trade fail otherwise. But this happens after the taker fee is paid, so if the taker does not manage to not pay the taker fee they will have costs for each attempt. 
Even if they manage to avoid to pay the taker fee they would only gain in case they can earn at least 0.15 BTC, which would require a weight of about 11%, which is already quite a lot (about 50k BSQ), which brings such an attacker into the group of major contributors and the game-theoretical aspects discussed in case 1 apply.  
</strike> 
EDIT: This case is not relevant anymore as we will include all CRs as outputs, at least above a certain payout amount. Some parts might be still relevant but should get a new assessment once the implementaion details are more clearly defined.

<strike> 4. The seller who is a contributor could try out as many nonces until they get their own CRs included.
I think this cannot be avoided but there is not way to gain anything if the seller is not a major contributor. Lets assume a 1 BTC trade again. The seller selects a nonce to have their address included. With 100 outputs one output is 0.013 BTC. If they have done CRs every cycle its max. 18 outputs which results in 0.234 BTC. Letting the trade fail after having received the altcoin amount the seller will be even with the sell amount. They will lose the arbitration case and lose the security deposit which is 0.15 BTC. So they can gain 0.084 (about 1680 USD).
If they have less then 11 outputs (11 * 0.013 BTC = 0.143 BTC) they would not be able to gain from the scam. To manage to get more than 11 outputs selected by the algorithm is also a kind of proof of work, not sure how hard it is but likely that is not a prohibitive pow cost to protect against that. With excluding small amount CR we can reduce the risk again. A scammer would need to be active in Bisq for a long period which is already very unlikely for scammers and manage to get reasonable CRs over a long period. I guess in that context we can assume that this scenario is not a critical risk.
</strike> 
EDIT: This case is not relevant anymore as we will include all CRs as outputs, at least above a certain payout amount. Some parts might be still relevant but should get a new assessment once the implementaion details are more clearly defined.

To mitigate the above mentioned risks we need to have several parameters set right:
- Min. security deposit of 15% (is in place). 
- Winner in arbitration case does not receive peers security deposit. See https://github.com/bisq-network/proposals/issues/386
- Reduction of max. trade amount to a value below 1 BTC (I would suggest 0.25-0.75 BTC). See #387, #388, #389
- Exclude CRs below a certain value (suggest 500 BSQ)
- Use the max. number of outputs -> We will include all CRs for DPT above a certain amount.
- We weight the output value by the CRs weight

## Refund agent/reimbursements
With lower max. trade amounts the volume for reimbursements should be lower as well.
The refund agent (RA) trades currently with the BM to compensate them for the refunded BTC to traders. As the BM will be removed that process has to be done in the open market which adds more work and potentially higher costs due volatility and fees to the RA. Those drawbacks have to be compensated by higher compensation by the RA and therefore higher costs for the DAO. On the other hand the costs for the BM are gone.

I think currently traders who got reimbursed by the DAO can do coordinated trades with the BM at the same rate they got reimbursed reducing volatility risks and making the conversion of BSQ back to BTC easier for traders. This would become more work and adds more risks for traders if the BM is removed.
If the RA can take over all payouts to avoid that traders have to go the extra mile for getting their reimbursed BSQ converted to BTC in a less liquid market depends on the RA and the max. trade amounts. I think its an additional factor to reduce the max. trade amount more aggressively. I think it would be good that the RA can take over all trades as long the total volume is not exploding (which should be lower as now when reducing the max trade amounts). So we still could keep the option for DAO reimbursement for traders open but in normal cases the traders get the benefit to get reimbursed directly by the RA and the RA takes over the extra work and costs and delegates that to the DAO by compensation requests.

UPDATE:
Added some changes in relation to the number of CRs included. Initially it was assumes its a probabilisitic selection of a subset of CRs, but it seems we can add all CRs for those DPTs above a certain amount. Details will get added later once implementation has started to figure out whats the best model here.

**Comment by w0000000t** [comment]
Regarding the ignoring of CRs below 500BSQ, from a support agent's stance, as long as the BSQ value is this low, that will not constitute an issue; when BSQ value will go above 1.2USD for 600USD CRs, this will definitely constitute an issue.
A workaround could be to group CRs by skipping one cycle, so roughly every two months there will be a double-amount CR, which will be over 500BSQ.
Can it be argued that such a workaround would probabilistically deal the exact same contribution in BTC, in a 18 months span, as that of cycle-by-cycle CRs, where the 500BSQ bar was not in place? Missing this, the system would penalize long-term support agents.

**Comment by HenrikJannsen** [comment]
> Regarding the ignoring of CRs below 500BSQ, from a support agent's stance, as long as the BSQ value is this low, that will not constitute an issue; when BSQ value will go above 1.2USD for 600USD CRs, this will definitely constitute an issue. A workaround could be to group CRs by skipping one cycle, so roughly every two months there will be a double-amount CR, which will be over 500BSQ. Can it be argued that such a workaround would probabilistically deal the exact same contribution in BTC, in a 18 months span, as that of cycle-by-cycle CRs, where the 500BSQ bar was not in place? Missing this, the system would penalize long-term support agents.

Maybe that limit is not needed at all anymore. Will post soon an update and the risk scenarios to see if there are still risks.

**Comment by HenrikJannsen** [comment]
I started implementing it and a few details have changed to the initial description.

The taker sends the hash of the issuance list sorted by TxId to the maker at the offer availability request. The maker verifies if they have the same hash, if not the request fails.

At the first take offer message the taker sends again the hash as well as stores the issuance list in the trade process model. The maker again verifies and also stores the issuance list in the model for later use. 

The seller creates the DPT using the stored issuance list. They add all CRs above 500 BSQ and set the output amount according to the weighted amounts. We check then if there are outputs < 5000 sat (about 1 USD) and remove those. We do the output amount calculation again as now there might be less outputs.

The buyer verifies the DPT by creating it with the same algorithm and using their stored issuance list. 

By that implementation there is no selection nonce but we add all as long the output is > 5000 sat.
I guess we can remove the 500 BSQ limit, but will write up the open attack scenarios first to be sure.
One case we have to consider as well is a self trader who changed the code so they receive all the output themself. When arbitration is opened we need to verify if the outputs addresses are addressed from CRs.

### Some numbers:
With current live issuance data we get those results:
With a 2 BTC trade we get 203 outputs. Largest output is 0.16867102 BTC (3507 USD)
With a 0.25 BTC trade we get 195 outputs. Largest output is 0.0209077 BTC (434 USD)
With a 0.0001 BTC trade we get 2 outputs.

Fee with about 200 outputs is 0.00065468 BTC (about 15 USD) with 10 sat/byte fee rate.

**Comment by w0000000t** [comment]
> One case we have to consider as well is a self trader who changed the code so they receive all the output themself. When arbitration is opened we need to verify if the outputs addresses are addressed from CRs.

For added security, could it be possible to pass to the arbitrator the stored issuance list, and have arbitrator also build the DPT to verify it matches? I suppose it needs to be done in a trustless way though, since someone altering code would cover for that as well?

In general, while removing outputs <5000sats is undoubtedly a sane choice, as the cost for those at 10sat/vB would be 310sats amounting to at least 6% miner fee, I still see reason for long term but "simpler" contributors to be penalized in the end, unless the usual workaround of grouping CRs is implemented, and even that could generate competition between contributors as they could be incentivized to group CRs across three or more cycles, to make sure they get the largest CRs possible to "make it" into as many DPTs as possible.
But maybe I'm just overthinking this.

**Comment by HenrikJannsen** [comment]
> For added security, could it be possible to pass to the arbitrator the stored issuance list, and have arbitrator also build the DPT to verify it matches? I suppose it needs to be done in a trustless way though, since someone altering code would cover for that as well?

Yes thats an interesting idea. I need to look into the code to see whats the best option there.

> In general, while removing outputs <5000sats is undoubtedly a sane choice, as the cost for those at 10sat/vB would be 310sats amounting to at least 6% miner fee, I still see reason for long term but "simpler" contributors to be penalized in the end, unless the usual workaround of grouping CRs is implemented, and even that could generate competition between contributors as they could be incentivized to group CRs across three or more cycles, to make sure they get the largest CRs possible to "make it" into as many DPTs as possible.
But maybe I'm just overthinking this.

You mean to remove or lower the 5000 sat limit?
I guess the amounts are so tiny and DPTs are not happening that often, atm i guess 30/months. So I doubt ppl who fall into that limit would do much extra effort like bundling CRs to receive a few bucks... But nothing prevents them either from that. Volatility risks likely will eat up any potential gain or at least add more risks... But anyway, prefer to keep all at the min. complexity and don't see a reason to change that part. Maybe the 5000 sat could be lower or a bit higher... but I guess its a reasonable number.

For the 500 BSQ limit I need more time still but I am pretty sure we can remove that.

**Comment by pazza83** [comment]
> Fee with about 200 outputs is 0.00065468 BTC (about 15 USD) with 10 sat/byte fee rate.

Who pays the fee? Is it the taker at the time or taking the offer or is the fee taken from the amount in the multisig prior to sending to the contributors?

**Comment by HenrikJannsen** [comment]
Its taken from the MS output.

**Comment by w0000000t** [comment]
> You mean to remove or lower the 5000 sat limit?
> I guess the amounts are so tiny and DPTs are not happening that often, atm i guess 30/months. So I doubt ppl who fall into that limit would do much extra effort like bundling CRs to receive a few bucks...

I could be making wrong assumptions because I miss real case scenarios... it could be useful to have simulations, based on past cycles' CRs data, so it is possible to know, for example over a 0.01BTC DPT, how much of it would be weighted for every 100BSQ-worth of CR. It may be that less-than-5000sats payouts would be returned for very, very small CRs, making it a non-issue.

**Comment by HenrikJannsen** [comment]
Yes I can run some test with diff. setup to see what sat ouput are generated. But a 1 USD output with 30 cases/months results in total 30 USD, so not really a super relevant amount...

**Comment by HenrikJannsen** [comment]
Close in favor of a new proposal (will be published soon).

**Comment by w0000000t** [comment]
> Yes I can run some test with diff. setup to see what sat ouput are generated. But a 1 USD output with 30 cases/months results in total 30 USD, so not really a super relevant amount...

I wouldn't underestimate even 10USD per month, it's still more sats! 😄
