### ISSUE TITLE
Do not pay out the security deposit of the trade peer to the arbitration case winner

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/proposals#386]
At the moment the winning party receives next to its own loss also the security deposit of the peer (minus a arbitration fee in some cases). 
The proposal or removing the burningman would have more open risks is we keep that model. Therefore that proposal suggests to alter that model to not pay out the security deposit of the peer.

The details about the potential abuse scenarios where this aspect matters is discussed here: 
https://github.com/bisq-network/proposals/issues/385

I am aware of the motivation to give some compensation for the lost time and effort to the trader. But I think its better to reduce the risk from the suggested changes to remove the burningman. Also one need to take into account that such reimbursement is not typical. If there are troubles at any service (like a CEX blocking your payment) they usually never reimburse their clients for lost time, extra work, etc.

**Comment by pazza83** [comment]
Tangentially to this, maybe to potential reduce the number of non responsive peers taking cases all the way to arbitration maybe it would be a good idea to ban the onion addresses of non responsive peers post arbitration.

Should the above proposal be implemented non responsive peers would be even more of an inconvenience to traders using Bisq then they are currently.

**Comment by pazza83** [comment]
I am in favor of this should https://github.com/bisq-network/proposals/issues/390 be accepted.

I think that traders however should be able to claim back reimbursement for any mining fees / trading fees for these trades so they are not out of pocket. They could do this using the same process that is in place for failed trades.

**Comment by HenrikJannsen** [comment]
@jmacxx Would you be available for implementing the required changes in the arbitration payout screens?

**Comment by ghost** [comment]
Yes.

**Comment by refund-agent2** [comment]
I agree with the need of this proposal, but seeing that even after getting the security deposit some traders are upset, Bisq needs to explain why this is necessary a lot.

There are some trades that end into arbitration due to a bug or something else, where there is no winner. How should I proceed with those?

> Tangentially to this, maybe to potential reduce the number of non responsive peers taking cases all the way to arbitration maybe it would be a good idea to ban the onion addresses of non responsive peers post arbitration.

It wouldn't be very helpful, unresponsive traders don't use the same onion address. They must stop using Bisq after losing funds.

> I think that traders however should be able to claim back reimbursement for any mining fees / trading fees for these trades so they are not out of pocket. They could do this using the same process that is in place for failed trades.

I find this messy for traders. I consider the amount of trading and mining small enough to be reimbursed by refund agent, it would suppose a very low risk.

**Comment by pazza83** [comment]
> I agree with the need of this proposal, but seeing that even after getting the security deposit some traders are upset, Bisq needs to explain why this is necessary a lot.

Agreed, I think the wiki will need to be updated in quite a few places once the new trade protocol is in place to make this clear.

**Comment by pazza83** [comment]
> There are some trades that end into arbitration due to a bug or something else, where there is no winner. How should I proceed with those?

I think you should be able to use your discretion and refund the full amount if you feel it is appropriate to do so.

**Comment by exitramp505** [comment]
I've been using BISQ since Nov 2022 providing liquidity. I grew my liquidity to provide 3 to 4 open orders a day. On Feb 5 I had my first bad trade that needed full arbitration. It took 20 day of my BTC locked up with little to no explanation of the process. It was extremely difficult to figure out if the arbitration process was even moving forward as I was not aware o a small "arbitration" tab inside support. MY HOPE through this process is that I was assured that I would receive the losing parties' deposit. I CANT put up 15% minimum collateral for NO personal benefit it a trade goes sideways. I want to use BISQ but I cant continue when their so much upfront collatoral needed and absolutly no benifit to either party. Please let me know when this proposal is overturned.

**Comment by pazza83** [comment]
@exitramp505 

Thanks for the comments sorry to hear you had a bad experience.

What changes would you like to see to improve user experience and make you more likely to provide liquidity?

**Comment by MwithM** [comment]
The personal benefit of the security deposit is that it enables traders to exchange without knowing each other (reputation means less privacy), as it happens in more than 99% of the times, which is the frequency of arbitration in relation to total number of trades.
It was better for those who did right in case of arbitration because they received compensation, but this change is necessary because previously there was a huge single point of failure in the trading protocol. With burningman being distributed into multiple agents now Bisq is safer, which is a personal benefit for the network and yourself as well.

One way to reduce the harm of getting into arbitration would be to reduce the amount of time necessary until you're able to open it: https://github.com/bisq-network/proposals/issues/297
But it requires a hard  fork in Bisq and I don't think if this will ever be changed unless there is a high demand and it's clear that won't affect the safety in case of disputes.

**Comment by exitramp505** [comment]
The mediation process is difficult. BISQ does a good job with having pop-up boxes to help explain things. The mediation is like going blind. I didn't even know there was a difference between mediation and arbitration until yesterday. This is not clear to the user. As far as liquidity goes, I do not understand why there needs to be a security deposit for the liquidity provider. Who or what is that for if it doesn't go to the winner of the arbitration? Their security is the BTC they have locked up to make the trade. It is like there are all these hoops to jump through and in the end, if you go to Arbitration, there is Zero upside. The liquidity provider is taking WAY more risk than the buyer. 

My recommendation is either remove the security deposit for the liquidity provider OR return the winning arbitration reward.

**Comment by exitramp505** [comment]
> 

The mediation process is difficult. BISQ does a good job with having pop-up boxes to help explain things. The mediation is like going blind. I didn't even know there was a difference between mediation and arbitration until yesterday. This is not clear to the user. As far as liquidity goes, I do not understand why there needs to be a security deposit for the liquidity provider. Who or what is that for if it doesn't go to the winner of the arbitration? Their security is the BTC they have locked up to make the trade. It is like there are all these hoops to jump through and in the end, if you go to Arbitration, there is Zero upside. The liquidity provider is taking WAY more risk than the buyer.

My recommendation is either remove the security deposit for the liquidity provider OR return the winning arbitration reward.

**Comment by MwithM** [comment]
I agree that mediation and arbitration UI is not great, and there is a [project](https://github.com/bisq-network/projects/issues/67) to improve that, hopefully you keep using Bisq but don't need to see if it really improved often.

> As far as liquidity goes, I do not understand why there needs to be a security deposit for the liquidity provider. Who or what is that for if it doesn't go to the winner of the arbitration?

Instead of going to the one who wins the arbitration case, it goes to DAO contributors who have burned BSQ in advance. The security deposit is completely lost for the one who creates makes arbitration necessary, which is an incentive for them to accept mediation and at least keep a part of the security deposit.

Why can't you receive that security deposit as compensation?
Imagine that a burningman is both buyer and seller: if the burningman receives the full amount from the arbitrator, BTC distributed to the burningmen will be a profit for the burningman that created a fake trade, so more trades like this will be created only to scam the DAO.

**Comment by exitramp505** [comment]
I understand there is technical aspects to this. I do not understand what burningman is. 
I am also blind to how the back end work and who gets compensation but I will say this. BISQ is the most expensive P2P platform to use (This is not a criticism but rather an observation). 

I am just a user. I love Bitcoin and privacy. I barely know enough to keep BISQ up and running. All I have to say is I cant put up a bunch of BTC and have it stuck for 20 day with no beneficial outcome. At the end of the day it just doesn't make sense for the liquidity provider to take all the RISK and for the DOA to get all the reward.

**Comment by pazza83** [comment]
I agree the dispute process can be confusing.

Have you read the wiki about it here: https://bisq.wiki/Dispute_resolution

> As far as liquidity goes, I do not understand why there needs to be a security deposit for the liquidity provider. Who or what is that for if it doesn't go to the winner of the arbitration?

Most disputes are resolved in mediation and the security deposits can be used to penalize bad behavior in-turn compensating the other peer. For info see:  

- https://bisq.wiki/Trading_rules
- https://bisq.wiki/Table_of_penalties

> if you go to Arbitration, there is Zero upside

Yes, that is correct. Arbitration is meant as a last resort. 

I think Bisq would prefer for the users to be compensated if possible by the refund agent but doing so without opening up the risk of a user attaching the DAO by self trading cannot currently be protected against.

> My recommendation is either remove the security deposit for the liquidity provider OR return the winning arbitration reward.

Bisq 2, soon to be released, will remove the security deposits needed.

It would be great to return the winning arbitration reward but doing so would involve making changes to the trade protocol which might also add different downsides and risks.

> At the end of the day it just doesn't make sense for the liquidity provider to take all the RISK and for the DOA to get all the reward.

I agree this is the case when trades go to arbitration. Luckily only about 1% of trades end in arbitration. For cases resolved in mediation the trader in the right can be compensated from the trader in the wrongs security deposit.

**Comment by exitramp505** [comment]
Thanks for the information. I have previously read the wiki on Dispute resolution. I did not read the newest one as I was surprised not to receive the reward deposit. I was told by Leo in the Matrix Mediation chat that I would receive it. (mistakes happen. I don't hold it against Leo). The new WIKI does not show how to access the Arbitration chat. This was VERY confusing. 

Let me know when/if a new BISQ will have lower risk for liquidity providers. If I do two trades a day, at a 1% arbitration rate that means I will be in arbitration every month and a half and then have to wait 20 days for resolution. With those stats it is just not worth the headache. At the end of the day there has to be a balance between privacy, security and user friendliness. I humbly and respectfully present to you all that BISQ feels off balance. 

Thanks everyone who responded.

**Comment by onlymarcus** [comment]
What security do we traders have in providing 1 or 2 bitcoins in an offer knowing that if it goes to arbitration we could spend 20 days with the bitcoin locked up? Also receive only 0.5 BTC and the rest in BSQ. There is also the risk of receiving a blacklisted bitcoin. I send XMR and the counterparty sends me a blacklisted Bitcoin, when I deposit it in any broker I will have them blocked. This has already happened to me, I had to explain myself to the cybercrime department in Germany, and only after 4 months my bitcoins were released. I think that in mediation the winning party should receive 5% or 10% and in arbitration too, 10% or 15% at least.

**Comment by onlymarcus** [comment]
> I am aware of the motivation to give some compensation for the lost time and effort to the trader. But I think its better to reduce the risk from the suggested changes to remove the burningman. Also one need to take into account that such reimbursement is not typical. If there are troubles at any service (like a CEX blocking your payment) they usually never reimburse their clients for lost time, extra work, etc.

If a CEX blocks your money for a while, you can file a lawsuit for lost profits, and the judge will give you reason. As we are a community and not an independent broker, we must review this, and at least give compensation of at least 5% to the winning party.

**Comment by MwithM** [comment]
1 BTC trade with min security deposit 15% (0.15 BTC) and 5% of the trade amount as compensation for the winning party in arbitration would give a burningman doing a self trade 0.043 BTC as a reward, if they had burned BSQ to get the max share of 11% of the amount sent in the DPT. 
3.3% return in a couple weeks, with little risk.

So, if Bisq compensates the way you propose to traders, I promise that, being one of the burningmen, I'll begin to create fake orders myself before someone else does.

**Comment by onlymarcus** [comment]
> 1 BTC trade with min security deposit 15% (0.15 BTC) and 5% of the trade amount as compensation for the winning party in arbitration would give a burningman doing a self trade 0.043 BTC as a reward, if they had burned BSQ to get the max share of 11% of the amount sent in the DPT. 3.3% return in a couple weeks, with little risk.
> 
> So, if Bisq compensates the way you propose to traders, I promise that, being one of the burningmen, I'll begin to create fake orders myself before someone else does.

Sorry I did not understand.
Maker makes an offer, buys 1 btc for 150 xmr and deposits 1.15 btc.
Taker accepts the offer, deposits 1.15 btc.
Maker sends 150 XMR to taker.
Taker stops responding and loses 0.15 BTC
Maker earns 0.05BTC per compensation.
Final balance:
Maker 1.15 + 0.05 = 1.20
Taker 150 XMR = 1BTC
If it was a self trade, before the trades the trader would have 2.30 (1.15+1.15) BTC, and after the fake trades he would have 2.20 BTC.

**Comment by MwithM** [comment]
I place an offer to buy 1BTC. I place 0.15 BTC as security deposit.
I take an offer to sell 1BTC. I place 1.15BTC as security deposit.
I, BTC buyer do not send XMR. I disappeared. I, the seller, open arbitration.
I, as a burningman, receive 10% of the 1.30 BTC that have been sent to the burningmen. I could get 11% but I'm not that greedy. I get 0.13BTC
I, as a seller, receive the trade amount + security deposit + 5% trade amount as compensation = 1.20 BTC from the arbitrator.
I will have 1.33, adding up 1.2 from arbitration to 0.13 as a burningman. 
I win 0.03 investing 1.3, a 2.3% in 13 days.

**Comment by onlymarcus** [comment]
I think this idea of yours will bring down the price of the BSQ token. For example: Maker deposits 0.15BTC for a 1BTC bid for XMR. It sends the XMR to the taker, and the taker stops responding. The maker will only receive 0.5 BTC and the remaining 0.65 BTC converted into BSQ at the 30-day average price.
There is no longer a burningman who is the person who provided liquidity, so the maker will have to sell cheap to book buyers, losing money and lowering the BSQ. With each massive sale that happens, the price of the BSQ drops. We will only have large sales, we will not have large purchases to balance the price, this will make the price drop even more with each case that goes to arbitration.

**Comment by MwithM** [comment]
These are different issues:
I explained why it's not possible to compensate arbitration winners.
You're now commenting that with no burningman, there is noone to buy BSQ to reimbursed traders and arbitrator. I also have doubts about it, but theoretically, BMen still need to buy BSQ to burn them later, they're just not forced to do it.

**Comment by onlymarcus** [comment]
Purchases of BSQ to burn should be given priority to those who obtained a refund from the arbitration.
I was already at a loss, I received based on the 30-day average price and the price dropped, and I have to wait for someone to buy me. This is unfair.

My offer id:
Offer id's:
DRAOY-bcfe5a66-1060-4fa6-9ea6-981c6c13ffa6-199
GmRSp-6e4e1694-d673-46c0-88af-721e5d350689-199
UYYJD-d560e45d-57d6-4fa1-b5b6-528e9496e10d-199
857670-ee41573b-e5ab-4c40-81fb-32748b5991c6-199
465663-82e922cb-c18a-44be-a594-fafc9ecee400-199
qogv0e-51af96f8-3fb4-44dd-ad32-28f5b16c0162-199

**Comment by MwithM** [comment]
Offer ID's are not visible to those taking an offer. You could publish your onion address, I wouldn't do it here as generally, traders will only get best offers and that's how it should work.
There might be someone willing to help someone in your situation and preferring to pay a little bit more in order to help a forced BSQ seller. I would use matrix for that purpose.
Have you read #411? What do you think?

**Comment by onlymarcus** [comment]
> Offer ID's are not visible to those taking an offer. You could publish your onion address, I wouldn't do it here as generally, traders will only get best offers and that's how it should work. There might be someone willing to help someone in your situation and preferring to pay a little bit more in order to help a forced BSQ seller. I would use matrix for that purpose. Have you read #411? What do you think?

rcudj5a57z6bjvukydn4qdmyxvecnaqeuiz2s66fpk7kuooht3c5msyd.onion:9999
I received the BSQ at an average price of 0.00003596 and I couldn't sell it, today it's at an average price of 0.00003229. An 11.36% loss on 18,592.60 bsq. I was harmed by the XMR buyer that stopped responding. I think that BISQ should review this proposal of not reimbursing the maker. It is the maker that makes BISQ have offers and attract customers.
I would like priority to be given to offers to sell bsq from those who were harmed.

![image](https://user-images.githubusercontent.com/36059034/229367061-78532f32-9fbd-4ad9-b2a6-5e166cca0156.png)

**Comment by clearwater-trust** [comment]
I agree with @onlymarcus - Bisq should liquidate itself in _the attempt_ to make TRADERS WHOLE. Else, what is the point?

The unresponsive trader, we can fix this. We must fix this. Somebody buy this man's BSQ!

We cannot allow the unresponsive trader to beat us!

**Comment by pazza83** [comment]
Maybe another Refund Agent could be introduced.

Currently there is only one Refund Agent.

The reason for traders being partially refunded in BSQ is that the Refund Agent does not have an unlimited supply of BTC.

If there were two Refund Agents this would half the amount of refunds any one Refund Agent has to make, and hopefully end to practice of only partially reimbursing traders.

As big grows I think more than one Refund Agent will be needed to scale with Bisq's growth.

This would not fix the problem of not paying out the security deposit of the trade peer to the arbitration case winner (however [this proposal](https://github.com/bisq-network/proposals/issues/411) does go someway to addressing it), but it could end the practice of [only partially reimbursing high volume trades](https://github.com/bisq-network/proposals/issues/296).

**Comment by onlymarcus** [comment]
> Maybe another Refund Agent could be introduced.
> 
> Currently there is only one Refund Agent.
> 
> The reason for traders being partially refunded in BSQ is that the Refund Agent does not have an unlimited supply of BTC.
> 
> If there were two Refund Agents this would half the amount of refunds any one Refund Agent has to make, and hopefully end to practice of only partially reimbursing traders.
> 
> As big grows I think more than one Refund Agent will be needed to scale with Bisq's growth.
> 
> This would not fix the problem of not paying out the security deposit of the trade peer to the arbitration case winner (however [this proposal](https://github.com/bisq-network/proposals/issues/411) does go someway to addressing it), but it could end the practice of [only partially reimbursing high volume trades](https://github.com/bisq-network/proposals/issues/296).

Can this be proposed for voting in the dao?
Guys, I'm really hurt. I'm stuck with 18000 bisq that nobody wants to buy at the average price I got. I need bitcoins to continue my trades.

**Comment by onlymarcus** [comment]
> Maybe another Refund Agent could be introduced.
> 
> Currently there is only one Refund Agent.
> 
> The reason for traders being partially refunded in BSQ is that the Refund Agent does not have an unlimited supply of BTC.
> 
> If there were two Refund Agents this would half the amount of refunds any one Refund Agent has to make, and hopefully end to practice of only partially reimbursing traders.
> 
> As big grows I think more than one Refund Agent will be needed to scale with Bisq's growth.
> 
> This would not fix the problem of not paying out the security deposit of the trade peer to the arbitration case winner (however [this proposal](https://github.com/bisq-network/proposals/issues/411) does go someway to addressing it), but it could end the practice of [only partially reimbursing high volume trades](https://github.com/bisq-network/proposals/issues/296).

Since BISQ can only commit to refunding 0.5 btc per failed transaction, I propose lowering the BTC limit to be transacted from 2 to 0.5.
How can you allow a transaction with a volume of 2 bitcoins if you can't protect the merchant with 2 bitcoins, just 0.5? Shall we lower the maximum limit to 0.5?

**Comment by clearwater-trust** [comment]
Does the client offer a warning message for this dangerous scenario? Trades over .5 btc cannot be made whole- except through BSQ market.

How many trades do we have of this type? Greater than .5btc ? 

The risk seems to be a little more than our system can bare at this time. I agree we should only allow trades that Bisq can Wholesomely handle.

**Comment by pazza83** [comment]
> ince BISQ can only commit to refunding 0.5 btc per failed transaction, I propose lowering the BTC limit to be transacted from 2 to 0.5.
> How can you allow a transaction with a volume of 2 bitcoins if you can't protect the merchant with 2 bitcoins, just 0.5? Shall we lower the maximum limit to 0.5?

I think this would be a valid proposal.

I think it would be better for you to open it as a new proposal though to get more visability.

See the guide to proposal here: https://bisq.wiki/Proposals

**Comment by pazza83** [comment]
> Does the client offer a warning message for this dangerous scenario? Trades over .5 btc cannot be made whole- except through BSQ market.

No, it does not. I think a warning somewhere would be good. But my preference would be to avoid it by restoring full refunds. 

> How many trades do we have of this type? Greater than .5btc ?

Maybe a couple a month. You can check out DAO > Governance, and see the list of reimbursements in each cycle request.

> The risk seems to be a little more than our system can bare at this time. I agree we should only allow trades that Bisq can Wholesomely handle.

With the old trade protocol although traders were reimbursed with BSQ for trades over 0.5 BTC they always had the option to trade with the burningman as the same BTC/BSQ to be made whole in BTC terms. 

Changing the trade protocol means the BTC is distributed to multiple contributors. Therefore the burningman is not getting any significant amount of BTC (less than 0.02 BTC last cycle), and so there is no option for reimbursed trades to trade directly with them.

There seem to be a few ways this could be addressed. I agree it is something should be done as currently I feel reluctant to recommend Bisq for people that want to do trades over 0.5 BTC which seems like a shame.

**Comment by exitramp505** [comment]
What's the current status on "Arbitration Pay"? Is the liquidity provider still screwed? I haven't posted a trade on BISQ since Feb and wont until it's safe again for liquidity providers. I dont want to get screwed again. 
Since Paxful blew up people have been looking for a new place to buy/sell. I have not recommended BISQ yet until it's a fair playing field.

**Comment by MwithM** [comment]
If security deposit is over 17.5%, the peer who replies in arbitration will get a compensation of at least 1.5% of the trade amount from unresponsive peer's security deposit. 
https://github.com/bisq-network/proposals/issues/411

**Comment by onlymarcus** [comment]
> > ince BISQ can only commit to refunding 0.5 btc per failed transaction, I propose lowering the BTC limit to be transacted from 2 to 0.5.
> > How can you allow a transaction with a volume of 2 bitcoins if you can't protect the merchant with 2 bitcoins, just 0.5? Shall we lower the maximum limit to 0.5?
> 
> I think this would be a valid proposal.
> 
> I think it would be better for you to open it as a new proposal though to get more visability.
> 
> See the guide to proposal here: https://bisq.wiki/Proposals

[Proposal to limit trade size](https://github.com/bisq-network/proposals/issues/413)

**Comment by BarbzYHOOL** [comment]
so is it good or not? such a headache to understand all of this

**Comment by onlymarcus** [comment]
Only now after 10 months I managed to sell all the bsq at a loss. I opened two trades selling XMR. Two offers of 0.5 BTC on the XMR/BTC pair. Once again they took my orders, I paid the XMR and the trader stopped responding. Will I be harmed again after 10 months of trying to sell BSQ after a case like this? I should receive the 15% from the other party as compensation.
