### ISSUE TITLE
Reduce the max. trade amount for altcoins to 0.5 BTC

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/proposals#387]
Currently the max. trade amount for altcoins is 2 BTC. 

For improving the distribution of funds from the delayed payout transaction (see https://github.com/bisq-network/proposals/issues/385) and mitigating risks this proposal suggest a reduction of the max. trade amount to **0.5 BTC**.

There will be 2 more proposals with a higher and lower amount and the DAO should decide by voting which is the most acceptable. The winner will be selected by the highest accept % and if there are multiple with same value the highest stake put it counts. If also same stake values it can be further discussed to lower one will be selected.

This realtively high amount should have been reduced anyway long ago as it carries some risks and increase the burden for arbitration cases (as well increase risk there). The high amount was set in early days when BTC price was much lower and Bisq never adjusted that to equivalent fiat values. There was no good reason why that was not done earlier. 

Problems with high trade amounts:
- Risk if one manage to trick the trade protocol (happened once)
- Risk for arbitrator (and DAO) to make a wrong decision 
- Risk if both users lose their wallet/data directory
- Risk that new proposal how delayed payout is distributed gets abused
- More uneven/unfair distribution of trade fees with new proposal
- Overall volume in arbitration cases is higher and more volatile
- Potentially higher costs for the DAO from reimbursments and BSQ volatility
- Refund agent cannot refund high amounts. Trader need to do it themself which will be more painful with new [proposal](https://github.com/bisq-network/proposals/issues/385)
- Higher risk for trader to end up in arbitration with a large amount. Splitting a large trade in smaller ones distributes the risk to potentially multiple traders and by that lowers risk to trade with an unresponsive user which is the majority of reasons for arbitration.

Benefit of high trade amounts:
- More convenient for traders to do large trades. BUT traders can simply repeat some trades.

Consequences for open offers:
Open offer who have paid the maker fee for the 2 BTC fees will need to get compensated for the invalidated offers. 
We can roll that out in 2 steps: 
1. No new offers can be created by higher amounts. 
2. Existing offers with higher amounte become invalid. Makers need to make a compensation request for the lost fees.

**Comment by Conza88** [comment]
Any reason you don't indicate the cons?



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: HenrikJannsen ***@***.***>
Sent: Wednesday, October 26, 2022 5:47:04 AM
To: bisq-network/proposals ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bisq-network/proposals] Reduce the max. trade amount for altcoins to 0.5 BTC (Issue #387)


Currently the max. trade amount for altcoins is 2 BTC.

For improving the distribution of funds from the delayed payout transaction (see #385<https://github.com/bisq-network/proposals/issues/385>) and mitigating risks this proposal suggest a reduction of the max. trade amount to 0.5 BTC.

There will be 2 more proposals with a higher and lower amount and the DAO should decide by voting which is the most acceptable. The winner will be selected by the highest accept % and if there are multiple with same value the highest stake put it counts. If also same stake values it can be further discussed to lower one will be selected.

This realtively high amount should have been reduced anyway long ago as it carries some risks and increase the burden for arbitration cases (as well increase risk there). The high amount was set in early days when BTC price was much lower and Bisq never adjusted that to equivalent fiat values. There was no good reason why that was not done earlier.

Problems with high trade amounts:

  *   Risk if one manage to trick the trade protocol (happened once)
  *   Risk for arbitrator (and DAO) to make a wrong decision
  *   Risk if both users lose their wallet/data directory
  *   Risk that new proposal how delayed payout is distributed gets abused
  *   Overall volume in arbitration cases is higher and more volatile
  *   Potentially higher costs for the DAO from reimbursments and BSQ volatility
  *   Refund agent cannot refund high amounts. Trader need to do it themself which will be more painful with new proposal<https://github.com/bisq-network/proposals/issues/385>
  *   Higher risk for trader to end up in arbitration with a large amount. Splitting a large trade in smaller ones distributes the risk to potentially multiple traders and by that lowers risk to trade with an unresponsive user which is the majority of reasons for arbitration.

Benefit of high trade amounts:

  *   More convenient for traders to do large trades. BUT traders can simply repeat some trades.

Consequences for open offers:
Open offer who have paid the maker fee for the 2 BTC fees will need to get compensated for the invalidated offers.
We can roll that out in 2 steps:

  1.  No new offers can be created by higher amounts.
  2.  Existing offers with higher amounte become invalid. Makers need to make a compensation request for the lost fees.

**Comment by HenrikJannsen** [comment]
Not needed anymore in context of https://github.com/bisq-network/proposals/issues/390
