### ISSUE TITLE
Hungarian (Magyar) translation [hu]

### ISSUE THREAD

**Issue by Viking0x** [bisq-network/proposals#39]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I can help with Hungarian (Magyar) translation

**Comment by ripcurlx** [comment]
@Viking0x: Thanks! All translations are done within https://www.transifex.com/bisq/bisq-desktop/dashboard
Please request access there and I'll add you as a translator.

**Comment by Viking0x** [comment]
Done!
