### ISSUE TITLE
@cbeams to repost bond for DNS Admin role

### ISSUE THREAD

**Issue by cbeams** [bisq-network/proposals#393]
I've been playing the DNS Admin role since #213 with a 20K BSQ bond; this proposal is to repost my bond at the current rate of 10K. When this proposal is approved, I'll have a new bond in place for 10K BSQ and I'll then unlock the current 20K BSQ bond.

**Comment by cbeams** [comment]
DAO proposal txid: `12cf459fbae3e9f37481bc4dd39c9397fe82f4c74533e621cee90bc575d9a4f8`

**Comment by pazza83** [comment]
This proposal was approved in Cycle 41.

**Comment by pazza83** [comment]
Hi @cbeams 

Please can you let post your tx id for the new bond when complete and I will close this proposal.

Many thanks

**Comment by cbeams** [comment]
Will do; I expect the previous bond will unlock mid-next month (March), and will post the new one then.

**Comment by cbeams** [comment]
> Please can you let post your tx id for the new bond when complete and I will close this proposal.

`02480d82acc52c8fe84325fd96c39756384cd8d966b902a1ef6c4119a0e55ed8` as per https://github.com/bisq-network/roles/issues/18#issuecomment-1469607352

**Comment by pazza83** [comment]
Thanks will close now.
