### ISSUE TITLE
Bisq Maintainer Role

### ISSUE THREAD

**Issue by alejandrogarcia83** [bisq-network/proposals#394]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

Hi Bisq DAO,
I want to become a Bisq Maintainer.

**Comment by alejandrogarcia83** [comment]
Proposal txid: `dcd0f4a950ab4852e0a80ec177d705c4f7ce129dcc5d7ba3a71124b9bc5495b4`

**Comment by pazza83** [comment]
Hi @alejandrogarcia83 your proposal was approved in Cycle 41. Welcome to Bisq :)

**Comment by pazza83** [comment]
closing as accepted and bond locked
