### ISSUE TITLE
Enable XMR-auto confirm by default

### ISSUE THREAD

**Issue by pazza83** [bisq-network/proposals#395]
## Proposal:

This proposal is to enable [XMR-auto confirm](https://bisq.wiki/Trading_Monero#Auto-confirming_trades) by default.

Reasoning:

With the introduction of distribute [Burningman role to contributors who burned BSQ](https://github.com/bisq-network/proposals/issues/390) and [do not pay out the security deposit of the trade peer to the arbitration case winner](https://github.com/bisq-network/proposals/issues/386) it makes sense to try and reduce the funds that go to arbitration for a few reasons:

- Trades that go to arbitration will result in refund agent not paying out the full trade amount in the multisig for security reasons. This means that trader's that have a non responsive counterparty will be inconvenienced more then they are currently
- Delayed payout transactions (DPT) are caused when trader's send trades to arbitration. The DPT create volatility for the Bisq DAO, as a result this has the potential to cause swings in the amounts needed for the new burning men burn to reduce the inflation that is caused when refund agent reimburses traders and/or traders are reimbursed from the DAO in BSQ for trades over 0.5 BTC.

### Outcome:

This proposal seeks to limit the amount of XMR trades going to arbitration by having more XMR/BTC trades paid out automatically by use of auto-confirm. This will result in quicker payouts for traders and less potential for trades going to arbitration due to non responsive XMR traders.

### Solution:

[XMR-auto confirm](https://bisq.wiki/Trading_Monero#Auto-confirming_trades) has been used for a while and works well. When trades have auto-confirm enabled the payout is automatic so non responsive BTC sellers (XMR receivers) would are no longer be an issue. 

Using XMR-auto confirm would not help reduce the incidence however of non responsive BTC buyer (XMR senders) not sending the XMR and resulting in trades entering the dispute process.

Currently XMR-auto confirm is not enabled by default, traders have to enable it manually. If XMR-auto confirm is enabled by default more trades will be completed by auto confirm improving the experience for both buyers and sellers.

### Risks:

Not sure what the risks are of users using the default XMR explorers in Bisq for auto confirms should they be compromised?

Enabling XMR-auto confirm by default does not mean users have to use it. They could un-enable it if they were not happy to use it. Alternatively the XMR sender can simply not input their transaction IDs / secret keys to avoid auto confirm. Likely however the users familiar enough to do this are more aware of the Bisq trade process and, therefore, less likely to be non-responsive traders.

**Comment by MwithM** [comment]
Remind, though, that autoconfirm could fail and in that case BTC sellers should be accountable for not paying attention to the trade.

**Comment by pazza83** [comment]
Agreed, I think if accepted this should be made clear in the [trading monero wiki](https://bisq.wiki/Trading_Monero)

**Comment by pazza83** [comment]
Closing as implemented.

Updated wiki to include information 

https://bisq.wiki/Trading_Monero#Auto-confirming_trades
