### ISSUE TITLE
Reduce larger BTC amounts going to arbitration for users inexperienced with how Bisq works 

### ISSUE THREAD

**Issue by pazza83** [bisq-network/proposals#396]
## Proposal

This proposal gives a few options for limiting BTC amounts above 0.25 BTC going to arbitration for users inexperienced with how Bisq works.

It expands on the work done for https://github.com/bisq-network/proposals/issues/391

### Reasoning:

With the introduction of distribute [Burningman role to contributors who burned BSQ](https://github.com/bisq-network/proposals/issues/390) and [do not pay out the security deposit of the trade peer to the arbitration case winner](https://github.com/bisq-network/proposals/issues/386) it makes sense to try and reduce the funds that go to arbitration for a few reasons:

- Trades that go to arbitration will result in refund agent not paying out the full trade amount in the multisig for security reasons. This means that trader's that have a non responsive counterparty will be inconvenienced more then they are currently
- Delayed payout transactions (DPT) are caused when trader's send trades to arbitration. The DPT create volatility for the Bisq DAO, as a result this has the potential to cause swings in the amounts needed for the new burning men burn to reduce the inflation that is caused when refund agent reimburses traders and/or traders are reimbursed from the DAO in BSQ for trades over 0.5 BTC.

### Theory of why new users cause trades to go to arbitration

Approximately 90% of trades that go to arbitration are cases where one of the traders is non-responsive. This can be seen by the regular cycle reports given by [Refund Agent](https://github.com/bisq-network/roles/issues/93).

It is difficult to know what causes traders to become non-responsive. My hypothesis is that a significant, but unknown, amount are caused by new users with a lack of knowledge about how Bisq works.

A few examples of trades going to arbitration are as follows:

1. A new user wants to buy some XMR in a non KYC way. They find out about Bisq and download it and take a trade to buy XMR. The new user sends the BTC and checks their XMR wallet. Once they receive the XMR they forget all about Bisq and do not confirm the XMR.
2.  A new user has taken a few XMR trades but they set up a password for their Bisq instance and have now forgotten what it is. They also did not back up their seed words correctly.  
3. A new user has taken a an ETH trade but they are having a few issues with connecting via TOR and are now unable to access Bisq. As they are new they do not understand they can reach out to Bisq support on Matrix etc to resolve the issue.
4. A new user takes a trade to Buy XMR, they receive the XMR but have a busy few days. They do not check back on Bisq for a week. When they do log back in they have received a penalty losing their deposit for not confirming the trade. Annoyed with themselves they close Bisq and try and forget about their experience. The trade ends up going to arbitration.

### Outcome

Reduce new users trading altcoins above the value of 0.25 BTC until they are familiar with Bisq. This will reduce the amount of BTC being sent to arbitration that is a result of users not familiar with how the Bisq process works. 

### Solution

Currently the proposal implemented in https://github.com/bisq-network/proposals/issues/391 does the following...

When a user takes a trade it checks their local `ClosedTrades` file. Is the file is empty this means no trades have been completed. This means they are unable to take or make a trade over 0.25 BTC.

This prevents brand new users trading amounts over 0.25 BTC, but does allow them to trade 2 BTC amounts as soon as they have completed 1 trade.

My suggestion is to expand on this.

After discussing with @jmacxx possible options parameters that can be used to ascertain if a trader is a new user or not could be as follows:

- Days since first trade in `ClosedTrades` - for example new users could have a 0.25 BTC limit in place until they have one completed trade that is at least 30 days old.

- Number of trades in `ClosedTrades` - for example new users could have a 0.25 BTC limit in place until they have completed 10 trades in total.
 
- Number of trades in `MediationDisputeList` - for example new users could have a 0.25 BTC limit in place until they have has have experience of at  least one trade going to mediation.
 
- Altcoins could be given an [account age](https://bisq.wiki/Account_limits#Account_aging) - for example new users could have a 0.25 BTC limit in place until their altcoin account is at least 30 days old.

My thoughts are Bisq should give new users a limit of 0.25 BTC until have have at least 20  trades in `ClosedTrades`. About 5% of trades enter mediation, therefore, statistically a user with 20 trades is more likely than not to have have experience with mediation.

**Comment by HenrikJannsen** [comment]
Not sure if that adds too much complexity for users to understand those rules? I guess if a user made one successful trader they undestand that they have to be online. So I think to limit it to the first trade case should be enough and its an easier rule to communicate. Still might have issues with traders who start a new app for each trade for privacy reason. To cover such we could add an advanced preferences or prog argument, intentionally hard to find/use so its only for pro-traders ...

**Comment by pazza83** [comment]
Hi @HenrikJannsen thanks for the feedback

> Not sure if that adds too much complexity for users to understand those rules?

From a user experience perspective I would imagine it would be pretty simple.

For example if 10 trades are decided to completed before trades over 0.25 BTC can be made then the trader would be shown a pop up message on Bisq.

![201205618-fb918d9f-b0e2-42c1-94bd-cde4e74ea8cc](https://user-images.githubusercontent.com/66367547/203569848-1dc04f6f-112c-4886-905f-561f4498145c.png)

Maybe the warning message would have more specific text, eg:

`Traders have to complete 10 trades before making trades of over 0.25 BTC. Please complete at least 10 trades to increase your limit to 2 BTC per trade.`

> I guess if a user made one successful trader they undestand that they have to be online. So I think to limit it to the first trade case should be enough and its an easier rule to communicate.

Yes, they understand they need to be online (if they have been a maker) but they might not understand they need to press the confirm button (as a seller) if their first trade was that of a BTC buyer.

Having the experience of more trades (maker/taker, buyer/seller) might make someone more familiar with the process and less likely to go AWOL.

**Comment by HenrikJannsen** [comment]
I think the warning should at least show what is the concrete reason for that user and not just list a few options, which leaves the user in a very unclear and frustrating state what is missing so that they can get over the limit.

**Comment by pazza83** [comment]
Going to close this in favor of a new proposal to be posted by @MwithM to give users the option to set limits in Bisq app.

**Comment by Conza88** [comment]
> A few examples of trades going to arbitration are as follows:
> 
> 1. A new user wants to buy some XMR in a non KYC way. They find out about Bisq and download it and take a trade to buy XMR. The new user sends the BTC and checks their XMR wallet. Once they receive the XMR they forget all about Bisq and do not confirm the XMR.
> 2. A new user has taken a few XMR trades but they set up a password for their Bisq instance and have now forgotten what it is. They also did not back up their seed words correctly.
> 3. A new user has taken a an ETH trade but they are having a few issues with connecting via TOR and are now unable to access Bisq. As they are new they do not understand they can reach out to Bisq support on Matrix etc to resolve the issue.
> 4. A new user takes a trade to Buy XMR, they receive the XMR but have a busy few days. They do not check back on Bisq for a week. When they do log back in they have received a penalty losing their deposit for not confirming the trade. Annoyed with themselves they close Bisq and try and forget about their experience. The trade ends up going to arbitration.

Sounds like the problem is shitcoins...

**Comment by pazza83** [comment]
This proposal was about larger BTC amounts (ie over 0.25 BTC) going to arbitration and almost all fiat trades are limited to 0.25 BTC, therefore, altcoins are the the trades that can send large amounts to arbitration (up to 2 BTC).
