### ISSUE TITLE
Increase trading limits as an opt-in setting

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#398]
### Proposal

Altcoin and no chargeback risk fiat traders to have the option to increase their trading limits after acknowledging to know the basic use of Bisq.

### Rationale

Bisq needs to **reduce trades into arbitration**, specially after [distributing burningman role](https://github.com/bisq-network/proposals/issues/390), which will make it more difficult to sell reimbursed BSQ, and traders winning an arbitration case [not receiving a compensation](https://github.com/bisq-network/proposals/issues/386).
Most of the trades that end in arbitration are from unresponsive peers. There are [reasons](https://github.com/bisq-network/proposals/issues/396) to think that some unresponsive peers are new Bisq users.
Drawing the line where a user becomes ready to participate in bigger trades is a [tough call](https://github.com/bisq-network/bisq/pull/6407), and the steps to enforce that only traders with a certain age, amount or volume of trades can raise the limits could reduce their privacy or create other inconveniences. So I think that, similar to how XMR traders will soon be able to opt-out from using the [auto-confirm feature](https://github.com/bisq-network/proposals/issues/395), is better to leave up to the users to decide when they're ready to participate in bigger trades.

### Details

- Add a toggle button into Settings tab to `Raise trading limits`, disabled by default. Optionally, to give users more flexibility, a text field to set their own trading limit could be placed when the toggle is enabled.
- When toggle button is enabled, show pop-up with the next info: 
>Trading limits are set to reduce risk of costly disputes and losing funds for new users. Raise trading limits under your own risk. Every trader has their own pace, but it's recommended to complete at least 5 trades before raising trade limits.
>By raising trading limits you acknowledge to be familiar with the basic use of Bisq, like [backing up your data](https://bisq.wiki/Backing_up_application_data), [trading rules](https://bisq.wiki/Trading_rules), [dispute resolution](https://bisq.wiki/Dispute_resolution), [penalties](https://bisq.wiki/Table_of_penalties) or  [find support](https://bisq.wiki/User_support).`
> [Account signing](https://bisq.wiki/Account_signing) limits are still applied to most National Account [payment methods](https://bisq.wiki/Payment_methods), to reduce chargeback risk. 

### Risks

- Users could increase their trading risks without knowing enough about Bisq. They may not know what they need to know. That's why at least 5 completed trades are recommended.
- Some users could not know that raising trading limits is possible. Being unable to raise the trading limit would be a feature in this case, as such users are more likely to ignore other basic knowledge to use Bisq with no issues.
- Bugs: I think that this option is easier to implement than those which require to take into account user's trading activity.

### Other considerations

- I don't think that new users are the only ones abandoning trades which end into arbitration, as they also don't claim their security deposits through other means like social media. That would be a point in favor of not having hard to remove trading limits, but afterall, is quite frustrating because I don't see an effective way to reduce arbitration tickets.
- If removing the trading limit becomes so easy, I think that 0.10 BTC as initial limit is enough, instead of the planned 0.25 BTC in #391 . 0.25 or 0.5 BTC could be the default amount after enabling the toggle button.

**Comment by flix1** [comment]
Totally agree with giving advanced traders the choice, especially for low risk payment methods.

I have been trying to get some larger traders to come to Bisq and their feedback is always: "too little liquidity, it takes forever to buy 1 BTC".

Of course zero risk trades like BSQ/BTC atomic swaps should not be limited at all.

**Comment by pazza83** [comment]
Added this information to the wiki:

https://bisq.wiki/Account_limits#New_user_opt-out_limits

**Comment by pazza83** [comment]
Closing issue as approved
