### ISSUE TITLE
Bisq2 - Android & Java code unification

### ISSUE THREAD

**Issue by niyid** [bisq-network/proposals#399]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I had to make changes to several sub-projects (`common`, `tor` and `persistence`) to the original Java project for a successful Android build.

Currently all the other issues are resolved and should work as well for Java, except for item 2 - the matter of **`java.lang.management.ManagementFactory`**. The idea is to find a O/S neutral way to start tor (or any process) that works on Both Android and Java.

Once this pending issue is resolved, there will be no need for code fragmentation where different versions of `common`, `tor` and `persistence` are maintained for Java and Android. Rather a unified code will be maintained.

Please find attached the issue list.

![javaVSandroid](https://user-images.githubusercontent.com/20237127/205602009-0493fc52-1ccd-46ad-9d86-3afc705f696c.jpg)

**Comment by niyid** [comment]
[Tor Android](https://github.com/guardianproject/tor-android/)  seems to be the best method for starting Tor on Android that I could find. But this will not be compatible with Java.

If there are any suggestions that will work for both Java and Android, they will be appreciated.

Of course if the unification will not work,we should proceed with maintaining bisq2-android as a fork.

**Comment by pazza83** [comment]
Hi @niyid thanks for creating this proposal.

Have you have a look at the proposal guidelines: https://bisq.wiki/Proposals ?

I am not understanding what you are proposing.

I am also not sure what you are looking to seek consensus on.

**Comment by niyid** [comment]
@pazza83 

Apologies if you find it difficult to understand the thrust of this proposal.

- I am working on a Bisq2 Android version.
- I had to make changes to several core projects as listed in the initial post because of limitations in Android.
- Some of these changes will work OK in Java; but the most stubborn issue is Tor.
- Since Bisq2 is still in its infancy, there is a chance to prevent fragmentation (forking) and maintain same code for Java and Android.

**Comment by HenrikJannsen** [comment]
@niyid I think you should just continue as a fork. The current devs do not have the resources to support this work at the current state. 
Also the proposal area is not the right place for such discussions.

**Comment by pazza83** [comment]
Closing due to lack of discussion

**Comment by niyid** [comment]
I suppose there is an alternative pathway to building for Android? 

It is my opinion that this is the right first step to prepare for an Android app. 

Without the protocol being the same for all devices (PC/Mobile/Handheld), it will be impossible to build for other devices.

**Comment by niyid** [comment]
[The Push Request for documentation purposes](https://github.com/bisq-network/bisq2/pull/614#issuecomment-1367950293)
