### ISSUE TITLE
Increase all compensations for OPS by 30%

### ISSUE THREAD

**Issue by Emzy** [bisq-network/proposals#401]
### Proposal:

This proposal is to increase all compensations for OPS by 30% for the Cycle 44.
Cycle 43 will be the DAO voting.

### Reasoning:

1. There is inflation compensation needed for a few years.
2. The requirements for disk space (bitcoin blockchain) have increased.
3. Over all the work is more than initially anticipated. (exchange rate problems, tor problems)

### Outcome:

Better coverage of operating costs and stronger financial incentive to run the OPS services.

### Solution:

Increase every OPS role by 30%.
List:
- $50 -> $65 Bitcoin node operator 
- $100 -> $130 Seed node operator
- $100 -> $130 Pricenode operator
- $100 -> $130 Relay operator for mobile notifications
- $200 -> $260 Mempool Explorer Operator
- $100 -> $130 Monero Explorer Operator
- $100 -> $130 Monitoring Operator
- $25 -> $33 GitHub Admin
- $100 -> $130 Forum operator

### Risks:

None.

**Comment by pazza83** [comment]
Hi @Emzy closing this as approved

**Comment by Emzy** [comment]
TXID: 2926fac4405fe54f71a0eaf7899ea2c53e0f751913be54a0305b259a0bda9341

**Comment by MwithM** [comment]
This proposal was already accepted, voting is unnecessary. Anyways, better leave it open because I  think I remember that removing offers could cause issues.
