### ISSUE TITLE
Add user defined Payment Method on Bisq

### ISSUE THREAD

**Issue by flix1** [bisq-network/proposals#406]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

### Background

Bisq's mission is to provide an uncensorable Bitcoin decentralized exchange open to everyone, anywhere in the world. In practice this means that there are 100+ currency pairs and 100s of possible payment methods. New payment methods are constantly appearing. Bisq does not have the resources to manually add or even know which ones are in demand in every single country. The current process is not flexible enough - see for example all the work it takes to add just one new payment method here https://github.com/bisq-network/growth/issues/222

In our conversations with Bisq users in Nigeria, China, Venezuela, Argentina as part of the Market Day initiative (https://github.com/bisq-network/growth/issues/274) we've had requests to add multiple payment methods. 

### Description

A more flexible workaround is to add a **user defined payment method** with a custom field. With trader chat enabled the details can be left to the peers once an offer is taken.

Account -> National Currency Accounts -> Custom -> Payment information

![image](https://user-images.githubusercontent.com/4233784/223392651-a4e34325-2146-473a-97d2-f33744028cd2.png)

It is important that the payment method name defined by the user actually appears in the order book and in the "offers by payment method" tab. 

### Pros
More flexibility for users (esp. in smaller markets).
Faster.
No time wasted adding payment methods that have no demand.
Bottom-up.
Resilient to change. Long term durability of Bisq even in Ragnarok scenario.

### Cons
Support difficulties. Support team could be faced with payment methods they know little about.
Fraud potential. Risk of reversible payments.
Spam potential. Could be used to send messages visible on the offer book for non trade purposes.

### Risk mitigation
A big warning label should make it clear to users that they trade with custom payment methods at their own risk.
Amount can be limited.
Time should be short - we can recommend this only for instant payment methods.
Cost of locking up capital in security deposits should limit spam.

Any payment methods that actually start being used frequently, we can add as an "official" Bisq payment method and spend a little time learning more about and creating a more specific UX.

**Comment by flix1** [comment]
For example, a lot of effort was put into adding multiple payment methods for India, including PayTM, RTGS, UPI NEFT... they have hardly been used. 

It's much better to allow users to take the initiative and once a payment method is proven popular, then you codify it.

![image](https://user-images.githubusercontent.com/4233784/223415683-b0f43da2-ab40-4bb1-b103-864e5e09e953.png)

**Comment by flix1** [comment]
As for how to display the custom payment name in the offer book, it's the same mechanism that is used to display the city name in F2F trades. Replace "The city will be displayed in the offer" with "The payment method will be displayed in the offer".

![image](https://user-images.githubusercontent.com/4233784/223416654-5cf86f49-b4c8-4839-bc11-781c1bb2ca68.png)

**Comment by flix1** [comment]
Actually thinking a bit more about this... we already have a workaround!

We can use F2F payment method as a sandbox and include the local payment method in the city field.

It's not "officially" sanctioned by the defined trade rules... but we can ask mediators and devs to make an exception for small markets for testing.

![image](https://user-images.githubusercontent.com/4233784/223421127-f7e9c771-dff4-4a24-a63c-61381ab785f4.png)

**Comment by apemithrandir** [comment]
Maybe we get a few broad categories like Local Instant payment method, similar to National Bank Transfer. Are there ways to categorise the new payment types that users want? We wouldn't want a complete free for all with people making PayPal offers.

**Comment by flix1** [comment]
>Maybe we get a few broad categories like Local Instant payment method, similar to National Bank Transfer. Are there ways to categorise the new payment types that users want? We wouldn't want a complete free for all with people making PayPal offers.

Part of the point is that **we don't know**. We only found out when we start talking to local markets. Letting users take the initiative helps the info flow... we would only have to look at the offer book to see what is being used.

But sure, having some broad categories like "Other - instant" and "Other - slow" could work.

**Comment by flix1** [comment]
As a test it looks like we are going to be experimenting with the workaround (F2F) until Market Day: 

https://twitter.com/bisq_network/status/1633093747306115072

![image](https://user-images.githubusercontent.com/4233784/223471313-2ae45827-eac1-44f7-8161-60aebc028d51.png)


Data will be very useful for this proposal.

**Comment by pazza83** [comment]
Hi @flix1 thanks for creating this proposal.

I am conflicted about this one.

Positives are all the reasons you mention.

Negatives, I think there will end up being trades for PayPal, CashApp, Venmo, trades that end up being reversed once the multisig has paid out.

Also people selling gift cards that do not work and no way for mediator to know which trader is telling the truth.

I am not certain if Bisq 2 that at least comes with 'trader reputation' would be a better medium to experiment with new payment methods and those being used regularly could then be added to Bisq.

I would be a little concerned seeing users post negative Bisq experiences on Bisq about being scammed by weaker custom payment methods. Bisq has a great reputation and I would not want to see scammers on the platform.

**Comment by w0000000t** [comment]
My opinion is the same as @pazza83 and actually while checking this I went first through a "hey nice idea, really like a Columbus' egg!" phase, then straight to "...but this will open the userbase to a whole lot of scams, and the support team will get the heat for it"

**Comment by apemithrandir** [comment]
I agree with @w0000000t and @pazza83. I think some more generic payment types but are still not a free for all.

It is tricky with +100 countries and currencies each with there own newer payment types, waiting a development cycle to get new payment types in is definitely not ideal for adoption.

**Comment by flix1** [comment]
I agree that the risks mentioned exist. Let's see how testing goes, it's only for a few weeks. 

We have been playing it safe for a long time on multiple fronts at the expense of growth. From time to time it's good to do limited experiments to see if our caution is excessive.

We need data to confirm or disprove our assumptions. A/B testing, short duration experiments and similar projects can provide that data. Otherwise assumptions just become set in stone. They key is to keep experiments cheap. 

This one in particular I expect to be extremely cheap: Limited in time, 0 dev time and very little support time.

By using the F2F payment method, which before we started only had 9 offers, we can very easily monitor it and keep it contained. 

In any case I don't expect people to use this much in already liquid markets like EUR, USD, BRL with well established payment systems. Where this flexibility is needed is in Africa, China, South América...

**Comment by flix1** [comment]
RakutenPay being tried in Japan

![image](https://user-images.githubusercontent.com/4233784/223717414-a0b6bf4e-636b-4f3c-8746-c445ec35a0b5.png)

**Comment by HenrikJannsen** [comment]
> Negatives, I think there will end up being trades for PayPal, CashApp, Venmo, trades that end up being reversed once the multisig has paid out.
> Also people selling gift cards that do not work and no way for mediator to know which trader is telling the truth.

We can mitigate that by showing a warning popup with mentioning known unsafe payment methods and clearly state that mediation and arbitration might not be able to figure out who has behaved incorrect, thus all funds of boths users might be lost (similar to MAD just that the DAO gets the funds).


> I am not certain if Bisq 2 that at least comes with 'trader reputation' would be a better medium to experiment with new payment methods and those being used regularly could then be added to Bisq.
> 
> I would be a little concerned seeing users post negative Bisq experiences on Bisq about being scammed by weaker custom payment methods. Bisq has a great reputation and I would not want to see scammers on the platform.

As @flix1 mentioned we could run it as experiment. If it turns out to not work well we can remove it again. I guess we have been too conservative in the past (e.g. not adding trader chat due concern of scam risks, F2F trade,...). There are different regions like Japan which would even allow reversible payment methods because the culture is just very different and ppl are extremely honest. Maybe we can maintain a list provided by the filter data of countries which are blocked for the new custom payment methods. I guess that could help to selectively tune it so that it brings benefits to the markets where we need it without opening the doors for scammer. We could set a clear metric for that, e.g. if there are more then 3 unresolveable arbitration cases (or clear scams) per 3 months period we block that country.

As said above it need to be clearly communicated that this option does not provide the same security as other payment methods. Users might need to click a checkbox to be aware of the risk that if the case cannot be resolved without doubt by the arbitrator that there will be no refund. Also we could limit the amounts to < 500 USD, though that might be bad for e.g. Japan market - the account age witness should cover the limits already.

**Comment by HenrikJannsen** [comment]
We could also permit that custom payment option only for countries not covered sufficiently by existing ones. I doubt that in EU, US, GB, AUS, CAN we need it, there it might be actually a larger risk that we attract scammers with little benefit as basically everyone has one of the offered payment methods.

**Comment by flix1** [comment]
It looks like Argentina is also joining the test. They were the ones most asking for payment methods, so I'm happy to see that they are taking advantage of this experiment.

![image](https://user-images.githubusercontent.com/4233784/224004677-7e2d78f3-e273-46b7-8f45-04606972efb6.png)

![image](https://user-images.githubusercontent.com/4233784/224005030-b8d504ae-4062-453c-90c7-133c48ecbcaa.png)

**Comment by pazza83** [comment]
I would be for trying it out a custom payment method that excludes established markets: EU, US, GB, AUS, CAN, BRL, and known payment methods that allow reversals.

Here is a list of payment methods considered for adding to Bisq that were rejected  as unsuitable:

- Apple Pay
- ATH Móvil
- Boleto
- Cash App
- CashU
- Chipper
- Curve
- Daviplata
- Efecty
- Gold Avenue
- Google Pay
- Jeton
- M-Pesa
- Neteller
- OkPay
- Payeer
- Payonner
- PayPal
- PingIt
- PostePay
- Ria Money Transfer
- Venmo
- WebMoney
- Wirex
