### ISSUE TITLE
Upgrade Mediation's Proposal Ticket

### ISSUE THREAD

**Issue by leo816** [bisq-network/proposals#407]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

After discussing several ideas on the support team weekly call, here are some things we think should be changed:

1. Currently we've had complaints that the mediation's payout proposals are hard to read, for example:

```
Ticket closed on 30 Oct 2022 21:00:36
Mediator node address: 6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion:9999

Summary:
Trade ID: -
Currency: EUR
Reason for dispute: Trader not responding
Payout suggestion: BTC seller gets trade amount plus compensation 25%
Trade amount: 0.01 BTC
Payout amount for BTC buyer: 0.0005 BTC
Payout amount for BTC seller: 0.0125 BTC

Summary notes:
BTC buyer did not send payment or respond to mediation
BTC seller requested compensation for non payment and non responsive buyer

-----BEGIN SIGNATURE-----

-----END SIGNATURE-----

Next steps:
Open trade and accept or reject suggestion from mediator
```

Instead we propose for there to be a clear message stating that the BTC seller is receiving back his deposit + principal + part buyer's deposit, followed by the BTC buyer's proposal where it would say: BTC buyer receives a penalty on his deposit

Also we would edit the "next steps" part so that it takes into account the new trade protocol and it's impact on arbitration

so it would look like:

```
Ticket closed on 30 Oct 2022 21:00:36
Mediator node address: 6c4cim7h7t3bm4bnchbf727qrhdfrfr6lhod25wjtizm2sifpkktvwad.onion:9999

Summary:
Trade ID: -
Currency: EUR
Reason for dispute: Trader not responding
Payout suggestion: BTC seller gets trade amount plus compensation 25%
Trade amount: 0.01 BTC
Payout amount for BTC buyer: 0.0005 BTC (BTC buyer receives a penalty on his deposit)
Payout amount for BTC seller: 0.0125 BTC (BTC seller receives back his deposit + trade amount + part seller's deposit.)


Summary notes:
BTC buyer did not send payment or respond to mediation
BTC seller requested compensation for non payment and non responsive buyer

-----BEGIN SIGNATURE-----

-----END SIGNATURE-----

Next steps:
Please accept or reject the proposal from mediator. If a trader doesn't accept the mediation proposal they can open arbitration, keep in mind that the arbitrator can only make the payout of the trade amount + 1 security deposit. the security deposit of the "losing" trader will be left unpaid.


```

The changes are:
**(BTC buyer receives a penalty on his deposit)
(BTC seller receives back his deposit + trade amount + part seller's deposit.)**
This will make it easier for traders to figure out if the amount they are receiving is correct

**Next steps:
Please accept or reject suggestion from mediator. If a trader doesn't 
accept the mediation proposal they can open arbitration, 
keep in mind that the arbitrator can only make the payout 
of the trade amount + 1 security deposit. the other security 
deposit will be left unpaid.**

-------

2. Change the button from "reject mediation proposal" to just "send to arbitration".
Since sometimes the proposal has been accepted anyways and it doesn't make sense for then to "reject" it

-------

3. Merging the support ticket with the trading chat + adding the mediation proposal directly in the chat.

It would make things much easier for the user to just request a support ticket within the trading chat window and have the mediator talk with both parties. This leaves out having two windows open at the same time and also makes it simpler by having the mediatior make the proposal on the chat itself for both parties to accept.

**Comment by refund-agent2** [comment]
I don't think that a proposal is required for the first two changes. They don't cause a big disruption on how the DAO or the software works.
The third change (merging support and trading ticket chats) might require a proposal, since it seems that the changes required to implement it will be big enough. The reasons why I think it's not a good idea to implement this change is that it would cost much, and that some details like bank details need to be shared privately between mediator and one of the traders.
It's an idea that it's worth discussing if we are willing to do big changes though.

I'll comment about the first 2 proposals at the [Improve dispute resolution](https://github.com/bisq-network/projects/issues/67) project.

**Comment by pazza83** [comment]
Closing as was superseded by 

https://github.com/bisq-network/projects/issues/67
