### ISSUE TITLE
Option for traders to use BSQ for the security deposit and allow responsive traders that end up in arbitration to be compensated

### ISSUE THREAD

**Issue by darawhelan** [bisq-network/proposals#408]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

This is a proposal to create a more equitable situation for responsive traders that end up though no fault of their own having their trades go to arbitration as a result of unresponsive trade peers.

The equability of the trade process for responsive traders with trades going to arbitration was negatively impacted by a the change to the [donation address protocol](https://github.com/bisq-network/proposals/issues/390) and the subsequent required [change to not pay out the security deposit of the trade peer to the arbitration case winner](https://github.com/bisq-network/proposals/issues/386). Whilst I understand the need for both changes to decentralize the DAO and protect it from a malicious burning man attack, it does not change the fact that the changes created a worse outcome than previous for responsive traders entering arbitration.

I have been a trader on Bisq for a while but since the change to the [donation address protocol](https://github.com/bisq-network/proposals/issues/390) I get a more frustrated than before when trades enter arbitration due to the inconvenience caused by the risks that come with being an offer maker on Bisq and receiving no compensation should I end up trading with an unresponsive peer. Prior to the change in the trade protocol I would have been compensated for both my time and having some of my BTC capital locked up from the unresponsive peers security deposit.

Therefore, I would like to propose a solution to the problem so that offer makers can be confident that should they trade with an unresponsive peer they would be compensated.

The solution I propose involves the maker, at the point of offer creation, being able to choose to use BSQ as the security deposit should they wish. This trade would then be available to offer takers that also use BSQ as their security deposit. 

- Should the trade complete successfully both buyer and seller receive back their BSQ.
- Should the enter mediation the buyer and seller can be compensated or penalized from either the BTC payout amount or BSQ payout amount being changed and agreed by both buyer and seller.
- Should the trade enter arbitration then the BTC trade amount will be distributed the the burning men and the BSQ will be burnt.  The arbitrator can then reimburse the trade amount and the BSQ amount (including any proposed compensation from mediation).
 
This would allow compensation to the responsive peer while also removing the possibility of a malicious burning man attack. The arbitrator could also take a fee for the service by refunding less BSQ then was burnt resulting in profit for the DAO.

An example of a trade for 0.1 BTC would be as follows:

- BTC seller creates an offer to sell 0.1 BTC for XMR using BSQ as the security deposit.
- The Bisq software would reserve 0.1 BTC in their wallet for the trade plus 15% security deposit in BSQ currently about 300 BSQ ready for the trade. This BTC and BSQ would b reserved and therefore not be available for other transactions.
- The offer would be shown in the Bisq offer book, offer book would indicate the security deposit is 300 BSQ.
- A BTC buyer takes the offer.
- An on chain multisig is created with the trade amount (0.1 BTC) and the deposit amounts (600) BSQ.
- The BTC buyer sends the XMR.
- The BTC seller for whatever reason does not complete the trade
- The BTC buyer then opens mediation
- Mediator confirms on chain the XMR has been sent and messages BTC seller to see why they have not released the BTC
- The BTC seller does not respond to the mediator
- Mediator proposes BTC buyer gets trade amount 0.1 BTC plus 500 BSQ for their inconvenience, and seller gets 100 BSQ
- BTC buyer accepts, BTC seller still remains unresponsive  
- BTC buyer sends the trade to arbitration
- On chain the multisig pays out the burning man donation addresses and the 600 BSQ deposit is burnt
- BTC buyer is successful at arbitration and receives their 0.1 BTC plus the 500 BSQ as proposed in arbitration. Arbitrator then requests this from the DAO as part of their normal compensation request.  

The BTC buyer is happy they get 200 BSQ compensation for their inconvenience.

The DAO is happy that 600 BSQ was burnt and only 500 had to be compensated so the arbitration cost has been covered.

Other benefits are:

- The BTC offer maker and taker can trade on Bisq with less BTC collateral
- BSQ becomes more useful when it can be used as collateral for traders
- Traders being compensated in BSQ for trades over 0.5 BTC now have a strong use case for their BSQ (offer collateral) so they are not pressured to immediately sell.
- The ability to use BSQ as collateral could be useful for other applications in the future (off chain payments etc)

Negatives 

- I am assuming this is possible to use BSQ in this way, but imagine it would be complex to implement.
- Takers for BSQ security deposit offer would need BSQ to take the offers, this protocol might split the market.
  
Things to consider

A large number of offers makers pay trade fees with BSQ and a large percentage of the higher trade volumes also pay trade fees with BSQ. Therefore, I am thinking that traders on altcoin markets will likely be familiar and comfortable enough to hold BSQ that it makes this a feasible protocol for traders that would rather receive than not receive compensation should they trade with an unresponsive peers. 

Also, maybe, a BSQ holder will be more familiar with Bisq and trades done with this protocol would be a lot less likely to end in arbitration.

**Comment by darawhelan** [comment]
No sooner than I posted this I realized it would not work as a malicious burning man self trading would get:

0.1 BTC
500 BSQ
-----------
Loss of 100 BSQ from total trade amount

Plus up to 11% of the 0.1 BTC (0.011 BTC about 220 BSQ).

This would give them a total profit of about 0.006 BTC.

Maybe the answer would lie in making security deposits higher and charging a higher arbitration fee, but such a solution would make this unworkable.

Will close this proposal.

**Comment by clearwater-trust** [comment]
Good try. I share your unresponsive trader concern as a market maker.

Does Bisq need more support people?

**Comment by darawhelan** [comment]
Thanks, will try and make another proposal to remove BTC being used for the deposit and trade amount entirely to avoid the potential malicious burning man attack.

I am not sure about support needs. Maybe when Bisq 2 is up and running there will be an increase in support requirements.
