### ISSUE TITLE
Increase trading fees to 1.1% (BTC) and 0.55% (BSQ)

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#409]
As stated in #379, _Bisq should keep increasing trading fee % at a steady pace until total average trading fee reaches to the 0.8% target._ This goal has never been reached even for a single cycle, and since more trading fees are being paid in BSQ in this last [2 cycles](https://github.com/bisq-network/roles/issues/111#issuecomment-1459017657), the trading fees collected in relation to trading volume were under 0.7%.
I propose to raise BTC and BSQ trading fees a 10%, keeping the current 50% discount when paying in BSQ. 

  | Maker |   | Taker |   |  Total
-- | -- | -- | -- | -- | --
  | Current | New | Current | New |
BTC | 0,0012 | 0,001 | 0,0088 | 0,01 | 0,011
BSQ | 14,21 | 14.29* | 104,24 | 142.94* | 157.24

*Calculated with 24.300 USD/BTC and 0.85 USD/BSQ.

0.011 is the trading fee per 1BTC traded, and it's equivalent to 267USD.
157.24 BSQ is the trading fee per 1BTC traded, and it's equivalent to 133.65USD (50% discount when paid in BSQ).

With the the sudden raise in BTC price last day, I'm not sure if new trading fees were needed. Anyway, this proposal closes last update thread, #380.

**Proposals:**
BTC maker txid: 0ee317b1ad9f76a939d5aa5b6c98172275668ee9693cdc5fa6e2583901501891
BTC taker txid: 34a20757fff6888ac28ceadb6e45c68883a57722a6c909cb7512f69dd7efcc52
BSQ maker txid: b25e67d1a7bd28a59f0483fc8dec8f38b7e9c8e971cf90c2ce9e0abce307a127
BSQ taker txid: afdeedc6a7e6e3681631990d262e455a1ff0440245a8924b1c8fcf422583fa78

See [spreadsheet](https://docs.google.com/spreadsheets/d/1-hISy7F0NSqPnRxDOoi1k7df1qLJHfQTxhrVLt6NbX4/edit#gid=606155102) for details.

**Comment by MwithM** [comment]
Edited with final figures. Will publish the txids when mempool gives the opportunity.

**Comment by MwithM** [comment]
Proposals:
BTC maker txid: 0ee317b1ad9f76a939d5aa5b6c98172275668ee9693cdc5fa6e2583901501891
BTC taker txid: 34a20757fff6888ac28ceadb6e45c68883a57722a6c909cb7512f69dd7efcc52
BSQ maker txid: b25e67d1a7bd28a59f0483fc8dec8f38b7e9c8e971cf90c2ce9e0abce307a127
BSQ taker txid: afdeedc6a7e6e3681631990d262e455a1ff0440245a8924b1c8fcf422583fa78

**Comment by MwithM** [comment]
Trading fees updated as all proposals were accepted. 
Please update the software filters to adapt to this change.
Wiki updated.

Proposal must remain open to communicate whether updating the trading fee is necessary or not.

**Comment by ripcurlx** [comment]
Filter was updated 👍

**Comment by MwithM** [comment]
Closed as new increase has been proposed.
