### ISSUE TITLE
Option for traders to use BSQ for the multisig security deposit to allow responsive traders that end up in arbitration to be compensated

### ISSUE THREAD

**Issue by darawhelan** [bisq-network/proposals#410]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

This is a proposal to create a more equitable situation for responsive traders that end up though no fault of their own having their trades go to arbitration as a result of unresponsive trade peers.

The equability of the trade process for responsive traders with trades going to arbitration was negatively impacted by a the change to the [donation address protocol](https://github.com/bisq-network/proposals/issues/390) and the subsequent required [change to not pay out the security deposit of the trade peer to the arbitration case winner](https://github.com/bisq-network/proposals/issues/386). Whilst I understand the need for both changes to decentralize the DAO and protect it from a malicious burning man attack, it does not change the fact that the changes created a worse outcome than previous for responsive traders entering arbitration.

I have been a trader on Bisq for a while but since the change to the [donation address protocol](https://github.com/bisq-network/proposals/issues/390) I get a more frustrated than before when trades enter arbitration due to the inconvenience caused by the risks that come with being an offer maker on Bisq and receiving no compensation should I end up trading with an unresponsive peer. Prior to the change in the trade protocol I would have been compensated for both my time and having some of my BTC capital locked up from the unresponsive peers security deposit.

Therefore, I would like to propose a solution to the problem so that offer makers can be confident that should they trade with an unresponsive peer they would be compensated.

The solution I propose involves the maker, at the point of offer creation, being able to choose to use BSQ as the security deposit should they wish. This trade would then be available to offer takers that also use BSQ as their security deposit. 

_For this proposal I am defining the security deposit as the funds locked in a 2-of-2 multisig including the trade amount, which for this proposal is represented by a BSQ amount._

- Should the trade complete successfully both buyer and seller receive back the BSQ they put into the trade.
- Should the enter mediation the buyer and seller can be compensated or penalized from the BSQ payout being changed and agreed by both buyer and seller. This can be anything from the buyer and seller receiving back the BSQ they put into the trade, or the buyer or seller being penalized or compensated by their respective BSQ payouts. 
- Should the trade enter arbitration then all the BSQ in the multsig will be burnt. The arbitrator can then reimburse the BSQ amounts (including any proposed compensation from mediation).
 
This would allow compensation to the responsive peer while also removing the possibility of a malicious burning man attack as no BTC would be need to be distributed. The arbitrator could also take a fee for the service by refunding less BSQ then was burnt resulting in profit for the DAO.

So using easy to use values:

1 BTC = $20.000
1 BTC = 20,000 BSQ
1 BSQ = $1

An example of a trade for 0.1 BTC going smoothly would be as follows:

- BTC seller creates an offer to sell 0.1 BTC for XMR using BSQ as the security deposit.
- The Bisq software would reserve 0.1 BTC worth of BSQ (2,000 BSQ) in their wallet for the trade plus 15% security deposit in BSQ  (300 BSQ) ready for the trade. This BSQ would be reserved and, therefore, not be available for other BSQ transactions (trade fees, DAO governance, etc). The BTC seller in this instance would have reserved 2,300 BSQ in their Bisq BSQ wallet.
- The offer would be shown in the Bisq offer book, offer book would indicate the security deposit is 300 BSQ.
- A BTC buyer takes the offer.
- An on chain multisig is created with the total deposit amounts (2,600 BSQ).
- The BTC buyer sends the XMR.
- The BTC seller confirms receipt of the XMR and sends 0.1 BTC from any BTC wallet they control manually to the address provided by the seller and marks the payment as sent.
- The BTC buyer confirms the receipt of the BTC and the multisig pays out both traders their BSQ deposits back.

An example of a trade for 0.1 BTC needing arbitration would be as follows:

- BTC seller creates an offer to sell 0.1 BTC for XMR using BSQ as the security deposit.
- The Bisq software would reserve 0.1 BTC worth of BSQ (2,000 BSQ) in their wallet for the trade plus 15% security deposit in BSQ (300 BSQ) ready for the trade. This BSQ would be reserved and therefore not be available for other transactions. The BTC seller in this instance would have reserve 2,300 BSQ in their Bisq BSQ wallet.
- The offer would be shown in the Bisq offer book, offer book would indicate the security deposit is 300 BSQ.
- A BTC buyer takes the offer.
- An on chain multisig is created with the total deposit amounts (2,600) BSQ.
- The BTC buyer sends the XMR.
- The BTC seller for whatever reason does not complete the trade
- The BTC buyer then opens mediation
- Mediator confirms on chain the XMR has been sent and messages BTC seller to see why they have not sent the BTC.
- The BTC seller does not respond to the mediator
- Mediator proposes BTC buyer gets the majority of the combined security deposit for their inconvenience. This would be 2,500 BSQ. The proposal also includes the BTC seller getting 100 BSQ to incentivize them to accept the meditation proposal. 
- BTC buyer accepts the mediation proposal, BTC seller still remains unresponsive  
- BTC buyer sends the trade to arbitration
- On chain the BSQ multisig amount of 2,600 BSQ is burnt
- BTC buyer is successful at arbitration and receives the 2,500 BSQ as proposed in mediation. Arbitrator then requests this from the DAO as part of their normal compensation request.  

The BTC buyer is happy they get compensation from the seller's security deposit for their inconvenience. 

The DAO is happy that 2,600 BSQ was burnt and only 2,500 had to be compensated so the arbitration cost plus any BSQ printing costs have been covered.

Other benefits are:

- The BTC offer maker and taker can trade on Bisq with less BTC collateral
- BSQ becomes more useful when it can be used as collateral for traders
- Traders being compensated in BSQ for trades over 0.5 BTC now have a strong use case for their BSQ (offer collateral) so they are not pressured to immediately sell.
- The ability to use BSQ as collateral could be potentially useful for other applications in the future.

Negatives 

- I am assuming this is possible to use BSQ in this way, but imagine it would be complex to implement.
- Takers for BSQ security deposit offer would need BSQ to take the offers, this protocol might split the market.
- Volatility in price of BSQ, if the offers sit for too long on the offer book the collateral might be too low or too high both come with there own risks. However the collateral means that such trades sould be able to be resolved though agreement or cancelling via mediation or arbitration. An offer book filter could also be one solution to fix this issue.
- Compensated traders would be compensated via BSQ rather than BTC as is currently the case with trades resolved in mediation.
 
Things to consider

A large number of offers makers pay trade fees with BSQ and a large percentage of the higher trade volumes also pay trade fees with BSQ. Therefore, I am thinking that traders on altcoin markets will likely be familiar and comfortable enough to hold BSQ that it makes this a feasible protocol for traders that would rather receive than not receive compensation should they trade with an unresponsive peers. 

Also, maybe, a BSQ holder will be more familiar with Bisq and trades done with this protocol would be a lot less likely to end in arbitration.

**Comment by darawhelan** [comment]
Closing due to lack of feedback.

**Comment by HenrikJannsen** [comment]
Thanks for the proposal. 
Some things which makes BSQ not a prime candidate for security deposit are:
- BSQ is validated at blockchain confirmation. BTC can be used in unconfirmed state for the Multisig use case as a double spend would render all invalid.
- Price volatility of BSQ would add new risks
- Bisq only wants to use BSQ where it is needed and BTC cannot be used for it. Bisq does not want to push usage of BSQ for the sake of BSQ price/utility increase.
