### ISSUE TITLE
Safely compensate traders requiring arbitration

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#411]
### Rationale

After #386, the arbitrator does not pay one security deposit for security reasons, as an evil burningman could take profit from creating self trades. This is bad for the traders, who need to wait a long time to be reimbursed, and get no compensation for the time spent and the inconveniences caused. The security deposit is the amount that grants that a rogue burningman can't have a profit when 15% security deposit is used, but when traders set higher security deposits, it's possible to compensate the winner without putting the DAO in danger.
It needs to be considered that arbitration must be the last resource for traders, and that [distributing burningman](https://github.com/bisq-network/proposals/issues/385) role and its effects on the arbitrator should have a higher cost that needs to be subsidized with the security deposit from the peer who causes a trade going to arbitration. With that in mind, the compensated amount should not be very high.

### Proposal

Compensate the traders requiring arbitration with half of the extra amount that makes a burningman to be breakeven or have a small loss if he tried to create a self trade to take profit from the reimbursement.

### Details

I've checked with @refund-agent2 ond other contributors, and a reimbursement table like this could be applied safely:

Sec deposit % | Breakeven % | Compensation % | % BM keep 
-- | -- | -- | --
17.5 | 2.65 | 1.5 | 16
20 | 4.6 | 3.00 | 17
25 | 8.5 | 4.00 | 21
30 | 12.4 | 6.00 | 24
35 | 16.3 | 8.00 | 27
40 | 20.2 | 10.00 | 30
45 | 24.1 | 12.00 | 33
50 | 28 | 14.00 | 36
100 | 67 | 35.00 | 65

The % always refers to the trade amount. A trade using 18% as security deposit would get 1.5% trade amount as compensation and another one using 22% would get a 3%.
If this proposal has rough consensus, the payments could be automatically calculated, but this table gives an idea about what traders and the DAO should expect, and could be implemented sooner without waiting for a PR.

**Comment by MwithM** [comment]
It looks to me that this is approved, I miss some discussion or points that needed clarification but at least there's no one against it.

**Comment by pazza83** [comment]
I think it makes sense.

@refund-agent2 are you happy to start implementing this with trades that go to arbitration?

Is there anything else you need?

**Comment by refund-agent2** [comment]
Yes, from now on I will use this table.
I would like to have it implemented in the client, but that is not urgent.

**Comment by pazza83** [comment]
Ok will close this as approved.

@jmacxx is making changes to the client something you have the availability to take on?

**Comment by pazza83** [comment]
Hi @jmacxx 

Just following up. Are the changes to the client @refund-agent2 would like implemented on your to-do-list?

**Comment by refund-agent2** [comment]
No request has been submitted, I handle myself properly using the table above with no issues so far.

**Comment by pazza83** [comment]
Thanks, for the update. Will close this proposal as approved.
