### ISSUE TITLE
Boost BSQ trade fee usage

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/proposals#414]
Currently about 33% of trade fee revenue is coming from BSQ trade fees (59k BSQ) and the rest from BTC trade fees (128k BSQ).

<img width="1130" alt="Screenshot 2023-04-12 at 12 46 16" src="https://user-images.githubusercontent.com/116298498/231368699-1436f432-653a-4387-bd44-cc0c8e10ddf9.png">
<img width="330" alt="Screenshot 2023-04-12 at 12 49 47" src="https://user-images.githubusercontent.com/116298498/231368712-9df82b2b-fc08-473d-ad32-cec92dc38a76.png">

With the new distributed Burningman feature and the removal of the legacy BM the demand for buying BSQ in the BSQ market has decreased and the Bisq traders are the now the primary source for creating demand for BSQ. With the current BSQ/BTC fee ratio the demand for BSQ does not match the high supply (by refund agent BSQ sale, reimbursements from traders and contributors selling their BSQ).
This might become better once burningmen have drained their BSQ holdings and start to become active BSQ buyers on the market, but that might take some time (maybe in 1 year?).

We have seen already a decrease in BSQ price because of the imbalance of supply and demand and it could become more difficult for the refund agent and for traders who want to sell their reimbursed BSQ for BTC. Bigger changes in BSQ price also increase problems with volatility and incorrect pricing due the time delay from arbitration to reimbursement and the moment of BSQ sale.

To mitigate all that and to not risk that the BSQ price falls too far I suggest that we boost the usage of BSQ trade fees by increasing the discount and by promoting usage of BSQ for trade fees.

## Trade fee change

For a 1 BTC trade the current trade fees are:
Current BSQ maker fee: 14.29 BSQ about 12 EUR
Current BTC maker fee: 0.001 BTC (0.1%) about 27 EUR
<img width="235" alt="Screenshot 2023-04-12 at 14 10 59" src="https://user-images.githubusercontent.com/116298498/231379891-f0e7d22c-2248-47c6-b9e4-ebb304a4c169.png">

Current BSQ taker fee: 142.94 BSQ about 119 EUR
Current BTC taker fee: 0.01 BTC (1%) about 274 EUR
<img width="247" alt="Screenshot 2023-04-12 at 14 11 17" src="https://user-images.githubusercontent.com/116298498/231379905-547fef77-5724-4d5e-8927-749286e0c9de.png">

Using BSQ is about 44% of the cost of using BTC for trade fees or has a discount of 56%.

I suggest to increase that discount to reach about 80% by decrease BSQ fees by 50% and increase BTC fees by 10%.
I suggest those values:
New BSQ maker fee: 7.15 BSQ about 6 EUR
New BTC maker fee: 0.0011 BTC (0.11%) about 30 EUR

New BTC taker fee: 0.011 BTC (1.1%) about 303 EUR
New BSQ taker fee: 71.47 BSQ about 60 EUR

Using BSQ is then about 20% of the cost of using BTC for trade fees or has a discount of 80%.

Many small value fiat trades are covered by the min. trade fee. 
The current values are:
Min. BSQ maker and takerfee: 0.03 BSQ about 0.03 EUR
Min. BTC maker and taker fee: 0.00005 BTC about 1.37 EUR
<img width="244" alt="Screenshot 2023-04-12 at 14 26 19" src="https://user-images.githubusercontent.com/116298498/231383418-c9a1266e-c9ee-431f-9c0a-7c9dbf90f6dd.png">

Using BSQ is about 22% of the cost of using BTC for trade fees or has a discount of 78%. I think we do not need a change here as that is close to the intended 80% ratio. Also the low fees are probably not causing a change in user behavior even if we would increase the discount.

Beside the fee change we should promote BSQ trade fee usage by:
- Adding a popup for users who have no BSQ trades and not enabled BSQ trade fees to give them information about the discount and the importance of BSQ for the Bisq DAO
- Promoting the 50% BSQ trade fee reduction in social media and our communication channels.   
- Promote why using BSQ helps the Bisq ecosystem/DAO

**Comment by leo816** [comment]
I love the idea, It seems like a good incentive for there to be more demand of BSQ and avoid the downward spiral the demand is facing rn.

> This might become better once burningmen have drained their BSQ holdings and start to become active BSQ buyers on the market, but that might take some time (maybe in 1 year?).

I estimate the BSQ holdings for the new Burningmen will still take quite a while and we shouldn't really rely on that because with the decay it could turn out to be a perpetual burn for active contributors, only leaving out very few holders who are not actively contributing.

**Comment by suddenwhipvapor** [comment]
As a new onboarded contributor, after having read as much of the wiki as I could digest until now, I think this is a smart idea to fit the need to increase BSQ usage and value, without imposing rules like a central bank would do, but rather using the free market incentives.

**Comment by MwithM** [comment]
Is this measure temporary? 80% discount when paying in BSQ seems a lot to me for the long term, but I understand that right now is necessary as legacy BM can't buy BSQ anymore and the burningmen aren't buying BSQ as they still have BSQ to burn.
I would have preferred to increase BTC trading fees more, in order to not reduce BSQ trading fees by half but a little less, or not at all (something like 0.5% when paying in BSQ and 2% when paying in BTC, with a 75% discount when paying in BSQ).
If BSQ is used a lot to pay trading fees, they will have to be raised as the 0.8% trading volume target will be too far.

**Comment by pazza83** [comment]
> Currently about 33% of trade fee revenue is coming from BSQ trade fees (59k BSQ) and the rest from BTC trade fees (128k BSQ).

I think it is important to remember that that 33% of revenue represents about ~66% of traders choosing to use BSQ over BTC to get the ~50% discount.

66% of traders choosing to pay using BSQ seems good to me. Not sure what the target should be but I think getting to say 80% of traders using BSQ might be a ceiling. 

If we double the BSQ discount this will result in half the amount of BSQ being burned on trade fees. This would reduce revenue for the DAO, and currently the only 'revenue' the DAO gets is though burning men burning BSQ and traders choosing to pay in BSQ. Additionally traders would need to buy less BSQ for their trades which defeats the point of making BSQ more liquid. 

I think my preference would be to keep the current discount 50% and instead increase trading fees. The higher fees goes the more the incentive is for traders to use BSQ. Currently the combined BTC trading fee rate is 1.1% maybe this could be increased to 1.2%. 

- Maker 0.2% (50% discount with BSQ)
- Taker 1% in BTC (50% discount with BSQ)

Rough numbers would mean this would generate revenue of:

((1.2 x 0.66)/2) + (1.2 x 0.33)
= 0.396 + 0.396
= 0.792 % revenue as a percentage of trade fees

The target is 0.8% I think it would be good to continue to work towards this without making any sudden changes to the BSQ  discount.

> Beside the fee change we should promote BSQ trade fee usage by:
> 
> * Adding a popup for users who have no BSQ trades and not enabled BSQ trade fees to give them information about the discount and the importance of BSQ for the Bisq DAO
> * Promoting the 50% BSQ trade fee reduction in social media and our communication channels.
> * Promote why using BSQ helps the Bisq ecosystem/DAO

Agree with all this.

**Comment by HenrikJannsen** [comment]
> Is this measure temporary? 80% discount when paying in BSQ seems a lot to me for the long term, but I understand that right now is necessary as legacy BM can't buy BSQ anymore and the burningmen aren't buying BSQ as they still have BSQ to burn. 

Good question. Yes it is meant as temporary measure until we get the intended results.

> I would have preferred to increase BTC trading fees more, in order to not reduce BSQ trading fees by half but a little less, or not at all (something like 0.5% when paying in BSQ and 2% when paying in BTC, with a 75% discount when paying in BSQ). If BSQ is used a lot to pay trading fees, they will have to be raised as the 0.8% trading volume target will be too far.

I am open to that as well but I guess increasing too much the BTC fees might lead to negative feedback.

**Comment by HenrikJannsen** [comment]
> > Currently about 33% of trade fee revenue is coming from BSQ trade fees (59k BSQ) and the rest from BTC trade fees (128k BSQ).
> 
> I think it is important to remember that that 33% of revenue represents about ~66% of traders choosing to use BSQ over BTC to get the ~50% discount.
> 
> 66% of traders choosing to pay using BSQ seems good to me. Not sure what the target should be but I think getting to say 80% of traders using BSQ might be a ceiling.
> 

Good points! I also assume more then 80% will be hard to reach, so its actually just a 14% increase of users to use BSQ. The low revenue from BSQ seems to be then more from the discount rather from too little users using BSQ (which was my assumption initially).

**Comment by pazza83** [comment]
Yes, 66% of traders paying with a 50% BSQ discount will bring in more revenue than even 100% of traders paying with an 80% BSQ discount, even when BTC is excluded.

BSQ discount used to be adjusted when it reached 45% or exceed 55%. Now it is when it reaches 40% or exceeds 60%.  Since then traders have been getting an extra discount. Maybe this is not so bad as in future cycles they may not. Just a case of waiting more cycles to see how things play out.

**Comment by clearwater-trust** [comment]
> I would have preferred to increase BTC trading fees more

Careful, all contributors banking BTC fees should care about BSQ too.

wink and smile, but pretty serious. just sayin'  :heart:

**Comment by HenrikJannsen** [comment]
@pazza83 What numbers would you suggest?

**Comment by MwithM** [comment]
Let me suggest 1.3% when paying in BTC and 0.65% when paying in BSQ (current is 1.1% and 0.55%).
If 60% of traders use BSQ to pay trading fees and 40% use BTC, Bisq will get 0.91% trading fees from total trading volume. If 80% of traders use BSQ to pay trading fees (estimated ceiling) and 20% use BTC,  Bisq will get 0.78%  in trading fees.
You can check the [BSQ trading fees spreadsheet](https://docs.google.com/spreadsheets/d/1-hISy7F0NSqPnRxDOoi1k7df1qLJHfQTxhrVLt6NbX4/edit#gid=527097053) with the numbers for current data.

This won't boost BSQ trade fee usage a lot, but the numbers are already quite good, the problem is so little BSQ buyers in relation to reimbursements.

![image](https://user-images.githubusercontent.com/50149324/231740109-af5ced82-7230-45e2-8eb2-47a3b1d95ab7.png)

**Comment by pazza83** [comment]
> Let me suggest 1.3% when paying in BTC and 0.65% when paying in BSQ (current is 1.1% and 0.55%).

This looks good to me.

**Comment by HenrikJannsen** [comment]
I think we can close that in favor of https://github.com/bisq-network/proposals/issues/415 . If objections against closing let me know otherwise I will close it next days.

**Comment by pazza83** [comment]
@HenrikJannsen agreed, I also created an issue to add the available [BSQ balance to the menu bar](https://github.com/bisq-network/bisq/issues/6660)

Will discuss in the support chat the ways to promote BSQ usage.

> * Adding a popup for users who have no BSQ trades and not enabled BSQ trade fees to give them information about the discount and the importance of BSQ for the Bisq DAO

Are you still planning to implement this?

**Comment by HenrikJannsen** [comment]
> Are you still planning to implement this?

You mean the promotion of BSQ?

**Comment by pazza83** [comment]
@HenrikJannsen 

No, sorry I meant are you planning to introduce the pop-up.

I will bring up the promotion of BSQ in the next support call.
