### ISSUE TITLE
Increase trading fees to 1.3% (BTC) and 0.65% (BSQ)

### ISSUE THREAD

**Issue by MwithM** [bisq-network/proposals#415]
The goal to get 0.8% trading fees from all Bisq trading volume was never reached. BSQ needs to be used more than ever, since burningman won't buy BSQ from traders anymore.
Thus, I propose to raise the trading fees to a level that grants that with the current BSQ usage that goal is reached, while incentivizing those who still use BTC to start using BSQ to pay the trading fees. 
The 50% discount when trading in BSQ is left the same. 
If 60% of trades are done with BSQ, the revenue from trading fees (in BTC and BSQ together) will be 0.91%. Currently, the use of BSQ represents 66% of the trades. BSQ would need to be used for 80% of the trades to make it go under the 80% goal (0.78%).

  | Maker |   | Taker |   |  
-- | -- | -- | -- | -- | --
  | Current | New | Current | New | Total
BTC | 0,0010 | 0,0015 | 0,0100 | 0,0115 | **0,013**
BSQ | 14,29 | 25,66 | 142,94 | 196,69 | **222,35**

0.013 is the trading fee per 1BTC traded, and it's equivalent to 390USD.
222.35 BSQ is the trading fee per 1BTC traded, and it's equivalent to 195USD (50% discount using BSQ).

![image](https://user-images.githubusercontent.com/50149324/232409581-630a9565-867f-4e47-aa8a-aaac72be30e1.png)

If accepted, this proposal will close #409 and the change parameter part on #414

**Proposals:**
BTC maker txid: 6f680717f030ea42a2cdb2f30db689761c547e621f503dcd678756f6a3c5a598
BTC taker txid:  e9312ec03f6ef75824ba18a61ebdd51cb8da99533b1aba6c5f0d4f5631aa6a0a
BSQ maker txid: cf54b9e8b974148c7a12408556f45d289613f20c23b14cc024ba4978b4819da3
BSQ taker txid: ea84437015ed7e1e6586e9f6725f3170bd980c45a24620b55c5716bba1c4397a

See [spreadsheet](https://docs.google.com/spreadsheets/d/1-hISy7F0NSqPnRxDOoi1k7df1qLJHfQTxhrVLt6NbX4/edit#gid=527097053) for details.

**Comment by MwithM** [comment]
Proposals submitted with today's prices.

**Comment by MwithM** [comment]
Trading fees updated as all proposals were accepted.
Software filters updated.
Wiki updated.

Proposal must remain open to communicate whether updating the trading fee is necessary or not.

**Comment by apemithrandir** [comment]
Increasing the trading fees right before a huge bump in bitcoin on chain fees. I think this will lead to Robosats adoption and a decline in overall Bisq fee revenue and is not well thought out.

Also if the goal is to get more people to use BSQ then we should try to understand better why people don't use BSQ.

I could imagine a good deal of Bisq users do not use BSQ due to ideological reasons (bitcoin maxis) and would fee hiking fees on people who refuse to use BSQ as showing that they are less welcome on the platform.

**Comment by Conza88** [comment]
> Increasing the trading fees right before a huge bump in bitcoin on chain fees. I think this will lead to Robosats adoption and a decline in overall Bisq fee revenue and is not well thought out.
> 
> Also if the goal is to get more people to use BSQ then we should try to understand better why people don't use BSQ.
> 
> I could imagine a good deal of Bisq users do not use BSQ due to ideological reasons (bitcoin maxis) and would fee hiking fees on people who refuse to use BSQ as showing that they are less welcome on the platform.

As a Bitcoin maxi, coloured bitcoin is fine.

The only time it's ok to sell bitcoin, with it's not spend and replace, is with its so you can buy more bitcoin with cheaper fees. 😉

I've *clearly* indicated years ago+ why/how BSQ adoption could be improved. Some steps certainly in the right direction over that time. 

Actually calling it out more prominently a possible option.

**Comment by pazza83** [comment]
> Increasing the trading fees right before a huge bump in bitcoin on chain fees. I think this will lead to Robosats adoption and a decline in overall Bisq fee revenue and is not well thought out.

I think it will be the high miner fees rather than the fees that make users of small trades look elsewhere. There have been significantly less trades on Bisq this cycle due to the high fees.

April = 184 trades per day
May = 134 trades per day (to date)

> Also if the goal is to get more people to use BSQ then we should try to understand better why people don't use BSQ.

Quite a high percentage of traders are using Bisq, about 70% of trade fees are paid in Bisq. Would be good to increase it further but it is not a low percentage.

**Comment by pazza83** [comment]
> I've _clearly_ indicated years ago+ why/how BSQ adoption could be improved. Some steps certainly in the right direction over that time.

Can you point to a link again.

Would be good to know what has been actioned and what still needs to be actioned.

**Comment by MwithM** [comment]
_This proposal keeps a record of the [process](https://bisq.wiki/Updating_BSQ_trading_fees) to keep the BSQ trading fee at the target discount to BTC trading fee. It will remain open until we need to update BSQ trading fees again._

Last update was #409 

## Cycle 47
**Parameters** ([see issue](https://github.com/bisq-network/proposals/issues/289))
* USD/BTC price: 27.200
* USD/BSQ price: 0.82
* Current BSQ discount: 48.4% 

![image](https://github.com/bisq-network/proposals/assets/50149324/0c80e3fd-4e41-4be6-8465-488a061a3fcc)
![image](https://github.com/bisq-network/proposals/assets/50149324/13e61bb2-e337-4b15-af7a-25216d9e7a3e)

It's **not necessary to update BSQ trading fee** as current discount is between the 40-60% target.

**Comment by MwithM** [comment]
_This proposal keeps a record of the [process](https://bisq.wiki/Updating_BSQ_trading_fees) to keep the BSQ trading fee at the target discount to BTC trading fee. It will remain open until we need to update BSQ trading fees again._

Last update was #409 

## Cycle 48
**Parameters** ([see issue](https://github.com/bisq-network/proposals/issues/289))
* USD/BTC price: 26.500
* USD/BSQ price: 0.77
* Current BSQ discount: 50.3% 

![image](https://github.com/bisq-network/proposals/assets/50149324/15a49f96-b90a-4685-86c7-be9b619c0ccc)
![image](https://github.com/bisq-network/proposals/assets/50149324/392d535e-01d3-41a0-bce0-6f6eec118cfb)

It's **not necessary to update BSQ trading fee** as current discount is between the 40-60% target.

**Comment by MwithM** [comment]
_This proposal keeps a record of the [process](https://bisq.wiki/Updating_BSQ_trading_fees) to keep the BSQ trading fee at the target discount to BTC trading fee. It will remain open until we need to update BSQ trading fees again._

Last update was #409 

## Cycle 49
**Parameters** ([see issue](https://github.com/bisq-network/proposals/issues/289))
* USD/BTC price: 29.800
* USD/BSQ price: 0.83
* Current BSQ discount: 52.4% 

![image](https://github.com/bisq-network/proposals/assets/50149324/d467ec20-3cc1-4af0-8cda-546f1864a6f3)
![image](https://github.com/bisq-network/proposals/assets/50149324/09256d5a-0b46-47f2-887f-ffe6defee581)

It's **not necessary to update BSQ trading fee** as current discount is between the 40-60% target.

**Comment by pazza83** [comment]
Hi @MwithM 

FYI, the trade fee filter has been turned back on with the updated fee filter PR: https://github.com/bisq-network/bisq/pull/6670

This means that the filter will need updating with the BSQ rates should the values change at any point.

Thanks

**Comment by MwithM** [comment]
_This proposal keeps a record of the [process](https://bisq.wiki/Updating_BSQ_trading_fees) to keep the BSQ trading fee at the target discount to BTC trading fee. It will remain open until we need to update BSQ trading fees again._

Last update was #409 

## Cycle 50
**Parameters** ([see issue](https://github.com/bisq-network/proposals/issues/289))
* USD/BTC price: 26.000
* USD/BSQ price: 0.79
* Current BSQ discount: 48% 

![image](https://github.com/bisq-network/proposals/assets/50149324/c93deae4-bc51-47bf-b418-6cb183397638)
![image](https://github.com/bisq-network/proposals/assets/50149324/7938a8b2-9bde-4744-bc8f-e032150da999)

It's **not necessary to update BSQ trading fee** as current discount is between the 40-60% target.

**Comment by MwithM** [comment]
_This proposal keeps a record of the [process](https://bisq.wiki/Updating_BSQ_trading_fees) to keep the BSQ trading fee at the target discount to BTC trading fee. It will remain open until we need to update BSQ trading fees again._

Last update was #409 

## Cycle 51
**Parameters** ([see issue](https://github.com/bisq-network/proposals/issues/289))
* USD/BTC price: 27.000
* USD/BSQ price: 0.79
* Current BSQ discount: 50% 

![image](https://github.com/bisq-network/proposals/assets/50149324/184c5c0e-251d-4768-aaa9-64d43594e4b6)
![image](https://github.com/bisq-network/proposals/assets/50149324/a13ab247-ccbf-416b-9661-347f49a8d0d9)

It's **not necessary to update BSQ trading fee** as current discount is between the 40-60% target.

**Comment by MwithM** [comment]
Closed as an update was required.
