### ISSUE TITLE
Bisq_Lebanon

### ISSUE THREAD

**Issue by JS119** [bisq-network/proposals#417]
It is well recognized that people in MENA are losing their trust on banking institutions and looking for other alternatives like Cryptos. They are more open for basic financial services like opening an account (crypto wallet), storing the funds, performing local and international transactions freely without additional cost. The problem is that governments banned crypto currencies in some countries, and in some cases, there is no local exchange or platform where people can buy BTC or others cryptos. Added to that, some economies around the world suffering with financial restriction to buy FIAT and to move money abroad the country. Thus, peer to peer trading based is the solution to the failed banking system. In other words, people can transact worldwide freely.
Banks in Lebanon and Egypt block bank cards to trade bitcoin. We will start focusing on Facebook, Instagram and Twitter working on Ads and developing communities. But before that, people need to buy bitcoin in Lebanon. I am gonna work on that. I am going to teach people how to buy & sell bitcoin & how to save bitcoin in a wallet. The first step is to teach people how to buy bitcoin. Then save them in a wallet.

**Comment by pazza83** [comment]
Hi @JS119 

Thanks for the interest in promoting Bisq in Lebanon.

Have a look at how to create a proposal in Bisq here: https://bisq.wiki/Proposals

Have you tried doing any trades on Bisq in Lebanon? If so are there any pain points you have found?

**Comment by JS119** [comment]
> Hi @JS119
> 
> Thanks for the interest in promoting Bisq in Lebanon.
> 
> Have a look at how to create a proposal in Bisq here: https://bisq.wiki/Proposals
> 
> Have you tried doing any trades on Bisq in Lebanon? If so are there any pain points you have found?

Hi, no worries. Thank you. Are you the founder of bisq ? Do i get paid for that ?

**Comment by pazza83** [comment]
I am not a founder. I am a Bisq contributor.

You are not paid for making a proposal.

The idea of a proposal is outline what improvements you think could be made to Bisq. If work is needed to make these improvements you can suggest the budget for doing the work. This can then be approved or rejected by the DAO.

**Comment by JS119** [comment]
> I am not a founder. I am a Bisq contributor.
> 
> You are not paid for making a proposal.
> 
> The idea of a proposal is outline what improvements you think could be made to Bisq. If work is needed to make these improvements you can suggest the budget for doing the work. This can then be approved or rejected by the DAO.

Hi
I have written the proposal. More details can be discussed. The most important thing is to accept my proposal & then we can agree on details like how to get paid in bitcoin.

**Comment by JS119** [comment]
> > I am not a founder. I am a Bisq contributor.
> > You are not paid for making a proposal.
> > The idea of a proposal is outline what improvements you think could be made to Bisq. If work is needed to make these improvements you can suggest the budget for doing the work. This can then be approved or rejected by the DAO.
> 
> Hi I have written the proposal. More details can be discussed. The most important thing is to accept my proposal & then we can agree on details like how to get paid in bitcoin.

Hi
I have edited the proposal , check it plz
Thanks

**Comment by suddenwhipvapor** [comment]
> > I am not a founder. I am a Bisq contributor.
> > You are not paid for making a proposal.
> > The idea of a proposal is outline what improvements you think could be made to Bisq. If work is needed to make these improvements you can suggest the budget for doing the work. This can then be approved or rejected by the DAO.
> 
> Hi I have written the proposal. More details can be discussed. The most important thing is to accept my proposal & then we can agree on details like how to get paid in bitcoin.

Bisq compensations work on the basis of contributions delivered, after a detailed plan has been laid out, discussed, and approved, and contributors are paid in BSQ, not BTC.
Your proposal is basically saying "Banks bad, Bitcoin good, Lebanon in crisis, I teach Bitcoin to lebanese people, but first pay me", and this is not how it works.

First of all, Bisq already has a twitter account, no point marketing there.
How do you plan, exactly, to bring on your marketing campaign on facebook and instagram? What do you have planned, exactly, to teach Bitcoin to lebanese people? Do you even have the confidence to gain your people's interest in participating in a seminar, webinar, or the thing that you have in mind?

**Comment by JS119** [comment]
> > > I am not a founder. I am a Bisq contributor.
> > > You are not paid for making a proposal.
> > > The idea of a proposal is outline what improvements you think could be made to Bisq. If work is needed to make these improvements you can suggest the budget for doing the work. This can then be approved or rejected by the DAO.
> > 
> > 
> > Hi I have written the proposal. More details can be discussed. The most important thing is to accept my proposal & then we can agree on details like how to get paid in bitcoin.
> 
> Bisq compensations work on the basis of contributions delivered, after a detailed plan has been laid out, discussed, and approved, and contributors are paid in BSQ, not BTC. Your proposal is basically saying "Banks bad, Bitcoin good, Lebanon in crisis, I teach Bitcoin to lebanese people, but first pay me", and this is not how it works.
> 
> First of all, Bisq already has a twitter account, no point marketing there. How do you plan, exactly, to bring on your marketing campaign on facebook and instagram? What do you have planned, exactly, to teach Bitcoin to lebanese people? Do you even have the confidence to gain your people's interest in participating in a seminar, webinar, or the thing that you have in mind?

Hi
I am for example preparing for a course about bitcoin and I am knowleadgable about bitcoin & blockchain.
I can market bitcoin & I feel more than happy to market it more. We can do seminars in arabic language. But I need to be paid in bitcoin not bisq. Do u pay bisq or bitcoin? 
Thanks

**Comment by pazza83** [comment]
Hi @JS119 

All contributors are paid in BSQ. No payments are made in bitcoin.

For information on contributing please see:

https://bisq.wiki/Contributor_checklist
