### ISSUE TITLE
Community members aren't being active 

### ISSUE THREAD

**Issue by Thegreatbrossard1** [bisq-network/proposals#418]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

**Comment by pazza83** [comment]
Hi @Thegreatbrossard1 

The proposal is incomplete.

Please see here a guide to creating proposals:

https://bisq.wiki/Proposals

I will close this issue. Please feel free to create it as a complete proposal
