### ISSUE TITLE
Bisq on Bitcointalk

### ISSUE THREAD

**Issue by icopress** [bisq-network/proposals#419]
> 
> ## Description
Bitcointalk, the original Bitcoin forum, is still not only a quality discussion platform, but also a great place to promote privacy-focused projects. Advertising on Bitcointalk through a signature campaign has a lot to do with what is called Top-of-Mind. 
- Firstly, because the promotion of any project occurs without an explicit indication.
- Secondly, Bitcointalk ranks very high in the bitcoin niche.

Forum users are mostly familiar only with centralized exchangers, the use of which somehow provides for KYC. I think that if we were to resume our presence on Bitcointalk, then most of those who have a need to keep their finances anonymous would choose Bisq. This is exactly the argument that will tell people that the use of Bisq Network is based on elementary household caution.

> ## Rationale for the launch Signature Сampaign
Each forum user has the opportunity to place a bbcode in their personal settings, which will be displayed under each message they write. Users use this personal space either for personal purposes or rent it out to companies interested in advertising.

Advertising is shown under the member's profile through discussions in various sections of the forum without an explicit indication. It's completely voluntary and even if it's not direct clicks it definitely subconsciously settles in the minds (**below**).

![re](https://i.ibb.co/ZVJ2rHn/photo-2023-05-10-14-50-56.jpg)

Best candidates will be Bitcoiners to the core. Such users will form a positive public opinion about the project and in parallel, for the most part, we will get rid of the need for support in the thread, since all these users will partly take on this role.

Hired users should have a long history of posts (since the bbcode of the signature is also a "do-follow" link), because by setting a signature, it will be displayed under all previously written posts. Thus, if we hired 15 users, each of whom posted 4,000 posts earlier, then we will receive 60,000 bbcode banners, (not counting those posts that will be published in the future).

Also, when hiring, the manager pays attention to how active and authoritative a particular user is in his local section, therefore, by hiring influencers, he manages to evenly fill the forum with advertising so that not only English-speaking users know about the project. Seeing that opinion leaders approve of the use, users subconsciously perceive the advertised project as reliable.
> 
> ## Basic information

We can also use a tracker link to track traffic. From the point of view of expediency, the most objective fact of the assessment is whether competitors have signature campaigns (how many participants and how long campaigns of other projects last).

- Number of page views per day on Bitcointalk 900,000 & 30,000 posts [published](http://loyce.club/active/7d.html) weekly.
- There are 3.5 million registered people on Bitcointalk.
- Currently, 24 projects [have](https://bitcointalk.org/index.php?topic=615953.0) a signature campaign (information is updated weekly).
- The longest active campaign lasts continuously for 220 weeks.
- At the moment, the largest campaign has 112 participants.
- In the highest paying campaign, users receive $150 per week.

> ## Budget

A total of 15 campaign participants will generate up to 1800 organic posts per month (posts at least 200 characters long without any nonsense or spam). This is a preliminary estimate and we may adjust the package based on Bisq's capabilities.

- Need 15 participants in the campaign to cover the sections where the technical discussion is taking place.
- Taking the average value as a basis, hiring 1 tech savvy poster will cost 0.003 btc per week.
- The total monthly spending will be 0.2 btc (15 participants * 0.003 btc * 4 weeks) + 0.02 btc.

> ## Implementation

- The author of this proposal is a campaign manager and is also the [65th](https://bpip.org/Profile?id=1137579) most trusted Bitcointalk user.
- [Here](https://bitcointalk.org/index.php?topic=5251894.msg59035912#msg59035912)'s an edited old post confirming that this proposal comes from icopress's name.

The duties of the manager include the control of the obligations assumed by the users, the creation of bbcode banners and any other necessary design materials. Spreadsheet maintenance (for statistical accounting), timely processing of weekly payments and taking control of information noise using telegram bot (tg bot notifying about any mentions of the project).

- Work experience and my сompetence can be checked [here](https://bitcointalk.gitbook.io/sig/summary/experience).

If my proposal are approved, the next step will be a two-week preparation for the implementation of the ideas described in this proposal. The declared amounts include all major expenses, as well as the time and effort associated with the fulfillment.

**Comment by HenrikJannsen** [comment]
Thanks for the proposal. 
I am confident that you are very professional in executing such a campaign.

Though I am not in favor of such types of marketing as it is against my ethos.

I am aware that many ppl (specially those from the US) have no problem with trading reputation for advertising, but to me it gets a pretty negative smell both on the person selling their reputation and on the project buying it.

If I see a profile which has earned reputation by quality content adding some banners which clearly looks like a paid campaign (specially if others do the same its clear that its a paid campaign), I would immediately downgrade that users reputation. And I also downgrade my respect for the project being advertised that way. I got even surprised that Wasabis is doing that and I respect them a bit less now.

One reason why I react like that is that it shows that the person behind the profile is not an independent expert in some field (and make his living from that) but earns money by his communication work, thus shows he is doing that as job and not for altruistic reasons. I tend to trust experts who say what they think without dependencies on financial gains more.

That's my personal feeling and opinion and I am aware that others (whom I highly respect) have a different view on that. 
But Bisq has proven over many years that it has built up a great reputation and brand awareness without any classical marketing. I also guess that its one of the reasons for that high reputation. I think the potential damage of changing that path is larger than the potential gain.

Beside that, I doubt that Bitcointalk users are really our target group. They are usually aware of Bisq already. Those are usually oldschool crypto ppl (not sure who is around there today, I guess lot of scammers as well, as it has been also in earlier days) and not newbies. 
So I doubt that the invested money would be justified by the expected revenue increase, independent to the above statements.

**Comment by leo816** [comment]
I agree with @HenrikJannsen 's assessment. While the bitcointalk community might be our target, they likely already know about bisq and I wouldn't push advertisement in such way when Bisq has been doing well by just having a great product. Besides educational content, I believe the deployment of Bisq 2.0 is the best possible advertisement.

**Comment by icopress** [comment]
[@HenrikJannsen](https://github.com/HenrikJannsen), your opinion is erroneous (maybe it's my fault, since I did not fully disclose some of the nuances because I wanted to be as brief as possible). The essence of this strategy is that we invite to the campaign only those users who would publish posts even if there were no campaigns.

So I don't see how this can go against your spirit, given that the users I would invite to the Bisq campaign are extremely picky about advertisers and have their own independent opinion. Yes, it's true that a lot of people post to get paid, but these spammers can be seen from a mile away... and such people have no chance of getting into a campaign that includes real Bitcoin maximalists.

Below I have given an example of the post history of two users who are involved in two different campaigns, and if you take a quick look at their writing style, you will immediately understand what I mean by "independent opinion" and "high-quality posters".

- https://bitcointalk.org/index.php?action=profile;u=1188543;sa=showPosts
- https://bitcointalk.org/index.php?action=profile;u=3373858;sa=showPosts

**Comment by pazza83** [comment]
Closing as rejected
