### ISSUE TITLE
Proposal: Increase Bisq's Reach with Fonbnk Integration (Payment Method Request)

### ISSUE THREAD

**Issue by nickfonbnk** [bisq-network/proposals#422]
Dear Bisq Team,

I'm Nicolas from Fonbnk, a platform transforming prepaid mobile SIM cards into digital currency for unbanked populations. We propose integrating Fonbnk into Bisq's payment methods.

This integration allows Bisq to tap into a massive, under-served market. Our non-custodial, no-chargeback service offers security and peace of mind for users, enhancing the trustworthiness of Bisq's transactions.

Fonbnk's low/no-code implementation ensures an effortless, quick integration process, reducing technical barriers and costs. By offering an alternative to traditional banking systems, Fonbnk extends Bisq's accessibility to unbanked individuals globally.

Let's discuss this potential market expansion. We're ready to bring this value to Bisq's network.

Please see a demo of our PayWidget here: https://twitter.com/fonbnk1/status/1624170773920243731?s=20

Please see our info deck here: https://docsend.com/view/yd4cn7n5avk7d4na

Best Regards,
Nicolas
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

**Comment by pazza83** [comment]
Hi @nickfonbnk 

Will mark this proposal as rejected due to lack of feedback.

Inclusion of a payment method would be better posted to the growth repository:

https://github.com/bisq-network/growth/issues
