### ISSUE TITLE
BSQ Affiliate Program

### ISSUE THREAD

**Issue by clearwater-trust** [bisq-network/proposals#425]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

Gamify BSQ marketing through hidden service Tor keys and BSQ.

Allow users to post link appending their hidden service ID.

Users are rewarded BSQ using DAO for payouts and payout schedule.

Or, use whatever ID scheme to point back to user.

Affiliate Marketing.

Rewarding correct behavior always works.

**Comment by pazza83** [comment]
Closing as stalled due to lack of feedback
