### ISSUE TITLE
@BisqSeed0101 to post bond for seednode operator

### ISSUE THREAD

**Issue by ghost** [bisq-network/proposals#426]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

This proposal is for @BisqSeed0101 to become a bonded Seednode Operator. 

Reference: https://github.com/bisq-network/roles/issues/15

**Comment by pazza83** [comment]
Closing as invalid as user to longer github member
