### ISSUE TITLE
@403State to post bond for Bisq2 seednode operator

### ISSUE THREAD

**Issue by 403State** [bisq-network/proposals#428]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

This proposal is for @403State to become a bonded Seednode Operator.

Reference: https://github.com/bisq-network/roles/issues/15

**Comment by 403State** [comment]
Proposal txid: 9df8d9b7c44e2c145efe8bd9712cc328b37d7cb9b3e0b7a4efa406425bc181c8

**Comment by 403State** [comment]
Bond TxId:
91da8e25f2de2120f3afd1848a724ad14f14788556af5fb17872f15b1ec42aed

**Comment by pazza83** [comment]
This proposal was accepted by a DAO vote in cycle 51.

Closing as approved
