### ISSUE TITLE
Content of the proposal details should be committed when proposal phase is over 

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#43]
When a contributor files a proposal in the Bisq app they have to add the link to the Github issue where the content of the proposal is described.

Once the proposal period has ended the content of that link should be persisted to an immutable datastore so it cannot be changed or deleted. 

It would be good if we can use the Github API to snapshot the issue and then commit it. It would be also good if the data is still readable (html) but I think that is not a hard requirement. It can be expected that there are no conflicts anyway which require to lookup an old proposal.
Not sure what would be the best and easiest way how to implement that. A special service which gets triggered by the first block after the proposal phase to snapshot the issues and then make a commit of that data. Multiple nodes (e.g. seed nodes) could do that and before committing they check if there is already a commit with that hash.

I am not sure if that feature is really important at least for the start probably not. But I wanted to write it down here for discussion and to for maybe implementing it later.

**Comment by cbeams** [comment]
> It would be also good if the data is still readable (html)

Should be possible (and preferable) to get the content as Markdown.

**Comment by sqrrm** [comment]
I think it needs to be committed for that cycle only. Might be nice to store for the future but that doesn't seem like a requirement.

It's probably good to not tie in the commitment format with github but apart from that I agree that using the API so snapshot sounds good.

**Comment by devinbileck** [comment]
There is a related discussion in https://github.com/bisq-network/proposals/issues/72#issuecomment-463548384 that mentions using PRs instead of issues for submitting proposals, and including a sha256 hash of the proposal content in the commit message (and potentially included when submitting the proposal). This should help in persisting the proposals (since contributors would have a copy of the repo) and ensuring they are immutable.

**Comment by MwithM** [comment]
closing as stalled
