### ISSUE TITLE
Application to become a bonded explorer operator

### ISSUE THREAD

**Issue by runbtc** [bisq-network/proposals#434]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I am applying to become a bonded explorer operator.
I am capable of running and maintaining a reliable mempool explorer instance.
I am aware of the requirements to post a bond of 10,000 BSQ.

Reference: https://github.com/bisq-network/roles/issues/107

**Comment by runbtc** [comment]
Proposal TxID 4cd540f7a71c6ce94f587a3327470475c1bf5208ad5ff60226c07b12543bb934

**Comment by pazza83** [comment]
This proposal was approved by DAO vote in cycle 53. @runbtc once you have posted the bond please comment here and I will close this issue. Thank you.

**Comment by runbtc** [comment]
Bond locked up.
dc17e860d467434467b1987a554e72c9dabaaed5a6fc94237db5e4a62a0900bd

**Comment by pazza83** [comment]
Closing as bond locked up
