### ISSUE TITLE
Application to become a mediator for Bisq 2

### ISSUE THREAD

**Issue by solomon1923** [bisq-network/proposals#436]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I am applying to become a bonded mediator for Bisq 2.

I am aware of the requirements to post a bond of 5,000 BSQ for the role.

Reference:  https://github.com/bisq-network/roles/issues/83

**Comment by solomon1923** [comment]
a7c59ad2d34ca06cdc50e2501eb845f6a036c46b97fcaf9739a413adb70b9742

**Comment by pazza83** [comment]
This proposal was approved by DAO vote in cycle 53. @solomon1923 once you have posted the bond please comment here and I will close this issue. Thank you.

**Comment by solomon1923** [comment]
@pazza83 I have locked up my bond for the mediator role.

91799443c4e664a46fd92f1301d9a78996163c92047ad0176bb6dd5c04011773

If anything else is required please let me know.

**Comment by pazza83** [comment]
Thanks, closing as complete
