### ISSUE TITLE
Application to become a mediator for Bisq 2

### ISSUE THREAD

**Issue by luis3672** [bisq-network/proposals#439]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I am applying to become a bonded mediator for Bisq 2.

I am aware of the requirements to post a bond of 5,000 BSQ for the role.

Reference: https://github.com/bisq-network/roles/issues/83

**Comment by luis3672** [comment]
a5632d6205ad750b45972d587230744b54e3a594254d379c06a746ff126368dd

**Comment by pazza83** [comment]
This proposal was approved by DAO vote in cycle 55. @luis3672  once you have posted the bond please comment here and I will close this issue. Thank you.

**Comment by pazza83** [comment]
Closing as accepted., bond locked with tx id: 1f0762a8180501755d306084f2d89d34478d874747a0f1c31125a32a88745d73
