### ISSUE TITLE
Support offline offers

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#44]
One solution for the problem that the offer maker need to be online could be that we offer a new feature with a new type of offer.
This new type - lets call it "trade intent" - would not have BTC reserved and a taker cannot take it directly. It would only give an option that an interested taker can contact the maker and then the maker receives a message and has to go online to convert his intent into a real offer. Then the taker receives a message so that he can browse that offer and can take it.
So there would be an out-of-system notification method required which helps to bring both parties online at the same time.

Here of course is the challenge which notification system we can use which does not require a running Bisq app. It could be simply email or any messenger but that comes with privacy and security (phishing) risks and it will not integrate well with the process.
Better would be a proxy system where the messages are routed over our P2P network and utilize the Bisq mobile app. There though we have atm only the solution where your Bisq app need to be online, but there are ideas/discussions to extend that model to support offline mode. 
Unfortunately there is no perfect trust-minimized way to achieve that, but at least it might be useful for those who prefer convenience and it would extend the reach of Bisq to such users and with that increase liquidity.

Just wanted to push that idea out for further discussion and conceptual refinement if it is considered worth to go further.

**Comment by clearwater-trust** [comment]
Would it require any kind of security deposit to post a "trade intent"?  I like the idea of an offline trade option. There is a risk of it becoming meaningless if nobody ever responds to their intent.  Maybe a small percentage of earnest money would keep everybody honest?

Is it possible to let the traders decide how to be notified?  My contact info is [insert contact info] - If they want to use email/sms/phone/walkie-talkie/smoke-signals, they are free to do so.

**Comment by initCCG** [comment]
Maybe make like a ghost of existing offer, if maker checks "Display while offline, until deleted online"?

**Comment by ManfredKarrer** [comment]
@clearwater-trust 
I have not tough much about the details... but basically the intent could be treated as a normal offer, so u pay the fee and reserve the required funds in your wallet. That helps to avoid spam and does not require an extra step later when the user goes online. So the intent is just a special form of an offer which was taken offline.  

Yes maybe we can just leave it up to the maker how he wants to get contacted. I just fear that not having a integrated standard it will make the process more manual... but will require more detail work on it to see if that is the case.

@initCCG Yes, "ghost offer" is a nice image ;-)
 It should be easy to the user and maybe it is default any offer where the maker goes offline stays as "ghost" and a taker can trigger a "wake up call". For the taker maybe we also would need some "costs" to avoid spam behavior. Not sure if a fee payment is here good as he might move over to other offers if the maker does not respond fast. But maybe its enough if the funds needed for the taking are reserved so he has less available funds in the wallet. That should add enough protection here to avoid abuse.

**Comment by initCCG** [comment]
Yes, cost for taking a ghost offer seems necessary to prevent abuse.

My guess is ghosts will increase your arbitrators' work, because makers lose their wallets, or something, and can't wake up the ghost.

That seems to lead to making ghosts expire after a few days, if not taken, or if they cause arbitrator intervention.

That also seems to lead to making offers expirable, if no one takes them, which would also increase arbitrator involvement, and maybe involve some kind of CHECKLOCKTIMEVERIFY mechanism?

Guess the ghosts will have to be kept online by online peers passing them to each other?

**Comment by ManfredKarrer** [comment]
We have a TTL and if that time expires the peers are removing the offer. We can change that behaviour so that once a certain time passed and the maker has no send a update msg which updates the TTL the offer will not be removed but will be marked as offline. When a taker takes an offline offer it triggers the notification to the maker. The taker can choose how long he is willing to wait until the maker comes online, after that time his reserved funds are unlocked again. Here is though a problem. It can be that when the maker comes online that the taker is offline ;-( . As the take offer process is requires both to be online there is a bit of coordination problem....
Hm, no good idea atm how to deal with that best.

**Comment by initCCG** [comment]
Depending on how take offer process works, is there something useful for this in the new bip-174?
