### ISSUE TITLE
 Application to become a moderator for Bisq 2 

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/proposals#441]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I am applying to become a moderator for Bisq 2.

I am rounding up the required 5,000 BSQ for the bonded role, and will post a bond ASAP

Reference: [bisq-network/roles#83](https://github.com/bisq-network/roles/issues/83)

**Comment by suddenwhipvapor** [comment]
`c81d29c276e3254cf451c6e55d5e44e61a6b87c0f550a56ea7834324c2601f8f`

**Comment by suddenwhipvapor** [comment]
Thank you for your support :-)

**Comment by pazza83** [comment]
This proposal was approved by DAO vote in cycle 53. @suddenwhipvapor once you have posted the bond please comment here and I will close this issue. Thank you.

**Comment by suddenwhipvapor** [comment]
I have just locked the required 5000BSQ bond

**Comment by pazza83** [comment]
Closing as complete. Bond locked:

ba7aba64c8136afc173093023576c68cd4090916bd75e8e69db31e028418cabc
