### ISSUE TITLE
Plan for Projects Maintainer role: First Stage

### ISSUE THREAD

**Issue by pazza83** [bisq-network/proposals#446]
## Background

For a while I have been saying on my compensation requests in contributions in progress the following:

> I am going to have a think about what might be needed to a Project Maintainer role. I have access to the Projects repository and will start to do some tidying up. I am also looking to form clearer links between accepted proposals and completed work / projects. Ideally people will be able to see what proposals have been approved and what the current state of it is now (work completed, stalled, retired etc).

This proposal is for me to define what that role is prior to getting started on it. I do not want to start messing around with the proposals and projects repositories without consensus!

## Description

When proposals are approved on Bisq they are not always actioned. Either due to lack or resources or other factors. When projects are created they often do not get updated.  This makes it hard for interested users to know what the status is of Bisq proposals and projects.

I think it would be better for the Bisq Projects repository to be used for the creation of 'approved proposals'. Where the status of the approved projects could be viewed. 

The workflow should be as follows:

1. User makes a proposal on proposals repository 
2. Proposal get accepted 
3. If proposal is actioned / completed within a month a comment should be made on the proposal to sate this.
4. If proposal is not actioned / not completed after a month a project should be created on the Bisq project repository. A comment can be made on the proposal linking the the newly created project and the proposal can be closed as approved
5. The open projects in the Bisq project repository will then be the projects being worked on. 
6. Once the project has been delivered a comment should be made to that effect and closed as completed.
7. If the project gets stale, superseded, abandoned etc, then a comment should be made to that effect and the project should be closed.

This way the Projects repository on Bisq will be a good way for users, existing and potential contributors to see what is happening with regards the development of Bisq.

## Rationale

According to the wiki the purpose of the project management process is to ensure we:

- Work on what's most important.
- Finish what we start.
- Stay within our budget.
- Don't spread ourselves too thin.

To this end good communication is important. Having a place for users and contributors to see at a glance what is happening will facilitate better teamwork and accountability. 

### First Stage

I think a realistic criteria for this work would to start with organizng the proposals and projects repositories. This would involve:

1. Assigning a project owner for each project
2. Ascertaining the status of the project from the project owner
3. Closing any projects that are now defunct  
4. Creating new projects for approved proposals that are yet to be actioned / assigning them a project owner / getting a status update / closing any that are now defunct  
5. Changing the process from anyone being able to open a project to only contributors that have has proposals approved can open projects
6. Updating [proposals](https://bisq.wiki/Proposals) and [projects](https://bisq.wiki/Project_management) wiki with the new info / process. 

### Second Stage

Once the above has been achieved then the second stage of what is needed might be more clear. Prior to starting I think it **could** involve **some** of the following:

- Assigning other involved contributors to projects 
- Ensure each project has the following;
    -  measure of success, 
    -  risks,
    -  tasks that need to be completed along with who is responsible for them,
    -  timescales, 
    -  cost estimates
 - If the project is large milestones should be identified
 - Sign off from Team Leads for any budgets involved
 - If the Project has changes from it's proposal, or significant new information has been added, then the project should required approval ideally through a rough consensus or if needed a DAO vote

It should be noted that I do not think the above would not be achievable by any one person. I see the Projects Maintainer role more about putting in place a process and then making sure it is followed (in the same way the proposals process is currently managed).

## Measures of success

Initially achieving points one to 1 to 6 from the First Stage, and once achieved come back with a new proposal for what the second stage should be.

## Risks

There are no risks I can think of for the first stage, other than I might annoy people by chasing them up about their previous proposals or projects!

For the second stage there might be risks in that some work moves from being autonomously done by contributors to work having to be approved as a proposal and then again as a more defined project. I think there is a balance to be had with what the project is and also the size of Bisq as an organization. It would not be good for additional processes to hinder development, but at the same time it would not be good for work to take place with lack of consensus of the above. This can be discussed more, in a subsequent proposal, when I have an idea of what the second stage should involve.

## Estimates

To sort out points 1 - 6 for the First Stage I would estimate a one off cost of $2,000.

For the ongoing Project Maintainer role I would estimate a cost between $100 -$300 per cycle depending on what was proposed / agreed for the Second Stage.

## Timeline

I would need about two months to complete points 1 - 6 for the First Stage following acceptance of this proposal.

**Comment by HenrikJannsen** [comment]
I would be good to clean up the current projects page as it is linked from some documents but totally outdated. Best to remove all projects there as I doubt that anyone is still active anymore.
Maybe also good to remove those links to the projects page until it has become alive again.

**Comment by pazza83** [comment]
Yes, I think most of the projects will end up being closed.

> Maybe also good to remove those links to the projects page until it has become alive again.

What links are you referring to? Can you include a link?

**Comment by namloan** [comment]
> It should be noted that I do not think the above would not be achievable by any one person. I see the Projects Maintainer role more about putting in place a process and then making sure it is followed

I agree with this. IMHO what you describe in the Second Stage sounds like stuff that project owners should do. For instance @HenrikJannsen is doing this 'Second Stage' work in Bisq2. Are we missing a Project Owner role?

**Comment by HenrikJannsen** [comment]
> What links are you referring to? Can you include a link?

I think it was the "How to contribute to Bisq" page, but not 100% sure where I stumbled over it.

**Comment by suddenwhipvapor** [comment]
Closing as completed, as no discussion is ongoing. Please ask me to reopen if needed.
