### ISSUE TITLE
Proposal for @solomon1923 to assume Growth Lead role

### ISSUE THREAD

**Issue by solomon1923** [bisq-network/proposals#448]
Following discussion on the [Thoughts on Bisq growth](https://github.com/bisq-network/growth/issues/287) and [Growth Team Lead](https://github.com/bisq-network/roles/issues/100#) I would like to assume the Growth Lead role.

My thoughts on what is needed can be found [here](https://github.com/bisq-network/roles/issues/100#issuecomment-1897671149) and [here](https://github.com/bisq-network/roles/issues/100#issuecomment-1899850414)

I will aim to discuss with the other growth lead applicants and interested potential growth contributors to establish a growth team.

Documenting it as a proposal to follow the official processes.

If approved I will need access the [Growth Repository](https://github.com/bisq-network/growth) 

Many thanks to @flix1 for pushing the Gowth Lead vacancy forwards

**Comment by pazza83** [comment]
Marking this as approved
