### ISSUE TITLE
Concept for decentralized binary option trading

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#45]
After a discussion with @flix1 we came up with an idea how to implement [binary option](https://en.wikipedia.org/wiki/Binary_option) trading in the BSQ system. That could be extended to other trading products later but binary options is the most simple one so it is good to use that as a base.

For users who are mainly interested in speculation such financial tools are more suited than normal exchange as they usually only want to bet on the price and not buy or sell the counter currency.

## Overview
There are 2 traders (lets call them A and B) making a contract for a binary option. They put in the same amount of money to the contract and if a certain event in the future confirms to a `true` result trader A gets all the money, otherwise trader B.

There are 2 problems to solve:
1. Decentralized execution of the contract
2. Decentralized source for the result (oracle problem)

Problem 1 can be solved within the BSQ system. Problem 2 could be solved if the result is a BTC trade price. Bisq could provide a decentralized price feed if trade volume is sufficiently high to not get gamed by self trades. There is a direct relation between volume (fees causing costs for manipulation attempts) and the security of the price feed. So it could be used already now for small scale trades (e.g. 0.1% of trade volume of a currency pair). 

There might be other open problems to solve to get a trust-minimized price feed from Bisq (network related issues, current concept of the trade statistic data is not built with such use cases in mind and might require changes) but that is out of the scope of that discussion.

For the sake of that discussion let's ignore the oracle problem (assume it can be either solved for certain trade limitations or a model like [oraclize](http://www.oraclize.it) provides sufficient security or use semi-trusted/centralized intermediate solution is used until a better model is available). 

One could argue if the source of the result is not decentralized then the decentralized execution has also no value, but that is not true as once a solution for a decentralized source is found (or at least within certain transparent limitations) decentralized execution is needed to make the whole system decentralized. 

## Smart contract
The smart contract is based on BSQ burning and issuance and would work like following:
Both traders burn the agreed amount in an atomic (all-or nothing) tx. In the opReturn there is the hash of the contract and the contract is published in the Bisq P2P network.

Trader A requests the inputs and change output from trader B and then creates a BSQ tx where he burns x BSQ, signs his inputs and sends that pre-signed tx to B. Trader B finalizes the tx with signing his inputs and then broadcast the tx. At that moment both traders have burned x BSQ in one atomic tx. If one of them is not cooperating it would have no effect to the other trader as then his BSQ are not burned as well. This model is similar like the creation of the deposit tx in Bisq trade protocol.

Example tx for burning 1000 BSQ on both sides, assume a miner fee of 0.005:
```
Input 1: Trade A - 10 000 BSQ
Input 2: Trade B - 5 000 BSQ
Input 3: Trade A - 0.01 BTC for miner fee (we could also split the miner fee that both pay but lets keep it simple here)

Output 1: Trade A - 9 000 BSQ (BSQchange - 1000 BSQ got burned)
Output 2: Trade B - 4 000 BSQ (BSQ change - 1000 BSQ got burned)
Output 3: Trade 1 - 0.003 BTC (BTC change - 0.002BTC or 2000 BSQ got burned, 
                so 0.005 required fee minus 0.002= 0.003 BTC)
Output 4: opReturn which has a typeByte, version byte 
                and the 20 bytes hash of the contract
```

If burned BSQ has more underlying BTC value as required for miner fee would add BTC change outputs to the traders.

Additionally both traders create an issuance tx where they issue 2 x BSQ to themselves. That is invalid as long the contract result execution is not completed. This is similar to BSQ compensation requests. That tx has some costs in BTC as the BTC input needed ("printing cost") has to be paid from the traders. We can consider that as trade costs like a fee.

The contract contains the block height when a certain price is expected and the execution price (price which triggers true/false) as well as the currency pair. If an oracle is used it would contain the relevant data for that as well (e.g. sending pubKey/address of oracle...).

Lets discuss first the model where we use Bisq's internal price feed (based on Bisq trading) so we have a decentralized data source (within certain limitations). Using a trusted 3rd party provider would work similar and will be discussed later.

When the defined block height is reached all BSQ nodes will calculate the price of the currency pair and will check if it was below or above the trigger price. If it was above it will mean that trader A's issuance tx becomes valid and he has issued BSQ to himself. Otherwise trader B will have his issuance tx validated. To avoid the rare case that the price is exactly the trigger price (no winner, no loser) we can introduce another rule to ensure that there is only one winner (e.g. use tx IDs and sort them and take the first, so the winner will be pseudo randomly taken).

If we want to use a trusted 3rd party (oracle) as data source provider it could work like that:
The oracle publishes the price at block height in a tx using opReturn). In the contract the sender address of the oracle was defined so any BSQ node can look up that tx and can read out the price for comparing it with the trigger price. As it was sent from the address the oracle owner is the only one who can create that tx.

## Summary
I think the basic concept can work but of course the details specially on the trusted price source problem need to be investigated further. It has to be clear that any such model will have limitation in which is can be considered to work "good enough". We could use the Bisq price feed for very low trades even now (at least those currency pairs which have already some volume like EUR, USD and XMR). For trade amounts of say 100 USD that is already good enough from my guts feeling (would require a bit of simple math with the fees to see what are the costs to game the price).

There will be more problems with using the trade statistic data as they are P2P network data and therefore only comes with eventual consistency which will have consensus implications. But that would be topic for future work to see it there are solutions for that...

There are no plans to work on that but as we want to be sure the BSQ system is future proof I think its worth to think about that.

**Comment by cbeams** [comment]
Generally I'm +1 for the idea. A couple quick thoughts:

1. I doubt traders would be happy with the prospect of randomly choosing the winner in case of a tie. They'd expect to get their stakes back, and I imagine that's what other platforms do. I understand why this is technically challenging, but explaining that to traders may not have any effect on their opinion.

2. In the case of an oracle that publishes the price, it should perhaps be that the oracle publishes at `blockHeight` and then BSQ nodes evaluate the contract at `blockHeight+1` in order to avoid race conditions.

**Comment by ManfredKarrer** [comment]
@cbeams Thanks for the feedback!

> 1. I doubt traders...

Yes good point. I think it will depend on the granularity of the price data. If it is a 4 decimal price it will be highly unlikely that this ever will happen. It just makes all easier as we don't need to support a refund mode. But of course it would be possible as well but might have some negative consequences. E.g. the traders need to make 2 issuance transactions. One with full payment to him and one with split refund payout. Those cost btc fees... But maybe there is a way to work with not published transactions as well and that the issuance tx will be only broadcasted in case of a win (or slipt refund) scenario.

> 2.  In the case of an oracle...

Good idea. Probably we will need some more buffer for avoiding issues with reorgs. Theoretically the result could be included in a block which gets later re-orged and then the alternative chain might contain another tx with another result. With 10 blocks break between price publishing and cntract result execution we avoid those problems.

**Comment by cbeams** [comment]
Regarding (1) above, the problem can also just be eliminated by defining the terms of the contract correctly, e.g. A wins if the price at block height B is less than X, B wins if the price is greater than *or equal to* X.

**Comment by ManfredKarrer** [comment]
@cbeams Ah yes that is a good idea!

**Comment by ManfredKarrer** [comment]
No plans to work on that in the foreseeable future.
