### ISSUE TITLE
Application to become a bonded pricenode operator

### ISSUE THREAD

**Issue by 403State** [bisq-network/proposals#451]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I am applying to become a bonded price node operator.
I am capable of running and maintaining a reliable price node instance.
I am aware of the requirements to post a bond of 10,000 BSQ.

Reference: https://github.com/bisq-network/roles/issues/14

**Comment by 403State** [comment]
Proposal txid: f2284bfcff0107bb737081af1f72057bf57fcb94a6d6b34ff515c98329073aad

**Comment by 403State** [comment]
Bond locked up: 6ba463e6eb9aab16c167ddeadba01bb42ec76d53a8211ebc283384afa1de7564

**Comment by pazza83** [comment]
Closing as approved and bond locked
