### ISSUE TITLE
Reduce max. trade amount via DAO voting

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/proposals#453]
Due the increased Bitcoin price we should adjust the max. trade amount.

Current value is 2 BTC. We should reduce it to 1 BTC.

**Comment by HenrikJannsen** [comment]
Proposal Tx ID: c823200898f56787e0ddf523eb240402ae957ec5cae77005ed6e8b00963146e7

**Comment by namloan** [comment]
Can you provide some details on why this is good idea and why we should do it now? In the future, what's the data that we should inspect in order to determine that the max trade amount should be increased or reduced further?

**Comment by HenrikJannsen** [comment]
With the rising BTC price there should have been adjustments in the past to keep the max. amount in Fiat currency more or less stable. Luckily most traders understand that trading 0.25 BTC carries significant risks and most avoid such trades (there are not many Fiat trades > 0.1 BTC). The security of the trade protocol has its limitations and it is not suited for extremely high amounts. Bank chargebacks are a certain risks for most payment methods. Beside that, the possibilities for mediators and arbitrators to resolve a dispute are limited. A motivated scammer could create quite some troubles for the counterparty as well as the Bisq DAO in case they manage to get an unjustified reimbursement.

I think we should adjust the limit on a more regular basis, e.g. every 6 months.
I also think that reducing it from 0.25 BTC to 0.125 BTC (the DAO parameter cannot be changed more then by factor 2 in one cycle) is not enough and we should do another reduction in the next cycle if this gets sufficient support. But lets discuss that at the next cycle.

**Comment by HenrikJannsen** [comment]
More details about the change:

If the proposal gets enough positive votes the change will be activated in the next DAO cycle (Block  847 867, estimated for 14 Jun 14:16).
Each payment method has a risk parameter assigned and depending on that the trade limit gets reduced. E.g. Sepa or Zelle which carries chargebackrisks got a redcuction factor of 8, so from the max. limit of 2 BTC the effective limit for those methods was 0.25 BTC. As now the max. limit is 1 BTC the effective limit for those methods is 0.125 BTC.
So any limit at any payment method gets reduced by 50%. As altcoins did not have a reduction their limit will drop from 2 BTC to 1 BTC.



Btw. There have been such a proposal already many years back (https://github.com/bisq-network/proposals/issues/453) but it did not find consensus in the discussion so to enter as DAO proposal for voting.

**Comment by HenrikJannsen** [comment]
Proposal got accepted by 99.92 % support.
