### ISSUE TITLE
Application to become a mediator for Bisq

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/proposals#464]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://bisq.wiki/Proposals)._

I am applying to become a mediator for Bisq.

If nobody is against this, I would post the required 5000BSQ bond as soon as I reach this amount with my contributions, and my existing bond as Bisq2 moderator could be used as coverage in the meantime.

Reference: https://github.com/bisq-network/roles/issues/83

**Comment by pazza83** [comment]
@suddenwhipvapor I think you would make a great Bisq mediator

**Comment by suddenwhipvapor** [comment]
Proposal txid
`fb4858c621ffc284939f713c7cbc3e9454adcd2ac55091282ba1ea4904b7027d`

**Comment by suddenwhipvapor** [comment]
Approved by DAO vote.

**Comment by suddenwhipvapor** [comment]
With some delay, I finally got around to posting the bond for this role:
`92d2018ad49b1d7d714cb2b0863f9f22d75aaf8c69ffbc4b97b7a1aa54758a84`
