### ISSUE TITLE
Bisq donates to other projects

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#48]
Related to a <strike>not yet published</strike> proposal (#52) for a bigger change of the arbitration system we might have the situation that there are no arbitrators anymore and therefor no receivers of the BTC trade fee. Once the DAO is launched there will still be trade fee payments in BTC as those who want to buy BSQ for the first time need to be able to do it in Bisq without the requirement of having already BSQ. Beside that we don't want to force users into buying BSQ for trading.

So if this new dispute resolution system will be implemented we will have the "happy problem" what we should do with the BTC trade fees (which goes to the arbitrators also after the DAO is launched).

Of course there would be many possibilities but one which migth fit very well to the spirit of the DAO would be that we donate those BTC to a receiving organisation which got selected by voting.

Lets assume someone suggests the Tor community as receiver. He makes a compensation request with the official BTC address of the Tor project and some explaination why he thinks that Tor would be a good candidate for receiving those funds. If it gets voted ok then this address will be used for receiving the BTC trade fee (the BSQ trade fee is burned and therefor distributed to all stakeholders).
Every month another receiver can be elected or if not the latest will remain.

I think that can build up nice synergies with projects where the Bisq community shares values and could be a first step in direction of a network of DAOs.

What do yout think?

**Comment by sqrrm** [comment]
I like the idea although intuitively I get a feeling there might be some problems with this. Probably get that feeling due to donations having a tendency to be squandered by certain organizations. I would still support it and if there are problems those can be dealt with through the DAO.

**Comment by ManfredKarrer** [comment]
@sqrrm It is all optional and voting based. We can donate also to the Bisq doantion address ;-)

@cbeams A reason why I would like to get a consensus for that is because it makes it easier if we add that before the DAO mainnet launch. Afterwards it will likely require a hrad fork or at least some hacks. Even if it is not fully implemented from all aspects (UI), if we have the consensus part implemented we are prepared when we want to use it. If we decide to not use it it will be just an inactive feature.

One aspect which makes that very interesting for me is that it would be the first step in a model where Bisq is not an isolated DAO but interacts economically with other projects, which are not DAOs yet but which carry similar mindsets and with such a simple donation model we have an easy bridge to the legacy world. Just imagine if the DAO idea will be successful and applied to more projects liek Wasabi Wallet, BitBox (Jonas Schnelli's hardware wallet box where they are considering to integrate Bisq), Samurai, Tor, JoinMarket, etc... All those projects can better cooperate and interact economically in a similar way as contribution requests. Too early to think too far here but I think with such a donation proposal we are prepared better than without.

**Comment by ripcurlx** [comment]
As discussed in person I like the idea as it would also help us to spread the word and would enable anyone to decide which projects to support instead if they don't use BSQ to pay the trading fees.

Of course it could be a non-problem in the future if we implement an automatic BTC2BSQ conversion during trading. Anyways I don't think it would hurt to have this type of proposal available when needed.

**Comment by clearwater-trust** [comment]
Excluding arbitrators and the BTC fees they collect from the DAO compensation system doesn't appear to be autonomous or decentralized and ignores valuable inflationary controls. The revenue collected through the client must be completely transparent in the governing system by listing the amount of BSQ burned and BTC collected for each compensation round. A token that can be colored in unlimited amounts at a ratio of a million to one is a very delicate thing. Indeed, it's almost worthless! Creating a donation system for BTC fees is some kind of fallacy in my view. First, we should create a system that donates the fees back into the DAO.

**Comment by ManfredKarrer** [comment]
@clearwater-trust 
Not sure if I understand your concerns correctly... I will try to make it more clear.

Regarding the last comment: 
How can it be done to convert the BTC trade fee back to the DAO (BSQ) in a decentralized way? I don't know a way to do that. If there would be an easy way we could have probably used that anyway instead using BSQ for distributing the fee to the stakeholders.

Maybe I need to specify a bit more details on the proposal:
The proposal contains the BTC address of the receiving organisation and every voter needs to do due dilligence to check if that address belongs really to the organisation. Only if the proposal gets voted ok the organisation will be used as receiver from the next voting cycle on. So it is clearly transparant who and how much they receive. We could use the Bisq donation address as the default receiver to start with.

As long we have the current arbitration system not replaced, this is not needed as the arbitrators need to get paid anyway and they will only request BSQ for the missing part. 

E.g. If they want to get compensated with 5000 USD for their work and have received BTC in the value of 3000 USD they will request BSQ in the value of 2000 BSQ. If they would earn more in BTC as they would/should earn, e.g. if they receive 6000 USD in BTC fees we also need a new model to deal with that. An easy informal way would be that they burn BSQ in that amount - thus paying 1000 USD back to the stakeholders or they fund some development work apid in BTC.

Btw. the BTC fees the arbitrators earn can be looked up by anyone on the blockchain by checking their address. Please not also that the arbitrators are co-founder and even with the currently high volume we are entering the area where they might earn more as they spend time on the work, that is not a real problem as they have donated a lot of time in the past without getting any compensation and arbitration work was underpaid for a long time as well.

I don't see a decentralized way how we can convert BTC to BSQ and we need some solution for that, specially in the case when there are no arbitrators anymore but new users who don't have BSQ want/need to pay the trade fee in BTC.

We will add also a feature for burning BSQ for repuation bonds (will be used for the planned off chain trade protocol, but can be used more generally as well). That feature would allow also a not-automated, not trustless conversion. 

E.g. a user proofs that he has burned 1000 BSQ and therefor could receive BTC in the value of 1000 BSQ. But as said, I don't see how that can be implemented trustlessly and automated. 

But if we receive too much BTC and dont want to give it away as donation to foreign projects we could consider to add a alternative not trustless/not automated solution based on that idea. 

One way could be that the Bisq donation address controller (me, will be a bonded role) will do that each months. E.g. the received BTC of a month will be converted to a BSQ value and I burn that and therefor have the right to take the BTC for myself. It is trust based but that is the donation fund anyway and it is secured via a bond. 

We could use then this feature so that I will sign up for a Bisq donation address and with end of the months I do a burning of BSQ. As long I stay honest I can continue that, otherwise the stakeholders can vote for anotherone to receive the BTC (and potentially do that conversion) and/or request confiscation of my bond. I am not very sure about the legal risks involved in such a model, and as the target is that the huge chunk of trade fee should be in BSQ anyway, I think the donation to other projects approach carries less risks.

And beside that it is a fact that we will have contribution from external projects where they do not make a compensation request for various reasons (they are too lazy to learn about BSQ, they are not crypto currency affine as part of the Tor community, they have problems to distribut it fairly - who should receive it if we want to make the Tor project a compensation?,...). Most NGOs have usually already a more or less working model with donations so that make it easier to bridge with those who are not a DAO yet.

And as @ripcurlx said it would add a positive aspect for connecting to those communities without appearing shady (e.g. you need to get into the Bisq DAO system then you can receive funds - many airdrop projects have created some damage here). E.g. if some Tor supporters think that Bitcoin and cryptcurrencies is just for speculators and scammers (I heared such complaints from some Tor guys) they will not do the step to partizipate in the Bisq DAO (beside that it takes time and effort to learn about it and evaluate it). But they probably will/can not reject if Tor gets selected to receive BTC trading fees as donations. After that maybe some will change their mind and it will be easier for Bisq to get developers from that community or find more cooperation.

Btw: We offer already compensation for people running Tor relays. But beside a Bisq contributor noboday has requested for it (I assume they dont know about it and its too much effort to learn about it). 

As Bisq heavily depends on Tor I think it is not only fair that we give something back but it is essential for pure selfish reasons. Bisq without Tor would be in huge troubles...

But of course Tor is only one example here, but that at least is an organisation where no Bisq supporter should have problems to support (otherwise they should try to run Bisq without Tor ;-)) or provide code for alternatives.

**Comment by clearwater-trust** [comment]
@ManfredKarrer - is it possible to move all fees collected from the client to a multisig the DAO controls?

**Comment by ManfredKarrer** [comment]
The DAO cannot control a multisig. In BTC u cannot have more then I think 5 keyholders, so in best case its a federated system. Using MS for decentralizing arbitration was always an idea but always limited to that fact that you can only move control to a small group not the the full stakeholder group which is open and unlimited from nr. of entities.

**Comment by ManfredKarrer** [comment]
The receiver can be anyone, it is just a btc address.
To use multiple adds complexity and I am not sure if it is needed. We can change each month if it gets too much and I think at the end there are not so many projects. 
I also see that as a niche aspect and if the BTC amount is > 10% of the trade revenue we need to find ways to incentivize traders more to use BSQ. BSQ will stay the default and preferred way how the DAO distributes funds.
Yes the process to select and communicate with the receiver is flexible. To ask and inform them is for sure not a bad idea.

**Comment by cbeams** [comment]
@ManfredKarrer wrote:

> A reason why I would like to get a consensus for that is because it makes it easier if we add that before the DAO mainnet launch. Afterwards it will likely require a hard fork or at least some hacks.

That makes sense, and I don't have any problem preparing to support this, but I wouldn't want to rush into it e.g. by supporting this from day one of the mainnet launch.

One reason for this is that donating BTC to supporting projects actually gives users an incentive to continue paying trading fees in BTC, because they want to feel good about supporting, say, Tor. This would work against the incentives we intend to create for them to pay in BSQ. It would be a confusing message, so I say we keep the communication simple out of the gate. Users have two options: pay fees in BTC, or pay lower fees in BSQ. That's it.

The second reason I'd avoid going live with this immediately or even early in the process of launching the DAO is that it's just unnecessary complexity. My assumption all along (we never actually discussed it) is that when the DAO goes live on mainnet, arbitrators will begin to submit compensation requests for their work to be paid in BSQ, just like all other contributors, but that they would deduct from those compensation requests whatever amount they got compensated directly in BTC. In the early days after the DAO goes live, this might mean that the arbitrators request zero BSQ because they are still getting compensated sufficiently via BTC. But as time goes on and (hopefully) more and more users choose to pay fees in BSQ, the arbitrators would begin requesting non-zero sums of BSQ to make up for the BTC they're no longer receiving. At some point in this process, the percentage of fees paid in BTC may become sufficiently low that it starts making sense to just donate it to other projects, and at that point we could start using the support that we've built in for that. This gradual, phased approach could also work well with the introduction of moderators into the dispute resolution system, which I also assume we will not switch to on day one of the DAO going live, but will rather introduce at a later time.

**Comment by ManfredKarrer** [comment]
Yes was also planning to deactivate it for mainnet. As well as other not must-have features. As said I just want to get all in what is consensus relevant as otherwise old nodes would be out of consensus when we add it later.

Good point with the incentive problem paying BSQ fees. Needs more thought....

Yes what you described with how arbitrators get compensated after DAO launch is also what I had in mind.

The new dispute system (with no arbitrations anymore) though will require some solution what we do with the BTC. Over time there might be more solutions like semi autimated swaps...

**Comment by ManfredKarrer** [comment]
The proposal for the new trade protocol (#52) which was the base for this proposal is now published.

**Comment by ManfredKarrer** [comment]
I will close that one as it is now part of the new trade protocol proposal.
