### ISSUE TITLE
Reimbursement proposal/request

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#49]
Related to a not yet published proposal for a bigger change of the arbitration system we might have the situation that we have to make reimbursements to users who experienced losses in a trade (e.g. the peer did not respond or was a scammer). 

Without going more into the details of that new dispute resolution concept we would need a solution for paying out such reimbursements in a decentralized way.

We could add a new proposal type to the DAO for reimbursements. If it gets voted ok the user who filed the request gets issued the requested amount. Technically it is the same like a compensation request and therefore it is quite easy to implement.

It is NOT intended for the current lost trade fee reimbursements which is often about very small amounts (cents to a few dollars). That would create too much "spam" for the voting process and should be still handled in some other - not yet defined - way, but as those amounts are relatively small I would not give priority for finding a solution for that. Best solution is to fix those bugs which causes it ;-).

I know that this proposal might be not 100% clear without knowing the details of those plan for the dispute resolution process but as I need to finalize the DAO and once the DAO is live on mainnet it will be hard to add any changes, I wanted to share the idea.

Beside that concrete use case it could be also use more generic for any cases where a reimbursement might make sense, for instance if users lose funds dua a bug or hack in the DAO.

**Comment by sqrrm** [comment]
I don't know that a different kind of request is necessary for this case. A normal compensation request could be used and would work just as well. The only reason I see to add a specific reimbursement type is to be able to easily differentiate them from compensation requests. Maybe that's worth it, additional  work to add the feature should be minimal since it's just the same as compensation request issuance.

No strong feelings if this is worth it or not. Perhaps I missed some important point, if so, please enlighten  me.

**Comment by ManfredKarrer** [comment]
@sqrrm Yes I think technically its exactly the same as a compensation request but conceptually it is something else and for the user I think its better to distinguish both.
The importance of that depends on the new dispute resolution model we have in mind. We will need a bit longer to get that well thought out and wrtten in a proposal but when we will use that new model we should have it integrated in the DAO as well and not just squeeze it in to an existing feature IMO. 

@cbeams Yes good point. But the balance between received BTC and BTC needed for reimbursing for failed trade fees is (should be) very asymetic. And anyway as soon we get a bit more dev power we should try to fix those issues so that they become super rare.
We also can use the current BTC donation fund for that. I will suggest also to add a bonded role for the one who is controlling that fund (me atm).

**Comment by ripcurlx** [comment]
I'm also not sure if we would/should need a new type of compensation request for this. The only reason for me having a certain type for this would be the case if the volume is so huge on Bisq and we need to add some filtering during the voting process as more and more scammers are attracted to Bisq. But even in that case I'm not sure if the number of requests would be that high that it is not manageable anymore during voting.

**Comment by ManfredKarrer** [comment]
@ripcurlx I think it is better to distinguish between what we issued for work and what we reimbured because of trade victims (scams or peer not reacting). we show the amount of bsq in the UI and if it would be mixed it think important information is lost.

**Comment by ManfredKarrer** [comment]
Implemented in https://github.com/bisq-network/bisq/pull/1813

**Comment by ManfredKarrer** [comment]
I will close that proposal as its accepted and implemented.

**Comment by ManfredKarrer** [comment]
@ripcurlx @sqrrm If you like please update the voting, so its reflect your support as discussed on phone. Might be not so clear if one just reads the comments here...
