### ISSUE TITLE
Add Monero wallet features to Bisq

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#51]
As repeatedly requested by the Monero community that Bisq add XMR support as base currnecy and to reflect the fact that Monero is by far the most traded currency (> 90% of volume) I would suggest as first step the integration of a Monero wallet via RPC to monerod.

The user need to run monerod and Bisq would connect vai RPC to the deamon. A basic Monero wallet UI for satisfying the needs for a Bisq Monero trade should be added as well. 
Maybe even better would be to automate a trade by triggering the Monero wallet transfer in case of a XMR seller or check if XMR was received in case of the XMR buyer.

**Comment by ManfredKarrer** [comment]
Seems that proposal gets soem love ;-). Only missing a dev to harvest that love ;-)

**Comment by sanecito** [comment]
As a Monero community member created a [Reddit post](https://www.reddit.com/r/Monero/comments/9qkxrf/fyi_call_for_developers_manfred_karrer_founder_of/) and pinged the monero-dev IRC channel. If it isn't mentioned in the next dev meeting, I'll mention it in the opens; this is something I'd very much like to see.

**Comment by clearwater-trust** [comment]
https://github.com/ExodusMovement/mymonero-core-js

**Comment by ManfredKarrer** [comment]
See https://www.reddit.com/r/bisq/comments/ae7z72/tighther_monero_integration_in_bisq_a_monero_devs/

**Comment by justpaulgmx** [comment]
I agree, this is a critical and time sensitive item and the talent and time to do it is very rare. I can do some recruitment on my end.

**Comment by battleofwizards** [comment]
What would be the **ideal end vision** for different cryptocurrency **wallets integrated** into Bisq?

Say in 10 years? Some possible options:

* Bitcoin + BSQ only
* Bitcoin + BSQ + Monero only
* All cryptocurrencies heavily traded on Bisq
* All fundamentally relevant cryptocurrencies
* All popular cryptocurrencies (lots of them...)

Thought experiment: say in 2 years Monero's 98% volume dominance collapsed to 1% (maybe a reverse turbo xmr.to showed up or sth). Do we maintain or remove the integration? Do we integrate whatever is then popular? How many wallets can we integrate and maintain before collapsing under own mass?

I don't have the answers - just food for thought.

**Comment by niyid** [comment]
Hi @ManfredKarrer 

I had to revisit this proposal because it is being handled as part of #110.

I have (mostly) completed the Monero Wallet and its functionalities and now I am looking at the integration into trades (buying and selling of XMR).

The question is: will it be best to implement similar to the current design for Bitcoin where BTC is the base currency allowing the exchange of anything for XMR and XMR for anything (in which case XMR is the base currency for such trades); or should it just plug into the current design as an enhancement to the accounts architecture - simply adding the wallet as one of the available XMR accounts?

Regards.

**Comment by chimp1984** [comment]
XMR as base curreny is not possible without monumental efforts. I don't have time to follow your efforts here. Please get in touch with other Bisq devs and maybe make a presentaion of what you have and whats your plans to avoid misalignments.

**Comment by remon-nashid** [comment]
> ... I don't have time to follow your efforts here. Please get in touch with other Bisq devs and maybe make a presentaion of what you have and whats your plans to avoid misalignments.

Way to encourage Bisq contributors! You could've at least answered his simple question.

**Comment by niyid** [comment]
> XMR as base curreny is not possible without monumental efforts. I don't have time to follow your efforts here. Please get in touch with other Bisq devs and maybe make a presentaion of what you have and whats your plans to avoid misalignments.

Thanks for your response.  As it will take a monumental effort to go with an XMR base currency design, I will simply concentrate on the latter: plugging the XMR Wallet functionality into the existing Altcoin Accounts design as currently exists for trading.


@remon-nashid Thanks. He's a he. :grin: 
Regards.

**Comment by mpolavieja** [comment]
@niyid, I understand that your assigned to this project.  Could we close this issue as approved and continue at issue #110?

**Comment by erciccione** [comment]
I agree this should be closed as approved.

**Comment by niyid** [comment]
Yes indeed. Regards.

**Comment by mpolavieja** [comment]
This proposal has been approved.  For ongoing discussion refer to issue #110

**Comment by chimp1984** [comment]
For reference about feasibility of XMR as base currency from Monero dev rbrunner: https://rbrunner7.github.io/bisq.html
