### ISSUE TITLE
Interac Interac E-transfers can be reversed if the account sending it claims their bank account was hacked

### ISSUE THREAD

**Issue by DODGwinsmile** [bisq-network/proposals#63]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

1 remedy is to require a photo from the buyer of: 
- selfie of them holding their drivers license and a note indicating: a) date, b) they are buying Xcad amount on Bisq via e-transfer c) the other party's email address that they are sending the e-transfer to

**Comment by ManfredKarrer** [comment]
All Bank payment methods have certain levels of chargeback risk. Main point is that a systematic scammer wants to repeat and serious banks will flag quickly such users. With Paypal, Venmo, Cashapp  that is not the case so thats why we don't support those. If you want to continue discussion please use the forum (http://bisq.community/). We use Github for mainly development related issues.
