### ISSUE TITLE
Use different trade fee for taker and maker

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#65]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Related to #64 I would like to discuss to change the maker and taker fee.
Currently they are both 0,2%. Some users commented that the maker fee should be lower to create more incentives for makers. There are also some privacy and convenience considerations where the taker has more advantages. One aspect to consider is that the taker pays the miner fee for both the deposit tx and the payout tx, so he gets a higher total fee if the tx fee is taked into account. This fee is currnetly rather low but could become a considerable factor once miners fees become more expensive again.

I would suggest to change the maker fee to 0,1% (fixed percentage without using calculation with the market distance) and the taker fee 0,3%.

Please upvote if you support that or downvote if not. If you have other suggestions or feedback please post it below!

Specially from pro traders feedback is very welcome!

**Comment by justpaulgmx** [comment]
Thank for revisiting this issue. I think it is an important change. As a contributor, I enthusiastically support the proposal. 

As a project contributer, I think there is another issue for makers worth considering, the inability to edit as maker. They can end up with multiple listing fees for an offer that never sold. Would it be possible to eliminate listing fees and increase fee for successful sale?

**Comment by clearwater-trust** [comment]
I agree with @justpaulgmx - i understand the listing fee is to discourage order book spamming, also, it is currently possible to edit an offer's price without sacrificing the fee. However, I think the listing fee provides a frightening barrier to new traders. They can't list a trade without risking the fee. I think listing new trades should take priority over order book spamming at this stage.

**Comment by ManfredKarrer** [comment]
I consider the proposal approved with 7 votes pro and 0 votes against it.

**Comment by ManfredKarrer** [comment]
Implemented with https://github.com/bisq-network/bisq/pull/2213

**Comment by HarryMacfinned** [comment]
Trying to take into account the above comments,
I wonder if Bisq could'nt implement some kind of PoW for the offers (to avoid spam),
and only take fees for successful offers ?

**Comment by ManfredKarrer** [comment]
Feel free to make new proposal. JavaScript cannot be used in Bisq.

**Comment by justpaulgmx** [comment]
Great. Harry MacFinned, do you want to do that?

Good point Manfred. I understand the reason but that will complicate / elongate this proposal. 

Does anyone know of a Java based monero miner? If not, I'm guessing a C based miner could be integrated? 

Manfred, could you share more of your thoughts on the right technical execution of this?

I could help with some of this but integration into a Java app would be new for me.

**Comment by HarryMacfinned** [comment]
@justpaulgmx 
I was only thinking out loud, for purpose of discussion.
atm Bisq has a solution which proves to be functional and works since several years.
Proposing something potentially better needs to be rather careful.
And also it needs significant support from users ... which is not very apparent right now.
