### ISSUE TITLE
List Ark altcoin

### ISSUE THREAD

**Issue by dlecan** [bisq-network/proposals#66]
I would like to add the Ark altcoin, #73 on https://coinmarketcap.com/
https://coinmarketcap.com/currencies/ark/

But, you recently added a new condition to list an asset:

> Please note: Bisq will not list your token if it has taken part in an initial coin offering (ICO). Given the uncertain regulatory treatment of such tokens, Bisq stakeholders determined they are currently too much of a legal risk for the project.

Clearly, Ark has been launched from an (failed) ICO.
But:
- it was two years ago
- other altcoins issued from ICO such as Ethereum are still listed on Bisq

Could Ark be accepted on Bisq?

**Comment by ManfredKarrer** [comment]
See https://docs.bisq.network/exchange/howto/list-asset.html
