### ISSUE TITLE
API security

### ISSUE THREAD

**Issue by blabno** [bisq-network/proposals#69]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

## Introduction

There is a work on exposing some of the Bisq functionality for external programatic access over HTTP API.
The API might be used by local scripts or programs or by remote clients, like a mobile app.

This proposal presents how to access API in a secure manner over TOR and using password and token based authentication.

![Bisq HTTP API network diagram](https://user-images.githubusercontent.com/431064/51472023-9e434300-1d78-11e9-900d-adbce651e086.png)

## Local access

API exposes an HTTP port bound to localhost only.
We do not use SSL because it would force every user to get an SSL certificate, which in turn requires a registered domain name.

---
**Important assumption** 

We assume that local machine is not compromised and local traffic is not being listened by any malicious actors.

---

In order to protect from CSRF attack (i.e. user visits website with hidden image linking to http://localhost:8080)
every request needs to have `Authorization` header which contains access token.
Access token is generated when user executes request to `/user/login` endpoint with a valid password.
Access token is stored only in process memory.
The password digest (SHA256) and salt (to prevent [Rainbow table](https://en.wikipedia.org/wiki/Rainbow_table) attack) is stored in Bisq data directory in a dedicated file.

---
*Side note*

Initially there was an idea to use wallet password instead separate password for the API, but there might be cases
when users don't want wallet password, which also complicates the startup/restart process as the wallet must be 
decrypted before other services are initialized.

---

## Remote access over TOR

Every service bound to localhost can be exposed over TOR as a [hidden service](https://www.torproject.org/docs/tor-onion-service).
Here is a code snipped showing how to publish hidden service that proxies traffic from port 80 (on TOR) to `localPort`: 

```
private void publishHiddenServiceIfTorEnabled() {
    try {
        Tor tor = Tor.getDefault();
        if (null == tor) {
            return;
        }
        final Integer localPort = bisqEnvironment.getHttpApiPort();
        final HsContainer hsContainer = tor.publishHiddenService$tor("http-api", 80, localPort);
        log.info("HTTP API Tor hostname: {}", hsContainer.getHostname$tor());
    } catch (Throwable ex) {
        throw new RuntimeException(ex);
    }
}
```

### Mobile devices

As of time of this writing, TOR is available only on Android devices.
In order to access the API from mobile device it needs to have [Orbot](https://guardianproject.info/apps/orbot/) installed.
User can download it from Goolge Play store.
Once Orbot is started user must enable `VPN mode` and press `Start` button.
Now the traffic will be directed over TOR and all hidden services will be visible to any application installed on that
mobile device (i.e. user can access the API using the browser).

### 2 factor authentication

Optionally user could enable 2 factor authentication using Time-based One-time Password.
Here is a [java example](https://github.com/j256/two-factor-auth/blob/master/src/test/java/com/j256/twofactorauth/TwoFactorAuthExample.java) 
Although it is not yet clear how the QR code should be presented to the user in headless mode. Logging it to console poses security risk as it will remain in the logs.

**Comment by ManfredKarrer** [comment]
I think there are unofficial Tor apps available on iOS.

**Comment by mrosseel** [comment]
looks good bernard, some general thoughts:
- did you look into JWT (https://jwt.io/ and https://en.wikipedia.org/wiki/JSON_Web_Token ) ? Not strictly needed of course, but used it lately and works well.
- With letsencrypt SSL has gotten much easier (add some docker containers and you have auto-updating free SSL) so would at least leave the option open for those who have a domain name. Basically an option to either disable TOR or have it running on a non-80 port.

**Comment by blabno** [comment]
@mrosseel the goal of JWT token is to allow backend to identify user without querying db, so the token always contains some unencrypted info about the user and a backend's signature to guarantee that data was not tempered. 
We don't query database and keep the token in memory so there is no benefit while we would have to expose some data about the user. This is a privacy concern.
If random token expires then it's useless. JWT tokens cannot expire, and even if the key used for signatures is changed, the token itself still contains some data about the user.

As far as I know letsencrypt still requires a registered domain name, doesn't it?

**Comment by ripcurlx** [comment]
@blabno Does the access token that is retrieved on login have a time out or is it valid forever? Probably not a big issue as long everything is accessed from localhost.

**Comment by blabno** [comment]
@ripcurlx good point, token expiry time could be configurable through the UI or commandline params. Access will be from all over the internet.
In future we could add UI with token usage stats, login attempts, open sessions (with ability to invalidate session/token).

**Comment by blabno** [comment]
Added section about 2FA.

**Comment by freimair** [comment]
@mrosseel, @blabno: by JWT you mean OAuth? or who else is creating the JWT in this use case?

**Comment by freimair** [comment]
ah ok, so you simply would replace a memorable password with the JWT token. In that case I agree that there is no added value, there might rather be a greater attack surface as a memorized password is not digitally accessible (given it is not stored by the browser or other parts of an OS), a token is. Never trust the browser, especially when it comes to riches.

And be aware that you might not be able to foreclose XSS attacks completely (might be considered as a kind of man-in-the-middle in this case). This attack happens before Tor and the only defence is the browser itself. And of course, a simple password might not protect against this attack (as the user might not realize what is going on and provide the password anyways).

2FA: please be aware that if you use one of the cheap 2FA technologies (i.e. a phone), the whole advantage is cancelled if the user uses the very same phone to do the remote controlling via the API. Other technologies (https://en.wikipedia.org/wiki/Universal_2nd_Factor and its hardware tokens for example) have a hard time being used on phones (although RFID enabled phones and the required software are in the coming)

What I wish to see being added is the option to disable the API via settings/command line parameter. Only a service that is not offered can be truly secure.

**Comment by blabno** [comment]
@freimair thank you for your input. I had similar feeling about 2FA, that it's just a second password.

In order to enable API user would have to explicitly start Bisq with additional parameters (i.e. `--desktopWithHtttpApi`). So regular users would by default have API disabled.

**Comment by freimair** [comment]
now that I think of it, one could use certificate authentication instead of JWT

this has several advantages:
- mobile phones grow more and more towards offering an embedded secure element. I.e. a mobile phone can use its secure element to store the certificate
- does client authentication in TLS/SSL needs to be a fully-fledged domain certificate? if so, one can just implement a challenge-response thingy for authentication
- certificate pinning can get your authentication sorted
- one can use the certificate pinning stuff for localhost access as well
- did I miss anything?

**Comment by blabno** [comment]
Results of a survey **I plan to use Bisq API:**
- to write automated trading bot - 7 votes (33%)
- to run it in headless mode on - 12 votes (57%)
- actually I do not plan to use the - 4 votes (19%)
- to access Bisq from mobile device - 7 votes (33%)
- to integrate in my coin tracking - 1 vote
- to run Bisq on nodl.it - 2 votes
- to write a small client side (desktop) - 1 vote

**Comment by ManfredKarrer** [comment]
I think that proposal can be close as a security model is implemented now.
