### ISSUE TITLE
Allow active contributors to sell BSQ earned during Phase Zero

### ISSUE THREAD

**Issue by cbeams** [bisq-network/proposals#7]
The Phase Zero plan in its current form prohibits the sale of BSQ as a strategic measure to mitigate what the plan refers to as **valuation risk** and **control risk**, defined as follows:

 - **Valuation risk**: token value falls too low to be viable (or rises too high too quickly)
 - **Control risk**: any kind of non-meritocratic takeover of stakeholder voting power

From https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#how-phase-zero-mitigates-risk:

> To address **valuation risk**, we eliminate the possibility of trading BSQ during Phase Zero. A fair market value for the token must still be established in order to compensate contributors, but this value can be estimated initially and then adjusted throughout Phase Zero. On completion of Phase Zero, the value of BSQ will become entirely subject to market forces, but the fact that many contributors worked throughout Phase Zero at a given fair market value should provide a stronger price foundation for BSQ than would be present if we were to simply enable trading from day one.
> 
> To address **control risk**, we ensure that only those who have contributed value to the project are able to vote during Phase Zero. This, too, is a result of prohibiting BSQ trading: because the only way to acquire BSQ during Phase Zero is to earn it, it becomes impossible to simply purchase voting power. Furthermore, it gives us time during Phase Zero to design and implement a longer-term solution for control risk in which we introduce a reputation factor into the BSQ-based voting process.

Not written in the document explicitly, but also true, is that by prohibiting the sale of BSQ, we also helped avoid a form of censorship risk. With no token available to the public, there is no way we could be seen as engaging in securities fraud, and therefore could not become the target of any related enforcement agency.

The prohibition on sale also helped distinguish very clearly that what we are doing with BSQ and the Bisq DAO is [not an ICO](https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#not-an-ico).

So there are many good reasons why we put the prohibition in place. And it's with this in mind **I propose we introduce the ability for individual contributors to privately sell the BSQ they have earned during Phase Zero thus far.**

### Why? And why now?

We're now entering our 6th month of Bisq DAO operations under the Phase Zero plan. Phase Zero has no estimated end date, it only has [exit criteria](). We did state in the document, however, that Phase Zero would last _at least_ 6 months. Given that we're at the 6-month mark, and we're still at least a few months away from hitting Phase Zero exit criteria, now is a good time to review this matter. 

During the last 6 months, a number of Bisq contributors have worked steadily on Bisq, and have been compensated in BSQ for those efforts, but have otherwise had no liquid form of compensation. For most contributors, such a situation can only go on so long—at some point, savings run low and one needs to pay bills.

It is excellent that contributors have worked in an equity-only fashion during these 6 months. It is a demonstration that Bisq and the Bisq DAO are something that contributors believe in and are willing to take considerable risk for to realize in the world. It is one thing to say these things; it is another thing entirely to work for months without (spendable) pay for them.

Another factor contributing to the creation of this proposal is that we are in fact getting requests from serious buyers about BSQ. A number of contributors have reported being approached by people they know who, given the opportunity, would buy their BSQ. I have also personally seen an uptick in these inquiries over the last weeks. So it is reasonable to predict contributors will actually have buyers to sell to.

### What are the benefits?

The obvious benefit is that individual contributors will now be able to manage how much BSQ they hold vs how much they liquidate according to their own needs, risk tolerance and time preference.

Another significant benefit is that through the process of individual contributors privately selling their BSQ to other individuals, we will be able to engage in a slow and controlled process of _price discovery_ for BSQ. Our [current working valuation for BSQ](https://github.com/bisq-network/docs/blob/master/dao/phase-zero.adoc#establish-and-refine-the-fair-market-value-of-the-bsq-token) is `1 BSQ == 1 USD`, and while this figure was the result of quite a lot of deliberation, there is no way to know a priori whether the market will agree with it. As we approach exiting Phase Zero, it will be very good indeed to have actual data informing us about what the market value of BSQ may be.

### What about the risks?

I've addressed **valuation risk** immediately above. Prohibiting BSQ trading at the start helped us mitigate valuation risk while BSQ was utterly untested and the Bisq DAO was brand new. Permitting trading now can help further mitigate valuation risk by helping discover what the market price actually is. After 6 months of road testing BSQ and the Bisq DAO with contributors, I believe this is a reasonably prudent thing to do.

On **control risk**, the question is whether buyers of contributors' BSQ will be able to vote with it during the remainder of Phase Zero. I am of two minds about this. On the first, I think these buyers should **not** be allowed to vote, in the name of keeping the Bisq DAO fully meritocratic throughout the remainder of Phase Zero at least. On the other hand, the nature of the way in which we are proposing to make this change (see below) is such that the only buyers will likely be those people who understand Bisq very well, know contributors personally, and are willing to deal with very significant risk around BSQ. If buyers do in fact fit anything like this profile, I would have no issue with them voting. Indeed, because they are engaging so early in the process, and providing a valuable early price discovery service to the DAO, I would go so far as to say that these new BSQ stakeholders _are Bisq DAO contributors_, and therefore should have voting rights by definition.

On balance, I am for allowing buyers to use their BSQ to vote, with the proviso that we may change this decision at any time, such that anyone who already has voting rights will keep them, but new buyers after a certain date cannot use their BSQ to vote. I mention this just as a contingency.

### What about BSQ earned as a past contributor?

Thus far I've talked only about contributors active during Phase Zero being able to spend the BSQ they've earned during Phase Zero, and that's been intentional. I propose that we limit sellable BSQ only to that BSQ which has been earned during Phase Zero, at least initially. This conservative approach will let us see how it goes with a small number of clearly dedicated contributors before opening things up more widely to many dozens more past contributors. Indeed we may not open it up further at all before exiting Phase Zero.

This conservative approach helps mitigate control risk, because only a relatively small number of BSQ can be sold (currently ~300K out of a total 2800K supply), and it also helps mitigate the above-mentioned regulatory / censorship risks, because with such a small amount being on offer from such a small number of contributors only and ever engaging in private transactions, it would be more difficult to cast this behavior as a 'public offering'.

### How will we implement this change?

I propose we do the simplest thing that could possibly work:

1. Modify the Phase Zero document to make it clear that BSQ selling is allowed with all the restrictions mentioned above. This makes the change official, as the Phase Zero document is the source document / constitution of the DAO right now.
2. Beginning with the next voting period (Apr 1–3), we allow contributors to add new rows to the stake and voting spreadsheet. Each new row would specify a new BSQ address belonging to a buyer that the contributor sold their BSQ to. The amount credited to that BSQ address must also be debited from the same BSQ address the contributor is using to vote with in that voting round. Any such changes will be verified by the Bisq DAO [compensation maintainer](https://github.com/bisq-network/roles/issues/31) as a new step in the now-routine process of conducting monthly compensation voting.

Also, we should put together a short list of risks that contributors should make very clear to buyers before any transaction. Buyers must understand the nature of BSQ, the nature of the Bisq DAO and must understand how early in this process we still are. There is a high degree of risk here, and absolutely no guarantees. Any transaction is 100% between contributors and their buyers. Beyond the verification mentioned in (2) above, there will be no duties performed by any Bisq DAO bonded contributor related to these sales. There may be other things of this nature that we want to add to a list of caveats. Please think about this and add to the list as you see fit.

### How do we decide on this change?

If there is a clear consensus among active contributors, there is no need to put this to a formal BSQ vote. Please give a thumbs up or thumbs down to this issue description and add comments as you see fit. Afterward (assuming consensus), I will go ahead with the changes to the Phase Zero doc described above, and starting next month, individual contributors may add new lines to the bottom of the stake and voting spreadsheet as described above.

/cc @bisq-network/contributors

**Comment by alexej996** [comment]
I agree with the conclusion of this proposal.
It seems like buyers will be taking most of the risk here and that the project can pretty much only benefit from this change.

I am unsure about legal regulation however, but I am generally not really familiar with it. It does seem to me like this can not really cause much of an issue really, at least not for the project as a whole, but perhaps maybe to those individuals that are selling BSQ.

**Comment by ManfredKarrer** [comment]
I agree with all you stated. 
Maybe one extra point to consider is if the sell price should be public or kept private. I think public would be better as it helps price discovery. Of course the 1 BSQ = 1 USD price we use for contributors is nor required to be kept for sellers.

**Comment by cbeams** [comment]
> one extra point to consider is if the sell price should be public or kept private.

Agreed. I meant to cover this above, thank you for bringing it up.

> I think public would be better as it helps price discovery.

Agreed, and it's better for transparency in any case. We can start by simply adding a comment in the stake and voting spreadsheet in the `balance` cell of the row for each new buyer. When a contributor who has sold their BSQ adds a line for the new buyer, they also add a comment saying what the sale price was. We can add another column for this, too, but starting with a comment would be the simplest thing to do during the first month or two.

People will rightly wonder about what's keeping contributors from doing self trades (i.e. transferring BSQ to themselves) and artificially inflating the price of BSQ along the awy. And the answer is that there is essentially nothing to prevent it. I am proposing this change now because I believe the current group of active contributors (i.e. those who have earned BSQ during Phase Zero thus far) have demonstrated a clear commitment to the project, are demonstrably good actors committed to the success of the project, and can reasonably be trusted not to engage in this kind of manipulation. Any prospective buyer should of course not take my or anyone else's word for it; they should do their own research into the project, should look at the profile and activity history of each of Bisq's active contributors and determine for themselves whether it is reasonable to trust that these people would report their BSQ sales accurately, both with regard to volume and price. They should look at the history of any such sales and ask themselves if they believe those volumes and prices to be plausible, and so forth.

> Of course the 1 BSQ = 1 USD price we use for contributors is nor required to be kept for sellers.

Agreed. Contributors are free to sell at any price their buyer is willing to pay. Otherwise, price discovery cannot occur. The `1 BSQ = 1 USD` valuation should be understood as the working valuation at which all contributors have agreed to operate in the absence of a market for BSQ. If, through the process of selling BSQ, we discover that `1 BSQ = 1 USD` is clearly wrong, we will update the official working valuation accordingly for use in future compensation requests.

**Comment by sqrrm** [comment]
I'm feeling hesitant towards this suggestion.

The main pro would be to let contributors actually get a monetary reward for the work they're currently doing before the BSQ tokes become freely tradable. This is a good reason though. Price discovery would be good but I don't think it's as important at this stage.

I see a couple of cons. First, the control and trust needed in the centralized accounting of these trades go against the ethos of decentralized trustless networks that I think is close to the core of what we're building with Bisq. It's already centralized with the issuance and voting, adding even more features to this centralized system seems inherently wrong.

On the legal side I don't know enough, and it seems no one really knows, but I worry this would be considered an investment contract according to US regulation. The tokens are currently controlled centrally and certain aspects are not yet available, especially the utility for fee payments. This makes it look awfully close to a centrally controlled shares of a company, with voting rights but nothing more. I would be happy to get educated on this matter though.

**Comment by citkane** [comment]
@sqrrm , I agree with your well articulated points and can see that you have a lower level understanding of the matter than me. I will maintain my thumbs up for now because I will be making my first compensation request soon, have a mortgage to tend to and only a few months of buffer for the Bisq work I would like to do.

Of course, if the DAO phase 0 bootstrap crashes over this, all arguments are irrelevant. Maybe we need a "sitting on the fence" emoticon.....

**Comment by ripcurlx** [comment]
As I'm not a lawyer and don't want to limit my travel plans in the future, I'm also fine with the decision that we focus our energy to release the DAO asap and not add this intermediary pre-release trading in the spreadsheet itself.

**Comment by cbeams** [comment]
Closing as rejected based on the content of the comments above and as reflected by the 2 👍 and 6 👎 reactions at time of closure. Thanks everyone for the thoughtful consideration of this matter. Onward to real live BSQ, then!
