### ISSUE TITLE
Update Bisq's fiat trade limits

### ISSUE THREAD

**Issue by HarryMacfinned** [bisq-network/proposals#71]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

We have quite often users complaining about the trade fiat limits being too low.
And maybe many users who say nothing but simply trade less (or stop ?).

I also had a look on the number of trades trend (which is decreasing).

BTC value is roughly half than one or two years ago.
I wonder if it should not be time for Bisq to update the trade limits accordingly ?

**Comment by ManfredKarrer** [comment]
Yes I agree basically, just not sure if it can be easily changed without breaking backward compatibility. I will have a look soon into it, if that is an issue. If I don't follow up here feel free to remind me....

**Comment by ManfredKarrer** [comment]
I checked the code and it seems it is possible without any major issues. I will make a PR for doubling the limits.

**Comment by HarryMacfinned** [comment]
I just want to point that **updating** will not mind making limits higher (as evaluated in fiat money, eg USD or EUR)
If we update by doubling the BTC limits, 
in USD or EUR, this will simply mean bring Bisq back on the same limit as 1 or 2 years ago, when BTC value was double than today.

**Comment by ManfredKarrer** [comment]
* Set max trade limit to 2 BTC (for altcoins)

* Add MAX_TRADE_LIMIT to Param

* Round first month trade limit to ensure we stick with precision 4 for
  the btc amount

* Use risk factors to derive trade limits for different payment method
  risk categories
