### ISSUE TITLE
Arbitration-free trading

### ISSUE THREAD

**Issue by meapistol** [bisq-network/proposals#84]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

I propose a simplified and optional trading protocol which eliminates the need for arbitrators and mediators. Similar ideas have been  commented on before: https://github.com/bisq-network/bisq/issues/2805, https://bisq.community/t/pr-for-face-to-face-trade/5821/22

The present proposal is far simpler to implement than previous proposals for a new trading protocol (https://github.com/bisq-network/proposals/issues/52) and is conceptually easy to understand for users. It will also allow F2F-trades to settle correctly with much higher certainty than is presently the case. My motivation for this proposal is simplicity. A chat system is better but harder to implement.

I propose that:

* There is a new account-type which contain an email.
* Offers using such accounts should be marked with a special symbol such that the taker knows he can communicate with the maker. The taker can have a non-email account type.
* The default security deposits should be high and if they are set high it should be visible in the offers.
* There should be an option for the buyer to do a payout to the seller, in case he cannot pay. Maybe his bankaccount has been blocked. If this is difficult to implement it can be skipped. People usually find some way to pay and the contract is signed.
* The trade window time is made very long for these accounts. The traders can still open a dispute in case they need to. There may be situations where there are no arbitrators and the traders need time to finish the trade.
* Traders should be able to make and take email-enabled offers even if there are no arbitrators available.

**Motivation**
The present system with a few "trusted" arbitrators will not work in the long run. They can scam, they can be(come) incompetent and they can (rage) quit. They are an attack surface for the state and should thus to be fully anonymous, which conflicts with being trusted. There are ways to solve this, (https://github.com/bisq-network/proposals/issues/52), but it is complicated to implement. A simple arbitrationless trading option has a certain appeal to me and will make Bisq immune to failure of the arbitration system.

**I am convinced that if the arbitration-problem is not solved Bisq will disappear.** This would be sad indeed for such a powerful project and a tremendous waste of intellectual effort. A worst case solution is to have a mandatory email field on all accounts which can be implemented in less than a day.

**Advantages**
* Arbitrators are not needed.
* There will be little incentive for blackmail since the blackmailer risks his deposit. There is an asymmetry in loss for a non-settled trade but both traders lose. 
* There is no cost associated, except the very minor cost of interest on the security deposit. 
* Full anonymity for anonymous payment methods can be achieved using anonymous email.
* Future trading is not profitable if the security deposit is high.
* In comparison with the off-chain trading protocol (https://github.com/bisq-network/proposals/issues/52) this proposal is fairly easy to implement.

**Disadvantages**
* People can use the communication channel for social engineering. However a contract with clear terms has been entered and the traders have little to argue about. In case they do start to argue about e. g. late payment it will still be in their best interest to complete the trade. They can then block each other from future trades.
* People can use Bisq to meet and then do off-Bisq trading. I doubt they will do this much since they lose the protection of a security deposit. There are already other venues to meet for OTC-trading.
* A high security deposit might be discouraging, in particular for new users. However there is little cost associated with a high deposit and I think the benefits outweigh the disadvantages. It is anyhow optional to use email-enabled accounts and people who dislike high security deposits don't have to use them.

**Comment by dan-da** [comment]
I agree with the spirit of this proposal.   +1.

**Comment by mpolavieja** [comment]
I like very much the idea of arbitration-free trading, but aren´t BTC sellers always in a much worse position or maybe what you propose is that the BTC of the seller are not locked?

**Comment by meapistol** [comment]
This is a minimal change proposal so the BTC of the seller is locked as usual. 
I doubt blackmail will be a problem in practise, and if it starts to arise the sellers will require a higher security deposit of the buyers. A sufficiently high security deposit for the buyer will make it worse to be a buyer (buyer pays, seller starts to blackmail for more fiat before releasing). 
It is thus so helpful if the takers could see, at least roughly, how high the maker-buyers security deposit is. Maybe with a some type of quantitative indicator or a set of stars. This indicates the degree of commitment of the buyer.

I don't think the DAO community realises how fragile the arbitration system is. There are now two arbitrators. If they quit, who will find the next trusted arbitrators?

**Comment by mpolavieja** [comment]
I fully agree with the fragility of the arbitration system.   

However, regarding blackmailing I see the problem on the opposite side.  If the seller´s BTC is locked and the buyer has not paid any fiat at all, it is the buyer who is in a stronger position to blackmail the seller.

**Comment by reipichu** [comment]
Maybe I'm missing something, but in what way is this proposal "arbitration-free?"

**Comment by meapistol** [comment]
@mpolavieja If the buyer deposit is low the seller is at risk for blackmail. If the buyers deposit is higher than the trade amount + the sellers deposit then the buyer is more at risk.
@reipichu This proposal is to have a backup in case arbitrators cannot be used. Both traders lock up enough money in security deposits such that they both have strong incentives to complete the trade.

**Comment by mpolavieja** [comment]
> If the buyers deposit is higher than the trade amount

Ok, so you propose a much higher security deposit for the buyer, like a 50% of the trade amount + seller security deposit. right?.

**Comment by meapistol** [comment]
@mpolavieja Something like that. Probably the market will find a suitable level for the deposits such that any prospective blackmailer is discouraged.

**Comment by flix1** [comment]
Completely agree that current arbitration system is not scalable to 10.000s of users, multiple countries, languages, currencies, etc.

Mutually assured destruction of security deposits is the only mechanism I see as strong enough to achieve security in an anonymous p2p exchanges.

Finding the correct amount for the security deposit probably requires a lot of trial and error... This parameter should be user-defined.

Additional security information as discussed in #80 would also help a lot with this.

**Comment by flix1** [comment]
There was actually a previous attempt at a DEX called Coinffeine (https://en.bitcoinwiki.org/wiki/Coinffeine) which used small but reusable security deposits so that a trade was actually completed in steps. For each step the security deposit was 100% of the amount exchanged for both buyer and seller and only when payment was completed and verified was the next step initiated, reusing the original security deposit to secure it.

This was a very strong MAD security model... however the ux would have been a nightmare if manual, so the project was dependent on APIs and automated payments via payment processor.

I believe that the project failed, although I still think the idea is worth exploring.

**Comment by meapistol** [comment]
Concerning blackmail, the security deposit must be high for both buyer and seller. 
A seller will simply not release the btc if he was blackmailed to accept less fiat out of anger. Thus it is very dangerous to try to blackmail as a buyer.
The buyer is in fact at risk for blackmail due to the power of the seller to not release the btc after payment. So the sellers security deposit must be high enough to incentivize him to release the btc after payment.

**Comment by MwithM** [comment]
What I've seen and I think is a very solid way to handle MAD is 1x the value of the transaction for the part that makes the payment first (usually fiat, but it wouldn't need to be necessary using this protocol), and 2x the value of the transaction for the other part.
It might be considered that lower security deposit would be good ennough, but this way is solid, as both parts have always something to lose.

Coinffeine's way is not valid for F2F, unless participants want to have to meet more than once. It would be a good way of handling other payment methods, but I think it wouldn't protect from chargebacks, wich is the biggest risk for electronic fiat payment methods. And LN would have to be integrated on Bisq, otherwise we would be using too much blockchain space, which is not almost free anymore.

**Comment by chimp1984** [comment]
@meapistol 
I assume the 1.2. release make that proposal not needed anymore? If you agree feel free to close it.

**Comment by chimp1984** [comment]
@mpolavieja Can you close that?

**Comment by MwithM** [comment]
I don't see how v1.2 relates to this proposal, other than a chat and use of 2of2 multisig. Maximum deposit is only 50% of the trade for buyer (seller doesn't even have to deposit anything else than the trade amount), and there's still an obligation to accept arbitrator's decision.

I understand to close this as stalled. But there are a lot of petitions (most of them by me) to allow Mutual Assured Destruction, specially for F2F trades. Bisq v1.2 opens a path for arbitration-free trading, and I'd like to keep discussing this, to see it in use for Bisq as an option.

**Comment by mpolavieja** [comment]
I´ll close this proposal as stalled, but I agree with @MwithM that we should keep discussing MAD.
