### ISSUE TITLE
Decentralized CFD

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#85]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Speculative traders are not interested in traditional trade where one currency is exchanged with another. Instead they want to speculate on the price change over a certain time period. [CFD](https://en.wikipedia.org/wiki/Contract_for_difference) can be such a vehicle.

To implement that in a decentralized way we could use the ideas laid out in one of the 2 off-chain trade protocolproposals [1](https://github.com/bisq-network/proposals/issues/32), [2](https://github.com/bisq-network/proposals/issues/76). The security for the contract execution is bound to a security deposit in BTC or BSQ bond and by that it is decoupled from the trade protocol or contract execution. This makes the contract execution much more simple as it does not need to entangle security mechanisms to avoid counterparty risk. 

[1](https://github.com/bisq-network/proposals/issues/32) 
[2](https://github.com/bisq-network/proposals/issues/76).

**Comment by flix1** [comment]
CFD and FX trading is a huge market, but regulation is a messy patchwork with some countries being very restrictive. A decentralized, uncensorable, private CFD system would be a bigger market for Bisq than altcoins are currently. BTC bonds would make a lot of sense for this.

**Comment by chimp1984** [comment]
Closed as the proposal is not clearly defined.

**Comment by MwithM** [comment]
Closing as stalled.
