### ISSUE TITLE
Automate altcoin trading

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#87]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

Altcoin trading can be automated for those altcoins where the tx can be verified in a blockexplorer (not valid for privacy coins like Monero). The altcoin seller can provide the tx ID when confirming the sending of the altcoin. The buyer's Bisq app can lookup a blockexplorer if the tx is confirmed and the receiver address and amount matches with the trade contract. If so, the trade can be completed automatically without requireing the altocin buyer to do a manual interaction. Only requirement is that the Bisq app is online. The number of required confirmations should be adjustable for each altcoins as the required number of confirmations to be secure against reorgs is different on each altcoin. If multiple explorers are available, multiple should be used and it is required that all results match to gain more securitity against corrupt explorers. The features should be optional to not force the user into a difference security model (risk that explorer is corrupted).

By sending the tx ID we avoid the problem that an altcoin buyer could have 2 parallel trades open with exactly the same amount and receiver address. That would not allow him to distinguish which trader has made the tx if he receives funds from one trade. That problem exists also now but has never been a problem as far as we know. But by providing the tx ID it can be eliminated at all. The sending of the altcoin is anyway a manual interaction and clicking the payment sent button and providing the tx ID is not slowing down the trade process.

The lookup for the blockexplorer should be done by a relay node over hidden services (similar like price nodes). The blockexplorer need to be defined for each altcoin which adds some additional development effort at integration time. But that feature could be enabled only for frequently traded altcoins.

**Comment by blabno** [comment]
Isn't it dangerous to trust centralized entity (block explorer operator)?

**Comment by ManfredKarrer** [comment]
Yes, sure we need to take care of that. It should be optional to use that feature and best would be to have several explorers. It can start with one or 2 most traded altcoins and then expand.... We could run our own explorers as well...

**Comment by dan-da** [comment]
ideally there would be an option to use the coin's own server eg litecoind, etc.    at least for bitcoin clones with compatible rpc api.   probably would be little used but at least provides a trustless best practice path for those that care.   for compat coins bisq would only need rpcport, rpcuser, rpcpass.

**Comment by MwithM** [comment]
Closed as superseeded in #239

**Comment by TheParanoik** [comment]
where are docs to interact with Bisq API? damn https://bisq.markets/api/ thats only thing I was able to found...

**Comment by sqrrm** [comment]
The API is not yet ready for public use, still changing quite bit. Pretty close though, docs would probably come at the same time as we go public with the API.
