### ISSUE TITLE
Hardware wallet integration

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#88]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

To integrate hardware wallets into Bisq is long time on our roadmap and we even started a few years ago with Trezor integration but as it turned out to be more challenging as expected that effort got stalled.

The current trade protocol requires non-interactive tx signing (when a taker takes an offer the makers Bisq app is signing the multiSig tx automatically without manual interaction). This requirement is likely not achieveable by most hardware wallets. But Bisq would still gain a lot of extra security if the user can swap BTC funds to a hardware wallet with one mouse click from the Bisq app.

**Comment by HarryMacfinned** [comment]
Do you target some specific BTC hardware wallet ?

**Comment by ManfredKarrer** [comment]
> Does this proposal target some specific BTC hardware wallet ?

I had Trezor in mind, but best would be to cover the most widley used ones if dev effort permits it.

**Comment by initCCG** [comment]
If we understand right, Wasabi was able to do HWI relatively quickly
https://github.com/zkSNACKs/WalletWasabi/issues/1325
 for several wallets at the same time by using:
https://github.com/bitcoin-core/HWI

**Comment by HarryMacfinned** [comment]
The easiest hardware wallet I found, is a simple 2nd hand laptop under debian, where the internet connection is only made possible via a usb wifi key (~100$).
With that, for your swaps you're already just one mouse click away. 
... and this hardware wallet is open-source.

**Comment by haimbender** [comment]
I have experience writing Apps for Ledger and would love to do some work for Bisq:
 
1] You can create your own app that does auto signing, and also you can have a multiwallet app, meaning it accepts all types of crypto currencies supported by Bisq. (This is a very expensive solution, starting at 75k$).

2] Bisq <-> Ledger deposit and export is a semi easy

**Comment by mpolavieja** [comment]
Closing this proposal as there has been no further discussion and it is also being considered to remove the wallet from Bisq in future versions.

**Comment by Leopold-Klotz** [comment]
Looking at reviving this discussion or am open to updates if anything has happened concerning it. Would love to hear if there is any other interest!
