### ISSUE TITLE
BSQ conversion rate for compensation requests

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/proposals#92]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

We discussed before the DAO launch how we should set the conversion rate used for compensation requests. All contributors and voters should have a consensus as otherwise proposals would risk to get rejected if contributor and voter have different rates in mind. There have been basically 2 ideas:
- Use the 1 USD/BTC rate for the first 3 months independent on the real market price
- Use the market price average of the last 3 months (would use 1 USD for the months before the launch)

We did not make a decision and left it a bit open how the market develops after the launch.

I think in the first voting round most people used the 1 USD rate even it was not explicitely discussed. 
I would suggest to try to find a consensus what we should use as otherwise it might be confusing, specially for new contributors.

I think both ideas above are good, but the fixed 1 USD would be somewhat easier and avoids the risk of a negative downward spiral as well we don't have a tool yet for the average and its the question how we deal with the timing as different dates for making the proposal would cause different rates.  

We have to keep in mind that the economic model of the DAO will need a few months to develop as we started with a 90% BSQ trade fee discount. As many users have already moved over to use BSQ that effect on the revenue is even stronger as anticipated. We should start to increase both the BSQ and BTC fee so that our target fee of 0.4% per trade is reached again. But we cannot do that too fast and too radical, so I think it will take 3-4 months until we get back to a revenue of 0.4% of the trade volume. Until that time the expenses for contribution requests should not be too extreme as otherwise the revenue/expense ratio turns even worse. A market based converion rate would carry some risk that people don't want to buy BSQ as expensed are getting higher and income from fees are lower, so the economic sustainibility is weak. As said we need a few months until raising the fees and I think in that time we should not over-expand the expenses.

But of course all just my opinion. Please leave your opinion or ideas in the comments and lets see if a consensus emerges.

**Comment by HarryMacfinned** [comment]
I'm also in favor of simplicity.
And also, looking the BTC/BSQ trades together with the BTC/USD ratio, it seems that, even small and volatile, the BSQ market itself tries to stuck to this 1 BSQ = 1 USD rate. Which I don't find really surprising.
(So, both way will probably lead to narrow amounts, but one is easier).

**Comment by initCCG** [comment]
We vote for the average price for last 3 months.

We think we understand why the 1$=1BSQ rate was used and continues to hold somewhat on the Ask side.
However, it is an arbitrary rate, which is based on Labor Theory of Value, and currently maintained through an informal mechanism similar to a cartel.

We also think that it doesn't reflect the true market value of that labor. 
We've seen instances of egregious padding and overcompensation for the work done, and suspect the ones noticed to be just the tip of the iceberg, which created and will create far more BSQ supply than the foreseeable demand.

Given that, in our humble view, the "downward spiral" -  which is really the normal market price discovery to find the free-market rate - is unavoidable. 
That would allow the free-market forces to price in the overcompensation issues, including work that has not added much if any value to Bisq.
The true value of BSQ, Bisq itself and its development in the global market would be reflected in that rate.

We think that continuing to set an arbitrary 1$=1BSQ rate in an LTV cartel fashion would defeat the purpose of making BSQ a free-floating token, and continue to repel free-market traders, who are the foundation of the cryptocurrency markets.
There's no point in having the Bid side in BSQ then. Just having the Ask side will be sufficient.

In our view, a BSQ trade fee discount doesn't need to be large to be attractive. 
We are convinced that the trade discount is not what most attracts its current holders to BSQ.
So, a 25% discount, as with BNB for example, would suffice also.

As Bitcoiners, we believe in the ability of the free-market forces to find the true value of everything.
So, of the options given, our vote is for the 3 month average rate.

**Comment by m52go** [comment]
This proposal suggests using a 1 USD/1 BSQ rate for a short time (first ~3 months), not in perpetuity. 

I think it's a reasonable course of action to allow volume to build and to let price history garner more meaning.
