### ISSUE TITLE
Opening disputes for settled trades

### ISSUE THREAD

**Issue by mpolavieja** [bisq-network/proposals#97]
> _This is a Bisq Network proposal. Please familiarize yourself with the [submission and review process](https://docs.bisq.network/proposals.html)._

### Introduction and Goal

This is a spin-off proposal from #93 to enable the possibility of opening disputes for settled trades.  The main goal is to speed up the process of blacklisting in case a user thinks he has been scammed. 

### UX and UI impact overview

This new feature would only be relevant for UX in case of a problem with a settled trade (i.e. chargebacks).  The affected user would initiate the procedure through an arbitrator as for any other dispute, instead of doing it by informally contacting the developers through slack or the community forum.   This will make the process more structured and private.  It will help avoid unnecessary public concerns  in open forums when the chargeback is a false positive and/or can be orderly solved in private between the traders. 

**UI implementation**

In the Portfolio tab, History subtab, a red dispute icon should be displayed next to the information icon in the Trade ID column.  Clicking the icon would open the trade details window. A tooltip with the text "Open Dispute" should be shown when hovering the mouse over the dispute icon.

![image](https://user-images.githubusercontent.com/17677608/59286017-3fbb2a80-8c6f-11e9-9053-660e4d99c507.png)

.
EDIT: Alternatively to the above, instead of the dispute icon a pop-up with a "don´t show again option" could be shown after a successful trade containing the text "You can open a dispute by opening trade details window in the Portfolio/history tab"
.
When opening up the trade details window (regardless on how it is opened), an "Open Dispute" button should be  displayed at the bottom:
.
.
![image](https://user-images.githubusercontent.com/17677608/59287067-37fc8580-8c71-11e9-8292-aa4b83c9233d.png)

Then, a pop-up asking for confirmation should be displayed.  ¿Are you sure you want to open a dispute for trade XXXXX?.  If the user confirms, then a standard Support Ticket would be open so the user can communicate the problem with the arbitrator.

**Comment by clearwater-trust** [comment]
I like the idea of being able to alert the arbitrators in the event of a trade issue (through the client).
I don't think we need the added **D** in the portfolio history display.

**Comment by m52go** [comment]
I think the icon is important to tell users that they _can_ open a dispute on a completed trade. The tooltip should take care of resulting confusion.

**Comment by clearwater-trust** [comment]
You're right. Plus you need a button to trigger the message. I don't like to have red warning messages on my lists. (aviation induced phobia of some kind) Red is a high level alert color.  Perhaps we could tone it down?

**Comment by m52go** [comment]
Yeah that's fair. Maybe just make it dark grey with no fill so it contrasts with the information icon. Also maybe make the outline shape an octagon so it's vaguely reminiscent of a stop sign so people get the hint that it's special (if that's possible).

**Comment by ripcurlx** [comment]
I'm not sure if it is necessary to display the dispute icon in the list, so people now they can open a dispute. I think it would be better to add this information after a successful trade (with a don't show again checkbox) in a popup to tell the user they can open a dispute by opening the info popup in the history tab.

**Comment by mpolavieja** [comment]
> I think it would be better to add this information after a successful trade

Added into the proposal

**Comment by mpolavieja** [comment]
@
